// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public enum ENU_Equipment_EDM_Type
{
	Image(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "이미지" } }),
	Documentation(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "문서" } }),
	Blueprint(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "도면" } }),
	Video(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "동영상" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENU_Equipment_EDM_Type(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
