// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초작성자 : 김동명
 * 최초작성일 : 2023-11-10
 * 최종수정자 : 
 * 최종수정일 :
 * 
 * 설명 : 설비정보조회페이지에서 Helper로 사용할 ENUM
 * 
 * V1.0 : 최초작성
 */
public enum ENU_Equipment_Information_Type
{
	List(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "목록" } }),
	Equipment_Information(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비정보" } }),
	Detail(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "상세" } }),
	ED(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "전자문서" } }),
	MaintenanceCost(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "보전비용" } }),
	Maintenance_Indicator(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "보전지표" } }),
	BOM(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "BOM구성" } }),
	Equipment_Specification(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비사양" } }),
	Work_History(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업이력" } }),
	Check_History(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "점검이력" } }),
	Material(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "소요자재" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENU_Equipment_Information_Type(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
