// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초작성자 : 김동명
 * 최초작성일 : 2023-12-01
 * 설명 : 설비 BOM에서 메뉴 선택시 화면 변경용 ENUM
 * V1.0: 최초작성
 */
public enum ENU_Equipment_BOM_Menu_Type
{
	Equipment_List(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Equipment_List" } }),
	MarterialList(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "MarterialList" } }),
	Multiple_Registration(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Multiple_Registration" } }),
	Equipment_BOM_New(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Equipment_BOM_New" } }),
	Equipment_BOM_Edit(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Equipment_BOM_Edit" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENU_Equipment_BOM_Menu_Type(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
