// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public class Equipment_EDM_Helper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipment_EDM_HelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.Equipment_EDM_Helper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		FileType("FileType"),
		Documentation("Documentation"),
		Equipment_EDM_Helper_EquipmentEDMFile("Equipment_Management.Equipment_EDM_Helper_EquipmentEDMFile"),
		Equipment_EDM_Helper_EquipmentEDM("Equipment_Management.Equipment_EDM_Helper_EquipmentEDM");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Equipment_EDM_Helper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Equipment_EDM_Helper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipment_EDM_HelperMendixObject)
	{
		if (equipment_EDM_HelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipment_EDM_HelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipment_EDM_HelperMendixObject = equipment_EDM_HelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.Equipment_EDM_Helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.Equipment_EDM_Helper(context, mendixObject);
	}

	public static equipment_management.proxies.Equipment_EDM_Helper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.Equipment_EDM_Helper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * Get value of FileType
	 * @param filetype
	 */
	public final equipment_management.proxies.ENU_Equipment_EDM_Type getFileType()
	{
		return getFileType(getContext());
	}

	/**
	 * @param context
	 * @return value of FileType
	 */
	public final equipment_management.proxies.ENU_Equipment_EDM_Type getFileType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FileType.toString());
		if (obj == null) {
			return null;
		}
		return equipment_management.proxies.ENU_Equipment_EDM_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FileType
	 * @param filetype
	 */
	public final void setFileType(equipment_management.proxies.ENU_Equipment_EDM_Type filetype)
	{
		setFileType(getContext(), filetype);
	}

	/**
	 * Set value of FileType
	 * @param context
	 * @param filetype
	 */
	public final void setFileType(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.ENU_Equipment_EDM_Type filetype)
	{
		if (filetype != null) {
			getMendixObject().setValue(context, MemberNames.FileType.toString(), filetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.FileType.toString(), null);
		}
	}

	/**
	 * @return value of Documentation
	 */
	public final java.lang.String getDocumentation()
	{
		return getDocumentation(getContext());
	}

	/**
	 * @param context
	 * @return value of Documentation
	 */
	public final java.lang.String getDocumentation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Documentation.toString());
	}

	/**
	 * Set value of Documentation
	 * @param documentation
	 */
	public final void setDocumentation(java.lang.String documentation)
	{
		setDocumentation(getContext(), documentation);
	}

	/**
	 * Set value of Documentation
	 * @param context
	 * @param documentation
	 */
	public final void setDocumentation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String documentation)
	{
		getMendixObject().setValue(context, MemberNames.Documentation.toString(), documentation);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EDM_Helper_EquipmentEDMFile
	 */
	public final equipment_management.proxies.EquipmentEDMFile getEquipment_EDM_Helper_EquipmentEDMFile() throws com.mendix.core.CoreException
	{
		return getEquipment_EDM_Helper_EquipmentEDMFile(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EDM_Helper_EquipmentEDMFile
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentEDMFile getEquipment_EDM_Helper_EquipmentEDMFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentEDMFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EDM_Helper_EquipmentEDMFile.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentEDMFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EDM_Helper_EquipmentEDMFile
	 * @param equipment_edm_helper_equipmentedmfile
	 */
	public final void setEquipment_EDM_Helper_EquipmentEDMFile(equipment_management.proxies.EquipmentEDMFile equipment_edm_helper_equipmentedmfile)
	{
		setEquipment_EDM_Helper_EquipmentEDMFile(getContext(), equipment_edm_helper_equipmentedmfile);
	}

	/**
	 * Set value of Equipment_EDM_Helper_EquipmentEDMFile
	 * @param context
	 * @param equipment_edm_helper_equipmentedmfile
	 */
	public final void setEquipment_EDM_Helper_EquipmentEDMFile(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentEDMFile equipment_edm_helper_equipmentedmfile)
	{
		if (equipment_edm_helper_equipmentedmfile == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EDM_Helper_EquipmentEDMFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EDM_Helper_EquipmentEDMFile.toString(), equipment_edm_helper_equipmentedmfile.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EDM_Helper_EquipmentEDM
	 */
	public final equipment_management.proxies.EquipmentEDM getEquipment_EDM_Helper_EquipmentEDM() throws com.mendix.core.CoreException
	{
		return getEquipment_EDM_Helper_EquipmentEDM(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EDM_Helper_EquipmentEDM
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentEDM getEquipment_EDM_Helper_EquipmentEDM(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentEDM result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EDM_Helper_EquipmentEDM.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentEDM.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EDM_Helper_EquipmentEDM
	 * @param equipment_edm_helper_equipmentedm
	 */
	public final void setEquipment_EDM_Helper_EquipmentEDM(equipment_management.proxies.EquipmentEDM equipment_edm_helper_equipmentedm)
	{
		setEquipment_EDM_Helper_EquipmentEDM(getContext(), equipment_edm_helper_equipmentedm);
	}

	/**
	 * Set value of Equipment_EDM_Helper_EquipmentEDM
	 * @param context
	 * @param equipment_edm_helper_equipmentedm
	 */
	public final void setEquipment_EDM_Helper_EquipmentEDM(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentEDM equipment_edm_helper_equipmentedm)
	{
		if (equipment_edm_helper_equipmentedm == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EDM_Helper_EquipmentEDM.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EDM_Helper_EquipmentEDM.toString(), equipment_edm_helper_equipmentedm.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipment_EDM_HelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.Equipment_EDM_Helper that = (equipment_management.proxies.Equipment_EDM_Helper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
