// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public class EquipmentEDM implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentEDMMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentEDM";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Title("Title"),
		FileType("FileType"),
		Documentation("Documentation"),
		Index("Index"),
		HasContents("HasContents"),
		EquipmentEDM_Equipment("Equipment_Management.EquipmentEDM_Equipment"),
		EquipmentEDM_EquipmentEDMFile("Equipment_Management.EquipmentEDM_EquipmentEDMFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentEDM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentEDM(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentEDMMendixObject)
	{
		if (equipmentEDMMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentEDMMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentEDMMendixObject = equipmentEDMMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentEDM initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentEDM(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentEDM load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentEDM.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentEDM> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentEDM.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Title
	 */
	public final java.lang.String getTitle()
	{
		return getTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of Title
	 */
	public final java.lang.String getTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Title.toString());
	}

	/**
	 * Set value of Title
	 * @param title
	 */
	public final void setTitle(java.lang.String title)
	{
		setTitle(getContext(), title);
	}

	/**
	 * Set value of Title
	 * @param context
	 * @param title
	 */
	public final void setTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String title)
	{
		getMendixObject().setValue(context, MemberNames.Title.toString(), title);
	}

	/**
	 * Get value of FileType
	 * @param filetype
	 */
	public final equipment_management.proxies.ENU_Equipment_EDM_Type getFileType()
	{
		return getFileType(getContext());
	}

	/**
	 * @param context
	 * @return value of FileType
	 */
	public final equipment_management.proxies.ENU_Equipment_EDM_Type getFileType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.FileType.toString());
		if (obj == null) {
			return null;
		}
		return equipment_management.proxies.ENU_Equipment_EDM_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of FileType
	 * @param filetype
	 */
	public final void setFileType(equipment_management.proxies.ENU_Equipment_EDM_Type filetype)
	{
		setFileType(getContext(), filetype);
	}

	/**
	 * Set value of FileType
	 * @param context
	 * @param filetype
	 */
	public final void setFileType(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.ENU_Equipment_EDM_Type filetype)
	{
		if (filetype != null) {
			getMendixObject().setValue(context, MemberNames.FileType.toString(), filetype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.FileType.toString(), null);
		}
	}

	/**
	 * @return value of Documentation
	 */
	public final java.lang.String getDocumentation()
	{
		return getDocumentation(getContext());
	}

	/**
	 * @param context
	 * @return value of Documentation
	 */
	public final java.lang.String getDocumentation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Documentation.toString());
	}

	/**
	 * Set value of Documentation
	 * @param documentation
	 */
	public final void setDocumentation(java.lang.String documentation)
	{
		setDocumentation(getContext(), documentation);
	}

	/**
	 * Set value of Documentation
	 * @param context
	 * @param documentation
	 */
	public final void setDocumentation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String documentation)
	{
		getMendixObject().setValue(context, MemberNames.Documentation.toString(), documentation);
	}

	/**
	 * @return value of Index
	 */
	public final java.lang.Integer getIndex()
	{
		return getIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of Index
	 */
	public final java.lang.Integer getIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Index.toString());
	}

	/**
	 * Set value of Index
	 * @param index
	 */
	public final void setIndex(java.lang.Integer index)
	{
		setIndex(getContext(), index);
	}

	/**
	 * Set value of Index
	 * @param context
	 * @param index
	 */
	public final void setIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer index)
	{
		getMendixObject().setValue(context, MemberNames.Index.toString(), index);
	}

	/**
	 * @return value of HasContents
	 */
	public final java.lang.Boolean getHasContents()
	{
		return getHasContents(getContext());
	}

	/**
	 * @param context
	 * @return value of HasContents
	 */
	public final java.lang.Boolean getHasContents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasContents.toString());
	}

	/**
	 * Set value of HasContents
	 * @param hascontents
	 */
	public final void setHasContents(java.lang.Boolean hascontents)
	{
		setHasContents(getContext(), hascontents);
	}

	/**
	 * Set value of HasContents
	 * @param context
	 * @param hascontents
	 */
	public final void setHasContents(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hascontents)
	{
		getMendixObject().setValue(context, MemberNames.HasContents.toString(), hascontents);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentEDM_Equipment
	 */
	public final equipment_management.proxies.Equipment getEquipmentEDM_Equipment() throws com.mendix.core.CoreException
	{
		return getEquipmentEDM_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentEDM_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getEquipmentEDM_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentEDM_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentEDM_Equipment
	 * @param equipmentedm_equipment
	 */
	public final void setEquipmentEDM_Equipment(equipment_management.proxies.Equipment equipmentedm_equipment)
	{
		setEquipmentEDM_Equipment(getContext(), equipmentedm_equipment);
	}

	/**
	 * Set value of EquipmentEDM_Equipment
	 * @param context
	 * @param equipmentedm_equipment
	 */
	public final void setEquipmentEDM_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment equipmentedm_equipment)
	{
		if (equipmentedm_equipment == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentEDM_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentEDM_Equipment.toString(), equipmentedm_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentEDM_EquipmentEDMFile
	 */
	public final equipment_management.proxies.EquipmentEDMFile getEquipmentEDM_EquipmentEDMFile() throws com.mendix.core.CoreException
	{
		return getEquipmentEDM_EquipmentEDMFile(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentEDM_EquipmentEDMFile
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentEDMFile getEquipmentEDM_EquipmentEDMFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentEDMFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentEDM_EquipmentEDMFile.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentEDMFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentEDM_EquipmentEDMFile
	 * @param equipmentedm_equipmentedmfile
	 */
	public final void setEquipmentEDM_EquipmentEDMFile(equipment_management.proxies.EquipmentEDMFile equipmentedm_equipmentedmfile)
	{
		setEquipmentEDM_EquipmentEDMFile(getContext(), equipmentedm_equipmentedmfile);
	}

	/**
	 * Set value of EquipmentEDM_EquipmentEDMFile
	 * @param context
	 * @param equipmentedm_equipmentedmfile
	 */
	public final void setEquipmentEDM_EquipmentEDMFile(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentEDMFile equipmentedm_equipmentedmfile)
	{
		if (equipmentedm_equipmentedmfile == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentEDM_EquipmentEDMFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentEDM_EquipmentEDMFile.toString(), equipmentedm_equipmentedmfile.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentEDMMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentEDM that = (equipment_management.proxies.EquipmentEDM) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
