// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/19
 * 최종 수정자 : 
 * 최종 수정일 : 
 * 설명 : 설비 등록 시 트리구조 선택을 위한 Entity
 * Version 1.0 : 생성
 */
public class EquipmentCreateHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentCreateHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentCreateHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentCreateHelper_EquipmentType("Equipment_Management.EquipmentCreateHelper_EquipmentType"),
		EquipmentCreateHelper_EquipmentLocation("Equipment_Management.EquipmentCreateHelper_EquipmentLocation"),
		EquipmentCreateHelper_Account("Equipment_Management.EquipmentCreateHelper_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentCreateHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentCreateHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentCreateHelperMendixObject)
	{
		if (equipmentCreateHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentCreateHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentCreateHelperMendixObject = equipmentCreateHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentCreateHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentCreateHelper(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentCreateHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentCreateHelper.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentCreateHelper> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentCreateHelper.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentCreateHelper_EquipmentType
	 */
	public final equipment_management.proxies.EquipmentType getEquipmentCreateHelper_EquipmentType() throws com.mendix.core.CoreException
	{
		return getEquipmentCreateHelper_EquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentCreateHelper_EquipmentType
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentType getEquipmentCreateHelper_EquipmentType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentCreateHelper_EquipmentType.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentCreateHelper_EquipmentType
	 * @param equipmentcreatehelper_equipmenttype
	 */
	public final void setEquipmentCreateHelper_EquipmentType(equipment_management.proxies.EquipmentType equipmentcreatehelper_equipmenttype)
	{
		setEquipmentCreateHelper_EquipmentType(getContext(), equipmentcreatehelper_equipmenttype);
	}

	/**
	 * Set value of EquipmentCreateHelper_EquipmentType
	 * @param context
	 * @param equipmentcreatehelper_equipmenttype
	 */
	public final void setEquipmentCreateHelper_EquipmentType(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentType equipmentcreatehelper_equipmenttype)
	{
		if (equipmentcreatehelper_equipmenttype == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentCreateHelper_EquipmentType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentCreateHelper_EquipmentType.toString(), equipmentcreatehelper_equipmenttype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentCreateHelper_EquipmentLocation
	 */
	public final equipment_management.proxies.EquipmentLocation getEquipmentCreateHelper_EquipmentLocation() throws com.mendix.core.CoreException
	{
		return getEquipmentCreateHelper_EquipmentLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentCreateHelper_EquipmentLocation
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentLocation getEquipmentCreateHelper_EquipmentLocation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentLocation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentCreateHelper_EquipmentLocation.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentLocation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentCreateHelper_EquipmentLocation
	 * @param equipmentcreatehelper_equipmentlocation
	 */
	public final void setEquipmentCreateHelper_EquipmentLocation(equipment_management.proxies.EquipmentLocation equipmentcreatehelper_equipmentlocation)
	{
		setEquipmentCreateHelper_EquipmentLocation(getContext(), equipmentcreatehelper_equipmentlocation);
	}

	/**
	 * Set value of EquipmentCreateHelper_EquipmentLocation
	 * @param context
	 * @param equipmentcreatehelper_equipmentlocation
	 */
	public final void setEquipmentCreateHelper_EquipmentLocation(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentLocation equipmentcreatehelper_equipmentlocation)
	{
		if (equipmentcreatehelper_equipmentlocation == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentCreateHelper_EquipmentLocation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentCreateHelper_EquipmentLocation.toString(), equipmentcreatehelper_equipmentlocation.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentCreateHelper_Account
	 */
	public final administration.proxies.Account getEquipmentCreateHelper_Account() throws com.mendix.core.CoreException
	{
		return getEquipmentCreateHelper_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentCreateHelper_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getEquipmentCreateHelper_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentCreateHelper_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentCreateHelper_Account
	 * @param equipmentcreatehelper_account
	 */
	public final void setEquipmentCreateHelper_Account(administration.proxies.Account equipmentcreatehelper_account)
	{
		setEquipmentCreateHelper_Account(getContext(), equipmentcreatehelper_account);
	}

	/**
	 * Set value of EquipmentCreateHelper_Account
	 * @param context
	 * @param equipmentcreatehelper_account
	 */
	public final void setEquipmentCreateHelper_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account equipmentcreatehelper_account)
	{
		if (equipmentcreatehelper_account == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentCreateHelper_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentCreateHelper_Account.toString(), equipmentcreatehelper_account.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentCreateHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentCreateHelper that = (equipment_management.proxies.EquipmentCreateHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
