// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/09/06
 * 최종 수정자 : 
 * 최종 수정일 : 2023/09/06
 * 설명 : 설비 사진 엔터티
 * Version 1.0 : 생성
 */
public class EquipmentMovementImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentMovementImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImageName("ImageName"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentMovementImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentMovementImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentMovementImageMendixObject)
	{
		super(context, equipmentMovementImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentMovementImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentMovementImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentMovementImage(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentMovementImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentMovementImage.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentMovementImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentMovementImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName()
	{
		return getImageName(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageName.toString());
	}

	/**
	 * Set value of ImageName
	 * @param imagename
	 */
	public final void setImageName(java.lang.String imagename)
	{
		setImageName(getContext(), imagename);
	}

	/**
	 * Set value of ImageName
	 * @param context
	 * @param imagename
	 */
	public final void setImageName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imagename)
	{
		getMendixObject().setValue(context, MemberNames.ImageName.toString(), imagename);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentMovementImage that = (equipment_management.proxies.EquipmentMovementImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
