// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/09/06
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/09/11
 * 설명 : 설비분류 엔터티
 * 
 * Version 1.1 : IsRoot 추가
 * Version 1.0 : 생성
 */
public class EquipmentType implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentTypeParentName("EquipmentTypeParentName"),
		EquipmentTypeCode("EquipmentTypeCode"),
		EquipmentTypeName("EquipmentTypeName"),
		EquipmentTypeNameEnglish("EquipmentTypeNameEnglish"),
		EquipmentTypeDescription("EquipmentTypeDescription"),
		EquipmentTypePath("EquipmentTypePath"),
		EquipmentTypeNumber("EquipmentTypeNumber"),
		IsEquipmentTypeActive("IsEquipmentTypeActive"),
		EquipmentTypeIsRoot("EquipmentTypeIsRoot"),
		Parent_EquipmentType("Equipment_Management.Parent_EquipmentType"),
		EquipmentType_EquipmentTypeHelper("Equipment_Management.EquipmentType_EquipmentTypeHelper"),
		EquipmentType_EquipmentTypehelper_Child("Equipment_Management.EquipmentType_EquipmentTypehelper_Child");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentTypeMendixObject)
	{
		if (equipmentTypeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentTypeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentTypeMendixObject = equipmentTypeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentType(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentType.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentType> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentType.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EquipmentTypeParentName
	 */
	public final java.lang.String getEquipmentTypeParentName()
	{
		return getEquipmentTypeParentName(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentTypeParentName
	 */
	public final java.lang.String getEquipmentTypeParentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentTypeParentName.toString());
	}

	/**
	 * Set value of EquipmentTypeParentName
	 * @param equipmenttypeparentname
	 */
	public final void setEquipmentTypeParentName(java.lang.String equipmenttypeparentname)
	{
		setEquipmentTypeParentName(getContext(), equipmenttypeparentname);
	}

	/**
	 * Set value of EquipmentTypeParentName
	 * @param context
	 * @param equipmenttypeparentname
	 */
	public final void setEquipmentTypeParentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttypeparentname)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentTypeParentName.toString(), equipmenttypeparentname);
	}

	/**
	 * @return value of EquipmentTypeCode
	 */
	public final java.lang.String getEquipmentTypeCode()
	{
		return getEquipmentTypeCode(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentTypeCode
	 */
	public final java.lang.String getEquipmentTypeCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentTypeCode.toString());
	}

	/**
	 * Set value of EquipmentTypeCode
	 * @param equipmenttypecode
	 */
	public final void setEquipmentTypeCode(java.lang.String equipmenttypecode)
	{
		setEquipmentTypeCode(getContext(), equipmenttypecode);
	}

	/**
	 * Set value of EquipmentTypeCode
	 * @param context
	 * @param equipmenttypecode
	 */
	public final void setEquipmentTypeCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttypecode)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentTypeCode.toString(), equipmenttypecode);
	}

	/**
	 * @return value of EquipmentTypeName
	 */
	public final java.lang.String getEquipmentTypeName()
	{
		return getEquipmentTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentTypeName
	 */
	public final java.lang.String getEquipmentTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentTypeName.toString());
	}

	/**
	 * Set value of EquipmentTypeName
	 * @param equipmenttypename
	 */
	public final void setEquipmentTypeName(java.lang.String equipmenttypename)
	{
		setEquipmentTypeName(getContext(), equipmenttypename);
	}

	/**
	 * Set value of EquipmentTypeName
	 * @param context
	 * @param equipmenttypename
	 */
	public final void setEquipmentTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttypename)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentTypeName.toString(), equipmenttypename);
	}

	/**
	 * @return value of EquipmentTypeNameEnglish
	 */
	public final java.lang.String getEquipmentTypeNameEnglish()
	{
		return getEquipmentTypeNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentTypeNameEnglish
	 */
	public final java.lang.String getEquipmentTypeNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentTypeNameEnglish.toString());
	}

	/**
	 * Set value of EquipmentTypeNameEnglish
	 * @param equipmenttypenameenglish
	 */
	public final void setEquipmentTypeNameEnglish(java.lang.String equipmenttypenameenglish)
	{
		setEquipmentTypeNameEnglish(getContext(), equipmenttypenameenglish);
	}

	/**
	 * Set value of EquipmentTypeNameEnglish
	 * @param context
	 * @param equipmenttypenameenglish
	 */
	public final void setEquipmentTypeNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttypenameenglish)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentTypeNameEnglish.toString(), equipmenttypenameenglish);
	}

	/**
	 * @return value of EquipmentTypeDescription
	 */
	public final java.lang.String getEquipmentTypeDescription()
	{
		return getEquipmentTypeDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentTypeDescription
	 */
	public final java.lang.String getEquipmentTypeDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentTypeDescription.toString());
	}

	/**
	 * Set value of EquipmentTypeDescription
	 * @param equipmenttypedescription
	 */
	public final void setEquipmentTypeDescription(java.lang.String equipmenttypedescription)
	{
		setEquipmentTypeDescription(getContext(), equipmenttypedescription);
	}

	/**
	 * Set value of EquipmentTypeDescription
	 * @param context
	 * @param equipmenttypedescription
	 */
	public final void setEquipmentTypeDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttypedescription)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentTypeDescription.toString(), equipmenttypedescription);
	}

	/**
	 * @return value of EquipmentTypePath
	 */
	public final java.lang.String getEquipmentTypePath()
	{
		return getEquipmentTypePath(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentTypePath
	 */
	public final java.lang.String getEquipmentTypePath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentTypePath.toString());
	}

	/**
	 * Set value of EquipmentTypePath
	 * @param equipmenttypepath
	 */
	public final void setEquipmentTypePath(java.lang.String equipmenttypepath)
	{
		setEquipmentTypePath(getContext(), equipmenttypepath);
	}

	/**
	 * Set value of EquipmentTypePath
	 * @param context
	 * @param equipmenttypepath
	 */
	public final void setEquipmentTypePath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttypepath)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentTypePath.toString(), equipmenttypepath);
	}

	/**
	 * @return value of EquipmentTypeNumber
	 */
	public final java.lang.Integer getEquipmentTypeNumber()
	{
		return getEquipmentTypeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentTypeNumber
	 */
	public final java.lang.Integer getEquipmentTypeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentTypeNumber.toString());
	}

	/**
	 * Set value of EquipmentTypeNumber
	 * @param equipmenttypenumber
	 */
	public final void setEquipmentTypeNumber(java.lang.Integer equipmenttypenumber)
	{
		setEquipmentTypeNumber(getContext(), equipmenttypenumber);
	}

	/**
	 * Set value of EquipmentTypeNumber
	 * @param context
	 * @param equipmenttypenumber
	 */
	public final void setEquipmentTypeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmenttypenumber)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentTypeNumber.toString(), equipmenttypenumber);
	}

	/**
	 * @return value of IsEquipmentTypeActive
	 */
	public final java.lang.Boolean getIsEquipmentTypeActive()
	{
		return getIsEquipmentTypeActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEquipmentTypeActive
	 */
	public final java.lang.Boolean getIsEquipmentTypeActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEquipmentTypeActive.toString());
	}

	/**
	 * Set value of IsEquipmentTypeActive
	 * @param isequipmenttypeactive
	 */
	public final void setIsEquipmentTypeActive(java.lang.Boolean isequipmenttypeactive)
	{
		setIsEquipmentTypeActive(getContext(), isequipmenttypeactive);
	}

	/**
	 * Set value of IsEquipmentTypeActive
	 * @param context
	 * @param isequipmenttypeactive
	 */
	public final void setIsEquipmentTypeActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isequipmenttypeactive)
	{
		getMendixObject().setValue(context, MemberNames.IsEquipmentTypeActive.toString(), isequipmenttypeactive);
	}

	/**
	 * @return value of EquipmentTypeIsRoot
	 */
	public final java.lang.Boolean getEquipmentTypeIsRoot()
	{
		return getEquipmentTypeIsRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentTypeIsRoot
	 */
	public final java.lang.Boolean getEquipmentTypeIsRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentTypeIsRoot.toString());
	}

	/**
	 * Set value of EquipmentTypeIsRoot
	 * @param equipmenttypeisroot
	 */
	public final void setEquipmentTypeIsRoot(java.lang.Boolean equipmenttypeisroot)
	{
		setEquipmentTypeIsRoot(getContext(), equipmenttypeisroot);
	}

	/**
	 * Set value of EquipmentTypeIsRoot
	 * @param context
	 * @param equipmenttypeisroot
	 */
	public final void setEquipmentTypeIsRoot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmenttypeisroot)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentTypeIsRoot.toString(), equipmenttypeisroot);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_EquipmentType
	 */
	public final equipment_management.proxies.EquipmentType getParent_EquipmentType() throws com.mendix.core.CoreException
	{
		return getParent_EquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_EquipmentType
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentType getParent_EquipmentType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_EquipmentType.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_EquipmentType
	 * @param parent_equipmenttype
	 */
	public final void setParent_EquipmentType(equipment_management.proxies.EquipmentType parent_equipmenttype)
	{
		setParent_EquipmentType(getContext(), parent_equipmenttype);
	}

	/**
	 * Set value of Parent_EquipmentType
	 * @param context
	 * @param parent_equipmenttype
	 */
	public final void setParent_EquipmentType(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentType parent_equipmenttype)
	{
		if (parent_equipmenttype == null) {
			getMendixObject().setValue(context, MemberNames.Parent_EquipmentType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_EquipmentType.toString(), parent_equipmenttype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentType_EquipmentTypeHelper
	 */
	public final equipment_management.proxies.EquipmentTypeHelper getEquipmentType_EquipmentTypeHelper() throws com.mendix.core.CoreException
	{
		return getEquipmentType_EquipmentTypeHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentType_EquipmentTypeHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentTypeHelper getEquipmentType_EquipmentTypeHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentTypeHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentType_EquipmentTypeHelper.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentTypeHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentType_EquipmentTypeHelper
	 * @param equipmenttype_equipmenttypehelper
	 */
	public final void setEquipmentType_EquipmentTypeHelper(equipment_management.proxies.EquipmentTypeHelper equipmenttype_equipmenttypehelper)
	{
		setEquipmentType_EquipmentTypeHelper(getContext(), equipmenttype_equipmenttypehelper);
	}

	/**
	 * Set value of EquipmentType_EquipmentTypeHelper
	 * @param context
	 * @param equipmenttype_equipmenttypehelper
	 */
	public final void setEquipmentType_EquipmentTypeHelper(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentTypeHelper equipmenttype_equipmenttypehelper)
	{
		if (equipmenttype_equipmenttypehelper == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentType_EquipmentTypeHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentType_EquipmentTypeHelper.toString(), equipmenttype_equipmenttypehelper.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentType_EquipmentTypehelper_Child
	 */
	public final equipment_management.proxies.EquipmentTypehelper_Child getEquipmentType_EquipmentTypehelper_Child() throws com.mendix.core.CoreException
	{
		return getEquipmentType_EquipmentTypehelper_Child(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentType_EquipmentTypehelper_Child
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentTypehelper_Child getEquipmentType_EquipmentTypehelper_Child(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentTypehelper_Child result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentType_EquipmentTypehelper_Child.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentTypehelper_Child.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentType_EquipmentTypehelper_Child
	 * @param equipmenttype_equipmenttypehelper_child
	 */
	public final void setEquipmentType_EquipmentTypehelper_Child(equipment_management.proxies.EquipmentTypehelper_Child equipmenttype_equipmenttypehelper_child)
	{
		setEquipmentType_EquipmentTypehelper_Child(getContext(), equipmenttype_equipmenttypehelper_child);
	}

	/**
	 * Set value of EquipmentType_EquipmentTypehelper_Child
	 * @param context
	 * @param equipmenttype_equipmenttypehelper_child
	 */
	public final void setEquipmentType_EquipmentTypehelper_Child(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentTypehelper_Child equipmenttype_equipmenttypehelper_child)
	{
		if (equipmenttype_equipmenttypehelper_child == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentType_EquipmentTypehelper_Child.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentType_EquipmentTypehelper_Child.toString(), equipmenttype_equipmenttypehelper_child.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentTypeMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentType that = (equipment_management.proxies.EquipmentType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
