// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초작성자 : 김동명
 * 최초작성일 : 2023-12-01
 * 설명 : 설비 BOM Entity
 * V1.0 : 최초작성
 */
public class Equipment_BOM implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipment_BOMMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.Equipment_BOM";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentBOMSafetyStock("EquipmentBOMSafetyStock"),
		EquipmentBOMExchangingPeriod("EquipmentBOMExchangingPeriod"),
		EquipmentBOMAmount("EquipmentBOMAmount"),
		EquipmentBOMDescription("EquipmentBOMDescription"),
		EquipmentBOMSort("EquipmentBOMSort"),
		EquipmentBOMFirstReplacement("EquipmentBOMFirstReplacement"),
		EquipmentFinalReplacement("EquipmentFinalReplacement"),
		EquipmentBOMCumulativeUsage("EquipmentBOMCumulativeUsage"),
		EquipmentBOMMaximumUseOnce("EquipmentBOMMaximumUseOnce"),
		EquipmentBOMAverageUsage("EquipmentBOMAverageUsage"),
		Equipment_BOM_Equipment("Equipment_Management.Equipment_BOM_Equipment"),
		Equipment_BOM_Material("Equipment_Management.Equipment_BOM_Material");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Equipment_BOM(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Equipment_BOM(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipment_BOMMendixObject)
	{
		if (equipment_BOMMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipment_BOMMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipment_BOMMendixObject = equipment_BOMMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.Equipment_BOM initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.Equipment_BOM(context, mendixObject);
	}

	public static equipment_management.proxies.Equipment_BOM load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.Equipment_BOM.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.Equipment_BOM> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.Equipment_BOM.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EquipmentBOMSafetyStock
	 */
	public final java.lang.Integer getEquipmentBOMSafetyStock()
	{
		return getEquipmentBOMSafetyStock(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMSafetyStock
	 */
	public final java.lang.Integer getEquipmentBOMSafetyStock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentBOMSafetyStock.toString());
	}

	/**
	 * Set value of EquipmentBOMSafetyStock
	 * @param equipmentbomsafetystock
	 */
	public final void setEquipmentBOMSafetyStock(java.lang.Integer equipmentbomsafetystock)
	{
		setEquipmentBOMSafetyStock(getContext(), equipmentbomsafetystock);
	}

	/**
	 * Set value of EquipmentBOMSafetyStock
	 * @param context
	 * @param equipmentbomsafetystock
	 */
	public final void setEquipmentBOMSafetyStock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentbomsafetystock)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMSafetyStock.toString(), equipmentbomsafetystock);
	}

	/**
	 * @return value of EquipmentBOMExchangingPeriod
	 */
	public final java.lang.Integer getEquipmentBOMExchangingPeriod()
	{
		return getEquipmentBOMExchangingPeriod(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMExchangingPeriod
	 */
	public final java.lang.Integer getEquipmentBOMExchangingPeriod(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentBOMExchangingPeriod.toString());
	}

	/**
	 * Set value of EquipmentBOMExchangingPeriod
	 * @param equipmentbomexchangingperiod
	 */
	public final void setEquipmentBOMExchangingPeriod(java.lang.Integer equipmentbomexchangingperiod)
	{
		setEquipmentBOMExchangingPeriod(getContext(), equipmentbomexchangingperiod);
	}

	/**
	 * Set value of EquipmentBOMExchangingPeriod
	 * @param context
	 * @param equipmentbomexchangingperiod
	 */
	public final void setEquipmentBOMExchangingPeriod(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentbomexchangingperiod)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMExchangingPeriod.toString(), equipmentbomexchangingperiod);
	}

	/**
	 * @return value of EquipmentBOMAmount
	 */
	public final java.lang.Integer getEquipmentBOMAmount()
	{
		return getEquipmentBOMAmount(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMAmount
	 */
	public final java.lang.Integer getEquipmentBOMAmount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentBOMAmount.toString());
	}

	/**
	 * Set value of EquipmentBOMAmount
	 * @param equipmentbomamount
	 */
	public final void setEquipmentBOMAmount(java.lang.Integer equipmentbomamount)
	{
		setEquipmentBOMAmount(getContext(), equipmentbomamount);
	}

	/**
	 * Set value of EquipmentBOMAmount
	 * @param context
	 * @param equipmentbomamount
	 */
	public final void setEquipmentBOMAmount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentbomamount)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMAmount.toString(), equipmentbomamount);
	}

	/**
	 * @return value of EquipmentBOMDescription
	 */
	public final java.lang.String getEquipmentBOMDescription()
	{
		return getEquipmentBOMDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMDescription
	 */
	public final java.lang.String getEquipmentBOMDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentBOMDescription.toString());
	}

	/**
	 * Set value of EquipmentBOMDescription
	 * @param equipmentbomdescription
	 */
	public final void setEquipmentBOMDescription(java.lang.String equipmentbomdescription)
	{
		setEquipmentBOMDescription(getContext(), equipmentbomdescription);
	}

	/**
	 * Set value of EquipmentBOMDescription
	 * @param context
	 * @param equipmentbomdescription
	 */
	public final void setEquipmentBOMDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentbomdescription)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMDescription.toString(), equipmentbomdescription);
	}

	/**
	 * @return value of EquipmentBOMSort
	 */
	public final java.lang.Integer getEquipmentBOMSort()
	{
		return getEquipmentBOMSort(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMSort
	 */
	public final java.lang.Integer getEquipmentBOMSort(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentBOMSort.toString());
	}

	/**
	 * Set value of EquipmentBOMSort
	 * @param equipmentbomsort
	 */
	public final void setEquipmentBOMSort(java.lang.Integer equipmentbomsort)
	{
		setEquipmentBOMSort(getContext(), equipmentbomsort);
	}

	/**
	 * Set value of EquipmentBOMSort
	 * @param context
	 * @param equipmentbomsort
	 */
	public final void setEquipmentBOMSort(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentbomsort)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMSort.toString(), equipmentbomsort);
	}

	/**
	 * @return value of EquipmentBOMFirstReplacement
	 */
	public final java.util.Date getEquipmentBOMFirstReplacement()
	{
		return getEquipmentBOMFirstReplacement(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMFirstReplacement
	 */
	public final java.util.Date getEquipmentBOMFirstReplacement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentBOMFirstReplacement.toString());
	}

	/**
	 * Set value of EquipmentBOMFirstReplacement
	 * @param equipmentbomfirstreplacement
	 */
	public final void setEquipmentBOMFirstReplacement(java.util.Date equipmentbomfirstreplacement)
	{
		setEquipmentBOMFirstReplacement(getContext(), equipmentbomfirstreplacement);
	}

	/**
	 * Set value of EquipmentBOMFirstReplacement
	 * @param context
	 * @param equipmentbomfirstreplacement
	 */
	public final void setEquipmentBOMFirstReplacement(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentbomfirstreplacement)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMFirstReplacement.toString(), equipmentbomfirstreplacement);
	}

	/**
	 * @return value of EquipmentFinalReplacement
	 */
	public final java.util.Date getEquipmentFinalReplacement()
	{
		return getEquipmentFinalReplacement(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentFinalReplacement
	 */
	public final java.util.Date getEquipmentFinalReplacement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentFinalReplacement.toString());
	}

	/**
	 * Set value of EquipmentFinalReplacement
	 * @param equipmentfinalreplacement
	 */
	public final void setEquipmentFinalReplacement(java.util.Date equipmentfinalreplacement)
	{
		setEquipmentFinalReplacement(getContext(), equipmentfinalreplacement);
	}

	/**
	 * Set value of EquipmentFinalReplacement
	 * @param context
	 * @param equipmentfinalreplacement
	 */
	public final void setEquipmentFinalReplacement(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentfinalreplacement)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentFinalReplacement.toString(), equipmentfinalreplacement);
	}

	/**
	 * @return value of EquipmentBOMCumulativeUsage
	 */
	public final java.lang.Integer getEquipmentBOMCumulativeUsage()
	{
		return getEquipmentBOMCumulativeUsage(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMCumulativeUsage
	 */
	public final java.lang.Integer getEquipmentBOMCumulativeUsage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentBOMCumulativeUsage.toString());
	}

	/**
	 * Set value of EquipmentBOMCumulativeUsage
	 * @param equipmentbomcumulativeusage
	 */
	public final void setEquipmentBOMCumulativeUsage(java.lang.Integer equipmentbomcumulativeusage)
	{
		setEquipmentBOMCumulativeUsage(getContext(), equipmentbomcumulativeusage);
	}

	/**
	 * Set value of EquipmentBOMCumulativeUsage
	 * @param context
	 * @param equipmentbomcumulativeusage
	 */
	public final void setEquipmentBOMCumulativeUsage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentbomcumulativeusage)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMCumulativeUsage.toString(), equipmentbomcumulativeusage);
	}

	/**
	 * @return value of EquipmentBOMMaximumUseOnce
	 */
	public final java.lang.Integer getEquipmentBOMMaximumUseOnce()
	{
		return getEquipmentBOMMaximumUseOnce(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMMaximumUseOnce
	 */
	public final java.lang.Integer getEquipmentBOMMaximumUseOnce(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentBOMMaximumUseOnce.toString());
	}

	/**
	 * Set value of EquipmentBOMMaximumUseOnce
	 * @param equipmentbommaximumuseonce
	 */
	public final void setEquipmentBOMMaximumUseOnce(java.lang.Integer equipmentbommaximumuseonce)
	{
		setEquipmentBOMMaximumUseOnce(getContext(), equipmentbommaximumuseonce);
	}

	/**
	 * Set value of EquipmentBOMMaximumUseOnce
	 * @param context
	 * @param equipmentbommaximumuseonce
	 */
	public final void setEquipmentBOMMaximumUseOnce(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentbommaximumuseonce)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMMaximumUseOnce.toString(), equipmentbommaximumuseonce);
	}

	/**
	 * @return value of EquipmentBOMAverageUsage
	 */
	public final java.lang.Integer getEquipmentBOMAverageUsage()
	{
		return getEquipmentBOMAverageUsage(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentBOMAverageUsage
	 */
	public final java.lang.Integer getEquipmentBOMAverageUsage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentBOMAverageUsage.toString());
	}

	/**
	 * Set value of EquipmentBOMAverageUsage
	 * @param equipmentbomaverageusage
	 */
	public final void setEquipmentBOMAverageUsage(java.lang.Integer equipmentbomaverageusage)
	{
		setEquipmentBOMAverageUsage(getContext(), equipmentbomaverageusage);
	}

	/**
	 * Set value of EquipmentBOMAverageUsage
	 * @param context
	 * @param equipmentbomaverageusage
	 */
	public final void setEquipmentBOMAverageUsage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentbomaverageusage)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentBOMAverageUsage.toString(), equipmentbomaverageusage);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_BOM_Equipment
	 */
	public final equipment_management.proxies.Equipment getEquipment_BOM_Equipment() throws com.mendix.core.CoreException
	{
		return getEquipment_BOM_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_BOM_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getEquipment_BOM_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_BOM_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_BOM_Equipment
	 * @param equipment_bom_equipment
	 */
	public final void setEquipment_BOM_Equipment(equipment_management.proxies.Equipment equipment_bom_equipment)
	{
		setEquipment_BOM_Equipment(getContext(), equipment_bom_equipment);
	}

	/**
	 * Set value of Equipment_BOM_Equipment
	 * @param context
	 * @param equipment_bom_equipment
	 */
	public final void setEquipment_BOM_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment equipment_bom_equipment)
	{
		if (equipment_bom_equipment == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_BOM_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_BOM_Equipment.toString(), equipment_bom_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_BOM_Material
	 */
	public final material_management.proxies.Material getEquipment_BOM_Material() throws com.mendix.core.CoreException
	{
		return getEquipment_BOM_Material(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_BOM_Material
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.Material getEquipment_BOM_Material(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.Material result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_BOM_Material.toString());
		if (identifier != null) {
			result = material_management.proxies.Material.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_BOM_Material
	 * @param equipment_bom_material
	 */
	public final void setEquipment_BOM_Material(material_management.proxies.Material equipment_bom_material)
	{
		setEquipment_BOM_Material(getContext(), equipment_bom_material);
	}

	/**
	 * Set value of Equipment_BOM_Material
	 * @param context
	 * @param equipment_bom_material
	 */
	public final void setEquipment_BOM_Material(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.Material equipment_bom_material)
	{
		if (equipment_bom_material == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_BOM_Material.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_BOM_Material.toString(), equipment_bom_material.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipment_BOMMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.Equipment_BOM that = (equipment_management.proxies.Equipment_BOM) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
