// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public class EquipmentSpecification implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentSpecificationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentSpecification";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentSpecName("EquipmentSpecName"),
		EquipenntSpecNameEnglish("EquipenntSpecNameEnglish"),
		EquipmentSpecValue("EquipmentSpecValue"),
		EquipmentSpecSequence("EquipmentSpecSequence"),
		IsEquipmentSpecActive("IsEquipmentSpecActive"),
		EquipmentSpecDescription("EquipmentSpecDescription"),
		EquipmentSpecification_Equipment("Equipment_Management.EquipmentSpecification_Equipment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentSpecification(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentSpecification(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentSpecificationMendixObject)
	{
		if (equipmentSpecificationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentSpecificationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentSpecificationMendixObject = equipmentSpecificationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentSpecification initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentSpecification(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentSpecification load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentSpecification.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentSpecification> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentSpecification.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EquipmentSpecName
	 */
	public final java.lang.String getEquipmentSpecName()
	{
		return getEquipmentSpecName(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSpecName
	 */
	public final java.lang.String getEquipmentSpecName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSpecName.toString());
	}

	/**
	 * Set value of EquipmentSpecName
	 * @param equipmentspecname
	 */
	public final void setEquipmentSpecName(java.lang.String equipmentspecname)
	{
		setEquipmentSpecName(getContext(), equipmentspecname);
	}

	/**
	 * Set value of EquipmentSpecName
	 * @param context
	 * @param equipmentspecname
	 */
	public final void setEquipmentSpecName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentspecname)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSpecName.toString(), equipmentspecname);
	}

	/**
	 * @return value of EquipenntSpecNameEnglish
	 */
	public final java.lang.String getEquipenntSpecNameEnglish()
	{
		return getEquipenntSpecNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipenntSpecNameEnglish
	 */
	public final java.lang.String getEquipenntSpecNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipenntSpecNameEnglish.toString());
	}

	/**
	 * Set value of EquipenntSpecNameEnglish
	 * @param equipenntspecnameenglish
	 */
	public final void setEquipenntSpecNameEnglish(java.lang.String equipenntspecnameenglish)
	{
		setEquipenntSpecNameEnglish(getContext(), equipenntspecnameenglish);
	}

	/**
	 * Set value of EquipenntSpecNameEnglish
	 * @param context
	 * @param equipenntspecnameenglish
	 */
	public final void setEquipenntSpecNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipenntspecnameenglish)
	{
		getMendixObject().setValue(context, MemberNames.EquipenntSpecNameEnglish.toString(), equipenntspecnameenglish);
	}

	/**
	 * @return value of EquipmentSpecValue
	 */
	public final java.lang.String getEquipmentSpecValue()
	{
		return getEquipmentSpecValue(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSpecValue
	 */
	public final java.lang.String getEquipmentSpecValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSpecValue.toString());
	}

	/**
	 * Set value of EquipmentSpecValue
	 * @param equipmentspecvalue
	 */
	public final void setEquipmentSpecValue(java.lang.String equipmentspecvalue)
	{
		setEquipmentSpecValue(getContext(), equipmentspecvalue);
	}

	/**
	 * Set value of EquipmentSpecValue
	 * @param context
	 * @param equipmentspecvalue
	 */
	public final void setEquipmentSpecValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentspecvalue)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSpecValue.toString(), equipmentspecvalue);
	}

	/**
	 * @return value of EquipmentSpecSequence
	 */
	public final java.lang.Integer getEquipmentSpecSequence()
	{
		return getEquipmentSpecSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSpecSequence
	 */
	public final java.lang.Integer getEquipmentSpecSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentSpecSequence.toString());
	}

	/**
	 * Set value of EquipmentSpecSequence
	 * @param equipmentspecsequence
	 */
	public final void setEquipmentSpecSequence(java.lang.Integer equipmentspecsequence)
	{
		setEquipmentSpecSequence(getContext(), equipmentspecsequence);
	}

	/**
	 * Set value of EquipmentSpecSequence
	 * @param context
	 * @param equipmentspecsequence
	 */
	public final void setEquipmentSpecSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentspecsequence)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSpecSequence.toString(), equipmentspecsequence);
	}

	/**
	 * @return value of IsEquipmentSpecActive
	 */
	public final java.lang.Boolean getIsEquipmentSpecActive()
	{
		return getIsEquipmentSpecActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEquipmentSpecActive
	 */
	public final java.lang.Boolean getIsEquipmentSpecActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEquipmentSpecActive.toString());
	}

	/**
	 * Set value of IsEquipmentSpecActive
	 * @param isequipmentspecactive
	 */
	public final void setIsEquipmentSpecActive(java.lang.Boolean isequipmentspecactive)
	{
		setIsEquipmentSpecActive(getContext(), isequipmentspecactive);
	}

	/**
	 * Set value of IsEquipmentSpecActive
	 * @param context
	 * @param isequipmentspecactive
	 */
	public final void setIsEquipmentSpecActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isequipmentspecactive)
	{
		getMendixObject().setValue(context, MemberNames.IsEquipmentSpecActive.toString(), isequipmentspecactive);
	}

	/**
	 * @return value of EquipmentSpecDescription
	 */
	public final java.lang.String getEquipmentSpecDescription()
	{
		return getEquipmentSpecDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSpecDescription
	 */
	public final java.lang.String getEquipmentSpecDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSpecDescription.toString());
	}

	/**
	 * Set value of EquipmentSpecDescription
	 * @param equipmentspecdescription
	 */
	public final void setEquipmentSpecDescription(java.lang.String equipmentspecdescription)
	{
		setEquipmentSpecDescription(getContext(), equipmentspecdescription);
	}

	/**
	 * Set value of EquipmentSpecDescription
	 * @param context
	 * @param equipmentspecdescription
	 */
	public final void setEquipmentSpecDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentspecdescription)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSpecDescription.toString(), equipmentspecdescription);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentSpecification_Equipment
	 */
	public final equipment_management.proxies.Equipment getEquipmentSpecification_Equipment() throws com.mendix.core.CoreException
	{
		return getEquipmentSpecification_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSpecification_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getEquipmentSpecification_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentSpecification_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentSpecification_Equipment
	 * @param equipmentspecification_equipment
	 */
	public final void setEquipmentSpecification_Equipment(equipment_management.proxies.Equipment equipmentspecification_equipment)
	{
		setEquipmentSpecification_Equipment(getContext(), equipmentspecification_equipment);
	}

	/**
	 * Set value of EquipmentSpecification_Equipment
	 * @param context
	 * @param equipmentspecification_equipment
	 */
	public final void setEquipmentSpecification_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment equipmentspecification_equipment)
	{
		if (equipmentspecification_equipment == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentSpecification_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentSpecification_Equipment.toString(), equipmentspecification_equipment.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentSpecificationMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentSpecification that = (equipment_management.proxies.EquipmentSpecification) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
