// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public class EquipmentDetailInformation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentDetailInformationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentDetailInformation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentDetail01("EquipmentDetail01"),
		EquipmentDetail02("EquipmentDetail02"),
		EquipmentDetail03("EquipmentDetail03"),
		EquipmentDetail04("EquipmentDetail04"),
		EquipmentDetail05("EquipmentDetail05"),
		Equipment_EquipmentDetailInformation("Equipment_Management.Equipment_EquipmentDetailInformation");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentDetailInformation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentDetailInformation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentDetailInformationMendixObject)
	{
		if (equipmentDetailInformationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentDetailInformationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentDetailInformationMendixObject = equipmentDetailInformationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentDetailInformation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentDetailInformation(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentDetailInformation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentDetailInformation.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentDetailInformation> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentDetailInformation.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EquipmentDetail01
	 */
	public final java.lang.String getEquipmentDetail01()
	{
		return getEquipmentDetail01(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDetail01
	 */
	public final java.lang.String getEquipmentDetail01(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentDetail01.toString());
	}

	/**
	 * Set value of EquipmentDetail01
	 * @param equipmentdetail01
	 */
	public final void setEquipmentDetail01(java.lang.String equipmentdetail01)
	{
		setEquipmentDetail01(getContext(), equipmentdetail01);
	}

	/**
	 * Set value of EquipmentDetail01
	 * @param context
	 * @param equipmentdetail01
	 */
	public final void setEquipmentDetail01(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentdetail01)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDetail01.toString(), equipmentdetail01);
	}

	/**
	 * @return value of EquipmentDetail02
	 */
	public final java.lang.String getEquipmentDetail02()
	{
		return getEquipmentDetail02(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDetail02
	 */
	public final java.lang.String getEquipmentDetail02(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentDetail02.toString());
	}

	/**
	 * Set value of EquipmentDetail02
	 * @param equipmentdetail02
	 */
	public final void setEquipmentDetail02(java.lang.String equipmentdetail02)
	{
		setEquipmentDetail02(getContext(), equipmentdetail02);
	}

	/**
	 * Set value of EquipmentDetail02
	 * @param context
	 * @param equipmentdetail02
	 */
	public final void setEquipmentDetail02(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentdetail02)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDetail02.toString(), equipmentdetail02);
	}

	/**
	 * @return value of EquipmentDetail03
	 */
	public final java.lang.String getEquipmentDetail03()
	{
		return getEquipmentDetail03(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDetail03
	 */
	public final java.lang.String getEquipmentDetail03(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentDetail03.toString());
	}

	/**
	 * Set value of EquipmentDetail03
	 * @param equipmentdetail03
	 */
	public final void setEquipmentDetail03(java.lang.String equipmentdetail03)
	{
		setEquipmentDetail03(getContext(), equipmentdetail03);
	}

	/**
	 * Set value of EquipmentDetail03
	 * @param context
	 * @param equipmentdetail03
	 */
	public final void setEquipmentDetail03(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentdetail03)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDetail03.toString(), equipmentdetail03);
	}

	/**
	 * @return value of EquipmentDetail04
	 */
	public final java.lang.String getEquipmentDetail04()
	{
		return getEquipmentDetail04(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDetail04
	 */
	public final java.lang.String getEquipmentDetail04(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentDetail04.toString());
	}

	/**
	 * Set value of EquipmentDetail04
	 * @param equipmentdetail04
	 */
	public final void setEquipmentDetail04(java.lang.String equipmentdetail04)
	{
		setEquipmentDetail04(getContext(), equipmentdetail04);
	}

	/**
	 * Set value of EquipmentDetail04
	 * @param context
	 * @param equipmentdetail04
	 */
	public final void setEquipmentDetail04(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentdetail04)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDetail04.toString(), equipmentdetail04);
	}

	/**
	 * @return value of EquipmentDetail05
	 */
	public final java.lang.String getEquipmentDetail05()
	{
		return getEquipmentDetail05(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDetail05
	 */
	public final java.lang.String getEquipmentDetail05(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentDetail05.toString());
	}

	/**
	 * Set value of EquipmentDetail05
	 * @param equipmentdetail05
	 */
	public final void setEquipmentDetail05(java.lang.String equipmentdetail05)
	{
		setEquipmentDetail05(getContext(), equipmentdetail05);
	}

	/**
	 * Set value of EquipmentDetail05
	 * @param context
	 * @param equipmentdetail05
	 */
	public final void setEquipmentDetail05(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentdetail05)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDetail05.toString(), equipmentdetail05);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EquipmentDetailInformation
	 */
	public final equipment_management.proxies.Equipment getEquipment_EquipmentDetailInformation() throws com.mendix.core.CoreException
	{
		return getEquipment_EquipmentDetailInformation(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EquipmentDetailInformation
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getEquipment_EquipmentDetailInformation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EquipmentDetailInformation.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EquipmentDetailInformation
	 * @param equipment_equipmentdetailinformation
	 */
	public final void setEquipment_EquipmentDetailInformation(equipment_management.proxies.Equipment equipment_equipmentdetailinformation)
	{
		setEquipment_EquipmentDetailInformation(getContext(), equipment_equipmentdetailinformation);
	}

	/**
	 * Set value of Equipment_EquipmentDetailInformation
	 * @param context
	 * @param equipment_equipmentdetailinformation
	 */
	public final void setEquipment_EquipmentDetailInformation(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment equipment_equipmentdetailinformation)
	{
		if (equipment_equipmentdetailinformation == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentDetailInformation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentDetailInformation.toString(), equipment_equipmentdetailinformation.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentDetailInformationMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentDetailInformation that = (equipment_management.proxies.EquipmentDetailInformation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
