// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/15
 * 최종 수정자 : 
 * 최종 수정일 : 
 * 
 * 설명 : 설비위치 엔터티
 * 
 * Version 1.0 : 생성
 */
public class EquipmentLocation implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentLocationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentLocation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentLocationParentName("EquipmentLocationParentName"),
		EquipmentLocationCode("EquipmentLocationCode"),
		EquipmentLocationName("EquipmentLocationName"),
		EquipmentLocationNameEnglish("EquipmentLocationNameEnglish"),
		EquipmentLocationPath("EquipmentLocationPath"),
		EquipmentLocationNumber("EquipmentLocationNumber"),
		EquipmentLocationDescription("EquipmentLocationDescription"),
		EquipmentLocationRoot("EquipmentLocationRoot"),
		EquipmentLocation_EquipmentLocationhelper("Equipment_Management.EquipmentLocation_EquipmentLocationhelper"),
		Parent_EquipmentLocation("Equipment_Management.Parent_EquipmentLocation"),
		EquipmentLocation_EquipmentLocationhelper_Child("Equipment_Management.EquipmentLocation_EquipmentLocationhelper_Child"),
		EquipmentLocation_Plant("Equipment_Management.EquipmentLocation_Plant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentLocation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentLocationMendixObject)
	{
		if (equipmentLocationMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentLocationMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentLocationMendixObject = equipmentLocationMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentLocation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentLocation(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentLocation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentLocation.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentLocation> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentLocation.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EquipmentLocationParentName
	 */
	public final java.lang.String getEquipmentLocationParentName()
	{
		return getEquipmentLocationParentName(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationParentName
	 */
	public final java.lang.String getEquipmentLocationParentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentLocationParentName.toString());
	}

	/**
	 * Set value of EquipmentLocationParentName
	 * @param equipmentlocationparentname
	 */
	public final void setEquipmentLocationParentName(java.lang.String equipmentlocationparentname)
	{
		setEquipmentLocationParentName(getContext(), equipmentlocationparentname);
	}

	/**
	 * Set value of EquipmentLocationParentName
	 * @param context
	 * @param equipmentlocationparentname
	 */
	public final void setEquipmentLocationParentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentlocationparentname)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLocationParentName.toString(), equipmentlocationparentname);
	}

	/**
	 * @return value of EquipmentLocationCode
	 */
	public final java.lang.String getEquipmentLocationCode()
	{
		return getEquipmentLocationCode(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationCode
	 */
	public final java.lang.String getEquipmentLocationCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentLocationCode.toString());
	}

	/**
	 * Set value of EquipmentLocationCode
	 * @param equipmentlocationcode
	 */
	public final void setEquipmentLocationCode(java.lang.String equipmentlocationcode)
	{
		setEquipmentLocationCode(getContext(), equipmentlocationcode);
	}

	/**
	 * Set value of EquipmentLocationCode
	 * @param context
	 * @param equipmentlocationcode
	 */
	public final void setEquipmentLocationCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentlocationcode)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLocationCode.toString(), equipmentlocationcode);
	}

	/**
	 * @return value of EquipmentLocationName
	 */
	public final java.lang.String getEquipmentLocationName()
	{
		return getEquipmentLocationName(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationName
	 */
	public final java.lang.String getEquipmentLocationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentLocationName.toString());
	}

	/**
	 * Set value of EquipmentLocationName
	 * @param equipmentlocationname
	 */
	public final void setEquipmentLocationName(java.lang.String equipmentlocationname)
	{
		setEquipmentLocationName(getContext(), equipmentlocationname);
	}

	/**
	 * Set value of EquipmentLocationName
	 * @param context
	 * @param equipmentlocationname
	 */
	public final void setEquipmentLocationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentlocationname)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLocationName.toString(), equipmentlocationname);
	}

	/**
	 * @return value of EquipmentLocationNameEnglish
	 */
	public final java.lang.String getEquipmentLocationNameEnglish()
	{
		return getEquipmentLocationNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationNameEnglish
	 */
	public final java.lang.String getEquipmentLocationNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentLocationNameEnglish.toString());
	}

	/**
	 * Set value of EquipmentLocationNameEnglish
	 * @param equipmentlocationnameenglish
	 */
	public final void setEquipmentLocationNameEnglish(java.lang.String equipmentlocationnameenglish)
	{
		setEquipmentLocationNameEnglish(getContext(), equipmentlocationnameenglish);
	}

	/**
	 * Set value of EquipmentLocationNameEnglish
	 * @param context
	 * @param equipmentlocationnameenglish
	 */
	public final void setEquipmentLocationNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentlocationnameenglish)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLocationNameEnglish.toString(), equipmentlocationnameenglish);
	}

	/**
	 * @return value of EquipmentLocationPath
	 */
	public final java.lang.String getEquipmentLocationPath()
	{
		return getEquipmentLocationPath(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationPath
	 */
	public final java.lang.String getEquipmentLocationPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentLocationPath.toString());
	}

	/**
	 * Set value of EquipmentLocationPath
	 * @param equipmentlocationpath
	 */
	public final void setEquipmentLocationPath(java.lang.String equipmentlocationpath)
	{
		setEquipmentLocationPath(getContext(), equipmentlocationpath);
	}

	/**
	 * Set value of EquipmentLocationPath
	 * @param context
	 * @param equipmentlocationpath
	 */
	public final void setEquipmentLocationPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentlocationpath)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLocationPath.toString(), equipmentlocationpath);
	}

	/**
	 * @return value of EquipmentLocationNumber
	 */
	public final java.lang.Integer getEquipmentLocationNumber()
	{
		return getEquipmentLocationNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationNumber
	 */
	public final java.lang.Integer getEquipmentLocationNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentLocationNumber.toString());
	}

	/**
	 * Set value of EquipmentLocationNumber
	 * @param equipmentlocationnumber
	 */
	public final void setEquipmentLocationNumber(java.lang.Integer equipmentlocationnumber)
	{
		setEquipmentLocationNumber(getContext(), equipmentlocationnumber);
	}

	/**
	 * Set value of EquipmentLocationNumber
	 * @param context
	 * @param equipmentlocationnumber
	 */
	public final void setEquipmentLocationNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentlocationnumber)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLocationNumber.toString(), equipmentlocationnumber);
	}

	/**
	 * @return value of EquipmentLocationDescription
	 */
	public final java.lang.String getEquipmentLocationDescription()
	{
		return getEquipmentLocationDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationDescription
	 */
	public final java.lang.String getEquipmentLocationDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentLocationDescription.toString());
	}

	/**
	 * Set value of EquipmentLocationDescription
	 * @param equipmentlocationdescription
	 */
	public final void setEquipmentLocationDescription(java.lang.String equipmentlocationdescription)
	{
		setEquipmentLocationDescription(getContext(), equipmentlocationdescription);
	}

	/**
	 * Set value of EquipmentLocationDescription
	 * @param context
	 * @param equipmentlocationdescription
	 */
	public final void setEquipmentLocationDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentlocationdescription)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLocationDescription.toString(), equipmentlocationdescription);
	}

	/**
	 * @return value of EquipmentLocationRoot
	 */
	public final java.lang.Boolean getEquipmentLocationRoot()
	{
		return getEquipmentLocationRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationRoot
	 */
	public final java.lang.Boolean getEquipmentLocationRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentLocationRoot.toString());
	}

	/**
	 * Set value of EquipmentLocationRoot
	 * @param equipmentlocationroot
	 */
	public final void setEquipmentLocationRoot(java.lang.Boolean equipmentlocationroot)
	{
		setEquipmentLocationRoot(getContext(), equipmentlocationroot);
	}

	/**
	 * Set value of EquipmentLocationRoot
	 * @param context
	 * @param equipmentlocationroot
	 */
	public final void setEquipmentLocationRoot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmentlocationroot)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLocationRoot.toString(), equipmentlocationroot);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentLocation_EquipmentLocationhelper
	 */
	public final equipment_management.proxies.EquipmentLocationhelper getEquipmentLocation_EquipmentLocationhelper() throws com.mendix.core.CoreException
	{
		return getEquipmentLocation_EquipmentLocationhelper(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocation_EquipmentLocationhelper
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentLocationhelper getEquipmentLocation_EquipmentLocationhelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentLocationhelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentLocation_EquipmentLocationhelper.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentLocationhelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentLocation_EquipmentLocationhelper
	 * @param equipmentlocation_equipmentlocationhelper
	 */
	public final void setEquipmentLocation_EquipmentLocationhelper(equipment_management.proxies.EquipmentLocationhelper equipmentlocation_equipmentlocationhelper)
	{
		setEquipmentLocation_EquipmentLocationhelper(getContext(), equipmentlocation_equipmentlocationhelper);
	}

	/**
	 * Set value of EquipmentLocation_EquipmentLocationhelper
	 * @param context
	 * @param equipmentlocation_equipmentlocationhelper
	 */
	public final void setEquipmentLocation_EquipmentLocationhelper(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentLocationhelper equipmentlocation_equipmentlocationhelper)
	{
		if (equipmentlocation_equipmentlocationhelper == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentLocation_EquipmentLocationhelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentLocation_EquipmentLocationhelper.toString(), equipmentlocation_equipmentlocationhelper.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_EquipmentLocation
	 */
	public final equipment_management.proxies.EquipmentLocation getParent_EquipmentLocation() throws com.mendix.core.CoreException
	{
		return getParent_EquipmentLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_EquipmentLocation
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentLocation getParent_EquipmentLocation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentLocation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_EquipmentLocation.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentLocation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_EquipmentLocation
	 * @param parent_equipmentlocation
	 */
	public final void setParent_EquipmentLocation(equipment_management.proxies.EquipmentLocation parent_equipmentlocation)
	{
		setParent_EquipmentLocation(getContext(), parent_equipmentlocation);
	}

	/**
	 * Set value of Parent_EquipmentLocation
	 * @param context
	 * @param parent_equipmentlocation
	 */
	public final void setParent_EquipmentLocation(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentLocation parent_equipmentlocation)
	{
		if (parent_equipmentlocation == null) {
			getMendixObject().setValue(context, MemberNames.Parent_EquipmentLocation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_EquipmentLocation.toString(), parent_equipmentlocation.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentLocation_EquipmentLocationhelper_Child
	 */
	public final equipment_management.proxies.EquipmentLocationhelper_Child getEquipmentLocation_EquipmentLocationhelper_Child() throws com.mendix.core.CoreException
	{
		return getEquipmentLocation_EquipmentLocationhelper_Child(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocation_EquipmentLocationhelper_Child
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentLocationhelper_Child getEquipmentLocation_EquipmentLocationhelper_Child(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentLocationhelper_Child result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentLocation_EquipmentLocationhelper_Child.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentLocationhelper_Child.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentLocation_EquipmentLocationhelper_Child
	 * @param equipmentlocation_equipmentlocationhelper_child
	 */
	public final void setEquipmentLocation_EquipmentLocationhelper_Child(equipment_management.proxies.EquipmentLocationhelper_Child equipmentlocation_equipmentlocationhelper_child)
	{
		setEquipmentLocation_EquipmentLocationhelper_Child(getContext(), equipmentlocation_equipmentlocationhelper_child);
	}

	/**
	 * Set value of EquipmentLocation_EquipmentLocationhelper_Child
	 * @param context
	 * @param equipmentlocation_equipmentlocationhelper_child
	 */
	public final void setEquipmentLocation_EquipmentLocationhelper_Child(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentLocationhelper_Child equipmentlocation_equipmentlocationhelper_child)
	{
		if (equipmentlocation_equipmentlocationhelper_child == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentLocation_EquipmentLocationhelper_Child.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentLocation_EquipmentLocationhelper_Child.toString(), equipmentlocation_equipmentlocationhelper_child.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentLocation_Plant
	 */
	public final cmms_administration.proxies.Plant getEquipmentLocation_Plant() throws com.mendix.core.CoreException
	{
		return getEquipmentLocation_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocation_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getEquipmentLocation_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentLocation_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentLocation_Plant
	 * @param equipmentlocation_plant
	 */
	public final void setEquipmentLocation_Plant(cmms_administration.proxies.Plant equipmentlocation_plant)
	{
		setEquipmentLocation_Plant(getContext(), equipmentlocation_plant);
	}

	/**
	 * Set value of EquipmentLocation_Plant
	 * @param context
	 * @param equipmentlocation_plant
	 */
	public final void setEquipmentLocation_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant equipmentlocation_plant)
	{
		if (equipmentlocation_plant == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentLocation_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentLocation_Plant.toString(), equipmentlocation_plant.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentLocationMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentLocation that = (equipment_management.proxies.EquipmentLocation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
