// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/15
 * 최종 수정자 : 
 * 최종 수정일 : 2023/09/15
 * 설명 : 트리에서 선택한 노드의 정보를 불러오기 위한 PE
 * Version 1.0 : 생성
 */
public class EquipmentLocationhelper_Child implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentLocationhelper_ChildMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentLocationhelper_Child";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Active("Active"),
		EquipmentLocationhelper_Child_Account("Equipment_Management.EquipmentLocationhelper_Child_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentLocationhelper_Child(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentLocationhelper_Child(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentLocationhelper_ChildMendixObject)
	{
		if (equipmentLocationhelper_ChildMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentLocationhelper_ChildMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentLocationhelper_ChildMendixObject = equipmentLocationhelper_ChildMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentLocationhelper_Child initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentLocationhelper_Child(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentLocationhelper_Child load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentLocationhelper_Child.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentLocationhelper_Child> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentLocationhelper_Child.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentLocationhelper_Child_Account
	 */
	public final administration.proxies.Account getEquipmentLocationhelper_Child_Account() throws com.mendix.core.CoreException
	{
		return getEquipmentLocationhelper_Child_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLocationhelper_Child_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getEquipmentLocationhelper_Child_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentLocationhelper_Child_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentLocationhelper_Child_Account
	 * @param equipmentlocationhelper_child_account
	 */
	public final void setEquipmentLocationhelper_Child_Account(administration.proxies.Account equipmentlocationhelper_child_account)
	{
		setEquipmentLocationhelper_Child_Account(getContext(), equipmentlocationhelper_child_account);
	}

	/**
	 * Set value of EquipmentLocationhelper_Child_Account
	 * @param context
	 * @param equipmentlocationhelper_child_account
	 */
	public final void setEquipmentLocationhelper_Child_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account equipmentlocationhelper_child_account)
	{
		if (equipmentlocationhelper_child_account == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentLocationhelper_Child_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentLocationhelper_Child_Account.toString(), equipmentlocationhelper_child_account.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentLocationhelper_ChildMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentLocationhelper_Child that = (equipment_management.proxies.EquipmentLocationhelper_Child) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
