// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public class Equipment_Image_Helper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipment_Image_HelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.Equipment_Image_Helper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Equipment_Image_Helper_Equipment("Equipment_Management.Equipment_Image_Helper_Equipment"),
		Equipment_Image_Helper_EquipmentImage("Equipment_Management.Equipment_Image_Helper_EquipmentImage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Equipment_Image_Helper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Equipment_Image_Helper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipment_Image_HelperMendixObject)
	{
		if (equipment_Image_HelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipment_Image_HelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipment_Image_HelperMendixObject = equipment_Image_HelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.Equipment_Image_Helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.Equipment_Image_Helper(context, mendixObject);
	}

	public static equipment_management.proxies.Equipment_Image_Helper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.Equipment_Image_Helper.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_Image_Helper_Equipment
	 */
	public final equipment_management.proxies.Equipment getEquipment_Image_Helper_Equipment() throws com.mendix.core.CoreException
	{
		return getEquipment_Image_Helper_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_Image_Helper_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getEquipment_Image_Helper_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_Image_Helper_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_Image_Helper_Equipment
	 * @param equipment_image_helper_equipment
	 */
	public final void setEquipment_Image_Helper_Equipment(equipment_management.proxies.Equipment equipment_image_helper_equipment)
	{
		setEquipment_Image_Helper_Equipment(getContext(), equipment_image_helper_equipment);
	}

	/**
	 * Set value of Equipment_Image_Helper_Equipment
	 * @param context
	 * @param equipment_image_helper_equipment
	 */
	public final void setEquipment_Image_Helper_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment equipment_image_helper_equipment)
	{
		if (equipment_image_helper_equipment == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_Image_Helper_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_Image_Helper_Equipment.toString(), equipment_image_helper_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_Image_Helper_EquipmentImage
	 */
	public final equipment_management.proxies.EquipmentImage getEquipment_Image_Helper_EquipmentImage() throws com.mendix.core.CoreException
	{
		return getEquipment_Image_Helper_EquipmentImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_Image_Helper_EquipmentImage
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentImage getEquipment_Image_Helper_EquipmentImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_Image_Helper_EquipmentImage.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_Image_Helper_EquipmentImage
	 * @param equipment_image_helper_equipmentimage
	 */
	public final void setEquipment_Image_Helper_EquipmentImage(equipment_management.proxies.EquipmentImage equipment_image_helper_equipmentimage)
	{
		setEquipment_Image_Helper_EquipmentImage(getContext(), equipment_image_helper_equipmentimage);
	}

	/**
	 * Set value of Equipment_Image_Helper_EquipmentImage
	 * @param context
	 * @param equipment_image_helper_equipmentimage
	 */
	public final void setEquipment_Image_Helper_EquipmentImage(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentImage equipment_image_helper_equipmentimage)
	{
		if (equipment_image_helper_equipmentimage == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_Image_Helper_EquipmentImage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_Image_Helper_EquipmentImage.toString(), equipment_image_helper_equipmentimage.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipment_Image_HelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.Equipment_Image_Helper that = (equipment_management.proxies.Equipment_Image_Helper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
