// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초작성자 : 김동명
 * 최초작성일 : 2023-11-30
 * 
 * 설명 : 설비를 선택해서 해당하는 BOM을 보여주기 위한 헬퍼
 * 
 * V1.0 : 최초작성
 */
public class Equipment_BOM_Helper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipment_BOM_HelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.Equipment_BOM_Helper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HelperAtrribute("HelperAtrribute"),
		Equipment_BOM_Helper_Equipment("Equipment_Management.Equipment_BOM_Helper_Equipment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Equipment_BOM_Helper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Equipment_BOM_Helper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipment_BOM_HelperMendixObject)
	{
		if (equipment_BOM_HelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipment_BOM_HelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipment_BOM_HelperMendixObject = equipment_BOM_HelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.Equipment_BOM_Helper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.Equipment_BOM_Helper(context, mendixObject);
	}

	public static equipment_management.proxies.Equipment_BOM_Helper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.Equipment_BOM_Helper.initialize(context, mendixObject);
	}

	/**
	 * Get value of HelperAtrribute
	 * @param helperatrribute
	 */
	public final equipment_management.proxies.ENU_Equipment_BOM_Menu_Type getHelperAtrribute()
	{
		return getHelperAtrribute(getContext());
	}

	/**
	 * @param context
	 * @return value of HelperAtrribute
	 */
	public final equipment_management.proxies.ENU_Equipment_BOM_Menu_Type getHelperAtrribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.HelperAtrribute.toString());
		if (obj == null) {
			return null;
		}
		return equipment_management.proxies.ENU_Equipment_BOM_Menu_Type.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of HelperAtrribute
	 * @param helperatrribute
	 */
	public final void setHelperAtrribute(equipment_management.proxies.ENU_Equipment_BOM_Menu_Type helperatrribute)
	{
		setHelperAtrribute(getContext(), helperatrribute);
	}

	/**
	 * Set value of HelperAtrribute
	 * @param context
	 * @param helperatrribute
	 */
	public final void setHelperAtrribute(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.ENU_Equipment_BOM_Menu_Type helperatrribute)
	{
		if (helperatrribute != null) {
			getMendixObject().setValue(context, MemberNames.HelperAtrribute.toString(), helperatrribute.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.HelperAtrribute.toString(), null);
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_BOM_Helper_Equipment
	 */
	public final equipment_management.proxies.Equipment getEquipment_BOM_Helper_Equipment() throws com.mendix.core.CoreException
	{
		return getEquipment_BOM_Helper_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_BOM_Helper_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getEquipment_BOM_Helper_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_BOM_Helper_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_BOM_Helper_Equipment
	 * @param equipment_bom_helper_equipment
	 */
	public final void setEquipment_BOM_Helper_Equipment(equipment_management.proxies.Equipment equipment_bom_helper_equipment)
	{
		setEquipment_BOM_Helper_Equipment(getContext(), equipment_bom_helper_equipment);
	}

	/**
	 * Set value of Equipment_BOM_Helper_Equipment
	 * @param context
	 * @param equipment_bom_helper_equipment
	 */
	public final void setEquipment_BOM_Helper_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment equipment_bom_helper_equipment)
	{
		if (equipment_bom_helper_equipment == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_BOM_Helper_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_BOM_Helper_Equipment.toString(), equipment_bom_helper_equipment.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipment_BOM_HelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.Equipment_BOM_Helper that = (equipment_management.proxies.Equipment_BOM_Helper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
