// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/21
 * 최종 수정자 : 
 * 최종 수정일 : 
 * 
 * 설명 : 설비 이동관리 이력을 위한 Entity
 *  
 * V1.0 : 최초작성
 */
public class EquipmentMovement implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentMovementMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentMovement";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MovementDay("MovementDay"),
		Description("Description"),
		SerialNumber("SerialNumber"),
		Edit("Edit"),
		ManagerName("ManagerName"),
		ApproverName("ApproverName"),
		LocationBefore("LocationBefore"),
		LocationAfter("LocationAfter"),
		EquipmentMovement_Equipment_History("Equipment_Management.EquipmentMovement_Equipment_History"),
		EquipmentMovement_EquipmentMovementImage_Before("Equipment_Management.EquipmentMovement_EquipmentMovementImage_Before"),
		EquipmentMovement_EquipmentMovementImage_After("Equipment_Management.EquipmentMovement_EquipmentMovementImage_After");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentMovement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentMovement(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentMovementMendixObject)
	{
		if (equipmentMovementMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentMovementMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentMovementMendixObject = equipmentMovementMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentMovement initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentMovement(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentMovement load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentMovement.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentMovement> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentMovement.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MovementDay
	 */
	public final java.util.Date getMovementDay()
	{
		return getMovementDay(getContext());
	}

	/**
	 * @param context
	 * @return value of MovementDay
	 */
	public final java.util.Date getMovementDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MovementDay.toString());
	}

	/**
	 * Set value of MovementDay
	 * @param movementday
	 */
	public final void setMovementDay(java.util.Date movementday)
	{
		setMovementDay(getContext(), movementday);
	}

	/**
	 * Set value of MovementDay
	 * @param context
	 * @param movementday
	 */
	public final void setMovementDay(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date movementday)
	{
		getMendixObject().setValue(context, MemberNames.MovementDay.toString(), movementday);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of SerialNumber
	 */
	public final java.lang.String getSerialNumber()
	{
		return getSerialNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of SerialNumber
	 */
	public final java.lang.String getSerialNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SerialNumber.toString());
	}

	/**
	 * Set value of SerialNumber
	 * @param serialnumber
	 */
	public final void setSerialNumber(java.lang.String serialnumber)
	{
		setSerialNumber(getContext(), serialnumber);
	}

	/**
	 * Set value of SerialNumber
	 * @param context
	 * @param serialnumber
	 */
	public final void setSerialNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String serialnumber)
	{
		getMendixObject().setValue(context, MemberNames.SerialNumber.toString(), serialnumber);
	}

	/**
	 * @return value of Edit
	 */
	public final java.lang.Boolean getEdit()
	{
		return getEdit(getContext());
	}

	/**
	 * @param context
	 * @return value of Edit
	 */
	public final java.lang.Boolean getEdit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Edit.toString());
	}

	/**
	 * Set value of Edit
	 * @param edit
	 */
	public final void setEdit(java.lang.Boolean edit)
	{
		setEdit(getContext(), edit);
	}

	/**
	 * Set value of Edit
	 * @param context
	 * @param edit
	 */
	public final void setEdit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean edit)
	{
		getMendixObject().setValue(context, MemberNames.Edit.toString(), edit);
	}

	/**
	 * @return value of ManagerName
	 */
	public final java.lang.String getManagerName()
	{
		return getManagerName(getContext());
	}

	/**
	 * @param context
	 * @return value of ManagerName
	 */
	public final java.lang.String getManagerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ManagerName.toString());
	}

	/**
	 * Set value of ManagerName
	 * @param managername
	 */
	public final void setManagerName(java.lang.String managername)
	{
		setManagerName(getContext(), managername);
	}

	/**
	 * Set value of ManagerName
	 * @param context
	 * @param managername
	 */
	public final void setManagerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String managername)
	{
		getMendixObject().setValue(context, MemberNames.ManagerName.toString(), managername);
	}

	/**
	 * @return value of ApproverName
	 */
	public final java.lang.String getApproverName()
	{
		return getApproverName(getContext());
	}

	/**
	 * @param context
	 * @return value of ApproverName
	 */
	public final java.lang.String getApproverName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApproverName.toString());
	}

	/**
	 * Set value of ApproverName
	 * @param approvername
	 */
	public final void setApproverName(java.lang.String approvername)
	{
		setApproverName(getContext(), approvername);
	}

	/**
	 * Set value of ApproverName
	 * @param context
	 * @param approvername
	 */
	public final void setApproverName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String approvername)
	{
		getMendixObject().setValue(context, MemberNames.ApproverName.toString(), approvername);
	}

	/**
	 * @return value of LocationBefore
	 */
	public final java.lang.String getLocationBefore()
	{
		return getLocationBefore(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationBefore
	 */
	public final java.lang.String getLocationBefore(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationBefore.toString());
	}

	/**
	 * Set value of LocationBefore
	 * @param locationbefore
	 */
	public final void setLocationBefore(java.lang.String locationbefore)
	{
		setLocationBefore(getContext(), locationbefore);
	}

	/**
	 * Set value of LocationBefore
	 * @param context
	 * @param locationbefore
	 */
	public final void setLocationBefore(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationbefore)
	{
		getMendixObject().setValue(context, MemberNames.LocationBefore.toString(), locationbefore);
	}

	/**
	 * @return value of LocationAfter
	 */
	public final java.lang.String getLocationAfter()
	{
		return getLocationAfter(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationAfter
	 */
	public final java.lang.String getLocationAfter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationAfter.toString());
	}

	/**
	 * Set value of LocationAfter
	 * @param locationafter
	 */
	public final void setLocationAfter(java.lang.String locationafter)
	{
		setLocationAfter(getContext(), locationafter);
	}

	/**
	 * Set value of LocationAfter
	 * @param context
	 * @param locationafter
	 */
	public final void setLocationAfter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationafter)
	{
		getMendixObject().setValue(context, MemberNames.LocationAfter.toString(), locationafter);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentMovement_Equipment_History
	 */
	public final equipment_management.proxies.Equipment getEquipmentMovement_Equipment_History() throws com.mendix.core.CoreException
	{
		return getEquipmentMovement_Equipment_History(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentMovement_Equipment_History
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getEquipmentMovement_Equipment_History(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentMovement_Equipment_History.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentMovement_Equipment_History
	 * @param equipmentmovement_equipment_history
	 */
	public final void setEquipmentMovement_Equipment_History(equipment_management.proxies.Equipment equipmentmovement_equipment_history)
	{
		setEquipmentMovement_Equipment_History(getContext(), equipmentmovement_equipment_history);
	}

	/**
	 * Set value of EquipmentMovement_Equipment_History
	 * @param context
	 * @param equipmentmovement_equipment_history
	 */
	public final void setEquipmentMovement_Equipment_History(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment equipmentmovement_equipment_history)
	{
		if (equipmentmovement_equipment_history == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentMovement_Equipment_History.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentMovement_Equipment_History.toString(), equipmentmovement_equipment_history.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentMovement_EquipmentMovementImage_Before
	 */
	public final equipment_management.proxies.EquipmentMovementImage getEquipmentMovement_EquipmentMovementImage_Before() throws com.mendix.core.CoreException
	{
		return getEquipmentMovement_EquipmentMovementImage_Before(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentMovement_EquipmentMovementImage_Before
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentMovementImage getEquipmentMovement_EquipmentMovementImage_Before(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentMovementImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentMovement_EquipmentMovementImage_Before.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentMovementImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentMovement_EquipmentMovementImage_Before
	 * @param equipmentmovement_equipmentmovementimage_before
	 */
	public final void setEquipmentMovement_EquipmentMovementImage_Before(equipment_management.proxies.EquipmentMovementImage equipmentmovement_equipmentmovementimage_before)
	{
		setEquipmentMovement_EquipmentMovementImage_Before(getContext(), equipmentmovement_equipmentmovementimage_before);
	}

	/**
	 * Set value of EquipmentMovement_EquipmentMovementImage_Before
	 * @param context
	 * @param equipmentmovement_equipmentmovementimage_before
	 */
	public final void setEquipmentMovement_EquipmentMovementImage_Before(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentMovementImage equipmentmovement_equipmentmovementimage_before)
	{
		if (equipmentmovement_equipmentmovementimage_before == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentMovement_EquipmentMovementImage_Before.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentMovement_EquipmentMovementImage_Before.toString(), equipmentmovement_equipmentmovementimage_before.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentMovement_EquipmentMovementImage_After
	 */
	public final equipment_management.proxies.EquipmentMovementImage getEquipmentMovement_EquipmentMovementImage_After() throws com.mendix.core.CoreException
	{
		return getEquipmentMovement_EquipmentMovementImage_After(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentMovement_EquipmentMovementImage_After
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentMovementImage getEquipmentMovement_EquipmentMovementImage_After(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentMovementImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentMovement_EquipmentMovementImage_After.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentMovementImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentMovement_EquipmentMovementImage_After
	 * @param equipmentmovement_equipmentmovementimage_after
	 */
	public final void setEquipmentMovement_EquipmentMovementImage_After(equipment_management.proxies.EquipmentMovementImage equipmentmovement_equipmentmovementimage_after)
	{
		setEquipmentMovement_EquipmentMovementImage_After(getContext(), equipmentmovement_equipmentmovementimage_after);
	}

	/**
	 * Set value of EquipmentMovement_EquipmentMovementImage_After
	 * @param context
	 * @param equipmentmovement_equipmentmovementimage_after
	 */
	public final void setEquipmentMovement_EquipmentMovementImage_After(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentMovementImage equipmentmovement_equipmentmovementimage_after)
	{
		if (equipmentmovement_equipmentmovementimage_after == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentMovement_EquipmentMovementImage_After.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentMovement_EquipmentMovementImage_After.toString(), equipmentmovement_equipmentmovementimage_after.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentMovementMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentMovement that = (equipment_management.proxies.EquipmentMovement) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
