// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public class EquipmentEDMFileImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.EquipmentEDMFileImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		EquipmentEDMFileImage_EquipmentEDMFile("Equipment_Management.EquipmentEDMFileImage_EquipmentEDMFile");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentEDMFileImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentEDMFileImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentEDMFileImageMendixObject)
	{
		super(context, equipmentEDMFileImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentEDMFileImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.EquipmentEDMFileImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.EquipmentEDMFileImage(context, mendixObject);
	}

	public static equipment_management.proxies.EquipmentEDMFileImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.EquipmentEDMFileImage.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.EquipmentEDMFileImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.EquipmentEDMFileImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentEDMFileImage_EquipmentEDMFile
	 */
	public final equipment_management.proxies.EquipmentEDMFile getEquipmentEDMFileImage_EquipmentEDMFile() throws com.mendix.core.CoreException
	{
		return getEquipmentEDMFileImage_EquipmentEDMFile(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentEDMFileImage_EquipmentEDMFile
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentEDMFile getEquipmentEDMFileImage_EquipmentEDMFile(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentEDMFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentEDMFileImage_EquipmentEDMFile.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentEDMFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentEDMFileImage_EquipmentEDMFile
	 * @param equipmentedmfileimage_equipmentedmfile
	 */
	public final void setEquipmentEDMFileImage_EquipmentEDMFile(equipment_management.proxies.EquipmentEDMFile equipmentedmfileimage_equipmentedmfile)
	{
		setEquipmentEDMFileImage_EquipmentEDMFile(getContext(), equipmentedmfileimage_equipmentedmfile);
	}

	/**
	 * Set value of EquipmentEDMFileImage_EquipmentEDMFile
	 * @param context
	 * @param equipmentedmfileimage_equipmentedmfile
	 */
	public final void setEquipmentEDMFileImage_EquipmentEDMFile(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentEDMFile equipmentedmfileimage_equipmentedmfile)
	{
		if (equipmentedmfileimage_equipmentedmfile == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentEDMFileImage_EquipmentEDMFile.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentEDMFileImage_EquipmentEDMFile.toString(), equipmentedmfileimage_equipmentedmfile.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.EquipmentEDMFileImage that = (equipment_management.proxies.EquipmentEDMFileImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
