// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/09/06
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/11/01
 * 설명 : 설비 정보를 담는 엔터티
 * Version 1.1 : 설비 루트 (Level 1)
 * Version 1.0 : 생성
 */
public class Equipment extends globalsearch.proxies.SearchableObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.Equipment";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentCode("EquipmentCode"),
		EquipmentName("EquipmentName"),
		EquipmentNameEnglish("EquipmentNameEnglish"),
		EquipmentSubName("EquipmentSubName"),
		EquipmentDayRunTime("EquipmentDayRunTime"),
		EquipnentWorkArea("EquipnentWorkArea"),
		EquipmentSpec1("EquipmentSpec1"),
		EquipmentSpec2("EquipmentSpec2"),
		EquipmentSpec3("EquipmentSpec3"),
		EquipmentSafety("EquipmentSafety"),
		EquipmentDTAnalysisFlag("EquipmentDTAnalysisFlag"),
		EquipmentInspectionFlag("EquipmentInspectionFlag"),
		EquipmentSafetyFlag("EquipmentSafetyFlag"),
		EquipmentCoreFlag("EquipmentCoreFlag"),
		EquipmentAnalyzeDate("EquipmentAnalyzeDate"),
		EquipmentManufactureDate("EquipmentManufactureDate"),
		EquipmentAccquisitionDate("EquipmentAccquisitionDate"),
		EquipmentRunStartDate("EquipmentRunStartDate"),
		FreeMaintenanceExpireDate("FreeMaintenanceExpireDate"),
		EquipmentDepreciationExpireDate("EquipmentDepreciationExpireDate"),
		EquipmentDisposalDate("EquipmentDisposalDate"),
		EquipmentSaleDate("EquipmentSaleDate"),
		EquipmentServiceLife("EquipmentServiceLife"),
		EquipmentPrice("EquipmentPrice"),
		EquipmentERPNumber("EquipmentERPNumber"),
		EquipmentMESNumber("EquipmentMESNumber"),
		EquipmentPLCNumber("EquipmentPLCNumber"),
		EquipmentModelNumber("EquipmentModelNumber"),
		EquipmentManufactureNumber("EquipmentManufactureNumber"),
		EquipmentSerialNumber("EquipmentSerialNumber"),
		EquipmentSortKey("EquipmentSortKey"),
		EquipmentLevel("EquipmentLevel"),
		EquipmentPath("EquipmentPath"),
		EquipmentSequence("EquipmentSequence"),
		EquipmentDescription("EquipmentDescription"),
		IsEquipmentActive("IsEquipmentActive"),
		VirtualEquipment("VirtualEquipment"),
		PowerControlItem("PowerControlItem"),
		EquipmentRoot("EquipmentRoot"),
		Parent_Equipment("Equipment_Management.Parent_Equipment"),
		Equipment_EquipmentImage("Equipment_Management.Equipment_EquipmentImage"),
		Equipment_EquipmentDetailInformation("Equipment_Management.Equipment_EquipmentDetailInformation"),
		Equipment_EquipmentType("Equipment_Management.Equipment_EquipmentType"),
		Equipment_EquipmentLocation("Equipment_Management.Equipment_EquipmentLocation"),
		Equipment_EquipmentHelper_Child("Equipment_Management.Equipment_EquipmentHelper_Child"),
		Equipment_EquipmentHelper("Equipment_Management.Equipment_EquipmentHelper"),
		MaintenanceCost_Equipment("Equipment_Management.MaintenanceCost_Equipment"),
		MaintenanceIndex_Equipment("Equipment_Management.MaintenanceIndex_Equipment"),
		Equipment_Plant("Equipment_Management.Equipment_Plant"),
		Management_Department("Equipment_Management.Management_Department"),
		Operation_Department("Equipment_Management.Operation_Department"),
		Equipment_BusinessPartner_Manufacture("Equipment_Management.Equipment_BusinessPartner_Manufacture"),
		Equipment_BusinessPartner_SupplyCompany("Equipment_Management.Equipment_BusinessPartner_SupplyCompany"),
		Equipment_BusinessPartner_MaintenanceCompany("Equipment_Management.Equipment_BusinessPartner_MaintenanceCompany"),
		Status_StandardCode("Equipment_Management.Status_StandardCode"),
		CostCenter_StandardCode("Equipment_Management.CostCenter_StandardCode"),
		WorkCenter_StandardCode("Equipment_Management.WorkCenter_StandardCode"),
		Grade_StandardCode("Equipment_Management.Grade_StandardCode"),
		Equipment_StandardCode_ManufactureCountry("Equipment_Management.Equipment_StandardCode_ManufactureCountry");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Equipment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Equipment(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentMendixObject)
	{
		super(context, equipmentMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.Equipment initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.Equipment(context, mendixObject);
	}

	public static equipment_management.proxies.Equipment load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.Equipment.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.Equipment> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.Equipment.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EquipmentCode
	 */
	public final java.lang.String getEquipmentCode()
	{
		return getEquipmentCode(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentCode
	 */
	public final java.lang.String getEquipmentCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentCode.toString());
	}

	/**
	 * Set value of EquipmentCode
	 * @param equipmentcode
	 */
	public final void setEquipmentCode(java.lang.String equipmentcode)
	{
		setEquipmentCode(getContext(), equipmentcode);
	}

	/**
	 * Set value of EquipmentCode
	 * @param context
	 * @param equipmentcode
	 */
	public final void setEquipmentCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentcode)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentCode.toString(), equipmentcode);
	}

	/**
	 * @return value of EquipmentName
	 */
	public final java.lang.String getEquipmentName()
	{
		return getEquipmentName(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentName
	 */
	public final java.lang.String getEquipmentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentName.toString());
	}

	/**
	 * Set value of EquipmentName
	 * @param equipmentname
	 */
	public final void setEquipmentName(java.lang.String equipmentname)
	{
		setEquipmentName(getContext(), equipmentname);
	}

	/**
	 * Set value of EquipmentName
	 * @param context
	 * @param equipmentname
	 */
	public final void setEquipmentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentname)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentName.toString(), equipmentname);
	}

	/**
	 * @return value of EquipmentNameEnglish
	 */
	public final java.lang.String getEquipmentNameEnglish()
	{
		return getEquipmentNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentNameEnglish
	 */
	public final java.lang.String getEquipmentNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentNameEnglish.toString());
	}

	/**
	 * Set value of EquipmentNameEnglish
	 * @param equipmentnameenglish
	 */
	public final void setEquipmentNameEnglish(java.lang.String equipmentnameenglish)
	{
		setEquipmentNameEnglish(getContext(), equipmentnameenglish);
	}

	/**
	 * Set value of EquipmentNameEnglish
	 * @param context
	 * @param equipmentnameenglish
	 */
	public final void setEquipmentNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentnameenglish)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentNameEnglish.toString(), equipmentnameenglish);
	}

	/**
	 * @return value of EquipmentSubName
	 */
	public final java.lang.String getEquipmentSubName()
	{
		return getEquipmentSubName(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSubName
	 */
	public final java.lang.String getEquipmentSubName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSubName.toString());
	}

	/**
	 * Set value of EquipmentSubName
	 * @param equipmentsubname
	 */
	public final void setEquipmentSubName(java.lang.String equipmentsubname)
	{
		setEquipmentSubName(getContext(), equipmentsubname);
	}

	/**
	 * Set value of EquipmentSubName
	 * @param context
	 * @param equipmentsubname
	 */
	public final void setEquipmentSubName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentsubname)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSubName.toString(), equipmentsubname);
	}

	/**
	 * @return value of EquipmentDayRunTime
	 */
	public final java.lang.Integer getEquipmentDayRunTime()
	{
		return getEquipmentDayRunTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDayRunTime
	 */
	public final java.lang.Integer getEquipmentDayRunTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentDayRunTime.toString());
	}

	/**
	 * Set value of EquipmentDayRunTime
	 * @param equipmentdayruntime
	 */
	public final void setEquipmentDayRunTime(java.lang.Integer equipmentdayruntime)
	{
		setEquipmentDayRunTime(getContext(), equipmentdayruntime);
	}

	/**
	 * Set value of EquipmentDayRunTime
	 * @param context
	 * @param equipmentdayruntime
	 */
	public final void setEquipmentDayRunTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentdayruntime)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDayRunTime.toString(), equipmentdayruntime);
	}

	/**
	 * @return value of EquipnentWorkArea
	 */
	public final java.lang.String getEquipnentWorkArea()
	{
		return getEquipnentWorkArea(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipnentWorkArea
	 */
	public final java.lang.String getEquipnentWorkArea(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipnentWorkArea.toString());
	}

	/**
	 * Set value of EquipnentWorkArea
	 * @param equipnentworkarea
	 */
	public final void setEquipnentWorkArea(java.lang.String equipnentworkarea)
	{
		setEquipnentWorkArea(getContext(), equipnentworkarea);
	}

	/**
	 * Set value of EquipnentWorkArea
	 * @param context
	 * @param equipnentworkarea
	 */
	public final void setEquipnentWorkArea(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipnentworkarea)
	{
		getMendixObject().setValue(context, MemberNames.EquipnentWorkArea.toString(), equipnentworkarea);
	}

	/**
	 * @return value of EquipmentSpec1
	 */
	public final java.lang.String getEquipmentSpec1()
	{
		return getEquipmentSpec1(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSpec1
	 */
	public final java.lang.String getEquipmentSpec1(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSpec1.toString());
	}

	/**
	 * Set value of EquipmentSpec1
	 * @param equipmentspec1
	 */
	public final void setEquipmentSpec1(java.lang.String equipmentspec1)
	{
		setEquipmentSpec1(getContext(), equipmentspec1);
	}

	/**
	 * Set value of EquipmentSpec1
	 * @param context
	 * @param equipmentspec1
	 */
	public final void setEquipmentSpec1(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentspec1)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSpec1.toString(), equipmentspec1);
	}

	/**
	 * @return value of EquipmentSpec2
	 */
	public final java.lang.String getEquipmentSpec2()
	{
		return getEquipmentSpec2(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSpec2
	 */
	public final java.lang.String getEquipmentSpec2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSpec2.toString());
	}

	/**
	 * Set value of EquipmentSpec2
	 * @param equipmentspec2
	 */
	public final void setEquipmentSpec2(java.lang.String equipmentspec2)
	{
		setEquipmentSpec2(getContext(), equipmentspec2);
	}

	/**
	 * Set value of EquipmentSpec2
	 * @param context
	 * @param equipmentspec2
	 */
	public final void setEquipmentSpec2(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentspec2)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSpec2.toString(), equipmentspec2);
	}

	/**
	 * @return value of EquipmentSpec3
	 */
	public final java.lang.String getEquipmentSpec3()
	{
		return getEquipmentSpec3(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSpec3
	 */
	public final java.lang.String getEquipmentSpec3(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSpec3.toString());
	}

	/**
	 * Set value of EquipmentSpec3
	 * @param equipmentspec3
	 */
	public final void setEquipmentSpec3(java.lang.String equipmentspec3)
	{
		setEquipmentSpec3(getContext(), equipmentspec3);
	}

	/**
	 * Set value of EquipmentSpec3
	 * @param context
	 * @param equipmentspec3
	 */
	public final void setEquipmentSpec3(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentspec3)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSpec3.toString(), equipmentspec3);
	}

	/**
	 * @return value of EquipmentSafety
	 */
	public final java.lang.String getEquipmentSafety()
	{
		return getEquipmentSafety(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSafety
	 */
	public final java.lang.String getEquipmentSafety(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSafety.toString());
	}

	/**
	 * Set value of EquipmentSafety
	 * @param equipmentsafety
	 */
	public final void setEquipmentSafety(java.lang.String equipmentsafety)
	{
		setEquipmentSafety(getContext(), equipmentsafety);
	}

	/**
	 * Set value of EquipmentSafety
	 * @param context
	 * @param equipmentsafety
	 */
	public final void setEquipmentSafety(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentsafety)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSafety.toString(), equipmentsafety);
	}

	/**
	 * @return value of EquipmentDTAnalysisFlag
	 */
	public final java.lang.Boolean getEquipmentDTAnalysisFlag()
	{
		return getEquipmentDTAnalysisFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDTAnalysisFlag
	 */
	public final java.lang.Boolean getEquipmentDTAnalysisFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentDTAnalysisFlag.toString());
	}

	/**
	 * Set value of EquipmentDTAnalysisFlag
	 * @param equipmentdtanalysisflag
	 */
	public final void setEquipmentDTAnalysisFlag(java.lang.Boolean equipmentdtanalysisflag)
	{
		setEquipmentDTAnalysisFlag(getContext(), equipmentdtanalysisflag);
	}

	/**
	 * Set value of EquipmentDTAnalysisFlag
	 * @param context
	 * @param equipmentdtanalysisflag
	 */
	public final void setEquipmentDTAnalysisFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmentdtanalysisflag)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDTAnalysisFlag.toString(), equipmentdtanalysisflag);
	}

	/**
	 * @return value of EquipmentInspectionFlag
	 */
	public final java.lang.Boolean getEquipmentInspectionFlag()
	{
		return getEquipmentInspectionFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentInspectionFlag
	 */
	public final java.lang.Boolean getEquipmentInspectionFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentInspectionFlag.toString());
	}

	/**
	 * Set value of EquipmentInspectionFlag
	 * @param equipmentinspectionflag
	 */
	public final void setEquipmentInspectionFlag(java.lang.Boolean equipmentinspectionflag)
	{
		setEquipmentInspectionFlag(getContext(), equipmentinspectionflag);
	}

	/**
	 * Set value of EquipmentInspectionFlag
	 * @param context
	 * @param equipmentinspectionflag
	 */
	public final void setEquipmentInspectionFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmentinspectionflag)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentInspectionFlag.toString(), equipmentinspectionflag);
	}

	/**
	 * @return value of EquipmentSafetyFlag
	 */
	public final java.lang.Boolean getEquipmentSafetyFlag()
	{
		return getEquipmentSafetyFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSafetyFlag
	 */
	public final java.lang.Boolean getEquipmentSafetyFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentSafetyFlag.toString());
	}

	/**
	 * Set value of EquipmentSafetyFlag
	 * @param equipmentsafetyflag
	 */
	public final void setEquipmentSafetyFlag(java.lang.Boolean equipmentsafetyflag)
	{
		setEquipmentSafetyFlag(getContext(), equipmentsafetyflag);
	}

	/**
	 * Set value of EquipmentSafetyFlag
	 * @param context
	 * @param equipmentsafetyflag
	 */
	public final void setEquipmentSafetyFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmentsafetyflag)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSafetyFlag.toString(), equipmentsafetyflag);
	}

	/**
	 * @return value of EquipmentCoreFlag
	 */
	public final java.lang.Boolean getEquipmentCoreFlag()
	{
		return getEquipmentCoreFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentCoreFlag
	 */
	public final java.lang.Boolean getEquipmentCoreFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentCoreFlag.toString());
	}

	/**
	 * Set value of EquipmentCoreFlag
	 * @param equipmentcoreflag
	 */
	public final void setEquipmentCoreFlag(java.lang.Boolean equipmentcoreflag)
	{
		setEquipmentCoreFlag(getContext(), equipmentcoreflag);
	}

	/**
	 * Set value of EquipmentCoreFlag
	 * @param context
	 * @param equipmentcoreflag
	 */
	public final void setEquipmentCoreFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmentcoreflag)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentCoreFlag.toString(), equipmentcoreflag);
	}

	/**
	 * @return value of EquipmentAnalyzeDate
	 */
	public final java.util.Date getEquipmentAnalyzeDate()
	{
		return getEquipmentAnalyzeDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentAnalyzeDate
	 */
	public final java.util.Date getEquipmentAnalyzeDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentAnalyzeDate.toString());
	}

	/**
	 * Set value of EquipmentAnalyzeDate
	 * @param equipmentanalyzedate
	 */
	public final void setEquipmentAnalyzeDate(java.util.Date equipmentanalyzedate)
	{
		setEquipmentAnalyzeDate(getContext(), equipmentanalyzedate);
	}

	/**
	 * Set value of EquipmentAnalyzeDate
	 * @param context
	 * @param equipmentanalyzedate
	 */
	public final void setEquipmentAnalyzeDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentanalyzedate)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentAnalyzeDate.toString(), equipmentanalyzedate);
	}

	/**
	 * @return value of EquipmentManufactureDate
	 */
	public final java.util.Date getEquipmentManufactureDate()
	{
		return getEquipmentManufactureDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentManufactureDate
	 */
	public final java.util.Date getEquipmentManufactureDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentManufactureDate.toString());
	}

	/**
	 * Set value of EquipmentManufactureDate
	 * @param equipmentmanufacturedate
	 */
	public final void setEquipmentManufactureDate(java.util.Date equipmentmanufacturedate)
	{
		setEquipmentManufactureDate(getContext(), equipmentmanufacturedate);
	}

	/**
	 * Set value of EquipmentManufactureDate
	 * @param context
	 * @param equipmentmanufacturedate
	 */
	public final void setEquipmentManufactureDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentmanufacturedate)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentManufactureDate.toString(), equipmentmanufacturedate);
	}

	/**
	 * @return value of EquipmentAccquisitionDate
	 */
	public final java.util.Date getEquipmentAccquisitionDate()
	{
		return getEquipmentAccquisitionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentAccquisitionDate
	 */
	public final java.util.Date getEquipmentAccquisitionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentAccquisitionDate.toString());
	}

	/**
	 * Set value of EquipmentAccquisitionDate
	 * @param equipmentaccquisitiondate
	 */
	public final void setEquipmentAccquisitionDate(java.util.Date equipmentaccquisitiondate)
	{
		setEquipmentAccquisitionDate(getContext(), equipmentaccquisitiondate);
	}

	/**
	 * Set value of EquipmentAccquisitionDate
	 * @param context
	 * @param equipmentaccquisitiondate
	 */
	public final void setEquipmentAccquisitionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentaccquisitiondate)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentAccquisitionDate.toString(), equipmentaccquisitiondate);
	}

	/**
	 * @return value of EquipmentRunStartDate
	 */
	public final java.util.Date getEquipmentRunStartDate()
	{
		return getEquipmentRunStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentRunStartDate
	 */
	public final java.util.Date getEquipmentRunStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentRunStartDate.toString());
	}

	/**
	 * Set value of EquipmentRunStartDate
	 * @param equipmentrunstartdate
	 */
	public final void setEquipmentRunStartDate(java.util.Date equipmentrunstartdate)
	{
		setEquipmentRunStartDate(getContext(), equipmentrunstartdate);
	}

	/**
	 * Set value of EquipmentRunStartDate
	 * @param context
	 * @param equipmentrunstartdate
	 */
	public final void setEquipmentRunStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentrunstartdate)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentRunStartDate.toString(), equipmentrunstartdate);
	}

	/**
	 * @return value of FreeMaintenanceExpireDate
	 */
	public final java.util.Date getFreeMaintenanceExpireDate()
	{
		return getFreeMaintenanceExpireDate(getContext());
	}

	/**
	 * @param context
	 * @return value of FreeMaintenanceExpireDate
	 */
	public final java.util.Date getFreeMaintenanceExpireDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.FreeMaintenanceExpireDate.toString());
	}

	/**
	 * Set value of FreeMaintenanceExpireDate
	 * @param freemaintenanceexpiredate
	 */
	public final void setFreeMaintenanceExpireDate(java.util.Date freemaintenanceexpiredate)
	{
		setFreeMaintenanceExpireDate(getContext(), freemaintenanceexpiredate);
	}

	/**
	 * Set value of FreeMaintenanceExpireDate
	 * @param context
	 * @param freemaintenanceexpiredate
	 */
	public final void setFreeMaintenanceExpireDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date freemaintenanceexpiredate)
	{
		getMendixObject().setValue(context, MemberNames.FreeMaintenanceExpireDate.toString(), freemaintenanceexpiredate);
	}

	/**
	 * @return value of EquipmentDepreciationExpireDate
	 */
	public final java.util.Date getEquipmentDepreciationExpireDate()
	{
		return getEquipmentDepreciationExpireDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDepreciationExpireDate
	 */
	public final java.util.Date getEquipmentDepreciationExpireDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentDepreciationExpireDate.toString());
	}

	/**
	 * Set value of EquipmentDepreciationExpireDate
	 * @param equipmentdepreciationexpiredate
	 */
	public final void setEquipmentDepreciationExpireDate(java.util.Date equipmentdepreciationexpiredate)
	{
		setEquipmentDepreciationExpireDate(getContext(), equipmentdepreciationexpiredate);
	}

	/**
	 * Set value of EquipmentDepreciationExpireDate
	 * @param context
	 * @param equipmentdepreciationexpiredate
	 */
	public final void setEquipmentDepreciationExpireDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentdepreciationexpiredate)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDepreciationExpireDate.toString(), equipmentdepreciationexpiredate);
	}

	/**
	 * @return value of EquipmentDisposalDate
	 */
	public final java.util.Date getEquipmentDisposalDate()
	{
		return getEquipmentDisposalDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDisposalDate
	 */
	public final java.util.Date getEquipmentDisposalDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentDisposalDate.toString());
	}

	/**
	 * Set value of EquipmentDisposalDate
	 * @param equipmentdisposaldate
	 */
	public final void setEquipmentDisposalDate(java.util.Date equipmentdisposaldate)
	{
		setEquipmentDisposalDate(getContext(), equipmentdisposaldate);
	}

	/**
	 * Set value of EquipmentDisposalDate
	 * @param context
	 * @param equipmentdisposaldate
	 */
	public final void setEquipmentDisposalDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentdisposaldate)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDisposalDate.toString(), equipmentdisposaldate);
	}

	/**
	 * @return value of EquipmentSaleDate
	 */
	public final java.util.Date getEquipmentSaleDate()
	{
		return getEquipmentSaleDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSaleDate
	 */
	public final java.util.Date getEquipmentSaleDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentSaleDate.toString());
	}

	/**
	 * Set value of EquipmentSaleDate
	 * @param equipmentsaledate
	 */
	public final void setEquipmentSaleDate(java.util.Date equipmentsaledate)
	{
		setEquipmentSaleDate(getContext(), equipmentsaledate);
	}

	/**
	 * Set value of EquipmentSaleDate
	 * @param context
	 * @param equipmentsaledate
	 */
	public final void setEquipmentSaleDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentsaledate)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSaleDate.toString(), equipmentsaledate);
	}

	/**
	 * @return value of EquipmentServiceLife
	 */
	public final java.lang.Integer getEquipmentServiceLife()
	{
		return getEquipmentServiceLife(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentServiceLife
	 */
	public final java.lang.Integer getEquipmentServiceLife(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentServiceLife.toString());
	}

	/**
	 * Set value of EquipmentServiceLife
	 * @param equipmentservicelife
	 */
	public final void setEquipmentServiceLife(java.lang.Integer equipmentservicelife)
	{
		setEquipmentServiceLife(getContext(), equipmentservicelife);
	}

	/**
	 * Set value of EquipmentServiceLife
	 * @param context
	 * @param equipmentservicelife
	 */
	public final void setEquipmentServiceLife(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentservicelife)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentServiceLife.toString(), equipmentservicelife);
	}

	/**
	 * @return value of EquipmentPrice
	 */
	public final java.math.BigDecimal getEquipmentPrice()
	{
		return getEquipmentPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentPrice
	 */
	public final java.math.BigDecimal getEquipmentPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.EquipmentPrice.toString());
	}

	/**
	 * Set value of EquipmentPrice
	 * @param equipmentprice
	 */
	public final void setEquipmentPrice(java.math.BigDecimal equipmentprice)
	{
		setEquipmentPrice(getContext(), equipmentprice);
	}

	/**
	 * Set value of EquipmentPrice
	 * @param context
	 * @param equipmentprice
	 */
	public final void setEquipmentPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal equipmentprice)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentPrice.toString(), equipmentprice);
	}

	/**
	 * @return value of EquipmentERPNumber
	 */
	public final java.lang.Integer getEquipmentERPNumber()
	{
		return getEquipmentERPNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentERPNumber
	 */
	public final java.lang.Integer getEquipmentERPNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentERPNumber.toString());
	}

	/**
	 * Set value of EquipmentERPNumber
	 * @param equipmenterpnumber
	 */
	public final void setEquipmentERPNumber(java.lang.Integer equipmenterpnumber)
	{
		setEquipmentERPNumber(getContext(), equipmenterpnumber);
	}

	/**
	 * Set value of EquipmentERPNumber
	 * @param context
	 * @param equipmenterpnumber
	 */
	public final void setEquipmentERPNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmenterpnumber)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentERPNumber.toString(), equipmenterpnumber);
	}

	/**
	 * @return value of EquipmentMESNumber
	 */
	public final java.lang.Integer getEquipmentMESNumber()
	{
		return getEquipmentMESNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentMESNumber
	 */
	public final java.lang.Integer getEquipmentMESNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentMESNumber.toString());
	}

	/**
	 * Set value of EquipmentMESNumber
	 * @param equipmentmesnumber
	 */
	public final void setEquipmentMESNumber(java.lang.Integer equipmentmesnumber)
	{
		setEquipmentMESNumber(getContext(), equipmentmesnumber);
	}

	/**
	 * Set value of EquipmentMESNumber
	 * @param context
	 * @param equipmentmesnumber
	 */
	public final void setEquipmentMESNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentmesnumber)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentMESNumber.toString(), equipmentmesnumber);
	}

	/**
	 * @return value of EquipmentPLCNumber
	 */
	public final java.lang.Integer getEquipmentPLCNumber()
	{
		return getEquipmentPLCNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentPLCNumber
	 */
	public final java.lang.Integer getEquipmentPLCNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentPLCNumber.toString());
	}

	/**
	 * Set value of EquipmentPLCNumber
	 * @param equipmentplcnumber
	 */
	public final void setEquipmentPLCNumber(java.lang.Integer equipmentplcnumber)
	{
		setEquipmentPLCNumber(getContext(), equipmentplcnumber);
	}

	/**
	 * Set value of EquipmentPLCNumber
	 * @param context
	 * @param equipmentplcnumber
	 */
	public final void setEquipmentPLCNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentplcnumber)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentPLCNumber.toString(), equipmentplcnumber);
	}

	/**
	 * @return value of EquipmentModelNumber
	 */
	public final java.lang.Integer getEquipmentModelNumber()
	{
		return getEquipmentModelNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentModelNumber
	 */
	public final java.lang.Integer getEquipmentModelNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentModelNumber.toString());
	}

	/**
	 * Set value of EquipmentModelNumber
	 * @param equipmentmodelnumber
	 */
	public final void setEquipmentModelNumber(java.lang.Integer equipmentmodelnumber)
	{
		setEquipmentModelNumber(getContext(), equipmentmodelnumber);
	}

	/**
	 * Set value of EquipmentModelNumber
	 * @param context
	 * @param equipmentmodelnumber
	 */
	public final void setEquipmentModelNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentmodelnumber)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentModelNumber.toString(), equipmentmodelnumber);
	}

	/**
	 * @return value of EquipmentManufactureNumber
	 */
	public final java.lang.Integer getEquipmentManufactureNumber()
	{
		return getEquipmentManufactureNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentManufactureNumber
	 */
	public final java.lang.Integer getEquipmentManufactureNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentManufactureNumber.toString());
	}

	/**
	 * Set value of EquipmentManufactureNumber
	 * @param equipmentmanufacturenumber
	 */
	public final void setEquipmentManufactureNumber(java.lang.Integer equipmentmanufacturenumber)
	{
		setEquipmentManufactureNumber(getContext(), equipmentmanufacturenumber);
	}

	/**
	 * Set value of EquipmentManufactureNumber
	 * @param context
	 * @param equipmentmanufacturenumber
	 */
	public final void setEquipmentManufactureNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentmanufacturenumber)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentManufactureNumber.toString(), equipmentmanufacturenumber);
	}

	/**
	 * @return value of EquipmentSerialNumber
	 */
	public final java.lang.Integer getEquipmentSerialNumber()
	{
		return getEquipmentSerialNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSerialNumber
	 */
	public final java.lang.Integer getEquipmentSerialNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentSerialNumber.toString());
	}

	/**
	 * Set value of EquipmentSerialNumber
	 * @param equipmentserialnumber
	 */
	public final void setEquipmentSerialNumber(java.lang.Integer equipmentserialnumber)
	{
		setEquipmentSerialNumber(getContext(), equipmentserialnumber);
	}

	/**
	 * Set value of EquipmentSerialNumber
	 * @param context
	 * @param equipmentserialnumber
	 */
	public final void setEquipmentSerialNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentserialnumber)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSerialNumber.toString(), equipmentserialnumber);
	}

	/**
	 * @return value of EquipmentSortKey
	 */
	public final java.lang.String getEquipmentSortKey()
	{
		return getEquipmentSortKey(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSortKey
	 */
	public final java.lang.String getEquipmentSortKey(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentSortKey.toString());
	}

	/**
	 * Set value of EquipmentSortKey
	 * @param equipmentsortkey
	 */
	public final void setEquipmentSortKey(java.lang.String equipmentsortkey)
	{
		setEquipmentSortKey(getContext(), equipmentsortkey);
	}

	/**
	 * Set value of EquipmentSortKey
	 * @param context
	 * @param equipmentsortkey
	 */
	public final void setEquipmentSortKey(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentsortkey)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSortKey.toString(), equipmentsortkey);
	}

	/**
	 * @return value of EquipmentLevel
	 */
	public final java.lang.Integer getEquipmentLevel()
	{
		return getEquipmentLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentLevel
	 */
	public final java.lang.Integer getEquipmentLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentLevel.toString());
	}

	/**
	 * Set value of EquipmentLevel
	 * @param equipmentlevel
	 */
	public final void setEquipmentLevel(java.lang.Integer equipmentlevel)
	{
		setEquipmentLevel(getContext(), equipmentlevel);
	}

	/**
	 * Set value of EquipmentLevel
	 * @param context
	 * @param equipmentlevel
	 */
	public final void setEquipmentLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentlevel)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentLevel.toString(), equipmentlevel);
	}

	/**
	 * @return value of EquipmentPath
	 */
	public final java.lang.String getEquipmentPath()
	{
		return getEquipmentPath(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentPath
	 */
	public final java.lang.String getEquipmentPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentPath.toString());
	}

	/**
	 * Set value of EquipmentPath
	 * @param equipmentpath
	 */
	public final void setEquipmentPath(java.lang.String equipmentpath)
	{
		setEquipmentPath(getContext(), equipmentpath);
	}

	/**
	 * Set value of EquipmentPath
	 * @param context
	 * @param equipmentpath
	 */
	public final void setEquipmentPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentpath)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentPath.toString(), equipmentpath);
	}

	/**
	 * @return value of EquipmentSequence
	 */
	public final java.lang.Integer getEquipmentSequence()
	{
		return getEquipmentSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentSequence
	 */
	public final java.lang.Integer getEquipmentSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EquipmentSequence.toString());
	}

	/**
	 * Set value of EquipmentSequence
	 * @param equipmentsequence
	 */
	public final void setEquipmentSequence(java.lang.Integer equipmentsequence)
	{
		setEquipmentSequence(getContext(), equipmentsequence);
	}

	/**
	 * Set value of EquipmentSequence
	 * @param context
	 * @param equipmentsequence
	 */
	public final void setEquipmentSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer equipmentsequence)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentSequence.toString(), equipmentsequence);
	}

	/**
	 * @return value of EquipmentDescription
	 */
	public final java.lang.String getEquipmentDescription()
	{
		return getEquipmentDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDescription
	 */
	public final java.lang.String getEquipmentDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentDescription.toString());
	}

	/**
	 * Set value of EquipmentDescription
	 * @param equipmentdescription
	 */
	public final void setEquipmentDescription(java.lang.String equipmentdescription)
	{
		setEquipmentDescription(getContext(), equipmentdescription);
	}

	/**
	 * Set value of EquipmentDescription
	 * @param context
	 * @param equipmentdescription
	 */
	public final void setEquipmentDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentdescription)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDescription.toString(), equipmentdescription);
	}

	/**
	 * @return value of IsEquipmentActive
	 */
	public final java.lang.Boolean getIsEquipmentActive()
	{
		return getIsEquipmentActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsEquipmentActive
	 */
	public final java.lang.Boolean getIsEquipmentActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsEquipmentActive.toString());
	}

	/**
	 * Set value of IsEquipmentActive
	 * @param isequipmentactive
	 */
	public final void setIsEquipmentActive(java.lang.Boolean isequipmentactive)
	{
		setIsEquipmentActive(getContext(), isequipmentactive);
	}

	/**
	 * Set value of IsEquipmentActive
	 * @param context
	 * @param isequipmentactive
	 */
	public final void setIsEquipmentActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isequipmentactive)
	{
		getMendixObject().setValue(context, MemberNames.IsEquipmentActive.toString(), isequipmentactive);
	}

	/**
	 * @return value of VirtualEquipment
	 */
	public final java.lang.Boolean getVirtualEquipment()
	{
		return getVirtualEquipment(getContext());
	}

	/**
	 * @param context
	 * @return value of VirtualEquipment
	 */
	public final java.lang.Boolean getVirtualEquipment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.VirtualEquipment.toString());
	}

	/**
	 * Set value of VirtualEquipment
	 * @param virtualequipment
	 */
	public final void setVirtualEquipment(java.lang.Boolean virtualequipment)
	{
		setVirtualEquipment(getContext(), virtualequipment);
	}

	/**
	 * Set value of VirtualEquipment
	 * @param context
	 * @param virtualequipment
	 */
	public final void setVirtualEquipment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean virtualequipment)
	{
		getMendixObject().setValue(context, MemberNames.VirtualEquipment.toString(), virtualequipment);
	}

	/**
	 * @return value of PowerControlItem
	 */
	public final java.lang.Boolean getPowerControlItem()
	{
		return getPowerControlItem(getContext());
	}

	/**
	 * @param context
	 * @return value of PowerControlItem
	 */
	public final java.lang.Boolean getPowerControlItem(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PowerControlItem.toString());
	}

	/**
	 * Set value of PowerControlItem
	 * @param powercontrolitem
	 */
	public final void setPowerControlItem(java.lang.Boolean powercontrolitem)
	{
		setPowerControlItem(getContext(), powercontrolitem);
	}

	/**
	 * Set value of PowerControlItem
	 * @param context
	 * @param powercontrolitem
	 */
	public final void setPowerControlItem(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean powercontrolitem)
	{
		getMendixObject().setValue(context, MemberNames.PowerControlItem.toString(), powercontrolitem);
	}

	/**
	 * @return value of EquipmentRoot
	 */
	public final java.lang.Boolean getEquipmentRoot()
	{
		return getEquipmentRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentRoot
	 */
	public final java.lang.Boolean getEquipmentRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentRoot.toString());
	}

	/**
	 * Set value of EquipmentRoot
	 * @param equipmentroot
	 */
	public final void setEquipmentRoot(java.lang.Boolean equipmentroot)
	{
		setEquipmentRoot(getContext(), equipmentroot);
	}

	/**
	 * Set value of EquipmentRoot
	 * @param context
	 * @param equipmentroot
	 */
	public final void setEquipmentRoot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmentroot)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentRoot.toString(), equipmentroot);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_Equipment
	 */
	public final equipment_management.proxies.Equipment getParent_Equipment() throws com.mendix.core.CoreException
	{
		return getParent_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getParent_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_Equipment
	 * @param parent_equipment
	 */
	public final void setParent_Equipment(equipment_management.proxies.Equipment parent_equipment)
	{
		setParent_Equipment(getContext(), parent_equipment);
	}

	/**
	 * Set value of Parent_Equipment
	 * @param context
	 * @param parent_equipment
	 */
	public final void setParent_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment parent_equipment)
	{
		if (parent_equipment == null) {
			getMendixObject().setValue(context, MemberNames.Parent_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_Equipment.toString(), parent_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EquipmentImage
	 */
	public final equipment_management.proxies.EquipmentImage getEquipment_EquipmentImage() throws com.mendix.core.CoreException
	{
		return getEquipment_EquipmentImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EquipmentImage
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentImage getEquipment_EquipmentImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EquipmentImage.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EquipmentImage
	 * @param equipment_equipmentimage
	 */
	public final void setEquipment_EquipmentImage(equipment_management.proxies.EquipmentImage equipment_equipmentimage)
	{
		setEquipment_EquipmentImage(getContext(), equipment_equipmentimage);
	}

	/**
	 * Set value of Equipment_EquipmentImage
	 * @param context
	 * @param equipment_equipmentimage
	 */
	public final void setEquipment_EquipmentImage(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentImage equipment_equipmentimage)
	{
		if (equipment_equipmentimage == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentImage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentImage.toString(), equipment_equipmentimage.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EquipmentDetailInformation
	 */
	public final equipment_management.proxies.EquipmentDetailInformation getEquipment_EquipmentDetailInformation() throws com.mendix.core.CoreException
	{
		return getEquipment_EquipmentDetailInformation(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EquipmentDetailInformation
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentDetailInformation getEquipment_EquipmentDetailInformation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentDetailInformation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EquipmentDetailInformation.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentDetailInformation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EquipmentDetailInformation
	 * @param equipment_equipmentdetailinformation
	 */
	public final void setEquipment_EquipmentDetailInformation(equipment_management.proxies.EquipmentDetailInformation equipment_equipmentdetailinformation)
	{
		setEquipment_EquipmentDetailInformation(getContext(), equipment_equipmentdetailinformation);
	}

	/**
	 * Set value of Equipment_EquipmentDetailInformation
	 * @param context
	 * @param equipment_equipmentdetailinformation
	 */
	public final void setEquipment_EquipmentDetailInformation(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentDetailInformation equipment_equipmentdetailinformation)
	{
		if (equipment_equipmentdetailinformation == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentDetailInformation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentDetailInformation.toString(), equipment_equipmentdetailinformation.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EquipmentType
	 */
	public final equipment_management.proxies.EquipmentType getEquipment_EquipmentType() throws com.mendix.core.CoreException
	{
		return getEquipment_EquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EquipmentType
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentType getEquipment_EquipmentType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EquipmentType.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EquipmentType
	 * @param equipment_equipmenttype
	 */
	public final void setEquipment_EquipmentType(equipment_management.proxies.EquipmentType equipment_equipmenttype)
	{
		setEquipment_EquipmentType(getContext(), equipment_equipmenttype);
	}

	/**
	 * Set value of Equipment_EquipmentType
	 * @param context
	 * @param equipment_equipmenttype
	 */
	public final void setEquipment_EquipmentType(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentType equipment_equipmenttype)
	{
		if (equipment_equipmenttype == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentType.toString(), equipment_equipmenttype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EquipmentLocation
	 */
	public final equipment_management.proxies.EquipmentLocation getEquipment_EquipmentLocation() throws com.mendix.core.CoreException
	{
		return getEquipment_EquipmentLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EquipmentLocation
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentLocation getEquipment_EquipmentLocation(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentLocation result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EquipmentLocation.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentLocation.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EquipmentLocation
	 * @param equipment_equipmentlocation
	 */
	public final void setEquipment_EquipmentLocation(equipment_management.proxies.EquipmentLocation equipment_equipmentlocation)
	{
		setEquipment_EquipmentLocation(getContext(), equipment_equipmentlocation);
	}

	/**
	 * Set value of Equipment_EquipmentLocation
	 * @param context
	 * @param equipment_equipmentlocation
	 */
	public final void setEquipment_EquipmentLocation(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentLocation equipment_equipmentlocation)
	{
		if (equipment_equipmentlocation == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentLocation.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentLocation.toString(), equipment_equipmentlocation.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EquipmentHelper_Child
	 */
	public final equipment_management.proxies.EquipmentHelper_Child getEquipment_EquipmentHelper_Child() throws com.mendix.core.CoreException
	{
		return getEquipment_EquipmentHelper_Child(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EquipmentHelper_Child
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentHelper_Child getEquipment_EquipmentHelper_Child(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentHelper_Child result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EquipmentHelper_Child.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentHelper_Child.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EquipmentHelper_Child
	 * @param equipment_equipmenthelper_child
	 */
	public final void setEquipment_EquipmentHelper_Child(equipment_management.proxies.EquipmentHelper_Child equipment_equipmenthelper_child)
	{
		setEquipment_EquipmentHelper_Child(getContext(), equipment_equipmenthelper_child);
	}

	/**
	 * Set value of Equipment_EquipmentHelper_Child
	 * @param context
	 * @param equipment_equipmenthelper_child
	 */
	public final void setEquipment_EquipmentHelper_Child(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentHelper_Child equipment_equipmenthelper_child)
	{
		if (equipment_equipmenthelper_child == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentHelper_Child.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentHelper_Child.toString(), equipment_equipmenthelper_child.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_EquipmentHelper
	 */
	public final equipment_management.proxies.EquipmentHelper getEquipment_EquipmentHelper() throws com.mendix.core.CoreException
	{
		return getEquipment_EquipmentHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_EquipmentHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentHelper getEquipment_EquipmentHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_EquipmentHelper.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_EquipmentHelper
	 * @param equipment_equipmenthelper
	 */
	public final void setEquipment_EquipmentHelper(equipment_management.proxies.EquipmentHelper equipment_equipmenthelper)
	{
		setEquipment_EquipmentHelper(getContext(), equipment_equipmenthelper);
	}

	/**
	 * Set value of Equipment_EquipmentHelper
	 * @param context
	 * @param equipment_equipmenthelper
	 */
	public final void setEquipment_EquipmentHelper(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentHelper equipment_equipmenthelper)
	{
		if (equipment_equipmenthelper == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_EquipmentHelper.toString(), equipment_equipmenthelper.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaintenanceCost_Equipment
	 */
	public final equipment_management.proxies.MaintenanceCost getMaintenanceCost_Equipment() throws com.mendix.core.CoreException
	{
		return getMaintenanceCost_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintenanceCost_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.MaintenanceCost getMaintenanceCost_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.MaintenanceCost result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaintenanceCost_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.MaintenanceCost.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaintenanceCost_Equipment
	 * @param maintenancecost_equipment
	 */
	public final void setMaintenanceCost_Equipment(equipment_management.proxies.MaintenanceCost maintenancecost_equipment)
	{
		setMaintenanceCost_Equipment(getContext(), maintenancecost_equipment);
	}

	/**
	 * Set value of MaintenanceCost_Equipment
	 * @param context
	 * @param maintenancecost_equipment
	 */
	public final void setMaintenanceCost_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.MaintenanceCost maintenancecost_equipment)
	{
		if (maintenancecost_equipment == null) {
			getMendixObject().setValue(context, MemberNames.MaintenanceCost_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaintenanceCost_Equipment.toString(), maintenancecost_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaintenanceIndex_Equipment
	 */
	public final equipment_management.proxies.MaintenanceIndex getMaintenanceIndex_Equipment() throws com.mendix.core.CoreException
	{
		return getMaintenanceIndex_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintenanceIndex_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.MaintenanceIndex getMaintenanceIndex_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.MaintenanceIndex result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaintenanceIndex_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.MaintenanceIndex.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaintenanceIndex_Equipment
	 * @param maintenanceindex_equipment
	 */
	public final void setMaintenanceIndex_Equipment(equipment_management.proxies.MaintenanceIndex maintenanceindex_equipment)
	{
		setMaintenanceIndex_Equipment(getContext(), maintenanceindex_equipment);
	}

	/**
	 * Set value of MaintenanceIndex_Equipment
	 * @param context
	 * @param maintenanceindex_equipment
	 */
	public final void setMaintenanceIndex_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.MaintenanceIndex maintenanceindex_equipment)
	{
		if (maintenanceindex_equipment == null) {
			getMendixObject().setValue(context, MemberNames.MaintenanceIndex_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaintenanceIndex_Equipment.toString(), maintenanceindex_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_Plant
	 */
	public final cmms_administration.proxies.Plant getEquipment_Plant() throws com.mendix.core.CoreException
	{
		return getEquipment_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getEquipment_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_Plant
	 * @param equipment_plant
	 */
	public final void setEquipment_Plant(cmms_administration.proxies.Plant equipment_plant)
	{
		setEquipment_Plant(getContext(), equipment_plant);
	}

	/**
	 * Set value of Equipment_Plant
	 * @param context
	 * @param equipment_plant
	 */
	public final void setEquipment_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant equipment_plant)
	{
		if (equipment_plant == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_Plant.toString(), equipment_plant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Management_Department
	 */
	public final cmms_administration.proxies.Department getManagement_Department() throws com.mendix.core.CoreException
	{
		return getManagement_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Management_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Department getManagement_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Management_Department.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Management_Department
	 * @param management_department
	 */
	public final void setManagement_Department(cmms_administration.proxies.Department management_department)
	{
		setManagement_Department(getContext(), management_department);
	}

	/**
	 * Set value of Management_Department
	 * @param context
	 * @param management_department
	 */
	public final void setManagement_Department(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Department management_department)
	{
		if (management_department == null) {
			getMendixObject().setValue(context, MemberNames.Management_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Management_Department.toString(), management_department.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Operation_Department
	 */
	public final cmms_administration.proxies.Department getOperation_Department() throws com.mendix.core.CoreException
	{
		return getOperation_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Operation_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Department getOperation_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Operation_Department.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Operation_Department
	 * @param operation_department
	 */
	public final void setOperation_Department(cmms_administration.proxies.Department operation_department)
	{
		setOperation_Department(getContext(), operation_department);
	}

	/**
	 * Set value of Operation_Department
	 * @param context
	 * @param operation_department
	 */
	public final void setOperation_Department(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Department operation_department)
	{
		if (operation_department == null) {
			getMendixObject().setValue(context, MemberNames.Operation_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Operation_Department.toString(), operation_department.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_BusinessPartner_Manufacture
	 */
	public final material_management.proxies.BusinessPartner getEquipment_BusinessPartner_Manufacture() throws com.mendix.core.CoreException
	{
		return getEquipment_BusinessPartner_Manufacture(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_BusinessPartner_Manufacture
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.BusinessPartner getEquipment_BusinessPartner_Manufacture(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_BusinessPartner_Manufacture.toString());
		if (identifier != null) {
			result = material_management.proxies.BusinessPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_BusinessPartner_Manufacture
	 * @param equipment_businesspartner_manufacture
	 */
	public final void setEquipment_BusinessPartner_Manufacture(material_management.proxies.BusinessPartner equipment_businesspartner_manufacture)
	{
		setEquipment_BusinessPartner_Manufacture(getContext(), equipment_businesspartner_manufacture);
	}

	/**
	 * Set value of Equipment_BusinessPartner_Manufacture
	 * @param context
	 * @param equipment_businesspartner_manufacture
	 */
	public final void setEquipment_BusinessPartner_Manufacture(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.BusinessPartner equipment_businesspartner_manufacture)
	{
		if (equipment_businesspartner_manufacture == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_BusinessPartner_Manufacture.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_BusinessPartner_Manufacture.toString(), equipment_businesspartner_manufacture.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_BusinessPartner_SupplyCompany
	 */
	public final material_management.proxies.BusinessPartner getEquipment_BusinessPartner_SupplyCompany() throws com.mendix.core.CoreException
	{
		return getEquipment_BusinessPartner_SupplyCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_BusinessPartner_SupplyCompany
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.BusinessPartner getEquipment_BusinessPartner_SupplyCompany(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_BusinessPartner_SupplyCompany.toString());
		if (identifier != null) {
			result = material_management.proxies.BusinessPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_BusinessPartner_SupplyCompany
	 * @param equipment_businesspartner_supplycompany
	 */
	public final void setEquipment_BusinessPartner_SupplyCompany(material_management.proxies.BusinessPartner equipment_businesspartner_supplycompany)
	{
		setEquipment_BusinessPartner_SupplyCompany(getContext(), equipment_businesspartner_supplycompany);
	}

	/**
	 * Set value of Equipment_BusinessPartner_SupplyCompany
	 * @param context
	 * @param equipment_businesspartner_supplycompany
	 */
	public final void setEquipment_BusinessPartner_SupplyCompany(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.BusinessPartner equipment_businesspartner_supplycompany)
	{
		if (equipment_businesspartner_supplycompany == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_BusinessPartner_SupplyCompany.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_BusinessPartner_SupplyCompany.toString(), equipment_businesspartner_supplycompany.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_BusinessPartner_MaintenanceCompany
	 */
	public final material_management.proxies.BusinessPartner getEquipment_BusinessPartner_MaintenanceCompany() throws com.mendix.core.CoreException
	{
		return getEquipment_BusinessPartner_MaintenanceCompany(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_BusinessPartner_MaintenanceCompany
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.BusinessPartner getEquipment_BusinessPartner_MaintenanceCompany(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_BusinessPartner_MaintenanceCompany.toString());
		if (identifier != null) {
			result = material_management.proxies.BusinessPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_BusinessPartner_MaintenanceCompany
	 * @param equipment_businesspartner_maintenancecompany
	 */
	public final void setEquipment_BusinessPartner_MaintenanceCompany(material_management.proxies.BusinessPartner equipment_businesspartner_maintenancecompany)
	{
		setEquipment_BusinessPartner_MaintenanceCompany(getContext(), equipment_businesspartner_maintenancecompany);
	}

	/**
	 * Set value of Equipment_BusinessPartner_MaintenanceCompany
	 * @param context
	 * @param equipment_businesspartner_maintenancecompany
	 */
	public final void setEquipment_BusinessPartner_MaintenanceCompany(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.BusinessPartner equipment_businesspartner_maintenancecompany)
	{
		if (equipment_businesspartner_maintenancecompany == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_BusinessPartner_MaintenanceCompany.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_BusinessPartner_MaintenanceCompany.toString(), equipment_businesspartner_maintenancecompany.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Status_StandardCode
	 */
	public final commons.proxies.StandardCode getStatus_StandardCode() throws com.mendix.core.CoreException
	{
		return getStatus_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Status_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Status_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Status_StandardCode
	 * @param status_standardcode
	 */
	public final void setStatus_StandardCode(commons.proxies.StandardCode status_standardcode)
	{
		setStatus_StandardCode(getContext(), status_standardcode);
	}

	/**
	 * Set value of Status_StandardCode
	 * @param context
	 * @param status_standardcode
	 */
	public final void setStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode status_standardcode)
	{
		if (status_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Status_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Status_StandardCode.toString(), status_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of CostCenter_StandardCode
	 */
	public final commons.proxies.StandardCode getCostCenter_StandardCode() throws com.mendix.core.CoreException
	{
		return getCostCenter_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of CostCenter_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getCostCenter_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.CostCenter_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of CostCenter_StandardCode
	 * @param costcenter_standardcode
	 */
	public final void setCostCenter_StandardCode(commons.proxies.StandardCode costcenter_standardcode)
	{
		setCostCenter_StandardCode(getContext(), costcenter_standardcode);
	}

	/**
	 * Set value of CostCenter_StandardCode
	 * @param context
	 * @param costcenter_standardcode
	 */
	public final void setCostCenter_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode costcenter_standardcode)
	{
		if (costcenter_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.CostCenter_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.CostCenter_StandardCode.toString(), costcenter_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkCenter_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkCenter_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkCenter_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkCenter_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkCenter_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkCenter_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkCenter_StandardCode
	 * @param workcenter_standardcode
	 */
	public final void setWorkCenter_StandardCode(commons.proxies.StandardCode workcenter_standardcode)
	{
		setWorkCenter_StandardCode(getContext(), workcenter_standardcode);
	}

	/**
	 * Set value of WorkCenter_StandardCode
	 * @param context
	 * @param workcenter_standardcode
	 */
	public final void setWorkCenter_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workcenter_standardcode)
	{
		if (workcenter_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkCenter_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkCenter_StandardCode.toString(), workcenter_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Grade_StandardCode
	 */
	public final commons.proxies.StandardCode getGrade_StandardCode() throws com.mendix.core.CoreException
	{
		return getGrade_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Grade_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getGrade_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Grade_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Grade_StandardCode
	 * @param grade_standardcode
	 */
	public final void setGrade_StandardCode(commons.proxies.StandardCode grade_standardcode)
	{
		setGrade_StandardCode(getContext(), grade_standardcode);
	}

	/**
	 * Set value of Grade_StandardCode
	 * @param context
	 * @param grade_standardcode
	 */
	public final void setGrade_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode grade_standardcode)
	{
		if (grade_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Grade_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Grade_StandardCode.toString(), grade_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Equipment_StandardCode_ManufactureCountry
	 */
	public final commons.proxies.StandardCode getEquipment_StandardCode_ManufactureCountry() throws com.mendix.core.CoreException
	{
		return getEquipment_StandardCode_ManufactureCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment_StandardCode_ManufactureCountry
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getEquipment_StandardCode_ManufactureCountry(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Equipment_StandardCode_ManufactureCountry.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Equipment_StandardCode_ManufactureCountry
	 * @param equipment_standardcode_manufacturecountry
	 */
	public final void setEquipment_StandardCode_ManufactureCountry(commons.proxies.StandardCode equipment_standardcode_manufacturecountry)
	{
		setEquipment_StandardCode_ManufactureCountry(getContext(), equipment_standardcode_manufacturecountry);
	}

	/**
	 * Set value of Equipment_StandardCode_ManufactureCountry
	 * @param context
	 * @param equipment_standardcode_manufacturecountry
	 */
	public final void setEquipment_StandardCode_ManufactureCountry(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode equipment_standardcode_manufacturecountry)
	{
		if (equipment_standardcode_manufacturecountry == null) {
			getMendixObject().setValue(context, MemberNames.Equipment_StandardCode_ManufactureCountry.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Equipment_StandardCode_ManufactureCountry.toString(), equipment_standardcode_manufacturecountry.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.Equipment that = (equipment_management.proxies.Equipment) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
