// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public class MaintenanceIndex implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject maintenanceIndexMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.MaintenanceIndex";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		AccquisitionDate("AccquisitionDate"),
		Today("Today"),
		AnalysisDay("AnalysisDay"),
		RepairCounter("RepairCounter"),
		RepairWorkTime("RepairWorkTime"),
		RepairDownTime("RepairDownTime"),
		WorkOrderCount("WorkOrderCount"),
		WorkOrderTotalTime("WorkOrderTotalTime"),
		WorkOrderTotalDownTime("WorkOrderTotalDownTime"),
		TotalRunTime("TotalRunTime"),
		RepairLastdate("RepairLastdate"),
		MTBFday("MTBFday"),
		MTTRtime("MTTRtime"),
		RateDown("RateDown"),
		RateRepair("RateRepair"),
		RateFrequency("RateFrequency"),
		RateSeverity("RateSeverity"),
		RateUtilization("RateUtilization"),
		MaintenanceIndex_Equipment("Equipment_Management.MaintenanceIndex_Equipment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MaintenanceIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MaintenanceIndex(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject maintenanceIndexMendixObject)
	{
		if (maintenanceIndexMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, maintenanceIndexMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.maintenanceIndexMendixObject = maintenanceIndexMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.MaintenanceIndex initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.MaintenanceIndex(context, mendixObject);
	}

	public static equipment_management.proxies.MaintenanceIndex load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.MaintenanceIndex.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.MaintenanceIndex> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.MaintenanceIndex.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of AccquisitionDate
	 */
	public final java.util.Date getAccquisitionDate()
	{
		return getAccquisitionDate(getContext());
	}

	/**
	 * @param context
	 * @return value of AccquisitionDate
	 */
	public final java.util.Date getAccquisitionDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.AccquisitionDate.toString());
	}

	/**
	 * Set value of AccquisitionDate
	 * @param accquisitiondate
	 */
	public final void setAccquisitionDate(java.util.Date accquisitiondate)
	{
		setAccquisitionDate(getContext(), accquisitiondate);
	}

	/**
	 * Set value of AccquisitionDate
	 * @param context
	 * @param accquisitiondate
	 */
	public final void setAccquisitionDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date accquisitiondate)
	{
		getMendixObject().setValue(context, MemberNames.AccquisitionDate.toString(), accquisitiondate);
	}

	/**
	 * @return value of Today
	 */
	public final java.util.Date getToday()
	{
		return getToday(getContext());
	}

	/**
	 * @param context
	 * @return value of Today
	 */
	public final java.util.Date getToday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Today.toString());
	}

	/**
	 * Set value of Today
	 * @param today
	 */
	public final void setToday(java.util.Date today)
	{
		setToday(getContext(), today);
	}

	/**
	 * Set value of Today
	 * @param context
	 * @param today
	 */
	public final void setToday(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date today)
	{
		getMendixObject().setValue(context, MemberNames.Today.toString(), today);
	}

	/**
	 * @return value of AnalysisDay
	 */
	public final java.math.BigDecimal getAnalysisDay()
	{
		return getAnalysisDay(getContext());
	}

	/**
	 * @param context
	 * @return value of AnalysisDay
	 */
	public final java.math.BigDecimal getAnalysisDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AnalysisDay.toString());
	}

	/**
	 * Set value of AnalysisDay
	 * @param analysisday
	 */
	public final void setAnalysisDay(java.math.BigDecimal analysisday)
	{
		setAnalysisDay(getContext(), analysisday);
	}

	/**
	 * Set value of AnalysisDay
	 * @param context
	 * @param analysisday
	 */
	public final void setAnalysisDay(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal analysisday)
	{
		getMendixObject().setValue(context, MemberNames.AnalysisDay.toString(), analysisday);
	}

	/**
	 * @return value of RepairCounter
	 */
	public final java.math.BigDecimal getRepairCounter()
	{
		return getRepairCounter(getContext());
	}

	/**
	 * @param context
	 * @return value of RepairCounter
	 */
	public final java.math.BigDecimal getRepairCounter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RepairCounter.toString());
	}

	/**
	 * Set value of RepairCounter
	 * @param repaircounter
	 */
	public final void setRepairCounter(java.math.BigDecimal repaircounter)
	{
		setRepairCounter(getContext(), repaircounter);
	}

	/**
	 * Set value of RepairCounter
	 * @param context
	 * @param repaircounter
	 */
	public final void setRepairCounter(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal repaircounter)
	{
		getMendixObject().setValue(context, MemberNames.RepairCounter.toString(), repaircounter);
	}

	/**
	 * @return value of RepairWorkTime
	 */
	public final java.math.BigDecimal getRepairWorkTime()
	{
		return getRepairWorkTime(getContext());
	}

	/**
	 * @param context
	 * @return value of RepairWorkTime
	 */
	public final java.math.BigDecimal getRepairWorkTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RepairWorkTime.toString());
	}

	/**
	 * Set value of RepairWorkTime
	 * @param repairworktime
	 */
	public final void setRepairWorkTime(java.math.BigDecimal repairworktime)
	{
		setRepairWorkTime(getContext(), repairworktime);
	}

	/**
	 * Set value of RepairWorkTime
	 * @param context
	 * @param repairworktime
	 */
	public final void setRepairWorkTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal repairworktime)
	{
		getMendixObject().setValue(context, MemberNames.RepairWorkTime.toString(), repairworktime);
	}

	/**
	 * @return value of RepairDownTime
	 */
	public final java.math.BigDecimal getRepairDownTime()
	{
		return getRepairDownTime(getContext());
	}

	/**
	 * @param context
	 * @return value of RepairDownTime
	 */
	public final java.math.BigDecimal getRepairDownTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RepairDownTime.toString());
	}

	/**
	 * Set value of RepairDownTime
	 * @param repairdowntime
	 */
	public final void setRepairDownTime(java.math.BigDecimal repairdowntime)
	{
		setRepairDownTime(getContext(), repairdowntime);
	}

	/**
	 * Set value of RepairDownTime
	 * @param context
	 * @param repairdowntime
	 */
	public final void setRepairDownTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal repairdowntime)
	{
		getMendixObject().setValue(context, MemberNames.RepairDownTime.toString(), repairdowntime);
	}

	/**
	 * @return value of WorkOrderCount
	 */
	public final java.math.BigDecimal getWorkOrderCount()
	{
		return getWorkOrderCount(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderCount
	 */
	public final java.math.BigDecimal getWorkOrderCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.WorkOrderCount.toString());
	}

	/**
	 * Set value of WorkOrderCount
	 * @param workordercount
	 */
	public final void setWorkOrderCount(java.math.BigDecimal workordercount)
	{
		setWorkOrderCount(getContext(), workordercount);
	}

	/**
	 * Set value of WorkOrderCount
	 * @param context
	 * @param workordercount
	 */
	public final void setWorkOrderCount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal workordercount)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderCount.toString(), workordercount);
	}

	/**
	 * @return value of WorkOrderTotalTime
	 */
	public final java.math.BigDecimal getWorkOrderTotalTime()
	{
		return getWorkOrderTotalTime(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderTotalTime
	 */
	public final java.math.BigDecimal getWorkOrderTotalTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.WorkOrderTotalTime.toString());
	}

	/**
	 * Set value of WorkOrderTotalTime
	 * @param workordertotaltime
	 */
	public final void setWorkOrderTotalTime(java.math.BigDecimal workordertotaltime)
	{
		setWorkOrderTotalTime(getContext(), workordertotaltime);
	}

	/**
	 * Set value of WorkOrderTotalTime
	 * @param context
	 * @param workordertotaltime
	 */
	public final void setWorkOrderTotalTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal workordertotaltime)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderTotalTime.toString(), workordertotaltime);
	}

	/**
	 * @return value of WorkOrderTotalDownTime
	 */
	public final java.math.BigDecimal getWorkOrderTotalDownTime()
	{
		return getWorkOrderTotalDownTime(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderTotalDownTime
	 */
	public final java.math.BigDecimal getWorkOrderTotalDownTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.WorkOrderTotalDownTime.toString());
	}

	/**
	 * Set value of WorkOrderTotalDownTime
	 * @param workordertotaldowntime
	 */
	public final void setWorkOrderTotalDownTime(java.math.BigDecimal workordertotaldowntime)
	{
		setWorkOrderTotalDownTime(getContext(), workordertotaldowntime);
	}

	/**
	 * Set value of WorkOrderTotalDownTime
	 * @param context
	 * @param workordertotaldowntime
	 */
	public final void setWorkOrderTotalDownTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal workordertotaldowntime)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderTotalDownTime.toString(), workordertotaldowntime);
	}

	/**
	 * @return value of TotalRunTime
	 */
	public final java.math.BigDecimal getTotalRunTime()
	{
		return getTotalRunTime(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalRunTime
	 */
	public final java.math.BigDecimal getTotalRunTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalRunTime.toString());
	}

	/**
	 * Set value of TotalRunTime
	 * @param totalruntime
	 */
	public final void setTotalRunTime(java.math.BigDecimal totalruntime)
	{
		setTotalRunTime(getContext(), totalruntime);
	}

	/**
	 * Set value of TotalRunTime
	 * @param context
	 * @param totalruntime
	 */
	public final void setTotalRunTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalruntime)
	{
		getMendixObject().setValue(context, MemberNames.TotalRunTime.toString(), totalruntime);
	}

	/**
	 * @return value of RepairLastdate
	 */
	public final java.util.Date getRepairLastdate()
	{
		return getRepairLastdate(getContext());
	}

	/**
	 * @param context
	 * @return value of RepairLastdate
	 */
	public final java.util.Date getRepairLastdate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RepairLastdate.toString());
	}

	/**
	 * Set value of RepairLastdate
	 * @param repairlastdate
	 */
	public final void setRepairLastdate(java.util.Date repairlastdate)
	{
		setRepairLastdate(getContext(), repairlastdate);
	}

	/**
	 * Set value of RepairLastdate
	 * @param context
	 * @param repairlastdate
	 */
	public final void setRepairLastdate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date repairlastdate)
	{
		getMendixObject().setValue(context, MemberNames.RepairLastdate.toString(), repairlastdate);
	}

	/**
	 * @return value of MTBFday
	 */
	public final java.math.BigDecimal getMTBFday()
	{
		return getMTBFday(getContext());
	}

	/**
	 * @param context
	 * @return value of MTBFday
	 */
	public final java.math.BigDecimal getMTBFday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MTBFday.toString());
	}

	/**
	 * Set value of MTBFday
	 * @param mtbfday
	 */
	public final void setMTBFday(java.math.BigDecimal mtbfday)
	{
		setMTBFday(getContext(), mtbfday);
	}

	/**
	 * Set value of MTBFday
	 * @param context
	 * @param mtbfday
	 */
	public final void setMTBFday(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal mtbfday)
	{
		getMendixObject().setValue(context, MemberNames.MTBFday.toString(), mtbfday);
	}

	/**
	 * @return value of MTTRtime
	 */
	public final java.math.BigDecimal getMTTRtime()
	{
		return getMTTRtime(getContext());
	}

	/**
	 * @param context
	 * @return value of MTTRtime
	 */
	public final java.math.BigDecimal getMTTRtime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MTTRtime.toString());
	}

	/**
	 * Set value of MTTRtime
	 * @param mttrtime
	 */
	public final void setMTTRtime(java.math.BigDecimal mttrtime)
	{
		setMTTRtime(getContext(), mttrtime);
	}

	/**
	 * Set value of MTTRtime
	 * @param context
	 * @param mttrtime
	 */
	public final void setMTTRtime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal mttrtime)
	{
		getMendixObject().setValue(context, MemberNames.MTTRtime.toString(), mttrtime);
	}

	/**
	 * @return value of RateDown
	 */
	public final java.math.BigDecimal getRateDown()
	{
		return getRateDown(getContext());
	}

	/**
	 * @param context
	 * @return value of RateDown
	 */
	public final java.math.BigDecimal getRateDown(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RateDown.toString());
	}

	/**
	 * Set value of RateDown
	 * @param ratedown
	 */
	public final void setRateDown(java.math.BigDecimal ratedown)
	{
		setRateDown(getContext(), ratedown);
	}

	/**
	 * Set value of RateDown
	 * @param context
	 * @param ratedown
	 */
	public final void setRateDown(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ratedown)
	{
		getMendixObject().setValue(context, MemberNames.RateDown.toString(), ratedown);
	}

	/**
	 * @return value of RateRepair
	 */
	public final java.math.BigDecimal getRateRepair()
	{
		return getRateRepair(getContext());
	}

	/**
	 * @param context
	 * @return value of RateRepair
	 */
	public final java.math.BigDecimal getRateRepair(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RateRepair.toString());
	}

	/**
	 * Set value of RateRepair
	 * @param raterepair
	 */
	public final void setRateRepair(java.math.BigDecimal raterepair)
	{
		setRateRepair(getContext(), raterepair);
	}

	/**
	 * Set value of RateRepair
	 * @param context
	 * @param raterepair
	 */
	public final void setRateRepair(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal raterepair)
	{
		getMendixObject().setValue(context, MemberNames.RateRepair.toString(), raterepair);
	}

	/**
	 * @return value of RateFrequency
	 */
	public final java.math.BigDecimal getRateFrequency()
	{
		return getRateFrequency(getContext());
	}

	/**
	 * @param context
	 * @return value of RateFrequency
	 */
	public final java.math.BigDecimal getRateFrequency(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RateFrequency.toString());
	}

	/**
	 * Set value of RateFrequency
	 * @param ratefrequency
	 */
	public final void setRateFrequency(java.math.BigDecimal ratefrequency)
	{
		setRateFrequency(getContext(), ratefrequency);
	}

	/**
	 * Set value of RateFrequency
	 * @param context
	 * @param ratefrequency
	 */
	public final void setRateFrequency(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal ratefrequency)
	{
		getMendixObject().setValue(context, MemberNames.RateFrequency.toString(), ratefrequency);
	}

	/**
	 * @return value of RateSeverity
	 */
	public final java.math.BigDecimal getRateSeverity()
	{
		return getRateSeverity(getContext());
	}

	/**
	 * @param context
	 * @return value of RateSeverity
	 */
	public final java.math.BigDecimal getRateSeverity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RateSeverity.toString());
	}

	/**
	 * Set value of RateSeverity
	 * @param rateseverity
	 */
	public final void setRateSeverity(java.math.BigDecimal rateseverity)
	{
		setRateSeverity(getContext(), rateseverity);
	}

	/**
	 * Set value of RateSeverity
	 * @param context
	 * @param rateseverity
	 */
	public final void setRateSeverity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal rateseverity)
	{
		getMendixObject().setValue(context, MemberNames.RateSeverity.toString(), rateseverity);
	}

	/**
	 * @return value of RateUtilization
	 */
	public final java.math.BigDecimal getRateUtilization()
	{
		return getRateUtilization(getContext());
	}

	/**
	 * @param context
	 * @return value of RateUtilization
	 */
	public final java.math.BigDecimal getRateUtilization(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RateUtilization.toString());
	}

	/**
	 * Set value of RateUtilization
	 * @param rateutilization
	 */
	public final void setRateUtilization(java.math.BigDecimal rateutilization)
	{
		setRateUtilization(getContext(), rateutilization);
	}

	/**
	 * Set value of RateUtilization
	 * @param context
	 * @param rateutilization
	 */
	public final void setRateUtilization(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal rateutilization)
	{
		getMendixObject().setValue(context, MemberNames.RateUtilization.toString(), rateutilization);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaintenanceIndex_Equipment
	 */
	public final equipment_management.proxies.Equipment getMaintenanceIndex_Equipment() throws com.mendix.core.CoreException
	{
		return getMaintenanceIndex_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintenanceIndex_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getMaintenanceIndex_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaintenanceIndex_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaintenanceIndex_Equipment
	 * @param maintenanceindex_equipment
	 */
	public final void setMaintenanceIndex_Equipment(equipment_management.proxies.Equipment maintenanceindex_equipment)
	{
		setMaintenanceIndex_Equipment(getContext(), maintenanceindex_equipment);
	}

	/**
	 * Set value of MaintenanceIndex_Equipment
	 * @param context
	 * @param maintenanceindex_equipment
	 */
	public final void setMaintenanceIndex_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment maintenanceindex_equipment)
	{
		if (maintenanceindex_equipment == null) {
			getMendixObject().setValue(context, MemberNames.MaintenanceIndex_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaintenanceIndex_Equipment.toString(), maintenanceindex_equipment.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return maintenanceIndexMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.MaintenanceIndex that = (equipment_management.proxies.MaintenanceIndex) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
