// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

public class MaintenanceCost implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject maintenanceCostMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.MaintenanceCost";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		HRCost_Mon("HRCost_Mon"),
		HRCost_Year("HRCost_Year"),
		HR_TotalCost("HR_TotalCost"),
		OutsourcingCost_Mon("OutsourcingCost_Mon"),
		OutsourcingCost_year("OutsourcingCost_year"),
		Outsourcing_TotalCost("Outsourcing_TotalCost"),
		MaterialCost_Mon("MaterialCost_Mon"),
		MaterialCost_Year("MaterialCost_Year"),
		MaterialCost_TotalCost("MaterialCost_TotalCost"),
		EtcCost_mon("EtcCost_mon"),
		EtcCost_year("EtcCost_year"),
		EtcCost_totalCost("EtcCost_totalCost"),
		Sum_mon("Sum_mon"),
		Sum_year("Sum_year"),
		Sum_Total("Sum_Total"),
		CheckCount("CheckCount"),
		MaintenanceCost_Equipment("Equipment_Management.MaintenanceCost_Equipment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MaintenanceCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MaintenanceCost(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject maintenanceCostMendixObject)
	{
		if (maintenanceCostMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, maintenanceCostMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.maintenanceCostMendixObject = maintenanceCostMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.MaintenanceCost initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.MaintenanceCost(context, mendixObject);
	}

	public static equipment_management.proxies.MaintenanceCost load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.MaintenanceCost.initialize(context, mendixObject);
	}

	public static java.util.List<equipment_management.proxies.MaintenanceCost> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> equipment_management.proxies.MaintenanceCost.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of HRCost_Mon
	 */
	public final java.math.BigDecimal getHRCost_Mon()
	{
		return getHRCost_Mon(getContext());
	}

	/**
	 * @param context
	 * @return value of HRCost_Mon
	 */
	public final java.math.BigDecimal getHRCost_Mon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.HRCost_Mon.toString());
	}

	/**
	 * Set value of HRCost_Mon
	 * @param hrcost_mon
	 */
	public final void setHRCost_Mon(java.math.BigDecimal hrcost_mon)
	{
		setHRCost_Mon(getContext(), hrcost_mon);
	}

	/**
	 * Set value of HRCost_Mon
	 * @param context
	 * @param hrcost_mon
	 */
	public final void setHRCost_Mon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal hrcost_mon)
	{
		getMendixObject().setValue(context, MemberNames.HRCost_Mon.toString(), hrcost_mon);
	}

	/**
	 * @return value of HRCost_Year
	 */
	public final java.math.BigDecimal getHRCost_Year()
	{
		return getHRCost_Year(getContext());
	}

	/**
	 * @param context
	 * @return value of HRCost_Year
	 */
	public final java.math.BigDecimal getHRCost_Year(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.HRCost_Year.toString());
	}

	/**
	 * Set value of HRCost_Year
	 * @param hrcost_year
	 */
	public final void setHRCost_Year(java.math.BigDecimal hrcost_year)
	{
		setHRCost_Year(getContext(), hrcost_year);
	}

	/**
	 * Set value of HRCost_Year
	 * @param context
	 * @param hrcost_year
	 */
	public final void setHRCost_Year(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal hrcost_year)
	{
		getMendixObject().setValue(context, MemberNames.HRCost_Year.toString(), hrcost_year);
	}

	/**
	 * @return value of HR_TotalCost
	 */
	public final java.math.BigDecimal getHR_TotalCost()
	{
		return getHR_TotalCost(getContext());
	}

	/**
	 * @param context
	 * @return value of HR_TotalCost
	 */
	public final java.math.BigDecimal getHR_TotalCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.HR_TotalCost.toString());
	}

	/**
	 * Set value of HR_TotalCost
	 * @param hr_totalcost
	 */
	public final void setHR_TotalCost(java.math.BigDecimal hr_totalcost)
	{
		setHR_TotalCost(getContext(), hr_totalcost);
	}

	/**
	 * Set value of HR_TotalCost
	 * @param context
	 * @param hr_totalcost
	 */
	public final void setHR_TotalCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal hr_totalcost)
	{
		getMendixObject().setValue(context, MemberNames.HR_TotalCost.toString(), hr_totalcost);
	}

	/**
	 * @return value of OutsourcingCost_Mon
	 */
	public final java.math.BigDecimal getOutsourcingCost_Mon()
	{
		return getOutsourcingCost_Mon(getContext());
	}

	/**
	 * @param context
	 * @return value of OutsourcingCost_Mon
	 */
	public final java.math.BigDecimal getOutsourcingCost_Mon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.OutsourcingCost_Mon.toString());
	}

	/**
	 * Set value of OutsourcingCost_Mon
	 * @param outsourcingcost_mon
	 */
	public final void setOutsourcingCost_Mon(java.math.BigDecimal outsourcingcost_mon)
	{
		setOutsourcingCost_Mon(getContext(), outsourcingcost_mon);
	}

	/**
	 * Set value of OutsourcingCost_Mon
	 * @param context
	 * @param outsourcingcost_mon
	 */
	public final void setOutsourcingCost_Mon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal outsourcingcost_mon)
	{
		getMendixObject().setValue(context, MemberNames.OutsourcingCost_Mon.toString(), outsourcingcost_mon);
	}

	/**
	 * @return value of OutsourcingCost_year
	 */
	public final java.math.BigDecimal getOutsourcingCost_year()
	{
		return getOutsourcingCost_year(getContext());
	}

	/**
	 * @param context
	 * @return value of OutsourcingCost_year
	 */
	public final java.math.BigDecimal getOutsourcingCost_year(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.OutsourcingCost_year.toString());
	}

	/**
	 * Set value of OutsourcingCost_year
	 * @param outsourcingcost_year
	 */
	public final void setOutsourcingCost_year(java.math.BigDecimal outsourcingcost_year)
	{
		setOutsourcingCost_year(getContext(), outsourcingcost_year);
	}

	/**
	 * Set value of OutsourcingCost_year
	 * @param context
	 * @param outsourcingcost_year
	 */
	public final void setOutsourcingCost_year(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal outsourcingcost_year)
	{
		getMendixObject().setValue(context, MemberNames.OutsourcingCost_year.toString(), outsourcingcost_year);
	}

	/**
	 * @return value of Outsourcing_TotalCost
	 */
	public final java.math.BigDecimal getOutsourcing_TotalCost()
	{
		return getOutsourcing_TotalCost(getContext());
	}

	/**
	 * @param context
	 * @return value of Outsourcing_TotalCost
	 */
	public final java.math.BigDecimal getOutsourcing_TotalCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Outsourcing_TotalCost.toString());
	}

	/**
	 * Set value of Outsourcing_TotalCost
	 * @param outsourcing_totalcost
	 */
	public final void setOutsourcing_TotalCost(java.math.BigDecimal outsourcing_totalcost)
	{
		setOutsourcing_TotalCost(getContext(), outsourcing_totalcost);
	}

	/**
	 * Set value of Outsourcing_TotalCost
	 * @param context
	 * @param outsourcing_totalcost
	 */
	public final void setOutsourcing_TotalCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal outsourcing_totalcost)
	{
		getMendixObject().setValue(context, MemberNames.Outsourcing_TotalCost.toString(), outsourcing_totalcost);
	}

	/**
	 * @return value of MaterialCost_Mon
	 */
	public final java.math.BigDecimal getMaterialCost_Mon()
	{
		return getMaterialCost_Mon(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCost_Mon
	 */
	public final java.math.BigDecimal getMaterialCost_Mon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaterialCost_Mon.toString());
	}

	/**
	 * Set value of MaterialCost_Mon
	 * @param materialcost_mon
	 */
	public final void setMaterialCost_Mon(java.math.BigDecimal materialcost_mon)
	{
		setMaterialCost_Mon(getContext(), materialcost_mon);
	}

	/**
	 * Set value of MaterialCost_Mon
	 * @param context
	 * @param materialcost_mon
	 */
	public final void setMaterialCost_Mon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal materialcost_mon)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCost_Mon.toString(), materialcost_mon);
	}

	/**
	 * @return value of MaterialCost_Year
	 */
	public final java.math.BigDecimal getMaterialCost_Year()
	{
		return getMaterialCost_Year(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCost_Year
	 */
	public final java.math.BigDecimal getMaterialCost_Year(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaterialCost_Year.toString());
	}

	/**
	 * Set value of MaterialCost_Year
	 * @param materialcost_year
	 */
	public final void setMaterialCost_Year(java.math.BigDecimal materialcost_year)
	{
		setMaterialCost_Year(getContext(), materialcost_year);
	}

	/**
	 * Set value of MaterialCost_Year
	 * @param context
	 * @param materialcost_year
	 */
	public final void setMaterialCost_Year(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal materialcost_year)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCost_Year.toString(), materialcost_year);
	}

	/**
	 * @return value of MaterialCost_TotalCost
	 */
	public final java.math.BigDecimal getMaterialCost_TotalCost()
	{
		return getMaterialCost_TotalCost(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCost_TotalCost
	 */
	public final java.math.BigDecimal getMaterialCost_TotalCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaterialCost_TotalCost.toString());
	}

	/**
	 * Set value of MaterialCost_TotalCost
	 * @param materialcost_totalcost
	 */
	public final void setMaterialCost_TotalCost(java.math.BigDecimal materialcost_totalcost)
	{
		setMaterialCost_TotalCost(getContext(), materialcost_totalcost);
	}

	/**
	 * Set value of MaterialCost_TotalCost
	 * @param context
	 * @param materialcost_totalcost
	 */
	public final void setMaterialCost_TotalCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal materialcost_totalcost)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCost_TotalCost.toString(), materialcost_totalcost);
	}

	/**
	 * @return value of EtcCost_mon
	 */
	public final java.math.BigDecimal getEtcCost_mon()
	{
		return getEtcCost_mon(getContext());
	}

	/**
	 * @param context
	 * @return value of EtcCost_mon
	 */
	public final java.math.BigDecimal getEtcCost_mon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.EtcCost_mon.toString());
	}

	/**
	 * Set value of EtcCost_mon
	 * @param etccost_mon
	 */
	public final void setEtcCost_mon(java.math.BigDecimal etccost_mon)
	{
		setEtcCost_mon(getContext(), etccost_mon);
	}

	/**
	 * Set value of EtcCost_mon
	 * @param context
	 * @param etccost_mon
	 */
	public final void setEtcCost_mon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal etccost_mon)
	{
		getMendixObject().setValue(context, MemberNames.EtcCost_mon.toString(), etccost_mon);
	}

	/**
	 * @return value of EtcCost_year
	 */
	public final java.math.BigDecimal getEtcCost_year()
	{
		return getEtcCost_year(getContext());
	}

	/**
	 * @param context
	 * @return value of EtcCost_year
	 */
	public final java.math.BigDecimal getEtcCost_year(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.EtcCost_year.toString());
	}

	/**
	 * Set value of EtcCost_year
	 * @param etccost_year
	 */
	public final void setEtcCost_year(java.math.BigDecimal etccost_year)
	{
		setEtcCost_year(getContext(), etccost_year);
	}

	/**
	 * Set value of EtcCost_year
	 * @param context
	 * @param etccost_year
	 */
	public final void setEtcCost_year(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal etccost_year)
	{
		getMendixObject().setValue(context, MemberNames.EtcCost_year.toString(), etccost_year);
	}

	/**
	 * @return value of EtcCost_totalCost
	 */
	public final java.math.BigDecimal getEtcCost_totalCost()
	{
		return getEtcCost_totalCost(getContext());
	}

	/**
	 * @param context
	 * @return value of EtcCost_totalCost
	 */
	public final java.math.BigDecimal getEtcCost_totalCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.EtcCost_totalCost.toString());
	}

	/**
	 * Set value of EtcCost_totalCost
	 * @param etccost_totalcost
	 */
	public final void setEtcCost_totalCost(java.math.BigDecimal etccost_totalcost)
	{
		setEtcCost_totalCost(getContext(), etccost_totalcost);
	}

	/**
	 * Set value of EtcCost_totalCost
	 * @param context
	 * @param etccost_totalcost
	 */
	public final void setEtcCost_totalCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal etccost_totalcost)
	{
		getMendixObject().setValue(context, MemberNames.EtcCost_totalCost.toString(), etccost_totalcost);
	}

	/**
	 * @return value of Sum_mon
	 */
	public final java.math.BigDecimal getSum_mon()
	{
		return getSum_mon(getContext());
	}

	/**
	 * @param context
	 * @return value of Sum_mon
	 */
	public final java.math.BigDecimal getSum_mon(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Sum_mon.toString());
	}

	/**
	 * Set value of Sum_mon
	 * @param sum_mon
	 */
	public final void setSum_mon(java.math.BigDecimal sum_mon)
	{
		setSum_mon(getContext(), sum_mon);
	}

	/**
	 * Set value of Sum_mon
	 * @param context
	 * @param sum_mon
	 */
	public final void setSum_mon(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sum_mon)
	{
		getMendixObject().setValue(context, MemberNames.Sum_mon.toString(), sum_mon);
	}

	/**
	 * @return value of Sum_year
	 */
	public final java.math.BigDecimal getSum_year()
	{
		return getSum_year(getContext());
	}

	/**
	 * @param context
	 * @return value of Sum_year
	 */
	public final java.math.BigDecimal getSum_year(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Sum_year.toString());
	}

	/**
	 * Set value of Sum_year
	 * @param sum_year
	 */
	public final void setSum_year(java.math.BigDecimal sum_year)
	{
		setSum_year(getContext(), sum_year);
	}

	/**
	 * Set value of Sum_year
	 * @param context
	 * @param sum_year
	 */
	public final void setSum_year(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sum_year)
	{
		getMendixObject().setValue(context, MemberNames.Sum_year.toString(), sum_year);
	}

	/**
	 * @return value of Sum_Total
	 */
	public final java.math.BigDecimal getSum_Total()
	{
		return getSum_Total(getContext());
	}

	/**
	 * @param context
	 * @return value of Sum_Total
	 */
	public final java.math.BigDecimal getSum_Total(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Sum_Total.toString());
	}

	/**
	 * Set value of Sum_Total
	 * @param sum_total
	 */
	public final void setSum_Total(java.math.BigDecimal sum_total)
	{
		setSum_Total(getContext(), sum_total);
	}

	/**
	 * Set value of Sum_Total
	 * @param context
	 * @param sum_total
	 */
	public final void setSum_Total(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal sum_total)
	{
		getMendixObject().setValue(context, MemberNames.Sum_Total.toString(), sum_total);
	}

	/**
	 * @return value of CheckCount
	 */
	public final java.lang.Integer getCheckCount()
	{
		return getCheckCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CheckCount
	 */
	public final java.lang.Integer getCheckCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CheckCount.toString());
	}

	/**
	 * Set value of CheckCount
	 * @param checkcount
	 */
	public final void setCheckCount(java.lang.Integer checkcount)
	{
		setCheckCount(getContext(), checkcount);
	}

	/**
	 * Set value of CheckCount
	 * @param context
	 * @param checkcount
	 */
	public final void setCheckCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer checkcount)
	{
		getMendixObject().setValue(context, MemberNames.CheckCount.toString(), checkcount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaintenanceCost_Equipment
	 */
	public final equipment_management.proxies.Equipment getMaintenanceCost_Equipment() throws com.mendix.core.CoreException
	{
		return getMaintenanceCost_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintenanceCost_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getMaintenanceCost_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaintenanceCost_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaintenanceCost_Equipment
	 * @param maintenancecost_equipment
	 */
	public final void setMaintenanceCost_Equipment(equipment_management.proxies.Equipment maintenancecost_equipment)
	{
		setMaintenanceCost_Equipment(getContext(), maintenancecost_equipment);
	}

	/**
	 * Set value of MaintenanceCost_Equipment
	 * @param context
	 * @param maintenancecost_equipment
	 */
	public final void setMaintenanceCost_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment maintenancecost_equipment)
	{
		if (maintenancecost_equipment == null) {
			getMendixObject().setValue(context, MemberNames.MaintenanceCost_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaintenanceCost_Equipment.toString(), maintenancecost_equipment.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return maintenanceCostMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.MaintenanceCost that = (equipment_management.proxies.MaintenanceCost) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
