// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package equipment_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/06
 * 최종 수정자 : 이단비
 * 최초 작성일 : 2023/10/06
 * 설명 : 설비정보 세부 페이지 오픈 헬퍼
 * 
 * Version 1.0 : 생성
 */
public class SideSubViewHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sideSubViewHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Equipment_Management.SideSubViewHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ShowSubpage("ShowSubpage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SideSubViewHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SideSubViewHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sideSubViewHelperMendixObject)
	{
		if (sideSubViewHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, sideSubViewHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sideSubViewHelperMendixObject = sideSubViewHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static equipment_management.proxies.SideSubViewHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new equipment_management.proxies.SideSubViewHelper(context, mendixObject);
	}

	public static equipment_management.proxies.SideSubViewHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return equipment_management.proxies.SideSubViewHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of ShowSubpage
	 */
	public final java.lang.Boolean getShowSubpage()
	{
		return getShowSubpage(getContext());
	}

	/**
	 * @param context
	 * @return value of ShowSubpage
	 */
	public final java.lang.Boolean getShowSubpage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ShowSubpage.toString());
	}

	/**
	 * Set value of ShowSubpage
	 * @param showsubpage
	 */
	public final void setShowSubpage(java.lang.Boolean showsubpage)
	{
		setShowSubpage(getContext(), showsubpage);
	}

	/**
	 * Set value of ShowSubpage
	 * @param context
	 * @param showsubpage
	 */
	public final void setShowSubpage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean showsubpage)
	{
		getMendixObject().setValue(context, MemberNames.ShowSubpage.toString(), showsubpage);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sideSubViewHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final equipment_management.proxies.SideSubViewHelper that = (equipment_management.proxies.SideSubViewHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
