// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Development_Settings module
	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/21
	 * 설명 : 중복선택 가능한 RMhelper Obj 저장
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_AddMenuPerRoleBuilder(
		development_settings.proxies.Tempview _tempview,
		development_settings.proxies.Menu _menu,
		commons.proxies.StandardCode _standardCode
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_AddMenuPerRole");
		builder = builder.withParam("Tempview", _tempview);
		builder = builder.withParam("Menu", _menu);
		builder = builder.withParam("StandardCode", _standardCode);
		return builder;
	}

	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/21
	 * 설명 : 중복선택 가능한 RMhelper Obj 저장
	 * Version 1.0 : 생성
	 */
	public static void aCT_AddMenuPerRole(
		IContext context,
		development_settings.proxies.Tempview _tempview,
		development_settings.proxies.Menu _menu,
		commons.proxies.StandardCode _standardCode
	)
	{
		aCT_AddMenuPerRoleBuilder(
				_tempview,
				_menu,
				_standardCode
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 이단비
	 * 최초 작성일 : 2023/09/01
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/01
	 * 설명 : 기준코드 데이터의 사용여부를 설정해서 저장하는 로직
	 * 데이터 그리드의 Active 체크박스 클릭 시 호출된다.
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Code_Type_ActiveBuilder(
		commons.proxies.CodeType _codeType
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_Code_Type_Active");
		builder = builder.withParam("CodeType", _codeType);
		return builder;
	}

	/**
	 * 최초 작성자 : 이단비
	 * 최초 작성일 : 2023/09/01
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/01
	 * 설명 : 기준코드 데이터의 사용여부를 설정해서 저장하는 로직
	 * 데이터 그리드의 Active 체크박스 클릭 시 호출된다.
	 * Version 1.0 : 생성
	 */
	public static void aCT_Code_Type_Active(
		IContext context,
		commons.proxies.CodeType _codeType
	)
	{
		aCT_Code_Type_ActiveBuilder(
				_codeType
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 이단비
	 * 최초 작성일 : 2023/09/01
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/01
	 * 설명 : 기준코드 데이터의 New / Edit 저장하는 로직으로 코드타입에 현재 선택된 코드 타입을자동으로 설정하고 새로운 코드의 경우 Sequence는 전체 카운트 +1로 자동 설정해준다.
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Code_Type_CommitBuilder(
		commons.proxies.CodeType _codeType
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_Code_Type_Commit");
		builder = builder.withParam("CodeType", _codeType);
		return builder;
	}

	/**
	 * 최초 작성자 : 이단비
	 * 최초 작성일 : 2023/09/01
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/01
	 * 설명 : 기준코드 데이터의 New / Edit 저장하는 로직으로 코드타입에 현재 선택된 코드 타입을자동으로 설정하고 새로운 코드의 경우 Sequence는 전체 카운트 +1로 자동 설정해준다.
	 * Version 1.0 : 생성
	 */
	public static void aCT_Code_Type_Commit(
		IContext context,
		commons.proxies.CodeType _codeType
	)
	{
		aCT_Code_Type_CommitBuilder(
				_codeType
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Code_Type_DeActiveBuilder(
		commons.proxies.CodeType _codeType
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_Code_Type_DeActive");
		builder = builder.withParam("CodeType", _codeType);
		return builder;
	}

	public static void aCT_Code_Type_DeActive(
		IContext context,
		commons.proxies.CodeType _codeType
	)
	{
		aCT_Code_Type_DeActiveBuilder(
				_codeType
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : Topbar에서 메뉴 클릭시 페이지 결정 MF
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MenuBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_Menu");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : Topbar에서 메뉴 클릭시 페이지 결정 MF
	 * Version 1.0 : 생성
	 */
	public static void aCT_Menu(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		aCT_MenuBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/20
	 * 설명 : 메뉴 등록을 위한 MF
	 * 
	 * V 1.1 : 개별화 로직 적용
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Menu_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_Menu_Create");
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/20
	 * 설명 : 메뉴 등록을 위한 MF
	 * 
	 * V 1.1 : 개별화 로직 적용
	 * Version 1.0 : 생성
	 */
	public static void aCT_Menu_Create(IContext context)
	{
		aCT_Menu_CreateBuilder().execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/20
	 * 설명 : 메뉴 수정을 위한 MF
	 * 
	 * V 1.1 : 개별화 로직 적용
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Menu_EditBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_Menu_Edit");
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/20
	 * 설명 : 메뉴 수정을 위한 MF
	 * 
	 * V 1.1 : 개별화 로직 적용
	 * Version 1.0 : 생성
	 */
	public static void aCT_Menu_Edit(IContext context)
	{
		aCT_Menu_EditBuilder().execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/06
	 * 설명 : 메뉴 순서를 낮추기 위한 MF
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Menu_OrderingDownBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_Menu_OrderingDown");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/06
	 * 설명 : 메뉴 순서를 낮추기 위한 MF
	 * Version 1.0 : 생성
	 */
	public static void aCT_Menu_OrderingDown(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		aCT_Menu_OrderingDownBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 김동명
	 * 최종 수정일 : 2023/09/08
	 * 
	 * 설명 : 메뉴 순서를 높히기 위한 MF
	 * 
	 * V 1.1 : Title Menu일경우 안되는 부분 수정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Menu_OrderingUpBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_Menu_OrderingUp");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 김동명
	 * 최종 수정일 : 2023/09/08
	 * 
	 * 설명 : 메뉴 순서를 높히기 위한 MF
	 * 
	 * V 1.1 : Title Menu일경우 안되는 부분 수정
	 * Version 1.0 : 생성
	 */
	public static void aCT_Menu_OrderingUp(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		aCT_Menu_OrderingUpBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/11
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/11
	 * 설명 : 선택한 menu Association에 커밋
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder act_Savemenu_UserroleBuilder(
		commons.proxies.StandardCode _standardCode,
		java.util.List<development_settings.proxies.Menu> _menuList_2
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.Act_Savemenu_Userrole");
		builder = builder.withParam("StandardCode", _standardCode);
		builder = builder.withParam("MenuList_2", _menuList_2);
		return builder;
	}

	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/11
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/11
	 * 설명 : 선택한 menu Association에 커밋
	 * Version 1.0 : 생성
	 */
	public static void act_Savemenu_Userrole(
		IContext context,
		commons.proxies.StandardCode _standardCode,
		java.util.List<development_settings.proxies.Menu> _menuList_2
	)
	{
		act_Savemenu_UserroleBuilder(
				_standardCode,
				_menuList_2
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 2023/11/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/11/21
	 * 설명 : SelectMulti로 node list 만들기
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_SelectMultiListBuilder(
		development_settings.proxies.Selecthelper _selecthelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.ACT_SelectMultiList");
		builder = builder.withParam("Selecthelper", _selecthelper);
		return builder;
	}

	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 2023/11/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/11/21
	 * 설명 : SelectMulti로 node list 만들기
	 * Version 1.0 : 생성
	 */
	public static void aCT_SelectMultiList(
		IContext context,
		development_settings.proxies.Selecthelper _selecthelper
	)
	{
		aCT_SelectMultiListBuilder(
				_selecthelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder cALC_Code_Type_All_CountBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.CALC_Code_Type_All_Count");
		return builder;
	}

	public static cmms_administration.proxies.TotalCount cALC_Code_Type_All_Count(IContext context)
	{
		Object result = cALC_Code_Type_All_CountBuilder().execute(context);
		return result == null ? null : cmms_administration.proxies.TotalCount.initialize(context, (IMendixObject) result);
	}
	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/21
	 * 설명 : CreateMenu
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder createMenuBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.CreateMenu");
		return builder;
	}

	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/21
	 * 설명 : CreateMenu
	 * Version 1.0 : 생성
	 */
	public static development_settings.proxies.Menu createMenu(IContext context)
	{
		Object result = createMenuBuilder().execute(context);
		return result == null ? null : development_settings.proxies.Menu.initialize(context, (IMendixObject) result);
	}
	/**
	 * 최초작성자 : 김동명
	 * 최초작성일 : 2023/09/08
	 * 최종수정자 : 
	 * 최종수정일 :
	 * 
	 * 설명: 회사 DS를 불러오는 MF
	 * 
	 * Version 1.1: 작성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_CompanyBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.DS_Company");
		return builder;
	}

	/**
	 * 최초작성자 : 김동명
	 * 최초작성일 : 2023/09/08
	 * 최종수정자 : 
	 * 최종수정일 :
	 * 
	 * 설명: 회사 DS를 불러오는 MF
	 * 
	 * Version 1.1: 작성
	 */
	public static commons.proxies.Company dS_Company(IContext context)
	{
		Object result = dS_CompanyBuilder().execute(context);
		return result == null ? null : commons.proxies.Company.initialize(context, (IMendixObject) result);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/06
	 * 설명 : MenuTreeview에 사용 될 DS
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Menu_TreeviewBuilder(
		commons.proxies.Company _company
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.DS_Menu_Treeview");
		builder = builder.withParam("Company", _company);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/06
	 * 설명 : MenuTreeview에 사용 될 DS
	 * Version 1.0 : 생성
	 */
	public static java.util.List<development_settings.proxies.Menu> dS_Menu_Treeview(
		IContext context,
		commons.proxies.Company _company
	)
	{
		Object result = dS_Menu_TreeviewBuilder(
				_company
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> development_settings.proxies.Menu.initialize(context, obj));
	}
	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/21
	 * 설명 : Menu Tree Page open
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_MenuTreePageOpenBuilder(
		commons.proxies.StandardCode _standardCode
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.DS_MenuTreePageOpen");
		builder = builder.withParam("StandardCode", _standardCode);
		return builder;
	}

	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/21
	 * 설명 : Menu Tree Page open
	 * Version 1.0 : 생성
	 */
	public static void dS_MenuTreePageOpen(
		IContext context,
		commons.proxies.StandardCode _standardCode
	)
	{
		dS_MenuTreePageOpenBuilder(
				_standardCode
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/21
	 * 설명 : Tree Tempview 만들기
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_TreeTempviewBuilder(
		development_settings.proxies.Menu _menu,
		commons.proxies.StandardCode _standardCode
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.DS_TreeTempview");
		builder = builder.withParam("Menu", _menu);
		builder = builder.withParam("StandardCode", _standardCode);
		return builder;
	}

	/**
	 * 최초 작성자 : 박재훈
	 * 최초 작성일 : 202310/21
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/10/21
	 * 설명 : Tree Tempview 만들기
	 * Version 1.0 : 생성
	 */
	public static development_settings.proxies.Tempview dS_TreeTempview(
		IContext context,
		development_settings.proxies.Menu _menu,
		commons.proxies.StandardCode _standardCode
	)
	{
		Object result = dS_TreeTempviewBuilder(
				_menu,
				_standardCode
			)
			.execute(context);
		return result == null ? null : development_settings.proxies.Tempview.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder menu_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.Menu_Create");
		return builder;
	}

	public static development_settings.proxies.Menu menu_Create(IContext context)
	{
		Object result = menu_CreateBuilder().execute(context);
		return result == null ? null : development_settings.proxies.Menu.initialize(context, (IMendixObject) result);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/20
	 * 최종 수정자 : 
	 * 최종 수정일 : 
	 * 
	 * 설명 : Helper 삭제 Sub MF
	 * 
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder menuHelper_DeleteBuilder(
		administration.proxies.Account _currentUser
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.MenuHelper_Delete");
		builder = builder.withParam("CurrentUser", _currentUser);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/20
	 * 최종 수정자 : 
	 * 최종 수정일 : 
	 * 
	 * 설명 : Helper 삭제 Sub MF
	 * 
	 * Version 1.0 : 생성
	 */
	public static void menuHelper_Delete(
		IContext context,
		administration.proxies.Account _currentUser
	)
	{
		menuHelper_DeleteBuilder(
				_currentUser
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/20
	 * 설명 : 트리뷰에서 노드 클릭했을때의 액션 / 단일 object 정의
	 * 
	 * V 1.1 : 개별화 로직 적용
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCK_MenuTreeview_NodeBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.OCK_MenuTreeview_Node");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/20
	 * 설명 : 트리뷰에서 노드 클릭했을때의 액션 / 단일 object 정의
	 * 
	 * V 1.1 : 개별화 로직 적용
	 * Version 1.0 : 생성
	 */
	public static void oCK_MenuTreeview_Node(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		oCK_MenuTreeview_NodeBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 김동명
	 * 최종 수정일 : 2023/09/20
	 * 설명 : 트리뷰에서 노드 클릭했을때의 액션 / 단일 object 정의
	 * 
	 * V 1.2 : 개별화 로직 적용
	 * V 1.1 : 이름 수정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCK_MenuTreeview_Node_CompanyBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.OCK_MenuTreeview_Node_Company");
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/06
	 * 최종 수정자 : 김동명
	 * 최종 수정일 : 2023/09/20
	 * 설명 : 트리뷰에서 노드 클릭했을때의 액션 / 단일 object 정의
	 * 
	 * V 1.2 : 개별화 로직 적용
	 * V 1.1 : 이름 수정
	 * Version 1.0 : 생성
	 */
	public static void oCK_MenuTreeview_Node_Company(IContext context)
	{
		oCK_MenuTreeview_Node_CompanyBuilder().execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_Check_History_ManagementBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_Check_History_Management");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_Check_History_Management(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_Check_History_ManagementBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_CMMS_AdministrationBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_CMMS_Administration");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_CMMS_Administration(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_CMMS_AdministrationBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_EDMSBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_EDMS");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_EDMS(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_EDMSBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_Equipment_Check_ManagementBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_Equipment_Check_Management");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_Equipment_Check_Management(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_Equipment_Check_ManagementBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_Equipment_ManagementBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_Equipment_Management");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_Equipment_Management(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_Equipment_ManagementBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_Material_ManagementBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_Material_Management");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_Material_Management(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_Material_ManagementBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_MonitoringBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_Monitoring");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_Monitoring(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_MonitoringBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_ReportBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_Report");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_Report(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_ReportBuilder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_SQL2008Builder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_SQL2008");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_SQL2008(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_SQL2008Builder(
				_menu
			)
			.execute(context);
	}
	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Menu_Work_ManagementBuilder(
		development_settings.proxies.Menu _menu
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Development_Settings.SUB_Menu_Work_Management");
		builder = builder.withParam("Menu", _menu);
		return builder;
	}

	/**
	 * 최초 작성자 : 김동명
	 * 최초 작성일 : 2023/09/05
	 * 최종 수정자 : 
	 * 최종 수정일 : 2023/09/05
	 * 설명 : 해당 모듈에서의 페이지 결정
	 * Version 1.0 : 생성
	 */
	public static void sUB_Menu_Work_Management(
		IContext context,
		development_settings.proxies.Menu _menu
	)
	{
		sUB_Menu_Work_ManagementBuilder(
				_menu
			)
			.execute(context);
	}
}
