// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies;

public class Account extends system.proxies.User
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Administration.Account";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FullName("FullName"),
		Email("Email"),
		IsLocalUser("IsLocalUser"),
		RegistrationDate("RegistrationDate"),
		EmployeeName("EmployeeName"),
		EnglishName("EnglishName"),
		No("No"),
		Userdescription("Userdescription"),
		SelectUserrole("SelectUserrole"),
		Outsourceactive("Outsourceactive"),
		IsUsed("IsUsed"),
		IsRegisted("IsRegisted"),
		Role("Role"),
		Name("Name"),
		Password("Password"),
		LastLogin("LastLogin"),
		Blocked("Blocked"),
		BlockedSince("BlockedSince"),
		Active("Active"),
		FailedLogins("FailedLogins"),
		WebServiceUser("WebServiceUser"),
		IsAnonymous("IsAnonymous"),
		Employee_Account("CMMS_Administration.Employee_Account"),
		StandardCode_Account("Commons.StandardCode_Account"),
		UserRoles("System.UserRoles"),
		User_Language("System.User_Language"),
		User_TimeZone("System.User_TimeZone");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Account(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Account(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject accountMendixObject)
	{
		super(context, accountMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, accountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static administration.proxies.Account initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("CMMS_Administration.User", mendixObject.getType())) {
			return cmms_administration.proxies.User.initialize(context, mendixObject);
		}
		return new administration.proxies.Account(context, mendixObject);
	}

	public static administration.proxies.Account load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return administration.proxies.Account.initialize(context, mendixObject);
	}

	public static java.util.List<? extends administration.proxies.Account> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> administration.proxies.Account.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of FullName
	 */
	public final java.lang.String getFullName()
	{
		return getFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of FullName
	 */
	public final java.lang.String getFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FullName.toString());
	}

	/**
	 * Set value of FullName
	 * @param fullname
	 */
	public final void setFullName(java.lang.String fullname)
	{
		setFullName(getContext(), fullname);
	}

	/**
	 * Set value of FullName
	 * @param context
	 * @param fullname
	 */
	public final void setFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String fullname)
	{
		getMendixObject().setValue(context, MemberNames.FullName.toString(), fullname);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of IsLocalUser
	 */
	public final java.lang.Boolean getIsLocalUser()
	{
		return getIsLocalUser(getContext());
	}

	/**
	 * @param context
	 * @return value of IsLocalUser
	 */
	public final java.lang.Boolean getIsLocalUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsLocalUser.toString());
	}

	/**
	 * Set value of IsLocalUser
	 * @param islocaluser
	 */
	public final void setIsLocalUser(java.lang.Boolean islocaluser)
	{
		setIsLocalUser(getContext(), islocaluser);
	}

	/**
	 * Set value of IsLocalUser
	 * @param context
	 * @param islocaluser
	 */
	public final void setIsLocalUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean islocaluser)
	{
		getMendixObject().setValue(context, MemberNames.IsLocalUser.toString(), islocaluser);
	}

	/**
	 * @return value of RegistrationDate
	 */
	public final java.util.Date getRegistrationDate()
	{
		return getRegistrationDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RegistrationDate
	 */
	public final java.util.Date getRegistrationDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RegistrationDate.toString());
	}

	/**
	 * Set value of RegistrationDate
	 * @param registrationdate
	 */
	public final void setRegistrationDate(java.util.Date registrationdate)
	{
		setRegistrationDate(getContext(), registrationdate);
	}

	/**
	 * Set value of RegistrationDate
	 * @param context
	 * @param registrationdate
	 */
	public final void setRegistrationDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date registrationdate)
	{
		getMendixObject().setValue(context, MemberNames.RegistrationDate.toString(), registrationdate);
	}

	/**
	 * @return value of EmployeeName
	 */
	public final java.lang.String getEmployeeName()
	{
		return getEmployeeName(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeName
	 */
	public final java.lang.String getEmployeeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeName.toString());
	}

	/**
	 * Set value of EmployeeName
	 * @param employeename
	 */
	public final void setEmployeeName(java.lang.String employeename)
	{
		setEmployeeName(getContext(), employeename);
	}

	/**
	 * Set value of EmployeeName
	 * @param context
	 * @param employeename
	 */
	public final void setEmployeeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeename)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeName.toString(), employeename);
	}

	/**
	 * @return value of EnglishName
	 */
	public final java.lang.String getEnglishName()
	{
		return getEnglishName(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishName
	 */
	public final java.lang.String getEnglishName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EnglishName.toString());
	}

	/**
	 * Set value of EnglishName
	 * @param englishname
	 */
	public final void setEnglishName(java.lang.String englishname)
	{
		setEnglishName(getContext(), englishname);
	}

	/**
	 * Set value of EnglishName
	 * @param context
	 * @param englishname
	 */
	public final void setEnglishName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String englishname)
	{
		getMendixObject().setValue(context, MemberNames.EnglishName.toString(), englishname);
	}

	/**
	 * @return value of No
	 */
	public final java.lang.Long getNo()
	{
		return getNo(getContext());
	}

	/**
	 * @param context
	 * @return value of No
	 */
	public final java.lang.Long getNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.No.toString());
	}

	/**
	 * Set value of No
	 * @param no
	 */
	public final void setNo(java.lang.Long no)
	{
		setNo(getContext(), no);
	}

	/**
	 * Set value of No
	 * @param context
	 * @param no
	 */
	public final void setNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long no)
	{
		getMendixObject().setValue(context, MemberNames.No.toString(), no);
	}

	/**
	 * @return value of Userdescription
	 */
	public final java.lang.String getUserdescription()
	{
		return getUserdescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Userdescription
	 */
	public final java.lang.String getUserdescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Userdescription.toString());
	}

	/**
	 * Set value of Userdescription
	 * @param userdescription
	 */
	public final void setUserdescription(java.lang.String userdescription)
	{
		setUserdescription(getContext(), userdescription);
	}

	/**
	 * Set value of Userdescription
	 * @param context
	 * @param userdescription
	 */
	public final void setUserdescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String userdescription)
	{
		getMendixObject().setValue(context, MemberNames.Userdescription.toString(), userdescription);
	}

	/**
	 * @return value of SelectUserrole
	 */
	public final java.lang.String getSelectUserrole()
	{
		return getSelectUserrole(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectUserrole
	 */
	public final java.lang.String getSelectUserrole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SelectUserrole.toString());
	}

	/**
	 * Set value of SelectUserrole
	 * @param selectuserrole
	 */
	public final void setSelectUserrole(java.lang.String selectuserrole)
	{
		setSelectUserrole(getContext(), selectuserrole);
	}

	/**
	 * Set value of SelectUserrole
	 * @param context
	 * @param selectuserrole
	 */
	public final void setSelectUserrole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String selectuserrole)
	{
		getMendixObject().setValue(context, MemberNames.SelectUserrole.toString(), selectuserrole);
	}

	/**
	 * @return value of Outsourceactive
	 */
	public final java.lang.Boolean getOutsourceactive()
	{
		return getOutsourceactive(getContext());
	}

	/**
	 * @param context
	 * @return value of Outsourceactive
	 */
	public final java.lang.Boolean getOutsourceactive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Outsourceactive.toString());
	}

	/**
	 * Set value of Outsourceactive
	 * @param outsourceactive
	 */
	public final void setOutsourceactive(java.lang.Boolean outsourceactive)
	{
		setOutsourceactive(getContext(), outsourceactive);
	}

	/**
	 * Set value of Outsourceactive
	 * @param context
	 * @param outsourceactive
	 */
	public final void setOutsourceactive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean outsourceactive)
	{
		getMendixObject().setValue(context, MemberNames.Outsourceactive.toString(), outsourceactive);
	}

	/**
	 * @return value of IsUsed
	 */
	public final java.lang.Boolean getIsUsed()
	{
		return getIsUsed(getContext());
	}

	/**
	 * @param context
	 * @return value of IsUsed
	 */
	public final java.lang.Boolean getIsUsed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsUsed.toString());
	}

	/**
	 * Set value of IsUsed
	 * @param isused
	 */
	public final void setIsUsed(java.lang.Boolean isused)
	{
		setIsUsed(getContext(), isused);
	}

	/**
	 * Set value of IsUsed
	 * @param context
	 * @param isused
	 */
	public final void setIsUsed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isused)
	{
		getMendixObject().setValue(context, MemberNames.IsUsed.toString(), isused);
	}

	/**
	 * @return value of IsRegisted
	 */
	public final java.lang.Boolean getIsRegisted()
	{
		return getIsRegisted(getContext());
	}

	/**
	 * @param context
	 * @return value of IsRegisted
	 */
	public final java.lang.Boolean getIsRegisted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsRegisted.toString());
	}

	/**
	 * Set value of IsRegisted
	 * @param isregisted
	 */
	public final void setIsRegisted(java.lang.Boolean isregisted)
	{
		setIsRegisted(getContext(), isregisted);
	}

	/**
	 * Set value of IsRegisted
	 * @param context
	 * @param isregisted
	 */
	public final void setIsRegisted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isregisted)
	{
		getMendixObject().setValue(context, MemberNames.IsRegisted.toString(), isregisted);
	}

	/**
	 * @return value of Role
	 */
	public final java.lang.String getRole()
	{
		return getRole(getContext());
	}

	/**
	 * @param context
	 * @return value of Role
	 */
	public final java.lang.String getRole(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Role.toString());
	}

	/**
	 * Set value of Role
	 * @param role
	 */
	public final void setRole(java.lang.String role)
	{
		setRole(getContext(), role);
	}

	/**
	 * Set value of Role
	 * @param context
	 * @param role
	 */
	public final void setRole(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String role)
	{
		getMendixObject().setValue(context, MemberNames.Role.toString(), role);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Account
	 */
	public final cmms_administration.proxies.Employee getEmployee_Account() throws com.mendix.core.CoreException
	{
		return getEmployee_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Account.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Account
	 * @param employee_account
	 */
	public final void setEmployee_Account(cmms_administration.proxies.Employee employee_account)
	{
		setEmployee_Account(getContext(), employee_account);
	}

	/**
	 * Set value of Employee_Account
	 * @param context
	 * @param employee_account
	 */
	public final void setEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee employee_account)
	{
		if (employee_account == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), employee_account.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StandardCode_Account
	 */
	public final commons.proxies.StandardCode getStandardCode_Account() throws com.mendix.core.CoreException
	{
		return getStandardCode_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of StandardCode_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getStandardCode_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StandardCode_Account.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StandardCode_Account
	 * @param standardcode_account
	 */
	public final void setStandardCode_Account(commons.proxies.StandardCode standardcode_account)
	{
		setStandardCode_Account(getContext(), standardcode_account);
	}

	/**
	 * Set value of StandardCode_Account
	 * @param context
	 * @param standardcode_account
	 */
	public final void setStandardCode_Account(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode standardcode_account)
	{
		if (standardcode_account == null) {
			getMendixObject().setValue(context, MemberNames.StandardCode_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StandardCode_Account.toString(), standardcode_account.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final administration.proxies.Account that = (administration.proxies.Account) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
