// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package administration.proxies;

public enum Enum_Userrole
{
	Administrator(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "시스템관리자" } }),
	GeneralManager(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "관리자" } }),
	Requester(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "요청자" } }),
	Developer(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "개발자" } }),
	Approver(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "승인자" } }),
	MaintenanceManager(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "보전관리자" } }),
	MaintenanceWorker(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "보전작업자" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Enum_Userrole(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
