// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package globalsearch.proxies;

public class Movie extends globalsearch.proxies.SearchableObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GlobalSearch.Movie";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Description("Description"),
		StarRating("StarRating"),
		Actors("Actors"),
		Genres("Genres"),
		Genre_Movie("GlobalSearch.Genre_Movie"),
		Actor_Movie("GlobalSearch.Actor_Movie");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Movie(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Movie(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject movieMendixObject)
	{
		super(context, movieMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, movieMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static globalsearch.proxies.Movie initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new globalsearch.proxies.Movie(context, mendixObject);
	}

	public static globalsearch.proxies.Movie load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return globalsearch.proxies.Movie.initialize(context, mendixObject);
	}

	public static java.util.List<globalsearch.proxies.Movie> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> globalsearch.proxies.Movie.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Description
	 */
	public final java.lang.String getDescription()
	{
		return getDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of Description
	 */
	public final java.lang.String getDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Description.toString());
	}

	/**
	 * Set value of Description
	 * @param description
	 */
	public final void setDescription(java.lang.String description)
	{
		setDescription(getContext(), description);
	}

	/**
	 * Set value of Description
	 * @param context
	 * @param description
	 */
	public final void setDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String description)
	{
		getMendixObject().setValue(context, MemberNames.Description.toString(), description);
	}

	/**
	 * @return value of StarRating
	 */
	public final java.lang.Integer getStarRating()
	{
		return getStarRating(getContext());
	}

	/**
	 * @param context
	 * @return value of StarRating
	 */
	public final java.lang.Integer getStarRating(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.StarRating.toString());
	}

	/**
	 * Set value of StarRating
	 * @param starrating
	 */
	public final void setStarRating(java.lang.Integer starrating)
	{
		setStarRating(getContext(), starrating);
	}

	/**
	 * Set value of StarRating
	 * @param context
	 * @param starrating
	 */
	public final void setStarRating(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer starrating)
	{
		getMendixObject().setValue(context, MemberNames.StarRating.toString(), starrating);
	}

	/**
	 * @return value of Actors
	 */
	public final java.lang.String getActors()
	{
		return getActors(getContext());
	}

	/**
	 * @param context
	 * @return value of Actors
	 */
	public final java.lang.String getActors(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Actors.toString());
	}

	/**
	 * Set value of Actors
	 * @param actors
	 */
	public final void setActors(java.lang.String actors)
	{
		setActors(getContext(), actors);
	}

	/**
	 * Set value of Actors
	 * @param context
	 * @param actors
	 */
	public final void setActors(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String actors)
	{
		getMendixObject().setValue(context, MemberNames.Actors.toString(), actors);
	}

	/**
	 * @return value of Genres
	 */
	public final java.lang.String getGenres()
	{
		return getGenres(getContext());
	}

	/**
	 * @param context
	 * @return value of Genres
	 */
	public final java.lang.String getGenres(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Genres.toString());
	}

	/**
	 * Set value of Genres
	 * @param genres
	 */
	public final void setGenres(java.lang.String genres)
	{
		setGenres(getContext(), genres);
	}

	/**
	 * Set value of Genres
	 * @param context
	 * @param genres
	 */
	public final void setGenres(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String genres)
	{
		getMendixObject().setValue(context, MemberNames.Genres.toString(), genres);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Genre_Movie
	 */
	public final java.util.List<globalsearch.proxies.Genre> getGenre_Movie() throws com.mendix.core.CoreException
	{
		return getGenre_Movie(getContext());
	}

	/**
	 * @param context
	 * @return value of Genre_Movie
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<globalsearch.proxies.Genre> getGenre_Movie(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<globalsearch.proxies.Genre> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Genre_Movie.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(globalsearch.proxies.Genre.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Genre_Movie
	 * @param genre_movie
	 */
	public final void setGenre_Movie(java.util.List<globalsearch.proxies.Genre> genre_movie)
	{
		setGenre_Movie(getContext(), genre_movie);
	}

	/**
	 * Set value of Genre_Movie
	 * @param context
	 * @param genre_movie
	 */
	public final void setGenre_Movie(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<globalsearch.proxies.Genre> genre_movie)
	{
		var identifiers = genre_movie
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Genre_Movie.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Actor_Movie
	 */
	public final java.util.List<globalsearch.proxies.Actor> getActor_Movie() throws com.mendix.core.CoreException
	{
		return getActor_Movie(getContext());
	}

	/**
	 * @param context
	 * @return value of Actor_Movie
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<globalsearch.proxies.Actor> getActor_Movie(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<globalsearch.proxies.Actor> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Actor_Movie.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(globalsearch.proxies.Actor.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Actor_Movie
	 * @param actor_movie
	 */
	public final void setActor_Movie(java.util.List<globalsearch.proxies.Actor> actor_movie)
	{
		setActor_Movie(getContext(), actor_movie);
	}

	/**
	 * Set value of Actor_Movie
	 * @param context
	 * @param actor_movie
	 */
	public final void setActor_Movie(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<globalsearch.proxies.Actor> actor_movie)
	{
		var identifiers = actor_movie
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Actor_Movie.toString(), identifiers);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final globalsearch.proxies.Movie that = (globalsearch.proxies.Movie) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
