// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package globalsearch.proxies;

public class SearchableObjectCache implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchableObjectCacheMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GlobalSearch.SearchableObjectCache";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EntityName("EntityName"),
		EntityGUID("EntityGUID"),
		Indexed("Indexed");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SearchableObjectCache(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SearchableObjectCache(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchableObjectCacheMendixObject)
	{
		if (searchableObjectCacheMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, searchableObjectCacheMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.searchableObjectCacheMendixObject = searchableObjectCacheMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static globalsearch.proxies.SearchableObjectCache initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new globalsearch.proxies.SearchableObjectCache(context, mendixObject);
	}

	public static globalsearch.proxies.SearchableObjectCache load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return globalsearch.proxies.SearchableObjectCache.initialize(context, mendixObject);
	}

	public static java.util.List<globalsearch.proxies.SearchableObjectCache> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> globalsearch.proxies.SearchableObjectCache.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EntityName
	 */
	public final java.lang.String getEntityName()
	{
		return getEntityName(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityName
	 */
	public final java.lang.String getEntityName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EntityName.toString());
	}

	/**
	 * Set value of EntityName
	 * @param entityname
	 */
	public final void setEntityName(java.lang.String entityname)
	{
		setEntityName(getContext(), entityname);
	}

	/**
	 * Set value of EntityName
	 * @param context
	 * @param entityname
	 */
	public final void setEntityName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entityname)
	{
		getMendixObject().setValue(context, MemberNames.EntityName.toString(), entityname);
	}

	/**
	 * @return value of EntityGUID
	 */
	public final java.lang.String getEntityGUID()
	{
		return getEntityGUID(getContext());
	}

	/**
	 * @param context
	 * @return value of EntityGUID
	 */
	public final java.lang.String getEntityGUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EntityGUID.toString());
	}

	/**
	 * Set value of EntityGUID
	 * @param entityguid
	 */
	public final void setEntityGUID(java.lang.String entityguid)
	{
		setEntityGUID(getContext(), entityguid);
	}

	/**
	 * Set value of EntityGUID
	 * @param context
	 * @param entityguid
	 */
	public final void setEntityGUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String entityguid)
	{
		getMendixObject().setValue(context, MemberNames.EntityGUID.toString(), entityguid);
	}

	/**
	 * @return value of Indexed
	 */
	public final java.lang.Boolean getIndexed()
	{
		return getIndexed(getContext());
	}

	/**
	 * @param context
	 * @return value of Indexed
	 */
	public final java.lang.Boolean getIndexed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Indexed.toString());
	}

	/**
	 * Set value of Indexed
	 * @param indexed
	 */
	public final void setIndexed(java.lang.Boolean indexed)
	{
		setIndexed(getContext(), indexed);
	}

	/**
	 * Set value of Indexed
	 * @param context
	 * @param indexed
	 */
	public final void setIndexed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean indexed)
	{
		getMendixObject().setValue(context, MemberNames.Indexed.toString(), indexed);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchableObjectCacheMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final globalsearch.proxies.SearchableObjectCache that = (globalsearch.proxies.SearchableObjectCache) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
