// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package globalsearch.proxies;

public class SearchableObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searchableObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GlobalSearch.SearchableObject";

	public SearchableObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SearchableObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searchableObjectMendixObject)
	{
		if (searchableObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, searchableObjectMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.searchableObjectMendixObject = searchableObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static globalsearch.proxies.SearchableObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		if (com.mendix.core.Core.isSubClassOf("GlobalSearch.Actor", mendixObject.getType())) {
			return globalsearch.proxies.Actor.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("Equipment_Management.Equipment", mendixObject.getType())) {
			return equipment_management.proxies.Equipment.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("GlobalSearch.Movie", mendixObject.getType())) {
			return globalsearch.proxies.Movie.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("Monitoring.Sensor", mendixObject.getType())) {
			return monitoring.proxies.Sensor.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("Work_Management.WorkHistory", mendixObject.getType())) {
			return work_management.proxies.WorkHistory.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("Work_Management.WorkOrder", mendixObject.getType())) {
			return work_management.proxies.WorkOrder.initialize(context, mendixObject);
		}
		if (com.mendix.core.Core.isSubClassOf("Work_Management.WorkOrderResult", mendixObject.getType())) {
			return work_management.proxies.WorkOrderResult.initialize(context, mendixObject);
		}
		return new globalsearch.proxies.SearchableObject(context, mendixObject);
	}

	public static globalsearch.proxies.SearchableObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return globalsearch.proxies.SearchableObject.initialize(context, mendixObject);
	}

	public static java.util.List<? extends globalsearch.proxies.SearchableObject> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> globalsearch.proxies.SearchableObject.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searchableObjectMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final globalsearch.proxies.SearchableObject that = (globalsearch.proxies.SearchableObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
