// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package globalsearch.proxies;

public class Searcher implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject searcherMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "GlobalSearch.Searcher";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SearchString("SearchString"),
		NumberOfResults("NumberOfResults"),
		NumberOfseconds("NumberOfseconds"),
		SearchComplete("SearchComplete"),
		FilterApplied("FilterApplied"),
		HasFilters("HasFilters"),
		SearchType("SearchType"),
		IncludeFilters("IncludeFilters"),
		ResultListCount("ResultListCount"),
		Searcher_SearchableObject("GlobalSearch.Searcher_SearchableObject"),
		Searcher_Session("GlobalSearch.Searcher_Session");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Searcher(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Searcher(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject searcherMendixObject)
	{
		if (searcherMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, searcherMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.searcherMendixObject = searcherMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static globalsearch.proxies.Searcher initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new globalsearch.proxies.Searcher(context, mendixObject);
	}

	public static globalsearch.proxies.Searcher load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return globalsearch.proxies.Searcher.initialize(context, mendixObject);
	}

	/**
	 * @return value of SearchString
	 */
	public final java.lang.String getSearchString()
	{
		return getSearchString(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchString
	 */
	public final java.lang.String getSearchString(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SearchString.toString());
	}

	/**
	 * Set value of SearchString
	 * @param searchstring
	 */
	public final void setSearchString(java.lang.String searchstring)
	{
		setSearchString(getContext(), searchstring);
	}

	/**
	 * Set value of SearchString
	 * @param context
	 * @param searchstring
	 */
	public final void setSearchString(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String searchstring)
	{
		getMendixObject().setValue(context, MemberNames.SearchString.toString(), searchstring);
	}

	/**
	 * @return value of NumberOfResults
	 */
	public final java.lang.Integer getNumberOfResults()
	{
		return getNumberOfResults(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfResults
	 */
	public final java.lang.Integer getNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.NumberOfResults.toString());
	}

	/**
	 * Set value of NumberOfResults
	 * @param numberofresults
	 */
	public final void setNumberOfResults(java.lang.Integer numberofresults)
	{
		setNumberOfResults(getContext(), numberofresults);
	}

	/**
	 * Set value of NumberOfResults
	 * @param context
	 * @param numberofresults
	 */
	public final void setNumberOfResults(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer numberofresults)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfResults.toString(), numberofresults);
	}

	/**
	 * @return value of NumberOfseconds
	 */
	public final java.math.BigDecimal getNumberOfseconds()
	{
		return getNumberOfseconds(getContext());
	}

	/**
	 * @param context
	 * @return value of NumberOfseconds
	 */
	public final java.math.BigDecimal getNumberOfseconds(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NumberOfseconds.toString());
	}

	/**
	 * Set value of NumberOfseconds
	 * @param numberofseconds
	 */
	public final void setNumberOfseconds(java.math.BigDecimal numberofseconds)
	{
		setNumberOfseconds(getContext(), numberofseconds);
	}

	/**
	 * Set value of NumberOfseconds
	 * @param context
	 * @param numberofseconds
	 */
	public final void setNumberOfseconds(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal numberofseconds)
	{
		getMendixObject().setValue(context, MemberNames.NumberOfseconds.toString(), numberofseconds);
	}

	/**
	 * @return value of SearchComplete
	 */
	public final java.lang.Boolean getSearchComplete()
	{
		return getSearchComplete(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchComplete
	 */
	public final java.lang.Boolean getSearchComplete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SearchComplete.toString());
	}

	/**
	 * Set value of SearchComplete
	 * @param searchcomplete
	 */
	public final void setSearchComplete(java.lang.Boolean searchcomplete)
	{
		setSearchComplete(getContext(), searchcomplete);
	}

	/**
	 * Set value of SearchComplete
	 * @param context
	 * @param searchcomplete
	 */
	public final void setSearchComplete(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean searchcomplete)
	{
		getMendixObject().setValue(context, MemberNames.SearchComplete.toString(), searchcomplete);
	}

	/**
	 * @return value of FilterApplied
	 */
	public final java.lang.Boolean getFilterApplied()
	{
		return getFilterApplied(getContext());
	}

	/**
	 * @param context
	 * @return value of FilterApplied
	 */
	public final java.lang.Boolean getFilterApplied(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.FilterApplied.toString());
	}

	/**
	 * Set value of FilterApplied
	 * @param filterapplied
	 */
	public final void setFilterApplied(java.lang.Boolean filterapplied)
	{
		setFilterApplied(getContext(), filterapplied);
	}

	/**
	 * Set value of FilterApplied
	 * @param context
	 * @param filterapplied
	 */
	public final void setFilterApplied(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean filterapplied)
	{
		getMendixObject().setValue(context, MemberNames.FilterApplied.toString(), filterapplied);
	}

	/**
	 * @return value of HasFilters
	 */
	public final java.lang.Boolean getHasFilters()
	{
		return getHasFilters(getContext());
	}

	/**
	 * @param context
	 * @return value of HasFilters
	 */
	public final java.lang.Boolean getHasFilters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.HasFilters.toString());
	}

	/**
	 * Set value of HasFilters
	 * @param hasfilters
	 */
	public final void setHasFilters(java.lang.Boolean hasfilters)
	{
		setHasFilters(getContext(), hasfilters);
	}

	/**
	 * Set value of HasFilters
	 * @param context
	 * @param hasfilters
	 */
	public final void setHasFilters(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean hasfilters)
	{
		getMendixObject().setValue(context, MemberNames.HasFilters.toString(), hasfilters);
	}

	/**
	 * Get value of SearchType
	 * @param searchtype
	 */
	public final globalsearch.proxies.Enum_SearchType getSearchType()
	{
		return getSearchType(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchType
	 */
	public final globalsearch.proxies.Enum_SearchType getSearchType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.SearchType.toString());
		if (obj == null) {
			return null;
		}
		return globalsearch.proxies.Enum_SearchType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of SearchType
	 * @param searchtype
	 */
	public final void setSearchType(globalsearch.proxies.Enum_SearchType searchtype)
	{
		setSearchType(getContext(), searchtype);
	}

	/**
	 * Set value of SearchType
	 * @param context
	 * @param searchtype
	 */
	public final void setSearchType(com.mendix.systemwideinterfaces.core.IContext context, globalsearch.proxies.Enum_SearchType searchtype)
	{
		if (searchtype != null) {
			getMendixObject().setValue(context, MemberNames.SearchType.toString(), searchtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.SearchType.toString(), null);
		}
	}

	/**
	 * @return value of IncludeFilters
	 */
	public final java.lang.Boolean getIncludeFilters()
	{
		return getIncludeFilters(getContext());
	}

	/**
	 * @param context
	 * @return value of IncludeFilters
	 */
	public final java.lang.Boolean getIncludeFilters(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IncludeFilters.toString());
	}

	/**
	 * Set value of IncludeFilters
	 * @param includefilters
	 */
	public final void setIncludeFilters(java.lang.Boolean includefilters)
	{
		setIncludeFilters(getContext(), includefilters);
	}

	/**
	 * Set value of IncludeFilters
	 * @param context
	 * @param includefilters
	 */
	public final void setIncludeFilters(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean includefilters)
	{
		getMendixObject().setValue(context, MemberNames.IncludeFilters.toString(), includefilters);
	}

	/**
	 * @return value of ResultListCount
	 */
	public final java.lang.Integer getResultListCount()
	{
		return getResultListCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultListCount
	 */
	public final java.lang.Integer getResultListCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ResultListCount.toString());
	}

	/**
	 * Set value of ResultListCount
	 * @param resultlistcount
	 */
	public final void setResultListCount(java.lang.Integer resultlistcount)
	{
		setResultListCount(getContext(), resultlistcount);
	}

	/**
	 * Set value of ResultListCount
	 * @param context
	 * @param resultlistcount
	 */
	public final void setResultListCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer resultlistcount)
	{
		getMendixObject().setValue(context, MemberNames.ResultListCount.toString(), resultlistcount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Searcher_SearchableObject
	 */
	public final java.util.List<globalsearch.proxies.SearchableObject> getSearcher_SearchableObject() throws com.mendix.core.CoreException
	{
		return getSearcher_SearchableObject(getContext());
	}

	/**
	 * @param context
	 * @return value of Searcher_SearchableObject
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<globalsearch.proxies.SearchableObject> getSearcher_SearchableObject(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<globalsearch.proxies.SearchableObject> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Searcher_SearchableObject.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(globalsearch.proxies.SearchableObject.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Searcher_SearchableObject
	 * @param searcher_searchableobject
	 */
	public final void setSearcher_SearchableObject(java.util.List<globalsearch.proxies.SearchableObject> searcher_searchableobject)
	{
		setSearcher_SearchableObject(getContext(), searcher_searchableobject);
	}

	/**
	 * Set value of Searcher_SearchableObject
	 * @param context
	 * @param searcher_searchableobject
	 */
	public final void setSearcher_SearchableObject(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<globalsearch.proxies.SearchableObject> searcher_searchableobject)
	{
		var identifiers = searcher_searchableobject
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Searcher_SearchableObject.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Searcher_Session
	 */
	public final system.proxies.Session getSearcher_Session() throws com.mendix.core.CoreException
	{
		return getSearcher_Session(getContext());
	}

	/**
	 * @param context
	 * @return value of Searcher_Session
	 * @throws com.mendix.core.CoreException
	 */
	public final system.proxies.Session getSearcher_Session(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		system.proxies.Session result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Searcher_Session.toString());
		if (identifier != null) {
			result = system.proxies.Session.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Searcher_Session
	 * @param searcher_session
	 */
	public final void setSearcher_Session(system.proxies.Session searcher_session)
	{
		setSearcher_Session(getContext(), searcher_session);
	}

	/**
	 * Set value of Searcher_Session
	 * @param context
	 * @param searcher_session
	 */
	public final void setSearcher_Session(com.mendix.systemwideinterfaces.core.IContext context, system.proxies.Session searcher_session)
	{
		if (searcher_session == null) {
			getMendixObject().setValue(context, MemberNames.Searcher_Session.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Searcher_Session.toString(), searcher_session.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return searcherMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final globalsearch.proxies.Searcher that = (globalsearch.proxies.Searcher) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
