// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package monitoring.proxies;

public class SensorSearchHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sensorSearchHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Monitoring.SensorSearchHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SensorSearchHelper_StandardCode("Monitoring.SensorSearchHelper_StandardCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SensorSearchHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SensorSearchHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sensorSearchHelperMendixObject)
	{
		if (sensorSearchHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, sensorSearchHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sensorSearchHelperMendixObject = sensorSearchHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static monitoring.proxies.SensorSearchHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new monitoring.proxies.SensorSearchHelper(context, mendixObject);
	}

	public static monitoring.proxies.SensorSearchHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return monitoring.proxies.SensorSearchHelper.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SensorSearchHelper_StandardCode
	 */
	public final commons.proxies.StandardCode getSensorSearchHelper_StandardCode() throws com.mendix.core.CoreException
	{
		return getSensorSearchHelper_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorSearchHelper_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getSensorSearchHelper_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SensorSearchHelper_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SensorSearchHelper_StandardCode
	 * @param sensorsearchhelper_standardcode
	 */
	public final void setSensorSearchHelper_StandardCode(commons.proxies.StandardCode sensorsearchhelper_standardcode)
	{
		setSensorSearchHelper_StandardCode(getContext(), sensorsearchhelper_standardcode);
	}

	/**
	 * Set value of SensorSearchHelper_StandardCode
	 * @param context
	 * @param sensorsearchhelper_standardcode
	 */
	public final void setSensorSearchHelper_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode sensorsearchhelper_standardcode)
	{
		if (sensorsearchhelper_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.SensorSearchHelper_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SensorSearchHelper_StandardCode.toString(), sensorsearchhelper_standardcode.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sensorSearchHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final monitoring.proxies.SensorSearchHelper that = (monitoring.proxies.SensorSearchHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
