// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package monitoring.proxies;

public class SensorImage extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Monitoring.SensorImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImageName("ImageName"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		SensorImage_Sensor("Monitoring.SensorImage_Sensor");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SensorImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected SensorImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sensorImageMendixObject)
	{
		super(context, sensorImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, sensorImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static monitoring.proxies.SensorImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new monitoring.proxies.SensorImage(context, mendixObject);
	}

	public static monitoring.proxies.SensorImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return monitoring.proxies.SensorImage.initialize(context, mendixObject);
	}

	public static java.util.List<monitoring.proxies.SensorImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> monitoring.proxies.SensorImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName()
	{
		return getImageName(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageName.toString());
	}

	/**
	 * Set value of ImageName
	 * @param imagename
	 */
	public final void setImageName(java.lang.String imagename)
	{
		setImageName(getContext(), imagename);
	}

	/**
	 * Set value of ImageName
	 * @param context
	 * @param imagename
	 */
	public final void setImageName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imagename)
	{
		getMendixObject().setValue(context, MemberNames.ImageName.toString(), imagename);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SensorImage_Sensor
	 */
	public final monitoring.proxies.Sensor getSensorImage_Sensor() throws com.mendix.core.CoreException
	{
		return getSensorImage_Sensor(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorImage_Sensor
	 * @throws com.mendix.core.CoreException
	 */
	public final monitoring.proxies.Sensor getSensorImage_Sensor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		monitoring.proxies.Sensor result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SensorImage_Sensor.toString());
		if (identifier != null) {
			result = monitoring.proxies.Sensor.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SensorImage_Sensor
	 * @param sensorimage_sensor
	 */
	public final void setSensorImage_Sensor(monitoring.proxies.Sensor sensorimage_sensor)
	{
		setSensorImage_Sensor(getContext(), sensorimage_sensor);
	}

	/**
	 * Set value of SensorImage_Sensor
	 * @param context
	 * @param sensorimage_sensor
	 */
	public final void setSensorImage_Sensor(com.mendix.systemwideinterfaces.core.IContext context, monitoring.proxies.Sensor sensorimage_sensor)
	{
		if (sensorimage_sensor == null) {
			getMendixObject().setValue(context, MemberNames.SensorImage_Sensor.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SensorImage_Sensor.toString(), sensorimage_sensor.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final monitoring.proxies.SensorImage that = (monitoring.proxies.SensorImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
