// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package monitoring.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/05
 * 최종 수정자 : 
 * 최종 수정일 : 2023/10/05
 * 설명 : 실시간 센서 데이터를 담는 엔터티
 * Version 1.0 : 생성
 */
public class Sensor extends globalsearch.proxies.SearchableObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Monitoring.Sensor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SensorCode("SensorCode"),
		SensorName("SensorName"),
		IsAnalog("IsAnalog"),
		SendSMS("SendSMS"),
		SendEmail("SendEmail"),
		IsControlable("IsControlable"),
		StopStartTime("StopStartTime"),
		StopEndTime("StopEndTime"),
		NormalValue("NormalValue"),
		CorrectionValue("CorrectionValue"),
		UpperLimitValue("UpperLimitValue"),
		LowerLimitValue("LowerLimitValue"),
		InstallDate("InstallDate"),
		DataStoreDay("DataStoreDay"),
		SensorDescription("SensorDescription"),
		Active("Active"),
		Sensor_Server("Monitoring.Sensor_Server"),
		SensorImage_Sensor("Monitoring.SensorImage_Sensor"),
		Sensor_Plant("Monitoring.Sensor_Plant"),
		SensorStatus_StandardCode("Monitoring.SensorStatus_StandardCode"),
		SensorType_StandardCode("Monitoring.SensorType_StandardCode"),
		SensorUnit_StandardCode("Monitoring.SensorUnit_StandardCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Sensor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Sensor(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sensorMendixObject)
	{
		super(context, sensorMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, sensorMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static monitoring.proxies.Sensor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new monitoring.proxies.Sensor(context, mendixObject);
	}

	public static monitoring.proxies.Sensor load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return monitoring.proxies.Sensor.initialize(context, mendixObject);
	}

	public static java.util.List<monitoring.proxies.Sensor> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> monitoring.proxies.Sensor.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of SensorCode
	 */
	public final java.lang.String getSensorCode()
	{
		return getSensorCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorCode
	 */
	public final java.lang.String getSensorCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SensorCode.toString());
	}

	/**
	 * Set value of SensorCode
	 * @param sensorcode
	 */
	public final void setSensorCode(java.lang.String sensorcode)
	{
		setSensorCode(getContext(), sensorcode);
	}

	/**
	 * Set value of SensorCode
	 * @param context
	 * @param sensorcode
	 */
	public final void setSensorCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sensorcode)
	{
		getMendixObject().setValue(context, MemberNames.SensorCode.toString(), sensorcode);
	}

	/**
	 * @return value of SensorName
	 */
	public final java.lang.String getSensorName()
	{
		return getSensorName(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorName
	 */
	public final java.lang.String getSensorName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SensorName.toString());
	}

	/**
	 * Set value of SensorName
	 * @param sensorname
	 */
	public final void setSensorName(java.lang.String sensorname)
	{
		setSensorName(getContext(), sensorname);
	}

	/**
	 * Set value of SensorName
	 * @param context
	 * @param sensorname
	 */
	public final void setSensorName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sensorname)
	{
		getMendixObject().setValue(context, MemberNames.SensorName.toString(), sensorname);
	}

	/**
	 * @return value of IsAnalog
	 */
	public final java.lang.Boolean getIsAnalog()
	{
		return getIsAnalog(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAnalog
	 */
	public final java.lang.Boolean getIsAnalog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAnalog.toString());
	}

	/**
	 * Set value of IsAnalog
	 * @param isanalog
	 */
	public final void setIsAnalog(java.lang.Boolean isanalog)
	{
		setIsAnalog(getContext(), isanalog);
	}

	/**
	 * Set value of IsAnalog
	 * @param context
	 * @param isanalog
	 */
	public final void setIsAnalog(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isanalog)
	{
		getMendixObject().setValue(context, MemberNames.IsAnalog.toString(), isanalog);
	}

	/**
	 * @return value of SendSMS
	 */
	public final java.lang.Boolean getSendSMS()
	{
		return getSendSMS(getContext());
	}

	/**
	 * @param context
	 * @return value of SendSMS
	 */
	public final java.lang.Boolean getSendSMS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SendSMS.toString());
	}

	/**
	 * Set value of SendSMS
	 * @param sendsms
	 */
	public final void setSendSMS(java.lang.Boolean sendsms)
	{
		setSendSMS(getContext(), sendsms);
	}

	/**
	 * Set value of SendSMS
	 * @param context
	 * @param sendsms
	 */
	public final void setSendSMS(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sendsms)
	{
		getMendixObject().setValue(context, MemberNames.SendSMS.toString(), sendsms);
	}

	/**
	 * @return value of SendEmail
	 */
	public final java.lang.Boolean getSendEmail()
	{
		return getSendEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of SendEmail
	 */
	public final java.lang.Boolean getSendEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SendEmail.toString());
	}

	/**
	 * Set value of SendEmail
	 * @param sendemail
	 */
	public final void setSendEmail(java.lang.Boolean sendemail)
	{
		setSendEmail(getContext(), sendemail);
	}

	/**
	 * Set value of SendEmail
	 * @param context
	 * @param sendemail
	 */
	public final void setSendEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sendemail)
	{
		getMendixObject().setValue(context, MemberNames.SendEmail.toString(), sendemail);
	}

	/**
	 * @return value of IsControlable
	 */
	public final java.lang.Boolean getIsControlable()
	{
		return getIsControlable(getContext());
	}

	/**
	 * @param context
	 * @return value of IsControlable
	 */
	public final java.lang.Boolean getIsControlable(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsControlable.toString());
	}

	/**
	 * Set value of IsControlable
	 * @param iscontrolable
	 */
	public final void setIsControlable(java.lang.Boolean iscontrolable)
	{
		setIsControlable(getContext(), iscontrolable);
	}

	/**
	 * Set value of IsControlable
	 * @param context
	 * @param iscontrolable
	 */
	public final void setIsControlable(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscontrolable)
	{
		getMendixObject().setValue(context, MemberNames.IsControlable.toString(), iscontrolable);
	}

	/**
	 * @return value of StopStartTime
	 */
	public final java.util.Date getStopStartTime()
	{
		return getStopStartTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StopStartTime
	 */
	public final java.util.Date getStopStartTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StopStartTime.toString());
	}

	/**
	 * Set value of StopStartTime
	 * @param stopstarttime
	 */
	public final void setStopStartTime(java.util.Date stopstarttime)
	{
		setStopStartTime(getContext(), stopstarttime);
	}

	/**
	 * Set value of StopStartTime
	 * @param context
	 * @param stopstarttime
	 */
	public final void setStopStartTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date stopstarttime)
	{
		getMendixObject().setValue(context, MemberNames.StopStartTime.toString(), stopstarttime);
	}

	/**
	 * @return value of StopEndTime
	 */
	public final java.util.Date getStopEndTime()
	{
		return getStopEndTime(getContext());
	}

	/**
	 * @param context
	 * @return value of StopEndTime
	 */
	public final java.util.Date getStopEndTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.StopEndTime.toString());
	}

	/**
	 * Set value of StopEndTime
	 * @param stopendtime
	 */
	public final void setStopEndTime(java.util.Date stopendtime)
	{
		setStopEndTime(getContext(), stopendtime);
	}

	/**
	 * Set value of StopEndTime
	 * @param context
	 * @param stopendtime
	 */
	public final void setStopEndTime(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date stopendtime)
	{
		getMendixObject().setValue(context, MemberNames.StopEndTime.toString(), stopendtime);
	}

	/**
	 * @return value of NormalValue
	 */
	public final java.math.BigDecimal getNormalValue()
	{
		return getNormalValue(getContext());
	}

	/**
	 * @param context
	 * @return value of NormalValue
	 */
	public final java.math.BigDecimal getNormalValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NormalValue.toString());
	}

	/**
	 * Set value of NormalValue
	 * @param normalvalue
	 */
	public final void setNormalValue(java.math.BigDecimal normalvalue)
	{
		setNormalValue(getContext(), normalvalue);
	}

	/**
	 * Set value of NormalValue
	 * @param context
	 * @param normalvalue
	 */
	public final void setNormalValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal normalvalue)
	{
		getMendixObject().setValue(context, MemberNames.NormalValue.toString(), normalvalue);
	}

	/**
	 * @return value of CorrectionValue
	 */
	public final java.math.BigDecimal getCorrectionValue()
	{
		return getCorrectionValue(getContext());
	}

	/**
	 * @param context
	 * @return value of CorrectionValue
	 */
	public final java.math.BigDecimal getCorrectionValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.CorrectionValue.toString());
	}

	/**
	 * Set value of CorrectionValue
	 * @param correctionvalue
	 */
	public final void setCorrectionValue(java.math.BigDecimal correctionvalue)
	{
		setCorrectionValue(getContext(), correctionvalue);
	}

	/**
	 * Set value of CorrectionValue
	 * @param context
	 * @param correctionvalue
	 */
	public final void setCorrectionValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal correctionvalue)
	{
		getMendixObject().setValue(context, MemberNames.CorrectionValue.toString(), correctionvalue);
	}

	/**
	 * @return value of UpperLimitValue
	 */
	public final java.math.BigDecimal getUpperLimitValue()
	{
		return getUpperLimitValue(getContext());
	}

	/**
	 * @param context
	 * @return value of UpperLimitValue
	 */
	public final java.math.BigDecimal getUpperLimitValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.UpperLimitValue.toString());
	}

	/**
	 * Set value of UpperLimitValue
	 * @param upperlimitvalue
	 */
	public final void setUpperLimitValue(java.math.BigDecimal upperlimitvalue)
	{
		setUpperLimitValue(getContext(), upperlimitvalue);
	}

	/**
	 * Set value of UpperLimitValue
	 * @param context
	 * @param upperlimitvalue
	 */
	public final void setUpperLimitValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal upperlimitvalue)
	{
		getMendixObject().setValue(context, MemberNames.UpperLimitValue.toString(), upperlimitvalue);
	}

	/**
	 * @return value of LowerLimitValue
	 */
	public final java.math.BigDecimal getLowerLimitValue()
	{
		return getLowerLimitValue(getContext());
	}

	/**
	 * @param context
	 * @return value of LowerLimitValue
	 */
	public final java.math.BigDecimal getLowerLimitValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LowerLimitValue.toString());
	}

	/**
	 * Set value of LowerLimitValue
	 * @param lowerlimitvalue
	 */
	public final void setLowerLimitValue(java.math.BigDecimal lowerlimitvalue)
	{
		setLowerLimitValue(getContext(), lowerlimitvalue);
	}

	/**
	 * Set value of LowerLimitValue
	 * @param context
	 * @param lowerlimitvalue
	 */
	public final void setLowerLimitValue(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lowerlimitvalue)
	{
		getMendixObject().setValue(context, MemberNames.LowerLimitValue.toString(), lowerlimitvalue);
	}

	/**
	 * @return value of InstallDate
	 */
	public final java.util.Date getInstallDate()
	{
		return getInstallDate(getContext());
	}

	/**
	 * @param context
	 * @return value of InstallDate
	 */
	public final java.util.Date getInstallDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.InstallDate.toString());
	}

	/**
	 * Set value of InstallDate
	 * @param installdate
	 */
	public final void setInstallDate(java.util.Date installdate)
	{
		setInstallDate(getContext(), installdate);
	}

	/**
	 * Set value of InstallDate
	 * @param context
	 * @param installdate
	 */
	public final void setInstallDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date installdate)
	{
		getMendixObject().setValue(context, MemberNames.InstallDate.toString(), installdate);
	}

	/**
	 * @return value of DataStoreDay
	 */
	public final java.lang.Integer getDataStoreDay()
	{
		return getDataStoreDay(getContext());
	}

	/**
	 * @param context
	 * @return value of DataStoreDay
	 */
	public final java.lang.Integer getDataStoreDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DataStoreDay.toString());
	}

	/**
	 * Set value of DataStoreDay
	 * @param datastoreday
	 */
	public final void setDataStoreDay(java.lang.Integer datastoreday)
	{
		setDataStoreDay(getContext(), datastoreday);
	}

	/**
	 * Set value of DataStoreDay
	 * @param context
	 * @param datastoreday
	 */
	public final void setDataStoreDay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer datastoreday)
	{
		getMendixObject().setValue(context, MemberNames.DataStoreDay.toString(), datastoreday);
	}

	/**
	 * @return value of SensorDescription
	 */
	public final java.lang.String getSensorDescription()
	{
		return getSensorDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorDescription
	 */
	public final java.lang.String getSensorDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SensorDescription.toString());
	}

	/**
	 * Set value of SensorDescription
	 * @param sensordescription
	 */
	public final void setSensorDescription(java.lang.String sensordescription)
	{
		setSensorDescription(getContext(), sensordescription);
	}

	/**
	 * Set value of SensorDescription
	 * @param context
	 * @param sensordescription
	 */
	public final void setSensorDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sensordescription)
	{
		getMendixObject().setValue(context, MemberNames.SensorDescription.toString(), sensordescription);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Sensor_Server
	 */
	public final monitoring.proxies.Server getSensor_Server() throws com.mendix.core.CoreException
	{
		return getSensor_Server(getContext());
	}

	/**
	 * @param context
	 * @return value of Sensor_Server
	 * @throws com.mendix.core.CoreException
	 */
	public final monitoring.proxies.Server getSensor_Server(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		monitoring.proxies.Server result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sensor_Server.toString());
		if (identifier != null) {
			result = monitoring.proxies.Server.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Sensor_Server
	 * @param sensor_server
	 */
	public final void setSensor_Server(monitoring.proxies.Server sensor_server)
	{
		setSensor_Server(getContext(), sensor_server);
	}

	/**
	 * Set value of Sensor_Server
	 * @param context
	 * @param sensor_server
	 */
	public final void setSensor_Server(com.mendix.systemwideinterfaces.core.IContext context, monitoring.proxies.Server sensor_server)
	{
		if (sensor_server == null) {
			getMendixObject().setValue(context, MemberNames.Sensor_Server.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Sensor_Server.toString(), sensor_server.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SensorImage_Sensor
	 */
	public final monitoring.proxies.SensorImage getSensorImage_Sensor() throws com.mendix.core.CoreException
	{
		return getSensorImage_Sensor(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorImage_Sensor
	 * @throws com.mendix.core.CoreException
	 */
	public final monitoring.proxies.SensorImage getSensorImage_Sensor(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		monitoring.proxies.SensorImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SensorImage_Sensor.toString());
		if (identifier != null) {
			result = monitoring.proxies.SensorImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SensorImage_Sensor
	 * @param sensorimage_sensor
	 */
	public final void setSensorImage_Sensor(monitoring.proxies.SensorImage sensorimage_sensor)
	{
		setSensorImage_Sensor(getContext(), sensorimage_sensor);
	}

	/**
	 * Set value of SensorImage_Sensor
	 * @param context
	 * @param sensorimage_sensor
	 */
	public final void setSensorImage_Sensor(com.mendix.systemwideinterfaces.core.IContext context, monitoring.proxies.SensorImage sensorimage_sensor)
	{
		if (sensorimage_sensor == null) {
			getMendixObject().setValue(context, MemberNames.SensorImage_Sensor.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SensorImage_Sensor.toString(), sensorimage_sensor.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Sensor_Plant
	 */
	public final cmms_administration.proxies.Plant getSensor_Plant() throws com.mendix.core.CoreException
	{
		return getSensor_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of Sensor_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getSensor_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sensor_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Sensor_Plant
	 * @param sensor_plant
	 */
	public final void setSensor_Plant(cmms_administration.proxies.Plant sensor_plant)
	{
		setSensor_Plant(getContext(), sensor_plant);
	}

	/**
	 * Set value of Sensor_Plant
	 * @param context
	 * @param sensor_plant
	 */
	public final void setSensor_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant sensor_plant)
	{
		if (sensor_plant == null) {
			getMendixObject().setValue(context, MemberNames.Sensor_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Sensor_Plant.toString(), sensor_plant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SensorStatus_StandardCode
	 */
	public final commons.proxies.StandardCode getSensorStatus_StandardCode() throws com.mendix.core.CoreException
	{
		return getSensorStatus_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorStatus_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getSensorStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SensorStatus_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SensorStatus_StandardCode
	 * @param sensorstatus_standardcode
	 */
	public final void setSensorStatus_StandardCode(commons.proxies.StandardCode sensorstatus_standardcode)
	{
		setSensorStatus_StandardCode(getContext(), sensorstatus_standardcode);
	}

	/**
	 * Set value of SensorStatus_StandardCode
	 * @param context
	 * @param sensorstatus_standardcode
	 */
	public final void setSensorStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode sensorstatus_standardcode)
	{
		if (sensorstatus_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.SensorStatus_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SensorStatus_StandardCode.toString(), sensorstatus_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SensorType_StandardCode
	 */
	public final commons.proxies.StandardCode getSensorType_StandardCode() throws com.mendix.core.CoreException
	{
		return getSensorType_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorType_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getSensorType_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SensorType_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SensorType_StandardCode
	 * @param sensortype_standardcode
	 */
	public final void setSensorType_StandardCode(commons.proxies.StandardCode sensortype_standardcode)
	{
		setSensorType_StandardCode(getContext(), sensortype_standardcode);
	}

	/**
	 * Set value of SensorType_StandardCode
	 * @param context
	 * @param sensortype_standardcode
	 */
	public final void setSensorType_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode sensortype_standardcode)
	{
		if (sensortype_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.SensorType_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SensorType_StandardCode.toString(), sensortype_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of SensorUnit_StandardCode
	 */
	public final commons.proxies.StandardCode getSensorUnit_StandardCode() throws com.mendix.core.CoreException
	{
		return getSensorUnit_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorUnit_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getSensorUnit_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SensorUnit_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of SensorUnit_StandardCode
	 * @param sensorunit_standardcode
	 */
	public final void setSensorUnit_StandardCode(commons.proxies.StandardCode sensorunit_standardcode)
	{
		setSensorUnit_StandardCode(getContext(), sensorunit_standardcode);
	}

	/**
	 * Set value of SensorUnit_StandardCode
	 * @param context
	 * @param sensorunit_standardcode
	 */
	public final void setSensorUnit_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode sensorunit_standardcode)
	{
		if (sensorunit_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.SensorUnit_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.SensorUnit_StandardCode.toString(), sensorunit_standardcode.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final monitoring.proxies.Sensor that = (monitoring.proxies.Sensor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
