// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public enum GeocodingProvider
{
	Google(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Google" } }),
	Geocodio(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Geocodio" } }),
	LocationIQ(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "LocationIQ" } }),
	MapQuest(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "MapQuest" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private GeocodingProvider(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
