// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/13
 * 최종 수정자 : 
 * 최종 수정일 :
 * 
 * 설명 : 거래처 사진등록할 용도
 * 
 * V1.0 : 최초 작성
 */
public class BusinessPartnerPicture extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.BusinessPartnerPicture";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		BusinessPartnerPicture_BusinessPartner("Material_Management.BusinessPartnerPicture_BusinessPartner");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BusinessPartnerPicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BusinessPartnerPicture(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject businessPartnerPictureMendixObject)
	{
		super(context, businessPartnerPictureMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, businessPartnerPictureMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.BusinessPartnerPicture initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.BusinessPartnerPicture(context, mendixObject);
	}

	public static material_management.proxies.BusinessPartnerPicture load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.BusinessPartnerPicture.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.BusinessPartnerPicture> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.BusinessPartnerPicture.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BusinessPartnerPicture_BusinessPartner
	 */
	public final material_management.proxies.BusinessPartner getBusinessPartnerPicture_BusinessPartner() throws com.mendix.core.CoreException
	{
		return getBusinessPartnerPicture_BusinessPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessPartnerPicture_BusinessPartner
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.BusinessPartner getBusinessPartnerPicture_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BusinessPartnerPicture_BusinessPartner.toString());
		if (identifier != null) {
			result = material_management.proxies.BusinessPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BusinessPartnerPicture_BusinessPartner
	 * @param businesspartnerpicture_businesspartner
	 */
	public final void setBusinessPartnerPicture_BusinessPartner(material_management.proxies.BusinessPartner businesspartnerpicture_businesspartner)
	{
		setBusinessPartnerPicture_BusinessPartner(getContext(), businesspartnerpicture_businesspartner);
	}

	/**
	 * Set value of BusinessPartnerPicture_BusinessPartner
	 * @param context
	 * @param businesspartnerpicture_businesspartner
	 */
	public final void setBusinessPartnerPicture_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.BusinessPartner businesspartnerpicture_businesspartner)
	{
		if (businesspartnerpicture_businesspartner == null) {
			getMendixObject().setValue(context, MemberNames.BusinessPartnerPicture_BusinessPartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BusinessPartnerPicture_BusinessPartner.toString(), businesspartnerpicture_businesspartner.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.BusinessPartnerPicture that = (material_management.proxies.BusinessPartnerPicture) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
