// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

public class BusinessPartner implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject businessPartnerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.BusinessPartner";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PartnerCode("PartnerCode"),
		PartnerName("PartnerName"),
		PartnerNameEnglish("PartnerNameEnglish"),
		PartnerContactPerson("PartnerContactPerson"),
		PartnerBusiness("PartnerBusiness"),
		PartnerPhone("PartnerPhone"),
		PartnerEmail("PartnerEmail"),
		PartnerAddress("PartnerAddress"),
		PartnerCountry("PartnerCountry"),
		PartnerInOutFlag("PartnerInOutFlag"),
		PartnerRegularFlag("PartnerRegularFlag"),
		PartnerManufactureFlag("PartnerManufactureFlag"),
		ParnterSupplyFlag("ParnterSupplyFlag"),
		ParnterMaintenanceFlag("ParnterMaintenanceFlag"),
		PartnerSequence("PartnerSequence"),
		PartnerPath("PartnerPath"),
		IsParterActive("IsParterActive"),
		PartnerDescription("PartnerDescription"),
		AlreadyRegistered("AlreadyRegistered"),
		BusinessPartnerPicture_BusinessPartner("Material_Management.BusinessPartnerPicture_BusinessPartner"),
		BusinessPartner_Plant("Material_Management.BusinessPartner_Plant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject businessPartnerMendixObject)
	{
		if (businessPartnerMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, businessPartnerMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.businessPartnerMendixObject = businessPartnerMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.BusinessPartner initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.BusinessPartner(context, mendixObject);
	}

	public static material_management.proxies.BusinessPartner load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.BusinessPartner.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.BusinessPartner> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.BusinessPartner.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of PartnerCode
	 */
	public final java.lang.String getPartnerCode()
	{
		return getPartnerCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerCode
	 */
	public final java.lang.String getPartnerCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerCode.toString());
	}

	/**
	 * Set value of PartnerCode
	 * @param partnercode
	 */
	public final void setPartnerCode(java.lang.String partnercode)
	{
		setPartnerCode(getContext(), partnercode);
	}

	/**
	 * Set value of PartnerCode
	 * @param context
	 * @param partnercode
	 */
	public final void setPartnerCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnercode)
	{
		getMendixObject().setValue(context, MemberNames.PartnerCode.toString(), partnercode);
	}

	/**
	 * @return value of PartnerName
	 */
	public final java.lang.String getPartnerName()
	{
		return getPartnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerName
	 */
	public final java.lang.String getPartnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerName.toString());
	}

	/**
	 * Set value of PartnerName
	 * @param partnername
	 */
	public final void setPartnerName(java.lang.String partnername)
	{
		setPartnerName(getContext(), partnername);
	}

	/**
	 * Set value of PartnerName
	 * @param context
	 * @param partnername
	 */
	public final void setPartnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnername)
	{
		getMendixObject().setValue(context, MemberNames.PartnerName.toString(), partnername);
	}

	/**
	 * @return value of PartnerNameEnglish
	 */
	public final java.lang.String getPartnerNameEnglish()
	{
		return getPartnerNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerNameEnglish
	 */
	public final java.lang.String getPartnerNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerNameEnglish.toString());
	}

	/**
	 * Set value of PartnerNameEnglish
	 * @param partnernameenglish
	 */
	public final void setPartnerNameEnglish(java.lang.String partnernameenglish)
	{
		setPartnerNameEnglish(getContext(), partnernameenglish);
	}

	/**
	 * Set value of PartnerNameEnglish
	 * @param context
	 * @param partnernameenglish
	 */
	public final void setPartnerNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnernameenglish)
	{
		getMendixObject().setValue(context, MemberNames.PartnerNameEnglish.toString(), partnernameenglish);
	}

	/**
	 * @return value of PartnerContactPerson
	 */
	public final java.lang.String getPartnerContactPerson()
	{
		return getPartnerContactPerson(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerContactPerson
	 */
	public final java.lang.String getPartnerContactPerson(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerContactPerson.toString());
	}

	/**
	 * Set value of PartnerContactPerson
	 * @param partnercontactperson
	 */
	public final void setPartnerContactPerson(java.lang.String partnercontactperson)
	{
		setPartnerContactPerson(getContext(), partnercontactperson);
	}

	/**
	 * Set value of PartnerContactPerson
	 * @param context
	 * @param partnercontactperson
	 */
	public final void setPartnerContactPerson(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnercontactperson)
	{
		getMendixObject().setValue(context, MemberNames.PartnerContactPerson.toString(), partnercontactperson);
	}

	/**
	 * @return value of PartnerBusiness
	 */
	public final java.lang.String getPartnerBusiness()
	{
		return getPartnerBusiness(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerBusiness
	 */
	public final java.lang.String getPartnerBusiness(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerBusiness.toString());
	}

	/**
	 * Set value of PartnerBusiness
	 * @param partnerbusiness
	 */
	public final void setPartnerBusiness(java.lang.String partnerbusiness)
	{
		setPartnerBusiness(getContext(), partnerbusiness);
	}

	/**
	 * Set value of PartnerBusiness
	 * @param context
	 * @param partnerbusiness
	 */
	public final void setPartnerBusiness(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnerbusiness)
	{
		getMendixObject().setValue(context, MemberNames.PartnerBusiness.toString(), partnerbusiness);
	}

	/**
	 * @return value of PartnerPhone
	 */
	public final java.lang.String getPartnerPhone()
	{
		return getPartnerPhone(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerPhone
	 */
	public final java.lang.String getPartnerPhone(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerPhone.toString());
	}

	/**
	 * Set value of PartnerPhone
	 * @param partnerphone
	 */
	public final void setPartnerPhone(java.lang.String partnerphone)
	{
		setPartnerPhone(getContext(), partnerphone);
	}

	/**
	 * Set value of PartnerPhone
	 * @param context
	 * @param partnerphone
	 */
	public final void setPartnerPhone(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnerphone)
	{
		getMendixObject().setValue(context, MemberNames.PartnerPhone.toString(), partnerphone);
	}

	/**
	 * @return value of PartnerEmail
	 */
	public final java.lang.String getPartnerEmail()
	{
		return getPartnerEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerEmail
	 */
	public final java.lang.String getPartnerEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerEmail.toString());
	}

	/**
	 * Set value of PartnerEmail
	 * @param partneremail
	 */
	public final void setPartnerEmail(java.lang.String partneremail)
	{
		setPartnerEmail(getContext(), partneremail);
	}

	/**
	 * Set value of PartnerEmail
	 * @param context
	 * @param partneremail
	 */
	public final void setPartnerEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partneremail)
	{
		getMendixObject().setValue(context, MemberNames.PartnerEmail.toString(), partneremail);
	}

	/**
	 * @return value of PartnerAddress
	 */
	public final java.lang.String getPartnerAddress()
	{
		return getPartnerAddress(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerAddress
	 */
	public final java.lang.String getPartnerAddress(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerAddress.toString());
	}

	/**
	 * Set value of PartnerAddress
	 * @param partneraddress
	 */
	public final void setPartnerAddress(java.lang.String partneraddress)
	{
		setPartnerAddress(getContext(), partneraddress);
	}

	/**
	 * Set value of PartnerAddress
	 * @param context
	 * @param partneraddress
	 */
	public final void setPartnerAddress(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partneraddress)
	{
		getMendixObject().setValue(context, MemberNames.PartnerAddress.toString(), partneraddress);
	}

	/**
	 * @return value of PartnerCountry
	 */
	public final java.lang.String getPartnerCountry()
	{
		return getPartnerCountry(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerCountry
	 */
	public final java.lang.String getPartnerCountry(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerCountry.toString());
	}

	/**
	 * Set value of PartnerCountry
	 * @param partnercountry
	 */
	public final void setPartnerCountry(java.lang.String partnercountry)
	{
		setPartnerCountry(getContext(), partnercountry);
	}

	/**
	 * Set value of PartnerCountry
	 * @param context
	 * @param partnercountry
	 */
	public final void setPartnerCountry(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnercountry)
	{
		getMendixObject().setValue(context, MemberNames.PartnerCountry.toString(), partnercountry);
	}

	/**
	 * @return value of PartnerInOutFlag
	 */
	public final java.lang.String getPartnerInOutFlag()
	{
		return getPartnerInOutFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerInOutFlag
	 */
	public final java.lang.String getPartnerInOutFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerInOutFlag.toString());
	}

	/**
	 * Set value of PartnerInOutFlag
	 * @param partnerinoutflag
	 */
	public final void setPartnerInOutFlag(java.lang.String partnerinoutflag)
	{
		setPartnerInOutFlag(getContext(), partnerinoutflag);
	}

	/**
	 * Set value of PartnerInOutFlag
	 * @param context
	 * @param partnerinoutflag
	 */
	public final void setPartnerInOutFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnerinoutflag)
	{
		getMendixObject().setValue(context, MemberNames.PartnerInOutFlag.toString(), partnerinoutflag);
	}

	/**
	 * @return value of PartnerRegularFlag
	 */
	public final java.lang.Boolean getPartnerRegularFlag()
	{
		return getPartnerRegularFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerRegularFlag
	 */
	public final java.lang.Boolean getPartnerRegularFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PartnerRegularFlag.toString());
	}

	/**
	 * Set value of PartnerRegularFlag
	 * @param partnerregularflag
	 */
	public final void setPartnerRegularFlag(java.lang.Boolean partnerregularflag)
	{
		setPartnerRegularFlag(getContext(), partnerregularflag);
	}

	/**
	 * Set value of PartnerRegularFlag
	 * @param context
	 * @param partnerregularflag
	 */
	public final void setPartnerRegularFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean partnerregularflag)
	{
		getMendixObject().setValue(context, MemberNames.PartnerRegularFlag.toString(), partnerregularflag);
	}

	/**
	 * @return value of PartnerManufactureFlag
	 */
	public final java.lang.Boolean getPartnerManufactureFlag()
	{
		return getPartnerManufactureFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerManufactureFlag
	 */
	public final java.lang.Boolean getPartnerManufactureFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PartnerManufactureFlag.toString());
	}

	/**
	 * Set value of PartnerManufactureFlag
	 * @param partnermanufactureflag
	 */
	public final void setPartnerManufactureFlag(java.lang.Boolean partnermanufactureflag)
	{
		setPartnerManufactureFlag(getContext(), partnermanufactureflag);
	}

	/**
	 * Set value of PartnerManufactureFlag
	 * @param context
	 * @param partnermanufactureflag
	 */
	public final void setPartnerManufactureFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean partnermanufactureflag)
	{
		getMendixObject().setValue(context, MemberNames.PartnerManufactureFlag.toString(), partnermanufactureflag);
	}

	/**
	 * @return value of ParnterSupplyFlag
	 */
	public final java.lang.Boolean getParnterSupplyFlag()
	{
		return getParnterSupplyFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of ParnterSupplyFlag
	 */
	public final java.lang.Boolean getParnterSupplyFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ParnterSupplyFlag.toString());
	}

	/**
	 * Set value of ParnterSupplyFlag
	 * @param parntersupplyflag
	 */
	public final void setParnterSupplyFlag(java.lang.Boolean parntersupplyflag)
	{
		setParnterSupplyFlag(getContext(), parntersupplyflag);
	}

	/**
	 * Set value of ParnterSupplyFlag
	 * @param context
	 * @param parntersupplyflag
	 */
	public final void setParnterSupplyFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean parntersupplyflag)
	{
		getMendixObject().setValue(context, MemberNames.ParnterSupplyFlag.toString(), parntersupplyflag);
	}

	/**
	 * @return value of ParnterMaintenanceFlag
	 */
	public final java.lang.Boolean getParnterMaintenanceFlag()
	{
		return getParnterMaintenanceFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of ParnterMaintenanceFlag
	 */
	public final java.lang.Boolean getParnterMaintenanceFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ParnterMaintenanceFlag.toString());
	}

	/**
	 * Set value of ParnterMaintenanceFlag
	 * @param parntermaintenanceflag
	 */
	public final void setParnterMaintenanceFlag(java.lang.Boolean parntermaintenanceflag)
	{
		setParnterMaintenanceFlag(getContext(), parntermaintenanceflag);
	}

	/**
	 * Set value of ParnterMaintenanceFlag
	 * @param context
	 * @param parntermaintenanceflag
	 */
	public final void setParnterMaintenanceFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean parntermaintenanceflag)
	{
		getMendixObject().setValue(context, MemberNames.ParnterMaintenanceFlag.toString(), parntermaintenanceflag);
	}

	/**
	 * @return value of PartnerSequence
	 */
	public final java.lang.Integer getPartnerSequence()
	{
		return getPartnerSequence(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerSequence
	 */
	public final java.lang.Integer getPartnerSequence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PartnerSequence.toString());
	}

	/**
	 * Set value of PartnerSequence
	 * @param partnersequence
	 */
	public final void setPartnerSequence(java.lang.Integer partnersequence)
	{
		setPartnerSequence(getContext(), partnersequence);
	}

	/**
	 * Set value of PartnerSequence
	 * @param context
	 * @param partnersequence
	 */
	public final void setPartnerSequence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer partnersequence)
	{
		getMendixObject().setValue(context, MemberNames.PartnerSequence.toString(), partnersequence);
	}

	/**
	 * @return value of PartnerPath
	 */
	public final java.lang.String getPartnerPath()
	{
		return getPartnerPath(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerPath
	 */
	public final java.lang.String getPartnerPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerPath.toString());
	}

	/**
	 * Set value of PartnerPath
	 * @param partnerpath
	 */
	public final void setPartnerPath(java.lang.String partnerpath)
	{
		setPartnerPath(getContext(), partnerpath);
	}

	/**
	 * Set value of PartnerPath
	 * @param context
	 * @param partnerpath
	 */
	public final void setPartnerPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnerpath)
	{
		getMendixObject().setValue(context, MemberNames.PartnerPath.toString(), partnerpath);
	}

	/**
	 * @return value of IsParterActive
	 */
	public final java.lang.Boolean getIsParterActive()
	{
		return getIsParterActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsParterActive
	 */
	public final java.lang.Boolean getIsParterActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsParterActive.toString());
	}

	/**
	 * Set value of IsParterActive
	 * @param isparteractive
	 */
	public final void setIsParterActive(java.lang.Boolean isparteractive)
	{
		setIsParterActive(getContext(), isparteractive);
	}

	/**
	 * Set value of IsParterActive
	 * @param context
	 * @param isparteractive
	 */
	public final void setIsParterActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isparteractive)
	{
		getMendixObject().setValue(context, MemberNames.IsParterActive.toString(), isparteractive);
	}

	/**
	 * @return value of PartnerDescription
	 */
	public final java.lang.String getPartnerDescription()
	{
		return getPartnerDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerDescription
	 */
	public final java.lang.String getPartnerDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerDescription.toString());
	}

	/**
	 * Set value of PartnerDescription
	 * @param partnerdescription
	 */
	public final void setPartnerDescription(java.lang.String partnerdescription)
	{
		setPartnerDescription(getContext(), partnerdescription);
	}

	/**
	 * Set value of PartnerDescription
	 * @param context
	 * @param partnerdescription
	 */
	public final void setPartnerDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnerdescription)
	{
		getMendixObject().setValue(context, MemberNames.PartnerDescription.toString(), partnerdescription);
	}

	/**
	 * @return value of AlreadyRegistered
	 */
	public final java.lang.Boolean getAlreadyRegistered()
	{
		return getAlreadyRegistered(getContext());
	}

	/**
	 * @param context
	 * @return value of AlreadyRegistered
	 */
	public final java.lang.Boolean getAlreadyRegistered(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AlreadyRegistered.toString());
	}

	/**
	 * Set value of AlreadyRegistered
	 * @param alreadyregistered
	 */
	public final void setAlreadyRegistered(java.lang.Boolean alreadyregistered)
	{
		setAlreadyRegistered(getContext(), alreadyregistered);
	}

	/**
	 * Set value of AlreadyRegistered
	 * @param context
	 * @param alreadyregistered
	 */
	public final void setAlreadyRegistered(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean alreadyregistered)
	{
		getMendixObject().setValue(context, MemberNames.AlreadyRegistered.toString(), alreadyregistered);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BusinessPartnerPicture_BusinessPartner
	 */
	public final material_management.proxies.BusinessPartnerPicture getBusinessPartnerPicture_BusinessPartner() throws com.mendix.core.CoreException
	{
		return getBusinessPartnerPicture_BusinessPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessPartnerPicture_BusinessPartner
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.BusinessPartnerPicture getBusinessPartnerPicture_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.BusinessPartnerPicture result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BusinessPartnerPicture_BusinessPartner.toString());
		if (identifier != null) {
			result = material_management.proxies.BusinessPartnerPicture.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BusinessPartnerPicture_BusinessPartner
	 * @param businesspartnerpicture_businesspartner
	 */
	public final void setBusinessPartnerPicture_BusinessPartner(material_management.proxies.BusinessPartnerPicture businesspartnerpicture_businesspartner)
	{
		setBusinessPartnerPicture_BusinessPartner(getContext(), businesspartnerpicture_businesspartner);
	}

	/**
	 * Set value of BusinessPartnerPicture_BusinessPartner
	 * @param context
	 * @param businesspartnerpicture_businesspartner
	 */
	public final void setBusinessPartnerPicture_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.BusinessPartnerPicture businesspartnerpicture_businesspartner)
	{
		if (businesspartnerpicture_businesspartner == null) {
			getMendixObject().setValue(context, MemberNames.BusinessPartnerPicture_BusinessPartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BusinessPartnerPicture_BusinessPartner.toString(), businesspartnerpicture_businesspartner.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BusinessPartner_Plant
	 */
	public final cmms_administration.proxies.Plant getBusinessPartner_Plant() throws com.mendix.core.CoreException
	{
		return getBusinessPartner_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of BusinessPartner_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getBusinessPartner_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BusinessPartner_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BusinessPartner_Plant
	 * @param businesspartner_plant
	 */
	public final void setBusinessPartner_Plant(cmms_administration.proxies.Plant businesspartner_plant)
	{
		setBusinessPartner_Plant(getContext(), businesspartner_plant);
	}

	/**
	 * Set value of BusinessPartner_Plant
	 * @param context
	 * @param businesspartner_plant
	 */
	public final void setBusinessPartner_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant businesspartner_plant)
	{
		if (businesspartner_plant == null) {
			getMendixObject().setValue(context, MemberNames.BusinessPartner_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BusinessPartner_Plant.toString(), businesspartner_plant.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return businessPartnerMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.BusinessPartner that = (material_management.proxies.BusinessPartner) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
