// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/09/06
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/09/11
 * 설명 : 자재종류를 담는 엔터티
 * Version 1.1 : MaterialSequence -> MaterialOrder, IsMaterialActive -> Active으로 이름 변경
 * Version 1.0 : 생성
 */
public class MaterialType implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject materialTypeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.MaterialType";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaterialTypeCode("MaterialTypeCode"),
		MaterialTypeName("MaterialTypeName"),
		MaterialTypeNameEnglish("MaterialTypeNameEnglish"),
		MaterialTypePath("MaterialTypePath"),
		MaterialTypeOrder("MaterialTypeOrder"),
		MaterialTypeDescription("MaterialTypeDescription"),
		Active("Active"),
		IsRoot("IsRoot"),
		No("No"),
		Parent_MaterialType("Material_Management.Parent_MaterialType"),
		MaterialType_MaterialTypeHelper("Material_Management.MaterialType_MaterialTypeHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MaterialType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MaterialType(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject materialTypeMendixObject)
	{
		if (materialTypeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, materialTypeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.materialTypeMendixObject = materialTypeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.MaterialType initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.MaterialType(context, mendixObject);
	}

	public static material_management.proxies.MaterialType load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.MaterialType.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.MaterialType> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.MaterialType.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MaterialTypeCode
	 */
	public final java.lang.String getMaterialTypeCode()
	{
		return getMaterialTypeCode(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialTypeCode
	 */
	public final java.lang.String getMaterialTypeCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialTypeCode.toString());
	}

	/**
	 * Set value of MaterialTypeCode
	 * @param materialtypecode
	 */
	public final void setMaterialTypeCode(java.lang.String materialtypecode)
	{
		setMaterialTypeCode(getContext(), materialtypecode);
	}

	/**
	 * Set value of MaterialTypeCode
	 * @param context
	 * @param materialtypecode
	 */
	public final void setMaterialTypeCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialtypecode)
	{
		getMendixObject().setValue(context, MemberNames.MaterialTypeCode.toString(), materialtypecode);
	}

	/**
	 * @return value of MaterialTypeName
	 */
	public final java.lang.String getMaterialTypeName()
	{
		return getMaterialTypeName(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialTypeName
	 */
	public final java.lang.String getMaterialTypeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialTypeName.toString());
	}

	/**
	 * Set value of MaterialTypeName
	 * @param materialtypename
	 */
	public final void setMaterialTypeName(java.lang.String materialtypename)
	{
		setMaterialTypeName(getContext(), materialtypename);
	}

	/**
	 * Set value of MaterialTypeName
	 * @param context
	 * @param materialtypename
	 */
	public final void setMaterialTypeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialtypename)
	{
		getMendixObject().setValue(context, MemberNames.MaterialTypeName.toString(), materialtypename);
	}

	/**
	 * @return value of MaterialTypeNameEnglish
	 */
	public final java.lang.String getMaterialTypeNameEnglish()
	{
		return getMaterialTypeNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialTypeNameEnglish
	 */
	public final java.lang.String getMaterialTypeNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialTypeNameEnglish.toString());
	}

	/**
	 * Set value of MaterialTypeNameEnglish
	 * @param materialtypenameenglish
	 */
	public final void setMaterialTypeNameEnglish(java.lang.String materialtypenameenglish)
	{
		setMaterialTypeNameEnglish(getContext(), materialtypenameenglish);
	}

	/**
	 * Set value of MaterialTypeNameEnglish
	 * @param context
	 * @param materialtypenameenglish
	 */
	public final void setMaterialTypeNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialtypenameenglish)
	{
		getMendixObject().setValue(context, MemberNames.MaterialTypeNameEnglish.toString(), materialtypenameenglish);
	}

	/**
	 * @return value of MaterialTypePath
	 */
	public final java.lang.String getMaterialTypePath()
	{
		return getMaterialTypePath(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialTypePath
	 */
	public final java.lang.String getMaterialTypePath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialTypePath.toString());
	}

	/**
	 * Set value of MaterialTypePath
	 * @param materialtypepath
	 */
	public final void setMaterialTypePath(java.lang.String materialtypepath)
	{
		setMaterialTypePath(getContext(), materialtypepath);
	}

	/**
	 * Set value of MaterialTypePath
	 * @param context
	 * @param materialtypepath
	 */
	public final void setMaterialTypePath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialtypepath)
	{
		getMendixObject().setValue(context, MemberNames.MaterialTypePath.toString(), materialtypepath);
	}

	/**
	 * @return value of MaterialTypeOrder
	 */
	public final java.lang.Integer getMaterialTypeOrder()
	{
		return getMaterialTypeOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialTypeOrder
	 */
	public final java.lang.Integer getMaterialTypeOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaterialTypeOrder.toString());
	}

	/**
	 * Set value of MaterialTypeOrder
	 * @param materialtypeorder
	 */
	public final void setMaterialTypeOrder(java.lang.Integer materialtypeorder)
	{
		setMaterialTypeOrder(getContext(), materialtypeorder);
	}

	/**
	 * Set value of MaterialTypeOrder
	 * @param context
	 * @param materialtypeorder
	 */
	public final void setMaterialTypeOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer materialtypeorder)
	{
		getMendixObject().setValue(context, MemberNames.MaterialTypeOrder.toString(), materialtypeorder);
	}

	/**
	 * @return value of MaterialTypeDescription
	 */
	public final java.lang.String getMaterialTypeDescription()
	{
		return getMaterialTypeDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialTypeDescription
	 */
	public final java.lang.String getMaterialTypeDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialTypeDescription.toString());
	}

	/**
	 * Set value of MaterialTypeDescription
	 * @param materialtypedescription
	 */
	public final void setMaterialTypeDescription(java.lang.String materialtypedescription)
	{
		setMaterialTypeDescription(getContext(), materialtypedescription);
	}

	/**
	 * Set value of MaterialTypeDescription
	 * @param context
	 * @param materialtypedescription
	 */
	public final void setMaterialTypeDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialtypedescription)
	{
		getMendixObject().setValue(context, MemberNames.MaterialTypeDescription.toString(), materialtypedescription);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of IsRoot
	 */
	public final java.lang.Boolean getIsRoot()
	{
		return getIsRoot(getContext());
	}

	/**
	 * @param context
	 * @return value of IsRoot
	 */
	public final java.lang.Boolean getIsRoot(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsRoot.toString());
	}

	/**
	 * Set value of IsRoot
	 * @param isroot
	 */
	public final void setIsRoot(java.lang.Boolean isroot)
	{
		setIsRoot(getContext(), isroot);
	}

	/**
	 * Set value of IsRoot
	 * @param context
	 * @param isroot
	 */
	public final void setIsRoot(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isroot)
	{
		getMendixObject().setValue(context, MemberNames.IsRoot.toString(), isroot);
	}

	/**
	 * @return value of No
	 */
	public final java.lang.Long getNo()
	{
		return getNo(getContext());
	}

	/**
	 * @param context
	 * @return value of No
	 */
	public final java.lang.Long getNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.No.toString());
	}

	/**
	 * Set value of No
	 * @param no
	 */
	public final void setNo(java.lang.Long no)
	{
		setNo(getContext(), no);
	}

	/**
	 * Set value of No
	 * @param context
	 * @param no
	 */
	public final void setNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long no)
	{
		getMendixObject().setValue(context, MemberNames.No.toString(), no);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_MaterialType
	 */
	public final material_management.proxies.MaterialType getParent_MaterialType() throws com.mendix.core.CoreException
	{
		return getParent_MaterialType(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_MaterialType
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.MaterialType getParent_MaterialType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.MaterialType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_MaterialType.toString());
		if (identifier != null) {
			result = material_management.proxies.MaterialType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_MaterialType
	 * @param parent_materialtype
	 */
	public final void setParent_MaterialType(material_management.proxies.MaterialType parent_materialtype)
	{
		setParent_MaterialType(getContext(), parent_materialtype);
	}

	/**
	 * Set value of Parent_MaterialType
	 * @param context
	 * @param parent_materialtype
	 */
	public final void setParent_MaterialType(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.MaterialType parent_materialtype)
	{
		if (parent_materialtype == null) {
			getMendixObject().setValue(context, MemberNames.Parent_MaterialType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_MaterialType.toString(), parent_materialtype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaterialType_MaterialTypeHelper
	 */
	public final material_management.proxies.MaterialTypeHelper getMaterialType_MaterialTypeHelper() throws com.mendix.core.CoreException
	{
		return getMaterialType_MaterialTypeHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialType_MaterialTypeHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.MaterialTypeHelper getMaterialType_MaterialTypeHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.MaterialTypeHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaterialType_MaterialTypeHelper.toString());
		if (identifier != null) {
			result = material_management.proxies.MaterialTypeHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaterialType_MaterialTypeHelper
	 * @param materialtype_materialtypehelper
	 */
	public final void setMaterialType_MaterialTypeHelper(material_management.proxies.MaterialTypeHelper materialtype_materialtypehelper)
	{
		setMaterialType_MaterialTypeHelper(getContext(), materialtype_materialtypehelper);
	}

	/**
	 * Set value of MaterialType_MaterialTypeHelper
	 * @param context
	 * @param materialtype_materialtypehelper
	 */
	public final void setMaterialType_MaterialTypeHelper(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.MaterialTypeHelper materialtype_materialtypehelper)
	{
		if (materialtype_materialtypehelper == null) {
			getMendixObject().setValue(context, MemberNames.MaterialType_MaterialTypeHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaterialType_MaterialTypeHelper.toString(), materialtype_materialtypehelper.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return materialTypeMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.MaterialType that = (material_management.proxies.MaterialType) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
