// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/09/06
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/06
 * 설명 : 자재 정보를 담는 엔터티
 * Version 1.2 : MaterialCode Association -> StandardCode Association으로 변경
 * Version 1.1 : RMK -> Description, MaterialSequence ->MAterialOrder, IsMaterialActive ->Active로 컬럼 이름 변경
 * Version 1.0 : 생성
 */
public class Material implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject materialMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.Material";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaterialCode("MaterialCode"),
		MaterialName("MaterialName"),
		MaterialNameEnglish("MaterialNameEnglish"),
		MaterialSpecification("MaterialSpecification"),
		MaterialImportedFlag("MaterialImportedFlag"),
		MaterialCoreFlag("MaterialCoreFlag"),
		MaterialLeadTime("MaterialLeadTime"),
		MaterialAverageUseTime("MaterialAverageUseTime"),
		CurrentStock("CurrentStock"),
		RemainingStock("RemainingStock"),
		MaterialPrice("MaterialPrice"),
		MaterialWorkPlace("MaterialWorkPlace"),
		MaterialUsage("MaterialUsage"),
		MaterialInspectionFlag("MaterialInspectionFlag"),
		MagerialAlarmFlag("MagerialAlarmFlag"),
		MaterialCycleFlag("MaterialCycleFlag"),
		MaterialPreCheckFlag("MaterialPreCheckFlag"),
		MaterialAutoOrderFlag("MaterialAutoOrderFlag"),
		MaterialDescription("MaterialDescription"),
		Active("Active"),
		MinimumStock("MinimumStock"),
		MaximumStock("MaximumStock"),
		No("No"),
		MaterialPartNo("MaterialPartNo"),
		IsAllocated_Warehouse("IsAllocated_Warehouse"),
		IsFirstRegist("IsFirstRegist"),
		Material_MaterialImage("Material_Management.Material_MaterialImage"),
		Material_MaterialType("Material_Management.Material_MaterialType"),
		Supplyment_BusinessPartner("Material_Management.Supplyment_BusinessPartner"),
		Manufacture_BusinessPartner("Material_Management.Manufacture_BusinessPartner"),
		Stock_StandardCode("Material_Management.Stock_StandardCode"),
		Grade_StandardCode("Material_Management.Grade_StandardCode"),
		Country_StandardCode("Material_Management.Country_StandardCode"),
		Unit_StandardCode("Material_Management.Unit_StandardCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Material(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Material(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject materialMendixObject)
	{
		if (materialMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, materialMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.materialMendixObject = materialMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.Material initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.Material(context, mendixObject);
	}

	public static material_management.proxies.Material load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.Material.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.Material> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.Material.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode()
	{
		return getMaterialCode(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialCode.toString());
	}

	/**
	 * Set value of MaterialCode
	 * @param materialcode
	 */
	public final void setMaterialCode(java.lang.String materialcode)
	{
		setMaterialCode(getContext(), materialcode);
	}

	/**
	 * Set value of MaterialCode
	 * @param context
	 * @param materialcode
	 */
	public final void setMaterialCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialcode)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCode.toString(), materialcode);
	}

	/**
	 * @return value of MaterialName
	 */
	public final java.lang.String getMaterialName()
	{
		return getMaterialName(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialName
	 */
	public final java.lang.String getMaterialName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialName.toString());
	}

	/**
	 * Set value of MaterialName
	 * @param materialname
	 */
	public final void setMaterialName(java.lang.String materialname)
	{
		setMaterialName(getContext(), materialname);
	}

	/**
	 * Set value of MaterialName
	 * @param context
	 * @param materialname
	 */
	public final void setMaterialName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialname)
	{
		getMendixObject().setValue(context, MemberNames.MaterialName.toString(), materialname);
	}

	/**
	 * @return value of MaterialNameEnglish
	 */
	public final java.lang.String getMaterialNameEnglish()
	{
		return getMaterialNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialNameEnglish
	 */
	public final java.lang.String getMaterialNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialNameEnglish.toString());
	}

	/**
	 * Set value of MaterialNameEnglish
	 * @param materialnameenglish
	 */
	public final void setMaterialNameEnglish(java.lang.String materialnameenglish)
	{
		setMaterialNameEnglish(getContext(), materialnameenglish);
	}

	/**
	 * Set value of MaterialNameEnglish
	 * @param context
	 * @param materialnameenglish
	 */
	public final void setMaterialNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialnameenglish)
	{
		getMendixObject().setValue(context, MemberNames.MaterialNameEnglish.toString(), materialnameenglish);
	}

	/**
	 * @return value of MaterialSpecification
	 */
	public final java.lang.String getMaterialSpecification()
	{
		return getMaterialSpecification(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialSpecification
	 */
	public final java.lang.String getMaterialSpecification(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialSpecification.toString());
	}

	/**
	 * Set value of MaterialSpecification
	 * @param materialspecification
	 */
	public final void setMaterialSpecification(java.lang.String materialspecification)
	{
		setMaterialSpecification(getContext(), materialspecification);
	}

	/**
	 * Set value of MaterialSpecification
	 * @param context
	 * @param materialspecification
	 */
	public final void setMaterialSpecification(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialspecification)
	{
		getMendixObject().setValue(context, MemberNames.MaterialSpecification.toString(), materialspecification);
	}

	/**
	 * @return value of MaterialImportedFlag
	 */
	public final java.lang.Boolean getMaterialImportedFlag()
	{
		return getMaterialImportedFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialImportedFlag
	 */
	public final java.lang.Boolean getMaterialImportedFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MaterialImportedFlag.toString());
	}

	/**
	 * Set value of MaterialImportedFlag
	 * @param materialimportedflag
	 */
	public final void setMaterialImportedFlag(java.lang.Boolean materialimportedflag)
	{
		setMaterialImportedFlag(getContext(), materialimportedflag);
	}

	/**
	 * Set value of MaterialImportedFlag
	 * @param context
	 * @param materialimportedflag
	 */
	public final void setMaterialImportedFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean materialimportedflag)
	{
		getMendixObject().setValue(context, MemberNames.MaterialImportedFlag.toString(), materialimportedflag);
	}

	/**
	 * @return value of MaterialCoreFlag
	 */
	public final java.lang.Boolean getMaterialCoreFlag()
	{
		return getMaterialCoreFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCoreFlag
	 */
	public final java.lang.Boolean getMaterialCoreFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MaterialCoreFlag.toString());
	}

	/**
	 * Set value of MaterialCoreFlag
	 * @param materialcoreflag
	 */
	public final void setMaterialCoreFlag(java.lang.Boolean materialcoreflag)
	{
		setMaterialCoreFlag(getContext(), materialcoreflag);
	}

	/**
	 * Set value of MaterialCoreFlag
	 * @param context
	 * @param materialcoreflag
	 */
	public final void setMaterialCoreFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean materialcoreflag)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCoreFlag.toString(), materialcoreflag);
	}

	/**
	 * @return value of MaterialLeadTime
	 */
	public final java.lang.Integer getMaterialLeadTime()
	{
		return getMaterialLeadTime(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialLeadTime
	 */
	public final java.lang.Integer getMaterialLeadTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaterialLeadTime.toString());
	}

	/**
	 * Set value of MaterialLeadTime
	 * @param materialleadtime
	 */
	public final void setMaterialLeadTime(java.lang.Integer materialleadtime)
	{
		setMaterialLeadTime(getContext(), materialleadtime);
	}

	/**
	 * Set value of MaterialLeadTime
	 * @param context
	 * @param materialleadtime
	 */
	public final void setMaterialLeadTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer materialleadtime)
	{
		getMendixObject().setValue(context, MemberNames.MaterialLeadTime.toString(), materialleadtime);
	}

	/**
	 * @return value of MaterialAverageUseTime
	 */
	public final java.lang.Integer getMaterialAverageUseTime()
	{
		return getMaterialAverageUseTime(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialAverageUseTime
	 */
	public final java.lang.Integer getMaterialAverageUseTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaterialAverageUseTime.toString());
	}

	/**
	 * Set value of MaterialAverageUseTime
	 * @param materialaverageusetime
	 */
	public final void setMaterialAverageUseTime(java.lang.Integer materialaverageusetime)
	{
		setMaterialAverageUseTime(getContext(), materialaverageusetime);
	}

	/**
	 * Set value of MaterialAverageUseTime
	 * @param context
	 * @param materialaverageusetime
	 */
	public final void setMaterialAverageUseTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer materialaverageusetime)
	{
		getMendixObject().setValue(context, MemberNames.MaterialAverageUseTime.toString(), materialaverageusetime);
	}

	/**
	 * @return value of CurrentStock
	 */
	public final java.math.BigDecimal getCurrentStock()
	{
		return getCurrentStock(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentStock
	 */
	public final java.math.BigDecimal getCurrentStock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.CurrentStock.toString());
	}

	/**
	 * Set value of CurrentStock
	 * @param currentstock
	 */
	public final void setCurrentStock(java.math.BigDecimal currentstock)
	{
		setCurrentStock(getContext(), currentstock);
	}

	/**
	 * Set value of CurrentStock
	 * @param context
	 * @param currentstock
	 */
	public final void setCurrentStock(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal currentstock)
	{
		getMendixObject().setValue(context, MemberNames.CurrentStock.toString(), currentstock);
	}

	/**
	 * @return value of RemainingStock
	 */
	public final java.math.BigDecimal getRemainingStock()
	{
		return getRemainingStock(getContext());
	}

	/**
	 * @param context
	 * @return value of RemainingStock
	 */
	public final java.math.BigDecimal getRemainingStock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RemainingStock.toString());
	}

	/**
	 * Set value of RemainingStock
	 * @param remainingstock
	 */
	public final void setRemainingStock(java.math.BigDecimal remainingstock)
	{
		setRemainingStock(getContext(), remainingstock);
	}

	/**
	 * Set value of RemainingStock
	 * @param context
	 * @param remainingstock
	 */
	public final void setRemainingStock(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal remainingstock)
	{
		getMendixObject().setValue(context, MemberNames.RemainingStock.toString(), remainingstock);
	}

	/**
	 * @return value of MaterialPrice
	 */
	public final java.math.BigDecimal getMaterialPrice()
	{
		return getMaterialPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialPrice
	 */
	public final java.math.BigDecimal getMaterialPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaterialPrice.toString());
	}

	/**
	 * Set value of MaterialPrice
	 * @param materialprice
	 */
	public final void setMaterialPrice(java.math.BigDecimal materialprice)
	{
		setMaterialPrice(getContext(), materialprice);
	}

	/**
	 * Set value of MaterialPrice
	 * @param context
	 * @param materialprice
	 */
	public final void setMaterialPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal materialprice)
	{
		getMendixObject().setValue(context, MemberNames.MaterialPrice.toString(), materialprice);
	}

	/**
	 * @return value of MaterialWorkPlace
	 */
	public final java.lang.String getMaterialWorkPlace()
	{
		return getMaterialWorkPlace(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialWorkPlace
	 */
	public final java.lang.String getMaterialWorkPlace(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialWorkPlace.toString());
	}

	/**
	 * Set value of MaterialWorkPlace
	 * @param materialworkplace
	 */
	public final void setMaterialWorkPlace(java.lang.String materialworkplace)
	{
		setMaterialWorkPlace(getContext(), materialworkplace);
	}

	/**
	 * Set value of MaterialWorkPlace
	 * @param context
	 * @param materialworkplace
	 */
	public final void setMaterialWorkPlace(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialworkplace)
	{
		getMendixObject().setValue(context, MemberNames.MaterialWorkPlace.toString(), materialworkplace);
	}

	/**
	 * @return value of MaterialUsage
	 */
	public final java.lang.String getMaterialUsage()
	{
		return getMaterialUsage(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialUsage
	 */
	public final java.lang.String getMaterialUsage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialUsage.toString());
	}

	/**
	 * Set value of MaterialUsage
	 * @param materialusage
	 */
	public final void setMaterialUsage(java.lang.String materialusage)
	{
		setMaterialUsage(getContext(), materialusage);
	}

	/**
	 * Set value of MaterialUsage
	 * @param context
	 * @param materialusage
	 */
	public final void setMaterialUsage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialusage)
	{
		getMendixObject().setValue(context, MemberNames.MaterialUsage.toString(), materialusage);
	}

	/**
	 * @return value of MaterialInspectionFlag
	 */
	public final java.lang.String getMaterialInspectionFlag()
	{
		return getMaterialInspectionFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialInspectionFlag
	 */
	public final java.lang.String getMaterialInspectionFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialInspectionFlag.toString());
	}

	/**
	 * Set value of MaterialInspectionFlag
	 * @param materialinspectionflag
	 */
	public final void setMaterialInspectionFlag(java.lang.String materialinspectionflag)
	{
		setMaterialInspectionFlag(getContext(), materialinspectionflag);
	}

	/**
	 * Set value of MaterialInspectionFlag
	 * @param context
	 * @param materialinspectionflag
	 */
	public final void setMaterialInspectionFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialinspectionflag)
	{
		getMendixObject().setValue(context, MemberNames.MaterialInspectionFlag.toString(), materialinspectionflag);
	}

	/**
	 * @return value of MagerialAlarmFlag
	 */
	public final java.lang.String getMagerialAlarmFlag()
	{
		return getMagerialAlarmFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of MagerialAlarmFlag
	 */
	public final java.lang.String getMagerialAlarmFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MagerialAlarmFlag.toString());
	}

	/**
	 * Set value of MagerialAlarmFlag
	 * @param magerialalarmflag
	 */
	public final void setMagerialAlarmFlag(java.lang.String magerialalarmflag)
	{
		setMagerialAlarmFlag(getContext(), magerialalarmflag);
	}

	/**
	 * Set value of MagerialAlarmFlag
	 * @param context
	 * @param magerialalarmflag
	 */
	public final void setMagerialAlarmFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String magerialalarmflag)
	{
		getMendixObject().setValue(context, MemberNames.MagerialAlarmFlag.toString(), magerialalarmflag);
	}

	/**
	 * @return value of MaterialCycleFlag
	 */
	public final java.lang.String getMaterialCycleFlag()
	{
		return getMaterialCycleFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCycleFlag
	 */
	public final java.lang.String getMaterialCycleFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialCycleFlag.toString());
	}

	/**
	 * Set value of MaterialCycleFlag
	 * @param materialcycleflag
	 */
	public final void setMaterialCycleFlag(java.lang.String materialcycleflag)
	{
		setMaterialCycleFlag(getContext(), materialcycleflag);
	}

	/**
	 * Set value of MaterialCycleFlag
	 * @param context
	 * @param materialcycleflag
	 */
	public final void setMaterialCycleFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialcycleflag)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCycleFlag.toString(), materialcycleflag);
	}

	/**
	 * @return value of MaterialPreCheckFlag
	 */
	public final java.lang.String getMaterialPreCheckFlag()
	{
		return getMaterialPreCheckFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialPreCheckFlag
	 */
	public final java.lang.String getMaterialPreCheckFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialPreCheckFlag.toString());
	}

	/**
	 * Set value of MaterialPreCheckFlag
	 * @param materialprecheckflag
	 */
	public final void setMaterialPreCheckFlag(java.lang.String materialprecheckflag)
	{
		setMaterialPreCheckFlag(getContext(), materialprecheckflag);
	}

	/**
	 * Set value of MaterialPreCheckFlag
	 * @param context
	 * @param materialprecheckflag
	 */
	public final void setMaterialPreCheckFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialprecheckflag)
	{
		getMendixObject().setValue(context, MemberNames.MaterialPreCheckFlag.toString(), materialprecheckflag);
	}

	/**
	 * @return value of MaterialAutoOrderFlag
	 */
	public final java.lang.String getMaterialAutoOrderFlag()
	{
		return getMaterialAutoOrderFlag(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialAutoOrderFlag
	 */
	public final java.lang.String getMaterialAutoOrderFlag(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialAutoOrderFlag.toString());
	}

	/**
	 * Set value of MaterialAutoOrderFlag
	 * @param materialautoorderflag
	 */
	public final void setMaterialAutoOrderFlag(java.lang.String materialautoorderflag)
	{
		setMaterialAutoOrderFlag(getContext(), materialautoorderflag);
	}

	/**
	 * Set value of MaterialAutoOrderFlag
	 * @param context
	 * @param materialautoorderflag
	 */
	public final void setMaterialAutoOrderFlag(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialautoorderflag)
	{
		getMendixObject().setValue(context, MemberNames.MaterialAutoOrderFlag.toString(), materialautoorderflag);
	}

	/**
	 * @return value of MaterialDescription
	 */
	public final java.lang.String getMaterialDescription()
	{
		return getMaterialDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialDescription
	 */
	public final java.lang.String getMaterialDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialDescription.toString());
	}

	/**
	 * Set value of MaterialDescription
	 * @param materialdescription
	 */
	public final void setMaterialDescription(java.lang.String materialdescription)
	{
		setMaterialDescription(getContext(), materialdescription);
	}

	/**
	 * Set value of MaterialDescription
	 * @param context
	 * @param materialdescription
	 */
	public final void setMaterialDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialdescription)
	{
		getMendixObject().setValue(context, MemberNames.MaterialDescription.toString(), materialdescription);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of MinimumStock
	 */
	public final java.lang.Integer getMinimumStock()
	{
		return getMinimumStock(getContext());
	}

	/**
	 * @param context
	 * @return value of MinimumStock
	 */
	public final java.lang.Integer getMinimumStock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MinimumStock.toString());
	}

	/**
	 * Set value of MinimumStock
	 * @param minimumstock
	 */
	public final void setMinimumStock(java.lang.Integer minimumstock)
	{
		setMinimumStock(getContext(), minimumstock);
	}

	/**
	 * Set value of MinimumStock
	 * @param context
	 * @param minimumstock
	 */
	public final void setMinimumStock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer minimumstock)
	{
		getMendixObject().setValue(context, MemberNames.MinimumStock.toString(), minimumstock);
	}

	/**
	 * @return value of MaximumStock
	 */
	public final java.lang.Integer getMaximumStock()
	{
		return getMaximumStock(getContext());
	}

	/**
	 * @param context
	 * @return value of MaximumStock
	 */
	public final java.lang.Integer getMaximumStock(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MaximumStock.toString());
	}

	/**
	 * Set value of MaximumStock
	 * @param maximumstock
	 */
	public final void setMaximumStock(java.lang.Integer maximumstock)
	{
		setMaximumStock(getContext(), maximumstock);
	}

	/**
	 * Set value of MaximumStock
	 * @param context
	 * @param maximumstock
	 */
	public final void setMaximumStock(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer maximumstock)
	{
		getMendixObject().setValue(context, MemberNames.MaximumStock.toString(), maximumstock);
	}

	/**
	 * @return value of No
	 */
	public final java.lang.Long getNo()
	{
		return getNo(getContext());
	}

	/**
	 * @param context
	 * @return value of No
	 */
	public final java.lang.Long getNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.No.toString());
	}

	/**
	 * Set value of No
	 * @param no
	 */
	public final void setNo(java.lang.Long no)
	{
		setNo(getContext(), no);
	}

	/**
	 * Set value of No
	 * @param context
	 * @param no
	 */
	public final void setNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long no)
	{
		getMendixObject().setValue(context, MemberNames.No.toString(), no);
	}

	/**
	 * @return value of MaterialPartNo
	 */
	public final java.lang.String getMaterialPartNo()
	{
		return getMaterialPartNo(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialPartNo
	 */
	public final java.lang.String getMaterialPartNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialPartNo.toString());
	}

	/**
	 * Set value of MaterialPartNo
	 * @param materialpartno
	 */
	public final void setMaterialPartNo(java.lang.String materialpartno)
	{
		setMaterialPartNo(getContext(), materialpartno);
	}

	/**
	 * Set value of MaterialPartNo
	 * @param context
	 * @param materialpartno
	 */
	public final void setMaterialPartNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialpartno)
	{
		getMendixObject().setValue(context, MemberNames.MaterialPartNo.toString(), materialpartno);
	}

	/**
	 * @return value of IsAllocated_Warehouse
	 */
	public final java.lang.Boolean getIsAllocated_Warehouse()
	{
		return getIsAllocated_Warehouse(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAllocated_Warehouse
	 */
	public final java.lang.Boolean getIsAllocated_Warehouse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAllocated_Warehouse.toString());
	}

	/**
	 * Set value of IsAllocated_Warehouse
	 * @param isallocated_warehouse
	 */
	public final void setIsAllocated_Warehouse(java.lang.Boolean isallocated_warehouse)
	{
		setIsAllocated_Warehouse(getContext(), isallocated_warehouse);
	}

	/**
	 * Set value of IsAllocated_Warehouse
	 * @param context
	 * @param isallocated_warehouse
	 */
	public final void setIsAllocated_Warehouse(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isallocated_warehouse)
	{
		getMendixObject().setValue(context, MemberNames.IsAllocated_Warehouse.toString(), isallocated_warehouse);
	}

	/**
	 * @return value of IsFirstRegist
	 */
	public final java.lang.Boolean getIsFirstRegist()
	{
		return getIsFirstRegist(getContext());
	}

	/**
	 * @param context
	 * @return value of IsFirstRegist
	 */
	public final java.lang.Boolean getIsFirstRegist(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsFirstRegist.toString());
	}

	/**
	 * Set value of IsFirstRegist
	 * @param isfirstregist
	 */
	public final void setIsFirstRegist(java.lang.Boolean isfirstregist)
	{
		setIsFirstRegist(getContext(), isfirstregist);
	}

	/**
	 * Set value of IsFirstRegist
	 * @param context
	 * @param isfirstregist
	 */
	public final void setIsFirstRegist(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isfirstregist)
	{
		getMendixObject().setValue(context, MemberNames.IsFirstRegist.toString(), isfirstregist);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Material_MaterialImage
	 */
	public final material_management.proxies.MaterialImage getMaterial_MaterialImage() throws com.mendix.core.CoreException
	{
		return getMaterial_MaterialImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Material_MaterialImage
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.MaterialImage getMaterial_MaterialImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.MaterialImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Material_MaterialImage.toString());
		if (identifier != null) {
			result = material_management.proxies.MaterialImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Material_MaterialImage
	 * @param material_materialimage
	 */
	public final void setMaterial_MaterialImage(material_management.proxies.MaterialImage material_materialimage)
	{
		setMaterial_MaterialImage(getContext(), material_materialimage);
	}

	/**
	 * Set value of Material_MaterialImage
	 * @param context
	 * @param material_materialimage
	 */
	public final void setMaterial_MaterialImage(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.MaterialImage material_materialimage)
	{
		if (material_materialimage == null) {
			getMendixObject().setValue(context, MemberNames.Material_MaterialImage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Material_MaterialImage.toString(), material_materialimage.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Material_MaterialType
	 */
	public final material_management.proxies.MaterialType getMaterial_MaterialType() throws com.mendix.core.CoreException
	{
		return getMaterial_MaterialType(getContext());
	}

	/**
	 * @param context
	 * @return value of Material_MaterialType
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.MaterialType getMaterial_MaterialType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.MaterialType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Material_MaterialType.toString());
		if (identifier != null) {
			result = material_management.proxies.MaterialType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Material_MaterialType
	 * @param material_materialtype
	 */
	public final void setMaterial_MaterialType(material_management.proxies.MaterialType material_materialtype)
	{
		setMaterial_MaterialType(getContext(), material_materialtype);
	}

	/**
	 * Set value of Material_MaterialType
	 * @param context
	 * @param material_materialtype
	 */
	public final void setMaterial_MaterialType(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.MaterialType material_materialtype)
	{
		if (material_materialtype == null) {
			getMendixObject().setValue(context, MemberNames.Material_MaterialType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Material_MaterialType.toString(), material_materialtype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Supplyment_BusinessPartner
	 */
	public final material_management.proxies.BusinessPartner getSupplyment_BusinessPartner() throws com.mendix.core.CoreException
	{
		return getSupplyment_BusinessPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of Supplyment_BusinessPartner
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.BusinessPartner getSupplyment_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Supplyment_BusinessPartner.toString());
		if (identifier != null) {
			result = material_management.proxies.BusinessPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Supplyment_BusinessPartner
	 * @param supplyment_businesspartner
	 */
	public final void setSupplyment_BusinessPartner(material_management.proxies.BusinessPartner supplyment_businesspartner)
	{
		setSupplyment_BusinessPartner(getContext(), supplyment_businesspartner);
	}

	/**
	 * Set value of Supplyment_BusinessPartner
	 * @param context
	 * @param supplyment_businesspartner
	 */
	public final void setSupplyment_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.BusinessPartner supplyment_businesspartner)
	{
		if (supplyment_businesspartner == null) {
			getMendixObject().setValue(context, MemberNames.Supplyment_BusinessPartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Supplyment_BusinessPartner.toString(), supplyment_businesspartner.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Manufacture_BusinessPartner
	 */
	public final material_management.proxies.BusinessPartner getManufacture_BusinessPartner() throws com.mendix.core.CoreException
	{
		return getManufacture_BusinessPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of Manufacture_BusinessPartner
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.BusinessPartner getManufacture_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Manufacture_BusinessPartner.toString());
		if (identifier != null) {
			result = material_management.proxies.BusinessPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Manufacture_BusinessPartner
	 * @param manufacture_businesspartner
	 */
	public final void setManufacture_BusinessPartner(material_management.proxies.BusinessPartner manufacture_businesspartner)
	{
		setManufacture_BusinessPartner(getContext(), manufacture_businesspartner);
	}

	/**
	 * Set value of Manufacture_BusinessPartner
	 * @param context
	 * @param manufacture_businesspartner
	 */
	public final void setManufacture_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.BusinessPartner manufacture_businesspartner)
	{
		if (manufacture_businesspartner == null) {
			getMendixObject().setValue(context, MemberNames.Manufacture_BusinessPartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Manufacture_BusinessPartner.toString(), manufacture_businesspartner.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Stock_StandardCode
	 */
	public final commons.proxies.StandardCode getStock_StandardCode() throws com.mendix.core.CoreException
	{
		return getStock_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Stock_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getStock_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Stock_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Stock_StandardCode
	 * @param stock_standardcode
	 */
	public final void setStock_StandardCode(commons.proxies.StandardCode stock_standardcode)
	{
		setStock_StandardCode(getContext(), stock_standardcode);
	}

	/**
	 * Set value of Stock_StandardCode
	 * @param context
	 * @param stock_standardcode
	 */
	public final void setStock_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode stock_standardcode)
	{
		if (stock_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Stock_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Stock_StandardCode.toString(), stock_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Grade_StandardCode
	 */
	public final commons.proxies.StandardCode getGrade_StandardCode() throws com.mendix.core.CoreException
	{
		return getGrade_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Grade_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getGrade_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Grade_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Grade_StandardCode
	 * @param grade_standardcode
	 */
	public final void setGrade_StandardCode(commons.proxies.StandardCode grade_standardcode)
	{
		setGrade_StandardCode(getContext(), grade_standardcode);
	}

	/**
	 * Set value of Grade_StandardCode
	 * @param context
	 * @param grade_standardcode
	 */
	public final void setGrade_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode grade_standardcode)
	{
		if (grade_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Grade_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Grade_StandardCode.toString(), grade_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Country_StandardCode
	 */
	public final commons.proxies.StandardCode getCountry_StandardCode() throws com.mendix.core.CoreException
	{
		return getCountry_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Country_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getCountry_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Country_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Country_StandardCode
	 * @param country_standardcode
	 */
	public final void setCountry_StandardCode(commons.proxies.StandardCode country_standardcode)
	{
		setCountry_StandardCode(getContext(), country_standardcode);
	}

	/**
	 * Set value of Country_StandardCode
	 * @param context
	 * @param country_standardcode
	 */
	public final void setCountry_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode country_standardcode)
	{
		if (country_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Country_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Country_StandardCode.toString(), country_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Unit_StandardCode
	 */
	public final commons.proxies.StandardCode getUnit_StandardCode() throws com.mendix.core.CoreException
	{
		return getUnit_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Unit_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getUnit_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Unit_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Unit_StandardCode
	 * @param unit_standardcode
	 */
	public final void setUnit_StandardCode(commons.proxies.StandardCode unit_standardcode)
	{
		setUnit_StandardCode(getContext(), unit_standardcode);
	}

	/**
	 * Set value of Unit_StandardCode
	 * @param context
	 * @param unit_standardcode
	 */
	public final void setUnit_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode unit_standardcode)
	{
		if (unit_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Unit_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Unit_StandardCode.toString(), unit_standardcode.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return materialMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.Material that = (material_management.proxies.Material) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
