// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

public class MaterialMasterLog implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject materialMasterLogMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.MaterialMasterLog";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaterialCode("MaterialCode"),
		REG_OwnerName("REG_OwnerName"),
		REG_Date("REG_Date"),
		REV_OwnerName("REV_OwnerName"),
		REV_Date("REV_Date"),
		REV_Contents("REV_Contents"),
		MaterialMasterLog_Material("Material_Management.MaterialMasterLog_Material");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MaterialMasterLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MaterialMasterLog(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject materialMasterLogMendixObject)
	{
		if (materialMasterLogMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, materialMasterLogMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.materialMasterLogMendixObject = materialMasterLogMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.MaterialMasterLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.MaterialMasterLog(context, mendixObject);
	}

	public static material_management.proxies.MaterialMasterLog load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.MaterialMasterLog.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.MaterialMasterLog> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.MaterialMasterLog.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode()
	{
		return getMaterialCode(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialCode.toString());
	}

	/**
	 * Set value of MaterialCode
	 * @param materialcode
	 */
	public final void setMaterialCode(java.lang.String materialcode)
	{
		setMaterialCode(getContext(), materialcode);
	}

	/**
	 * Set value of MaterialCode
	 * @param context
	 * @param materialcode
	 */
	public final void setMaterialCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialcode)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCode.toString(), materialcode);
	}

	/**
	 * @return value of REG_OwnerName
	 */
	public final java.lang.String getREG_OwnerName()
	{
		return getREG_OwnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of REG_OwnerName
	 */
	public final java.lang.String getREG_OwnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.REG_OwnerName.toString());
	}

	/**
	 * Set value of REG_OwnerName
	 * @param reg_ownername
	 */
	public final void setREG_OwnerName(java.lang.String reg_ownername)
	{
		setREG_OwnerName(getContext(), reg_ownername);
	}

	/**
	 * Set value of REG_OwnerName
	 * @param context
	 * @param reg_ownername
	 */
	public final void setREG_OwnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String reg_ownername)
	{
		getMendixObject().setValue(context, MemberNames.REG_OwnerName.toString(), reg_ownername);
	}

	/**
	 * @return value of REG_Date
	 */
	public final java.util.Date getREG_Date()
	{
		return getREG_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of REG_Date
	 */
	public final java.util.Date getREG_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.REG_Date.toString());
	}

	/**
	 * Set value of REG_Date
	 * @param reg_date
	 */
	public final void setREG_Date(java.util.Date reg_date)
	{
		setREG_Date(getContext(), reg_date);
	}

	/**
	 * Set value of REG_Date
	 * @param context
	 * @param reg_date
	 */
	public final void setREG_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date reg_date)
	{
		getMendixObject().setValue(context, MemberNames.REG_Date.toString(), reg_date);
	}

	/**
	 * @return value of REV_OwnerName
	 */
	public final java.lang.String getREV_OwnerName()
	{
		return getREV_OwnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of REV_OwnerName
	 */
	public final java.lang.String getREV_OwnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.REV_OwnerName.toString());
	}

	/**
	 * Set value of REV_OwnerName
	 * @param rev_ownername
	 */
	public final void setREV_OwnerName(java.lang.String rev_ownername)
	{
		setREV_OwnerName(getContext(), rev_ownername);
	}

	/**
	 * Set value of REV_OwnerName
	 * @param context
	 * @param rev_ownername
	 */
	public final void setREV_OwnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rev_ownername)
	{
		getMendixObject().setValue(context, MemberNames.REV_OwnerName.toString(), rev_ownername);
	}

	/**
	 * @return value of REV_Date
	 */
	public final java.util.Date getREV_Date()
	{
		return getREV_Date(getContext());
	}

	/**
	 * @param context
	 * @return value of REV_Date
	 */
	public final java.util.Date getREV_Date(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.REV_Date.toString());
	}

	/**
	 * Set value of REV_Date
	 * @param rev_date
	 */
	public final void setREV_Date(java.util.Date rev_date)
	{
		setREV_Date(getContext(), rev_date);
	}

	/**
	 * Set value of REV_Date
	 * @param context
	 * @param rev_date
	 */
	public final void setREV_Date(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date rev_date)
	{
		getMendixObject().setValue(context, MemberNames.REV_Date.toString(), rev_date);
	}

	/**
	 * @return value of REV_Contents
	 */
	public final java.lang.String getREV_Contents()
	{
		return getREV_Contents(getContext());
	}

	/**
	 * @param context
	 * @return value of REV_Contents
	 */
	public final java.lang.String getREV_Contents(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.REV_Contents.toString());
	}

	/**
	 * Set value of REV_Contents
	 * @param rev_contents
	 */
	public final void setREV_Contents(java.lang.String rev_contents)
	{
		setREV_Contents(getContext(), rev_contents);
	}

	/**
	 * Set value of REV_Contents
	 * @param context
	 * @param rev_contents
	 */
	public final void setREV_Contents(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String rev_contents)
	{
		getMendixObject().setValue(context, MemberNames.REV_Contents.toString(), rev_contents);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaterialMasterLog_Material
	 */
	public final material_management.proxies.Material getMaterialMasterLog_Material() throws com.mendix.core.CoreException
	{
		return getMaterialMasterLog_Material(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialMasterLog_Material
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.Material getMaterialMasterLog_Material(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.Material result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaterialMasterLog_Material.toString());
		if (identifier != null) {
			result = material_management.proxies.Material.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaterialMasterLog_Material
	 * @param materialmasterlog_material
	 */
	public final void setMaterialMasterLog_Material(material_management.proxies.Material materialmasterlog_material)
	{
		setMaterialMasterLog_Material(getContext(), materialmasterlog_material);
	}

	/**
	 * Set value of MaterialMasterLog_Material
	 * @param context
	 * @param materialmasterlog_material
	 */
	public final void setMaterialMasterLog_Material(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.Material materialmasterlog_material)
	{
		if (materialmasterlog_material == null) {
			getMendixObject().setValue(context, MemberNames.MaterialMasterLog_Material.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaterialMasterLog_Material.toString(), materialmasterlog_material.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return materialMasterLogMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.MaterialMasterLog that = (material_management.proxies.MaterialMasterLog) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
