// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

public class MaterialHistoryLog implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject materialHistoryLogMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.MaterialHistoryLog";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaterialPartNo("MaterialPartNo"),
		IsWarehousing("IsWarehousing"),
		OwnerName("OwnerName"),
		OrderDate("OrderDate"),
		WarehousingQuantity("WarehousingQuantity"),
		ForwardingQuantity("ForwardingQuantity"),
		UsageQuantity("UsageQuantity"),
		NotUsageQuantity("NotUsageQuantity"),
		Quantity("Quantity"),
		Price("Price"),
		ReferenceDescript("ReferenceDescript"),
		PlantName("PlantName"),
		WarehouseName("WarehouseName"),
		WarehouseLocation("WarehouseLocation"),
		StockLocation("StockLocation"),
		IsAudit("IsAudit"),
		Purpose("Purpose"),
		MaterialHistoryLog_Material("Material_Management.MaterialHistoryLog_Material");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MaterialHistoryLog(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MaterialHistoryLog(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject materialHistoryLogMendixObject)
	{
		if (materialHistoryLogMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, materialHistoryLogMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.materialHistoryLogMendixObject = materialHistoryLogMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.MaterialHistoryLog initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.MaterialHistoryLog(context, mendixObject);
	}

	public static material_management.proxies.MaterialHistoryLog load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.MaterialHistoryLog.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.MaterialHistoryLog> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.MaterialHistoryLog.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MaterialPartNo
	 */
	public final java.lang.String getMaterialPartNo()
	{
		return getMaterialPartNo(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialPartNo
	 */
	public final java.lang.String getMaterialPartNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialPartNo.toString());
	}

	/**
	 * Set value of MaterialPartNo
	 * @param materialpartno
	 */
	public final void setMaterialPartNo(java.lang.String materialpartno)
	{
		setMaterialPartNo(getContext(), materialpartno);
	}

	/**
	 * Set value of MaterialPartNo
	 * @param context
	 * @param materialpartno
	 */
	public final void setMaterialPartNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialpartno)
	{
		getMendixObject().setValue(context, MemberNames.MaterialPartNo.toString(), materialpartno);
	}

	/**
	 * @return value of IsWarehousing
	 */
	public final java.lang.Boolean getIsWarehousing()
	{
		return getIsWarehousing(getContext());
	}

	/**
	 * @param context
	 * @return value of IsWarehousing
	 */
	public final java.lang.Boolean getIsWarehousing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsWarehousing.toString());
	}

	/**
	 * Set value of IsWarehousing
	 * @param iswarehousing
	 */
	public final void setIsWarehousing(java.lang.Boolean iswarehousing)
	{
		setIsWarehousing(getContext(), iswarehousing);
	}

	/**
	 * Set value of IsWarehousing
	 * @param context
	 * @param iswarehousing
	 */
	public final void setIsWarehousing(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iswarehousing)
	{
		getMendixObject().setValue(context, MemberNames.IsWarehousing.toString(), iswarehousing);
	}

	/**
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName()
	{
		return getOwnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of OwnerName
	 */
	public final java.lang.String getOwnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.OwnerName.toString());
	}

	/**
	 * Set value of OwnerName
	 * @param ownername
	 */
	public final void setOwnerName(java.lang.String ownername)
	{
		setOwnerName(getContext(), ownername);
	}

	/**
	 * Set value of OwnerName
	 * @param context
	 * @param ownername
	 */
	public final void setOwnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String ownername)
	{
		getMendixObject().setValue(context, MemberNames.OwnerName.toString(), ownername);
	}

	/**
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate()
	{
		return getOrderDate(getContext());
	}

	/**
	 * @param context
	 * @return value of OrderDate
	 */
	public final java.util.Date getOrderDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.OrderDate.toString());
	}

	/**
	 * Set value of OrderDate
	 * @param orderdate
	 */
	public final void setOrderDate(java.util.Date orderdate)
	{
		setOrderDate(getContext(), orderdate);
	}

	/**
	 * Set value of OrderDate
	 * @param context
	 * @param orderdate
	 */
	public final void setOrderDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date orderdate)
	{
		getMendixObject().setValue(context, MemberNames.OrderDate.toString(), orderdate);
	}

	/**
	 * @return value of WarehousingQuantity
	 */
	public final java.math.BigDecimal getWarehousingQuantity()
	{
		return getWarehousingQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehousingQuantity
	 */
	public final java.math.BigDecimal getWarehousingQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.WarehousingQuantity.toString());
	}

	/**
	 * Set value of WarehousingQuantity
	 * @param warehousingquantity
	 */
	public final void setWarehousingQuantity(java.math.BigDecimal warehousingquantity)
	{
		setWarehousingQuantity(getContext(), warehousingquantity);
	}

	/**
	 * Set value of WarehousingQuantity
	 * @param context
	 * @param warehousingquantity
	 */
	public final void setWarehousingQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal warehousingquantity)
	{
		getMendixObject().setValue(context, MemberNames.WarehousingQuantity.toString(), warehousingquantity);
	}

	/**
	 * @return value of ForwardingQuantity
	 */
	public final java.math.BigDecimal getForwardingQuantity()
	{
		return getForwardingQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of ForwardingQuantity
	 */
	public final java.math.BigDecimal getForwardingQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ForwardingQuantity.toString());
	}

	/**
	 * Set value of ForwardingQuantity
	 * @param forwardingquantity
	 */
	public final void setForwardingQuantity(java.math.BigDecimal forwardingquantity)
	{
		setForwardingQuantity(getContext(), forwardingquantity);
	}

	/**
	 * Set value of ForwardingQuantity
	 * @param context
	 * @param forwardingquantity
	 */
	public final void setForwardingQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal forwardingquantity)
	{
		getMendixObject().setValue(context, MemberNames.ForwardingQuantity.toString(), forwardingquantity);
	}

	/**
	 * @return value of UsageQuantity
	 */
	public final java.math.BigDecimal getUsageQuantity()
	{
		return getUsageQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of UsageQuantity
	 */
	public final java.math.BigDecimal getUsageQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.UsageQuantity.toString());
	}

	/**
	 * Set value of UsageQuantity
	 * @param usagequantity
	 */
	public final void setUsageQuantity(java.math.BigDecimal usagequantity)
	{
		setUsageQuantity(getContext(), usagequantity);
	}

	/**
	 * Set value of UsageQuantity
	 * @param context
	 * @param usagequantity
	 */
	public final void setUsageQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal usagequantity)
	{
		getMendixObject().setValue(context, MemberNames.UsageQuantity.toString(), usagequantity);
	}

	/**
	 * @return value of NotUsageQuantity
	 */
	public final java.math.BigDecimal getNotUsageQuantity()
	{
		return getNotUsageQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of NotUsageQuantity
	 */
	public final java.math.BigDecimal getNotUsageQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.NotUsageQuantity.toString());
	}

	/**
	 * Set value of NotUsageQuantity
	 * @param notusagequantity
	 */
	public final void setNotUsageQuantity(java.math.BigDecimal notusagequantity)
	{
		setNotUsageQuantity(getContext(), notusagequantity);
	}

	/**
	 * Set value of NotUsageQuantity
	 * @param context
	 * @param notusagequantity
	 */
	public final void setNotUsageQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal notusagequantity)
	{
		getMendixObject().setValue(context, MemberNames.NotUsageQuantity.toString(), notusagequantity);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.math.BigDecimal getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.math.BigDecimal getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.math.BigDecimal quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice()
	{
		return getPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of Price
	 */
	public final java.math.BigDecimal getPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Price.toString());
	}

	/**
	 * Set value of Price
	 * @param price
	 */
	public final void setPrice(java.math.BigDecimal price)
	{
		setPrice(getContext(), price);
	}

	/**
	 * Set value of Price
	 * @param context
	 * @param price
	 */
	public final void setPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal price)
	{
		getMendixObject().setValue(context, MemberNames.Price.toString(), price);
	}

	/**
	 * @return value of ReferenceDescript
	 */
	public final java.lang.String getReferenceDescript()
	{
		return getReferenceDescript(getContext());
	}

	/**
	 * @param context
	 * @return value of ReferenceDescript
	 */
	public final java.lang.String getReferenceDescript(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ReferenceDescript.toString());
	}

	/**
	 * Set value of ReferenceDescript
	 * @param referencedescript
	 */
	public final void setReferenceDescript(java.lang.String referencedescript)
	{
		setReferenceDescript(getContext(), referencedescript);
	}

	/**
	 * Set value of ReferenceDescript
	 * @param context
	 * @param referencedescript
	 */
	public final void setReferenceDescript(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String referencedescript)
	{
		getMendixObject().setValue(context, MemberNames.ReferenceDescript.toString(), referencedescript);
	}

	/**
	 * @return value of PlantName
	 */
	public final java.lang.String getPlantName()
	{
		return getPlantName(getContext());
	}

	/**
	 * @param context
	 * @return value of PlantName
	 */
	public final java.lang.String getPlantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlantName.toString());
	}

	/**
	 * Set value of PlantName
	 * @param plantname
	 */
	public final void setPlantName(java.lang.String plantname)
	{
		setPlantName(getContext(), plantname);
	}

	/**
	 * Set value of PlantName
	 * @param context
	 * @param plantname
	 */
	public final void setPlantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plantname)
	{
		getMendixObject().setValue(context, MemberNames.PlantName.toString(), plantname);
	}

	/**
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName()
	{
		return getWarehouseName(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseName.toString());
	}

	/**
	 * Set value of WarehouseName
	 * @param warehousename
	 */
	public final void setWarehouseName(java.lang.String warehousename)
	{
		setWarehouseName(getContext(), warehousename);
	}

	/**
	 * Set value of WarehouseName
	 * @param context
	 * @param warehousename
	 */
	public final void setWarehouseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehousename)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseName.toString(), warehousename);
	}

	/**
	 * @return value of WarehouseLocation
	 */
	public final java.lang.String getWarehouseLocation()
	{
		return getWarehouseLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseLocation
	 */
	public final java.lang.String getWarehouseLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseLocation.toString());
	}

	/**
	 * Set value of WarehouseLocation
	 * @param warehouselocation
	 */
	public final void setWarehouseLocation(java.lang.String warehouselocation)
	{
		setWarehouseLocation(getContext(), warehouselocation);
	}

	/**
	 * Set value of WarehouseLocation
	 * @param context
	 * @param warehouselocation
	 */
	public final void setWarehouseLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehouselocation)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseLocation.toString(), warehouselocation);
	}

	/**
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation()
	{
		return getStockLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StockLocation.toString());
	}

	/**
	 * Set value of StockLocation
	 * @param stocklocation
	 */
	public final void setStockLocation(java.lang.String stocklocation)
	{
		setStockLocation(getContext(), stocklocation);
	}

	/**
	 * Set value of StockLocation
	 * @param context
	 * @param stocklocation
	 */
	public final void setStockLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stocklocation)
	{
		getMendixObject().setValue(context, MemberNames.StockLocation.toString(), stocklocation);
	}

	/**
	 * @return value of IsAudit
	 */
	public final java.lang.Boolean getIsAudit()
	{
		return getIsAudit(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAudit
	 */
	public final java.lang.Boolean getIsAudit(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAudit.toString());
	}

	/**
	 * Set value of IsAudit
	 * @param isaudit
	 */
	public final void setIsAudit(java.lang.Boolean isaudit)
	{
		setIsAudit(getContext(), isaudit);
	}

	/**
	 * Set value of IsAudit
	 * @param context
	 * @param isaudit
	 */
	public final void setIsAudit(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isaudit)
	{
		getMendixObject().setValue(context, MemberNames.IsAudit.toString(), isaudit);
	}

	/**
	 * @return value of Purpose
	 */
	public final java.lang.String getPurpose()
	{
		return getPurpose(getContext());
	}

	/**
	 * @param context
	 * @return value of Purpose
	 */
	public final java.lang.String getPurpose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Purpose.toString());
	}

	/**
	 * Set value of Purpose
	 * @param purpose
	 */
	public final void setPurpose(java.lang.String purpose)
	{
		setPurpose(getContext(), purpose);
	}

	/**
	 * Set value of Purpose
	 * @param context
	 * @param purpose
	 */
	public final void setPurpose(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String purpose)
	{
		getMendixObject().setValue(context, MemberNames.Purpose.toString(), purpose);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MaterialHistoryLog_Material
	 */
	public final material_management.proxies.Material getMaterialHistoryLog_Material() throws com.mendix.core.CoreException
	{
		return getMaterialHistoryLog_Material(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialHistoryLog_Material
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.Material getMaterialHistoryLog_Material(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.Material result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MaterialHistoryLog_Material.toString());
		if (identifier != null) {
			result = material_management.proxies.Material.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MaterialHistoryLog_Material
	 * @param materialhistorylog_material
	 */
	public final void setMaterialHistoryLog_Material(material_management.proxies.Material materialhistorylog_material)
	{
		setMaterialHistoryLog_Material(getContext(), materialhistorylog_material);
	}

	/**
	 * Set value of MaterialHistoryLog_Material
	 * @param context
	 * @param materialhistorylog_material
	 */
	public final void setMaterialHistoryLog_Material(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.Material materialhistorylog_material)
	{
		if (materialhistorylog_material == null) {
			getMendixObject().setValue(context, MemberNames.MaterialHistoryLog_Material.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MaterialHistoryLog_Material.toString(), materialhistorylog_material.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return materialHistoryLogMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.MaterialHistoryLog that = (material_management.proxies.MaterialHistoryLog) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
