// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/09/06
 * 최종 수정자 : 
 * 최종 수정일 : 2023/09/06
 * 설명 : 자재 사진을 담는 엔터티
 * Version 1.0 : 생성
 */
public class MaterialImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.MaterialImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImageName("ImageName"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Material_MaterialImage("Material_Management.Material_MaterialImage");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MaterialImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MaterialImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject materialImageMendixObject)
	{
		super(context, materialImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, materialImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.MaterialImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.MaterialImage(context, mendixObject);
	}

	public static material_management.proxies.MaterialImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.MaterialImage.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.MaterialImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.MaterialImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName()
	{
		return getImageName(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageName.toString());
	}

	/**
	 * Set value of ImageName
	 * @param imagename
	 */
	public final void setImageName(java.lang.String imagename)
	{
		setImageName(getContext(), imagename);
	}

	/**
	 * Set value of ImageName
	 * @param context
	 * @param imagename
	 */
	public final void setImageName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imagename)
	{
		getMendixObject().setValue(context, MemberNames.ImageName.toString(), imagename);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Material_MaterialImage
	 */
	public final material_management.proxies.Material getMaterial_MaterialImage() throws com.mendix.core.CoreException
	{
		return getMaterial_MaterialImage(getContext());
	}

	/**
	 * @param context
	 * @return value of Material_MaterialImage
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.Material getMaterial_MaterialImage(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.Material result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Material_MaterialImage.toString());
		if (identifier != null) {
			result = material_management.proxies.Material.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Material_MaterialImage
	 * @param material_materialimage
	 */
	public final void setMaterial_MaterialImage(material_management.proxies.Material material_materialimage)
	{
		setMaterial_MaterialImage(getContext(), material_materialimage);
	}

	/**
	 * Set value of Material_MaterialImage
	 * @param context
	 * @param material_materialimage
	 */
	public final void setMaterial_MaterialImage(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.Material material_materialimage)
	{
		if (material_materialimage == null) {
			getMendixObject().setValue(context, MemberNames.Material_MaterialImage.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Material_MaterialImage.toString(), material_materialimage.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.MaterialImage that = (material_management.proxies.MaterialImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
