// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

public class Stockcounter implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject stockcounterMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.Stockcounter";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GatheringCode("GatheringCode"),
		isWarehousing("isWarehousing"),
		MaterialCode("MaterialCode"),
		PlantName("PlantName"),
		WarehouseName("WarehouseName"),
		WarehouseLocation("WarehouseLocation"),
		StockLocation("StockLocation"),
		Quantity("Quantity"),
		InventoryAudit_Stockcounter("Material_Management.InventoryAudit_Stockcounter"),
		Stockcounter_MaterialHistoryLog("Material_Management.Stockcounter_MaterialHistoryLog"),
		Stockcounter_Material("Material_Management.Stockcounter_Material");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Stockcounter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Stockcounter(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject stockcounterMendixObject)
	{
		if (stockcounterMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, stockcounterMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.stockcounterMendixObject = stockcounterMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.Stockcounter initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.Stockcounter(context, mendixObject);
	}

	public static material_management.proxies.Stockcounter load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.Stockcounter.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.Stockcounter> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.Stockcounter.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of GatheringCode
	 */
	public final java.lang.String getGatheringCode()
	{
		return getGatheringCode(getContext());
	}

	/**
	 * @param context
	 * @return value of GatheringCode
	 */
	public final java.lang.String getGatheringCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GatheringCode.toString());
	}

	/**
	 * Set value of GatheringCode
	 * @param gatheringcode
	 */
	public final void setGatheringCode(java.lang.String gatheringcode)
	{
		setGatheringCode(getContext(), gatheringcode);
	}

	/**
	 * Set value of GatheringCode
	 * @param context
	 * @param gatheringcode
	 */
	public final void setGatheringCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gatheringcode)
	{
		getMendixObject().setValue(context, MemberNames.GatheringCode.toString(), gatheringcode);
	}

	/**
	 * @return value of isWarehousing
	 */
	public final java.lang.Boolean getisWarehousing()
	{
		return getisWarehousing(getContext());
	}

	/**
	 * @param context
	 * @return value of isWarehousing
	 */
	public final java.lang.Boolean getisWarehousing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isWarehousing.toString());
	}

	/**
	 * Set value of isWarehousing
	 * @param iswarehousing
	 */
	public final void setisWarehousing(java.lang.Boolean iswarehousing)
	{
		setisWarehousing(getContext(), iswarehousing);
	}

	/**
	 * Set value of isWarehousing
	 * @param context
	 * @param iswarehousing
	 */
	public final void setisWarehousing(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iswarehousing)
	{
		getMendixObject().setValue(context, MemberNames.isWarehousing.toString(), iswarehousing);
	}

	/**
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode()
	{
		return getMaterialCode(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialCode.toString());
	}

	/**
	 * Set value of MaterialCode
	 * @param materialcode
	 */
	public final void setMaterialCode(java.lang.String materialcode)
	{
		setMaterialCode(getContext(), materialcode);
	}

	/**
	 * Set value of MaterialCode
	 * @param context
	 * @param materialcode
	 */
	public final void setMaterialCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialcode)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCode.toString(), materialcode);
	}

	/**
	 * @return value of PlantName
	 */
	public final java.lang.String getPlantName()
	{
		return getPlantName(getContext());
	}

	/**
	 * @param context
	 * @return value of PlantName
	 */
	public final java.lang.String getPlantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlantName.toString());
	}

	/**
	 * Set value of PlantName
	 * @param plantname
	 */
	public final void setPlantName(java.lang.String plantname)
	{
		setPlantName(getContext(), plantname);
	}

	/**
	 * Set value of PlantName
	 * @param context
	 * @param plantname
	 */
	public final void setPlantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plantname)
	{
		getMendixObject().setValue(context, MemberNames.PlantName.toString(), plantname);
	}

	/**
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName()
	{
		return getWarehouseName(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseName.toString());
	}

	/**
	 * Set value of WarehouseName
	 * @param warehousename
	 */
	public final void setWarehouseName(java.lang.String warehousename)
	{
		setWarehouseName(getContext(), warehousename);
	}

	/**
	 * Set value of WarehouseName
	 * @param context
	 * @param warehousename
	 */
	public final void setWarehouseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehousename)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseName.toString(), warehousename);
	}

	/**
	 * @return value of WarehouseLocation
	 */
	public final java.lang.String getWarehouseLocation()
	{
		return getWarehouseLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseLocation
	 */
	public final java.lang.String getWarehouseLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseLocation.toString());
	}

	/**
	 * Set value of WarehouseLocation
	 * @param warehouselocation
	 */
	public final void setWarehouseLocation(java.lang.String warehouselocation)
	{
		setWarehouseLocation(getContext(), warehouselocation);
	}

	/**
	 * Set value of WarehouseLocation
	 * @param context
	 * @param warehouselocation
	 */
	public final void setWarehouseLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehouselocation)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseLocation.toString(), warehouselocation);
	}

	/**
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation()
	{
		return getStockLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StockLocation.toString());
	}

	/**
	 * Set value of StockLocation
	 * @param stocklocation
	 */
	public final void setStockLocation(java.lang.String stocklocation)
	{
		setStockLocation(getContext(), stocklocation);
	}

	/**
	 * Set value of StockLocation
	 * @param context
	 * @param stocklocation
	 */
	public final void setStockLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stocklocation)
	{
		getMendixObject().setValue(context, MemberNames.StockLocation.toString(), stocklocation);
	}

	/**
	 * @return value of Quantity
	 */
	public final java.math.BigDecimal getQuantity()
	{
		return getQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of Quantity
	 */
	public final java.math.BigDecimal getQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Quantity.toString());
	}

	/**
	 * Set value of Quantity
	 * @param quantity
	 */
	public final void setQuantity(java.math.BigDecimal quantity)
	{
		setQuantity(getContext(), quantity);
	}

	/**
	 * Set value of Quantity
	 * @param context
	 * @param quantity
	 */
	public final void setQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal quantity)
	{
		getMendixObject().setValue(context, MemberNames.Quantity.toString(), quantity);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of InventoryAudit_Stockcounter
	 */
	public final material_management.proxies.InventoryAudit getInventoryAudit_Stockcounter() throws com.mendix.core.CoreException
	{
		return getInventoryAudit_Stockcounter(getContext());
	}

	/**
	 * @param context
	 * @return value of InventoryAudit_Stockcounter
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.InventoryAudit getInventoryAudit_Stockcounter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.InventoryAudit result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.InventoryAudit_Stockcounter.toString());
		if (identifier != null) {
			result = material_management.proxies.InventoryAudit.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of InventoryAudit_Stockcounter
	 * @param inventoryaudit_stockcounter
	 */
	public final void setInventoryAudit_Stockcounter(material_management.proxies.InventoryAudit inventoryaudit_stockcounter)
	{
		setInventoryAudit_Stockcounter(getContext(), inventoryaudit_stockcounter);
	}

	/**
	 * Set value of InventoryAudit_Stockcounter
	 * @param context
	 * @param inventoryaudit_stockcounter
	 */
	public final void setInventoryAudit_Stockcounter(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.InventoryAudit inventoryaudit_stockcounter)
	{
		if (inventoryaudit_stockcounter == null) {
			getMendixObject().setValue(context, MemberNames.InventoryAudit_Stockcounter.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.InventoryAudit_Stockcounter.toString(), inventoryaudit_stockcounter.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Stockcounter_MaterialHistoryLog
	 */
	public final material_management.proxies.MaterialHistoryLog getStockcounter_MaterialHistoryLog() throws com.mendix.core.CoreException
	{
		return getStockcounter_MaterialHistoryLog(getContext());
	}

	/**
	 * @param context
	 * @return value of Stockcounter_MaterialHistoryLog
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.MaterialHistoryLog getStockcounter_MaterialHistoryLog(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.MaterialHistoryLog result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Stockcounter_MaterialHistoryLog.toString());
		if (identifier != null) {
			result = material_management.proxies.MaterialHistoryLog.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Stockcounter_MaterialHistoryLog
	 * @param stockcounter_materialhistorylog
	 */
	public final void setStockcounter_MaterialHistoryLog(material_management.proxies.MaterialHistoryLog stockcounter_materialhistorylog)
	{
		setStockcounter_MaterialHistoryLog(getContext(), stockcounter_materialhistorylog);
	}

	/**
	 * Set value of Stockcounter_MaterialHistoryLog
	 * @param context
	 * @param stockcounter_materialhistorylog
	 */
	public final void setStockcounter_MaterialHistoryLog(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.MaterialHistoryLog stockcounter_materialhistorylog)
	{
		if (stockcounter_materialhistorylog == null) {
			getMendixObject().setValue(context, MemberNames.Stockcounter_MaterialHistoryLog.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Stockcounter_MaterialHistoryLog.toString(), stockcounter_materialhistorylog.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Stockcounter_Material
	 */
	public final material_management.proxies.Material getStockcounter_Material() throws com.mendix.core.CoreException
	{
		return getStockcounter_Material(getContext());
	}

	/**
	 * @param context
	 * @return value of Stockcounter_Material
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.Material getStockcounter_Material(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.Material result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Stockcounter_Material.toString());
		if (identifier != null) {
			result = material_management.proxies.Material.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Stockcounter_Material
	 * @param stockcounter_material
	 */
	public final void setStockcounter_Material(material_management.proxies.Material stockcounter_material)
	{
		setStockcounter_Material(getContext(), stockcounter_material);
	}

	/**
	 * Set value of Stockcounter_Material
	 * @param context
	 * @param stockcounter_material
	 */
	public final void setStockcounter_Material(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.Material stockcounter_material)
	{
		if (stockcounter_material == null) {
			getMendixObject().setValue(context, MemberNames.Stockcounter_Material.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Stockcounter_Material.toString(), stockcounter_material.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return stockcounterMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.Stockcounter that = (material_management.proxies.Stockcounter) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
