// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

public class TempMaterialMove implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tempMaterialMoveMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.TempMaterialMove";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		GatheringCode("GatheringCode"),
		MaterialCode("MaterialCode"),
		MoveWarehousingQuantity("MoveWarehousingQuantity"),
		ChangedStockLocation("ChangedStockLocation"),
		TempMaterialMove_Stockcounter("Material_Management.TempMaterialMove_Stockcounter"),
		TempMaterialMove_Account("Material_Management.TempMaterialMove_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TempMaterialMove(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TempMaterialMove(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tempMaterialMoveMendixObject)
	{
		if (tempMaterialMoveMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, tempMaterialMoveMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tempMaterialMoveMendixObject = tempMaterialMoveMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.TempMaterialMove initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.TempMaterialMove(context, mendixObject);
	}

	public static material_management.proxies.TempMaterialMove load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.TempMaterialMove.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.TempMaterialMove> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.TempMaterialMove.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of GatheringCode
	 */
	public final java.lang.String getGatheringCode()
	{
		return getGatheringCode(getContext());
	}

	/**
	 * @param context
	 * @return value of GatheringCode
	 */
	public final java.lang.String getGatheringCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GatheringCode.toString());
	}

	/**
	 * Set value of GatheringCode
	 * @param gatheringcode
	 */
	public final void setGatheringCode(java.lang.String gatheringcode)
	{
		setGatheringCode(getContext(), gatheringcode);
	}

	/**
	 * Set value of GatheringCode
	 * @param context
	 * @param gatheringcode
	 */
	public final void setGatheringCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gatheringcode)
	{
		getMendixObject().setValue(context, MemberNames.GatheringCode.toString(), gatheringcode);
	}

	/**
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode()
	{
		return getMaterialCode(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialCode.toString());
	}

	/**
	 * Set value of MaterialCode
	 * @param materialcode
	 */
	public final void setMaterialCode(java.lang.String materialcode)
	{
		setMaterialCode(getContext(), materialcode);
	}

	/**
	 * Set value of MaterialCode
	 * @param context
	 * @param materialcode
	 */
	public final void setMaterialCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialcode)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCode.toString(), materialcode);
	}

	/**
	 * @return value of MoveWarehousingQuantity
	 */
	public final java.math.BigDecimal getMoveWarehousingQuantity()
	{
		return getMoveWarehousingQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of MoveWarehousingQuantity
	 */
	public final java.math.BigDecimal getMoveWarehousingQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MoveWarehousingQuantity.toString());
	}

	/**
	 * Set value of MoveWarehousingQuantity
	 * @param movewarehousingquantity
	 */
	public final void setMoveWarehousingQuantity(java.math.BigDecimal movewarehousingquantity)
	{
		setMoveWarehousingQuantity(getContext(), movewarehousingquantity);
	}

	/**
	 * Set value of MoveWarehousingQuantity
	 * @param context
	 * @param movewarehousingquantity
	 */
	public final void setMoveWarehousingQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal movewarehousingquantity)
	{
		getMendixObject().setValue(context, MemberNames.MoveWarehousingQuantity.toString(), movewarehousingquantity);
	}

	/**
	 * @return value of ChangedStockLocation
	 */
	public final java.lang.String getChangedStockLocation()
	{
		return getChangedStockLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of ChangedStockLocation
	 */
	public final java.lang.String getChangedStockLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ChangedStockLocation.toString());
	}

	/**
	 * Set value of ChangedStockLocation
	 * @param changedstocklocation
	 */
	public final void setChangedStockLocation(java.lang.String changedstocklocation)
	{
		setChangedStockLocation(getContext(), changedstocklocation);
	}

	/**
	 * Set value of ChangedStockLocation
	 * @param context
	 * @param changedstocklocation
	 */
	public final void setChangedStockLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String changedstocklocation)
	{
		getMendixObject().setValue(context, MemberNames.ChangedStockLocation.toString(), changedstocklocation);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TempMaterialMove_Stockcounter
	 */
	public final material_management.proxies.Stockcounter getTempMaterialMove_Stockcounter() throws com.mendix.core.CoreException
	{
		return getTempMaterialMove_Stockcounter(getContext());
	}

	/**
	 * @param context
	 * @return value of TempMaterialMove_Stockcounter
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.Stockcounter getTempMaterialMove_Stockcounter(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.Stockcounter result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TempMaterialMove_Stockcounter.toString());
		if (identifier != null) {
			result = material_management.proxies.Stockcounter.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TempMaterialMove_Stockcounter
	 * @param tempmaterialmove_stockcounter
	 */
	public final void setTempMaterialMove_Stockcounter(material_management.proxies.Stockcounter tempmaterialmove_stockcounter)
	{
		setTempMaterialMove_Stockcounter(getContext(), tempmaterialmove_stockcounter);
	}

	/**
	 * Set value of TempMaterialMove_Stockcounter
	 * @param context
	 * @param tempmaterialmove_stockcounter
	 */
	public final void setTempMaterialMove_Stockcounter(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.Stockcounter tempmaterialmove_stockcounter)
	{
		if (tempmaterialmove_stockcounter == null) {
			getMendixObject().setValue(context, MemberNames.TempMaterialMove_Stockcounter.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TempMaterialMove_Stockcounter.toString(), tempmaterialmove_stockcounter.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TempMaterialMove_Account
	 */
	public final administration.proxies.Account getTempMaterialMove_Account() throws com.mendix.core.CoreException
	{
		return getTempMaterialMove_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of TempMaterialMove_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getTempMaterialMove_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TempMaterialMove_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TempMaterialMove_Account
	 * @param tempmaterialmove_account
	 */
	public final void setTempMaterialMove_Account(administration.proxies.Account tempmaterialmove_account)
	{
		setTempMaterialMove_Account(getContext(), tempmaterialmove_account);
	}

	/**
	 * Set value of TempMaterialMove_Account
	 * @param context
	 * @param tempmaterialmove_account
	 */
	public final void setTempMaterialMove_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account tempmaterialmove_account)
	{
		if (tempmaterialmove_account == null) {
			getMendixObject().setValue(context, MemberNames.TempMaterialMove_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TempMaterialMove_Account.toString(), tempmaterialmove_account.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tempMaterialMoveMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.TempMaterialMove that = (material_management.proxies.TempMaterialMove) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
