// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

public class TempWarehousing implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject tempWarehousingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.TempWarehousing";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MaterialCode("MaterialCode"),
		MaterialName("MaterialName"),
		MaterialPartNo("MaterialPartNo"),
		WarehousingQuantity("WarehousingQuantity"),
		WarehousingCostPerEA("WarehousingCostPerEA"),
		WarehousingPrice("WarehousingPrice"),
		WarehousingDate("WarehousingDate"),
		StockLocation("StockLocation"),
		TempWarehousing_Account_2("Material_Management.TempWarehousing_Account_2");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TempWarehousing(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected TempWarehousing(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject tempWarehousingMendixObject)
	{
		if (tempWarehousingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, tempWarehousingMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.tempWarehousingMendixObject = tempWarehousingMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.TempWarehousing initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.TempWarehousing(context, mendixObject);
	}

	public static material_management.proxies.TempWarehousing load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.TempWarehousing.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.TempWarehousing> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.TempWarehousing.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode()
	{
		return getMaterialCode(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCode
	 */
	public final java.lang.String getMaterialCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialCode.toString());
	}

	/**
	 * Set value of MaterialCode
	 * @param materialcode
	 */
	public final void setMaterialCode(java.lang.String materialcode)
	{
		setMaterialCode(getContext(), materialcode);
	}

	/**
	 * Set value of MaterialCode
	 * @param context
	 * @param materialcode
	 */
	public final void setMaterialCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialcode)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCode.toString(), materialcode);
	}

	/**
	 * @return value of MaterialName
	 */
	public final java.lang.String getMaterialName()
	{
		return getMaterialName(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialName
	 */
	public final java.lang.String getMaterialName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialName.toString());
	}

	/**
	 * Set value of MaterialName
	 * @param materialname
	 */
	public final void setMaterialName(java.lang.String materialname)
	{
		setMaterialName(getContext(), materialname);
	}

	/**
	 * Set value of MaterialName
	 * @param context
	 * @param materialname
	 */
	public final void setMaterialName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialname)
	{
		getMendixObject().setValue(context, MemberNames.MaterialName.toString(), materialname);
	}

	/**
	 * @return value of MaterialPartNo
	 */
	public final java.lang.String getMaterialPartNo()
	{
		return getMaterialPartNo(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialPartNo
	 */
	public final java.lang.String getMaterialPartNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialPartNo.toString());
	}

	/**
	 * Set value of MaterialPartNo
	 * @param materialpartno
	 */
	public final void setMaterialPartNo(java.lang.String materialpartno)
	{
		setMaterialPartNo(getContext(), materialpartno);
	}

	/**
	 * Set value of MaterialPartNo
	 * @param context
	 * @param materialpartno
	 */
	public final void setMaterialPartNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialpartno)
	{
		getMendixObject().setValue(context, MemberNames.MaterialPartNo.toString(), materialpartno);
	}

	/**
	 * @return value of WarehousingQuantity
	 */
	public final java.math.BigDecimal getWarehousingQuantity()
	{
		return getWarehousingQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehousingQuantity
	 */
	public final java.math.BigDecimal getWarehousingQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.WarehousingQuantity.toString());
	}

	/**
	 * Set value of WarehousingQuantity
	 * @param warehousingquantity
	 */
	public final void setWarehousingQuantity(java.math.BigDecimal warehousingquantity)
	{
		setWarehousingQuantity(getContext(), warehousingquantity);
	}

	/**
	 * Set value of WarehousingQuantity
	 * @param context
	 * @param warehousingquantity
	 */
	public final void setWarehousingQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal warehousingquantity)
	{
		getMendixObject().setValue(context, MemberNames.WarehousingQuantity.toString(), warehousingquantity);
	}

	/**
	 * @return value of WarehousingCostPerEA
	 */
	public final java.math.BigDecimal getWarehousingCostPerEA()
	{
		return getWarehousingCostPerEA(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehousingCostPerEA
	 */
	public final java.math.BigDecimal getWarehousingCostPerEA(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.WarehousingCostPerEA.toString());
	}

	/**
	 * Set value of WarehousingCostPerEA
	 * @param warehousingcostperea
	 */
	public final void setWarehousingCostPerEA(java.math.BigDecimal warehousingcostperea)
	{
		setWarehousingCostPerEA(getContext(), warehousingcostperea);
	}

	/**
	 * Set value of WarehousingCostPerEA
	 * @param context
	 * @param warehousingcostperea
	 */
	public final void setWarehousingCostPerEA(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal warehousingcostperea)
	{
		getMendixObject().setValue(context, MemberNames.WarehousingCostPerEA.toString(), warehousingcostperea);
	}

	/**
	 * @return value of WarehousingPrice
	 */
	public final java.math.BigDecimal getWarehousingPrice()
	{
		return getWarehousingPrice(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehousingPrice
	 */
	public final java.math.BigDecimal getWarehousingPrice(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.WarehousingPrice.toString());
	}

	/**
	 * Set value of WarehousingPrice
	 * @param warehousingprice
	 */
	public final void setWarehousingPrice(java.math.BigDecimal warehousingprice)
	{
		setWarehousingPrice(getContext(), warehousingprice);
	}

	/**
	 * Set value of WarehousingPrice
	 * @param context
	 * @param warehousingprice
	 */
	public final void setWarehousingPrice(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal warehousingprice)
	{
		getMendixObject().setValue(context, MemberNames.WarehousingPrice.toString(), warehousingprice);
	}

	/**
	 * @return value of WarehousingDate
	 */
	public final java.util.Date getWarehousingDate()
	{
		return getWarehousingDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehousingDate
	 */
	public final java.util.Date getWarehousingDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WarehousingDate.toString());
	}

	/**
	 * Set value of WarehousingDate
	 * @param warehousingdate
	 */
	public final void setWarehousingDate(java.util.Date warehousingdate)
	{
		setWarehousingDate(getContext(), warehousingdate);
	}

	/**
	 * Set value of WarehousingDate
	 * @param context
	 * @param warehousingdate
	 */
	public final void setWarehousingDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date warehousingdate)
	{
		getMendixObject().setValue(context, MemberNames.WarehousingDate.toString(), warehousingdate);
	}

	/**
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation()
	{
		return getStockLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StockLocation.toString());
	}

	/**
	 * Set value of StockLocation
	 * @param stocklocation
	 */
	public final void setStockLocation(java.lang.String stocklocation)
	{
		setStockLocation(getContext(), stocklocation);
	}

	/**
	 * Set value of StockLocation
	 * @param context
	 * @param stocklocation
	 */
	public final void setStockLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stocklocation)
	{
		getMendixObject().setValue(context, MemberNames.StockLocation.toString(), stocklocation);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TempWarehousing_Account_2
	 */
	public final administration.proxies.Account getTempWarehousing_Account_2() throws com.mendix.core.CoreException
	{
		return getTempWarehousing_Account_2(getContext());
	}

	/**
	 * @param context
	 * @return value of TempWarehousing_Account_2
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getTempWarehousing_Account_2(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TempWarehousing_Account_2.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TempWarehousing_Account_2
	 * @param tempwarehousing_account_2
	 */
	public final void setTempWarehousing_Account_2(administration.proxies.Account tempwarehousing_account_2)
	{
		setTempWarehousing_Account_2(getContext(), tempwarehousing_account_2);
	}

	/**
	 * Set value of TempWarehousing_Account_2
	 * @param context
	 * @param tempwarehousing_account_2
	 */
	public final void setTempWarehousing_Account_2(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account tempwarehousing_account_2)
	{
		if (tempwarehousing_account_2 == null) {
			getMendixObject().setValue(context, MemberNames.TempWarehousing_Account_2.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TempWarehousing_Account_2.toString(), tempwarehousing_account_2.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return tempWarehousingMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.TempWarehousing that = (material_management.proxies.TempWarehousing) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
