// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package material_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/09/12
 * 최종 수정자 : 
 * 최종 수정일 : 2023/09/12
 * 설명 : 창고 정보를 담는 엔터티
 * Version 1.0 : 생성
 */
public class WareHouse implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject wareHouseMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Material_Management.WareHouse";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WarehouseNumber("WarehouseNumber"),
		WarehouseName("WarehouseName"),
		WarehouseNameEnglish("WarehouseNameEnglish"),
		WarehouseCode("WarehouseCode"),
		WarehouseOrder("WarehouseOrder"),
		WarehouseDescription("WarehouseDescription"),
		Active("Active"),
		WarehouseTitle("WarehouseTitle"),
		WareHouse_WareHouse("Material_Management.WareHouse_WareHouse"),
		WareHouse_WareHouseTreeHelper("Material_Management.WareHouse_WareHouseTreeHelper"),
		WareHouse_WareHouseTreeHelper_Child("Material_Management.WareHouse_WareHouseTreeHelper_Child"),
		WareHouse_Plant("Material_Management.WareHouse_Plant");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WareHouse(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WareHouse(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject wareHouseMendixObject)
	{
		if (wareHouseMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, wareHouseMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.wareHouseMendixObject = wareHouseMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static material_management.proxies.WareHouse initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new material_management.proxies.WareHouse(context, mendixObject);
	}

	public static material_management.proxies.WareHouse load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return material_management.proxies.WareHouse.initialize(context, mendixObject);
	}

	public static java.util.List<material_management.proxies.WareHouse> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> material_management.proxies.WareHouse.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of WarehouseNumber
	 */
	public final java.lang.Integer getWarehouseNumber()
	{
		return getWarehouseNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseNumber
	 */
	public final java.lang.Integer getWarehouseNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.WarehouseNumber.toString());
	}

	/**
	 * Set value of WarehouseNumber
	 * @param warehousenumber
	 */
	public final void setWarehouseNumber(java.lang.Integer warehousenumber)
	{
		setWarehouseNumber(getContext(), warehousenumber);
	}

	/**
	 * Set value of WarehouseNumber
	 * @param context
	 * @param warehousenumber
	 */
	public final void setWarehouseNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer warehousenumber)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseNumber.toString(), warehousenumber);
	}

	/**
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName()
	{
		return getWarehouseName(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseName.toString());
	}

	/**
	 * Set value of WarehouseName
	 * @param warehousename
	 */
	public final void setWarehouseName(java.lang.String warehousename)
	{
		setWarehouseName(getContext(), warehousename);
	}

	/**
	 * Set value of WarehouseName
	 * @param context
	 * @param warehousename
	 */
	public final void setWarehouseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehousename)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseName.toString(), warehousename);
	}

	/**
	 * @return value of WarehouseNameEnglish
	 */
	public final java.lang.String getWarehouseNameEnglish()
	{
		return getWarehouseNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseNameEnglish
	 */
	public final java.lang.String getWarehouseNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseNameEnglish.toString());
	}

	/**
	 * Set value of WarehouseNameEnglish
	 * @param warehousenameenglish
	 */
	public final void setWarehouseNameEnglish(java.lang.String warehousenameenglish)
	{
		setWarehouseNameEnglish(getContext(), warehousenameenglish);
	}

	/**
	 * Set value of WarehouseNameEnglish
	 * @param context
	 * @param warehousenameenglish
	 */
	public final void setWarehouseNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehousenameenglish)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseNameEnglish.toString(), warehousenameenglish);
	}

	/**
	 * @return value of WarehouseCode
	 */
	public final java.lang.String getWarehouseCode()
	{
		return getWarehouseCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseCode
	 */
	public final java.lang.String getWarehouseCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseCode.toString());
	}

	/**
	 * Set value of WarehouseCode
	 * @param warehousecode
	 */
	public final void setWarehouseCode(java.lang.String warehousecode)
	{
		setWarehouseCode(getContext(), warehousecode);
	}

	/**
	 * Set value of WarehouseCode
	 * @param context
	 * @param warehousecode
	 */
	public final void setWarehouseCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehousecode)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseCode.toString(), warehousecode);
	}

	/**
	 * @return value of WarehouseOrder
	 */
	public final java.lang.Integer getWarehouseOrder()
	{
		return getWarehouseOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseOrder
	 */
	public final java.lang.Integer getWarehouseOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.WarehouseOrder.toString());
	}

	/**
	 * Set value of WarehouseOrder
	 * @param warehouseorder
	 */
	public final void setWarehouseOrder(java.lang.Integer warehouseorder)
	{
		setWarehouseOrder(getContext(), warehouseorder);
	}

	/**
	 * Set value of WarehouseOrder
	 * @param context
	 * @param warehouseorder
	 */
	public final void setWarehouseOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer warehouseorder)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseOrder.toString(), warehouseorder);
	}

	/**
	 * @return value of WarehouseDescription
	 */
	public final java.lang.String getWarehouseDescription()
	{
		return getWarehouseDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseDescription
	 */
	public final java.lang.String getWarehouseDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseDescription.toString());
	}

	/**
	 * Set value of WarehouseDescription
	 * @param warehousedescription
	 */
	public final void setWarehouseDescription(java.lang.String warehousedescription)
	{
		setWarehouseDescription(getContext(), warehousedescription);
	}

	/**
	 * Set value of WarehouseDescription
	 * @param context
	 * @param warehousedescription
	 */
	public final void setWarehouseDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehousedescription)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseDescription.toString(), warehousedescription);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of WarehouseTitle
	 */
	public final java.lang.Boolean getWarehouseTitle()
	{
		return getWarehouseTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseTitle
	 */
	public final java.lang.Boolean getWarehouseTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WarehouseTitle.toString());
	}

	/**
	 * Set value of WarehouseTitle
	 * @param warehousetitle
	 */
	public final void setWarehouseTitle(java.lang.Boolean warehousetitle)
	{
		setWarehouseTitle(getContext(), warehousetitle);
	}

	/**
	 * Set value of WarehouseTitle
	 * @param context
	 * @param warehousetitle
	 */
	public final void setWarehouseTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean warehousetitle)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseTitle.toString(), warehousetitle);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WareHouse_WareHouse
	 */
	public final material_management.proxies.WareHouse getWareHouse_WareHouse() throws com.mendix.core.CoreException
	{
		return getWareHouse_WareHouse(getContext());
	}

	/**
	 * @param context
	 * @return value of WareHouse_WareHouse
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.WareHouse getWareHouse_WareHouse(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.WareHouse result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WareHouse_WareHouse.toString());
		if (identifier != null) {
			result = material_management.proxies.WareHouse.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WareHouse_WareHouse
	 * @param warehouse_warehouse
	 */
	public final void setWareHouse_WareHouse(material_management.proxies.WareHouse warehouse_warehouse)
	{
		setWareHouse_WareHouse(getContext(), warehouse_warehouse);
	}

	/**
	 * Set value of WareHouse_WareHouse
	 * @param context
	 * @param warehouse_warehouse
	 */
	public final void setWareHouse_WareHouse(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.WareHouse warehouse_warehouse)
	{
		if (warehouse_warehouse == null) {
			getMendixObject().setValue(context, MemberNames.WareHouse_WareHouse.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WareHouse_WareHouse.toString(), warehouse_warehouse.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WareHouse_WareHouseTreeHelper
	 */
	public final material_management.proxies.WareHouseTreeHelper getWareHouse_WareHouseTreeHelper() throws com.mendix.core.CoreException
	{
		return getWareHouse_WareHouseTreeHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of WareHouse_WareHouseTreeHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.WareHouseTreeHelper getWareHouse_WareHouseTreeHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.WareHouseTreeHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WareHouse_WareHouseTreeHelper.toString());
		if (identifier != null) {
			result = material_management.proxies.WareHouseTreeHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WareHouse_WareHouseTreeHelper
	 * @param warehouse_warehousetreehelper
	 */
	public final void setWareHouse_WareHouseTreeHelper(material_management.proxies.WareHouseTreeHelper warehouse_warehousetreehelper)
	{
		setWareHouse_WareHouseTreeHelper(getContext(), warehouse_warehousetreehelper);
	}

	/**
	 * Set value of WareHouse_WareHouseTreeHelper
	 * @param context
	 * @param warehouse_warehousetreehelper
	 */
	public final void setWareHouse_WareHouseTreeHelper(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.WareHouseTreeHelper warehouse_warehousetreehelper)
	{
		if (warehouse_warehousetreehelper == null) {
			getMendixObject().setValue(context, MemberNames.WareHouse_WareHouseTreeHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WareHouse_WareHouseTreeHelper.toString(), warehouse_warehousetreehelper.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WareHouse_WareHouseTreeHelper_Child
	 */
	public final material_management.proxies.WareHouseTreeHelper_Child getWareHouse_WareHouseTreeHelper_Child() throws com.mendix.core.CoreException
	{
		return getWareHouse_WareHouseTreeHelper_Child(getContext());
	}

	/**
	 * @param context
	 * @return value of WareHouse_WareHouseTreeHelper_Child
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.WareHouseTreeHelper_Child getWareHouse_WareHouseTreeHelper_Child(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.WareHouseTreeHelper_Child result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WareHouse_WareHouseTreeHelper_Child.toString());
		if (identifier != null) {
			result = material_management.proxies.WareHouseTreeHelper_Child.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WareHouse_WareHouseTreeHelper_Child
	 * @param warehouse_warehousetreehelper_child
	 */
	public final void setWareHouse_WareHouseTreeHelper_Child(material_management.proxies.WareHouseTreeHelper_Child warehouse_warehousetreehelper_child)
	{
		setWareHouse_WareHouseTreeHelper_Child(getContext(), warehouse_warehousetreehelper_child);
	}

	/**
	 * Set value of WareHouse_WareHouseTreeHelper_Child
	 * @param context
	 * @param warehouse_warehousetreehelper_child
	 */
	public final void setWareHouse_WareHouseTreeHelper_Child(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.WareHouseTreeHelper_Child warehouse_warehousetreehelper_child)
	{
		if (warehouse_warehousetreehelper_child == null) {
			getMendixObject().setValue(context, MemberNames.WareHouse_WareHouseTreeHelper_Child.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WareHouse_WareHouseTreeHelper_Child.toString(), warehouse_warehousetreehelper_child.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WareHouse_Plant
	 */
	public final cmms_administration.proxies.Plant getWareHouse_Plant() throws com.mendix.core.CoreException
	{
		return getWareHouse_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of WareHouse_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getWareHouse_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WareHouse_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WareHouse_Plant
	 * @param warehouse_plant
	 */
	public final void setWareHouse_Plant(cmms_administration.proxies.Plant warehouse_plant)
	{
		setWareHouse_Plant(getContext(), warehouse_plant);
	}

	/**
	 * Set value of WareHouse_Plant
	 * @param context
	 * @param warehouse_plant
	 */
	public final void setWareHouse_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant warehouse_plant)
	{
		if (warehouse_plant == null) {
			getMendixObject().setValue(context, MemberNames.WareHouse_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WareHouse_Plant.toString(), warehouse_plant.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return wareHouseMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final material_management.proxies.WareHouse that = (material_management.proxies.WareHouse) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
