// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * @returns {Promise.<void>}
 */
export async function JavaScript_action() {
	// BEGIN USER CODE

    function expandAll(){
        var testTreeElements = document.querySelectorAll(".test-tree"); // "test-tree" 클래스를 가진 모든 요소 선택
        var antTreeSwitcherCloseElements = [];

        testTreeElements.forEach(function(testTreeElement) {
            var antTreeSwitcherCloseDescendants = testTreeElement.querySelectorAll(".ant-tree-switcher_close");
            // "ant-tree-switcher_close" 클래스를 가진 모든 후손 요소 선택

            // 선택된 후손 요소를 배열에 추가
            antTreeSwitcherCloseElements = antTreeSwitcherCloseElements.concat(Array.from(antTreeSwitcherCloseDescendants));
        });
        var i;
            
        function callLoop() {
            //loops through the function expandAll until all the trees are expanded
            setTimeout(function(){
                expandAll();
            }, 10);
        }
        
        for(i=0;i<antTreeSwitcherCloseElements.length;i++){
            if(antTreeSwitcherCloseElements[i]){
                antTreeSwitcherCloseElements[i].click();
            }
        }
        if(i==antTreeSwitcherCloseElements.length-1){
            //on last element of the elem calls the function callLoop to loop through the expandAll function again and again until all thr trees are expanded
            callLoop();
        }    
    }
    
    setTimeout(function(){
        expandAll();
    }, 200);
	//throw new Error("JavaScript action was not implemented");
	// END USER CODE
}
