// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * 최초작성자 : 김동명
 * 최초작성일 : 2023-11-14
 * 
 * 설명 : 새창에서 팝업 페이지 열기
 * V1.0 : 최초작성
 * 
 * @param {string} urlcode
 * @param {Big} status
 * @returns {Promise.<void>}
 */
export async function New_Window(urlcode, status) {
	// BEGIN USER CODE
	if (status == 1){
		window.open('http://localhost:8080/p/'+urlcode+'/1', '_blank', 'width=800,height=600');
	}

	else if (status ==2){
		window.open('http://localhost:8080/p/'+urlcode+'/2', '_blank', 'width=800,height=600');
	}

	else {
		console.log('error');
	}
	// END USER CODE
}
