// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
import "mx-global";
import { Big } from "big.js";

// BEGIN EXTRA CODE
// END EXTRA CODE

/**
 * 최초작성자 : 김동명
 * 최초작성일 : 2023-11-14
 * 
 * 설명 : 페이지 인쇄 기능
 * 
 * V1.0 : 최초작성
 * 
 * @returns {Promise.<void>}
 */
export async function Page_Print() {
	// BEGIN USER CODE
    window.print();
	// END USER CODE
}
