// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package commons.proxies;

/**
 * 최초작성자:김동명
 * 최초작성일:2023-11-14
 * 
 * 설명 : 프린트를 해야 할 페이지로 이동 할 때 조건을 주기 위한 헬퍼
 * 
 * V1.0 : 최초작성
 */
public class PrintHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject printHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Commons.PrintHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CheckAttribute("CheckAttribute");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public PrintHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected PrintHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject printHelperMendixObject)
	{
		if (printHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, printHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.printHelperMendixObject = printHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static commons.proxies.PrintHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new commons.proxies.PrintHelper(context, mendixObject);
	}

	public static commons.proxies.PrintHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return commons.proxies.PrintHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of CheckAttribute
	 */
	public final java.lang.Integer getCheckAttribute()
	{
		return getCheckAttribute(getContext());
	}

	/**
	 * @param context
	 * @return value of CheckAttribute
	 */
	public final java.lang.Integer getCheckAttribute(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CheckAttribute.toString());
	}

	/**
	 * Set value of CheckAttribute
	 * @param checkattribute
	 */
	public final void setCheckAttribute(java.lang.Integer checkattribute)
	{
		setCheckAttribute(getContext(), checkattribute);
	}

	/**
	 * Set value of CheckAttribute
	 * @param context
	 * @param checkattribute
	 */
	public final void setCheckAttribute(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer checkattribute)
	{
		getMendixObject().setValue(context, MemberNames.CheckAttribute.toString(), checkattribute);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return printHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final commons.proxies.PrintHelper that = (commons.proxies.PrintHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
