// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package commons.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/08/30
 * 최종 수정자 : 
 * 최종 수정일 : 2023/08/30
 * 설명 : 표준 기준코드를 담는 엔터티
 * Version 1.0 : 생성
 */
public class StandardCode implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject standardCodeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Commons.StandardCode";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Code("Code"),
		CodeSequnce("CodeSequnce"),
		CodeName("CodeName"),
		CodeNameEnglish("CodeNameEnglish"),
		CodeDescription("CodeDescription"),
		IsCodeActive("IsCodeActive"),
		StandardCode_CodeType("Commons.StandardCode_CodeType"),
		Version_StandardCode("Commons.Version_StandardCode"),
		StandardCode_Account("Commons.StandardCode_Account");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public StandardCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected StandardCode(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject standardCodeMendixObject)
	{
		if (standardCodeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, standardCodeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.standardCodeMendixObject = standardCodeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static commons.proxies.StandardCode initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new commons.proxies.StandardCode(context, mendixObject);
	}

	public static commons.proxies.StandardCode load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return commons.proxies.StandardCode.initialize(context, mendixObject);
	}

	public static java.util.List<commons.proxies.StandardCode> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> commons.proxies.StandardCode.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Code
	 */
	public final java.lang.String getCode()
	{
		return getCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Code
	 */
	public final java.lang.String getCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Code.toString());
	}

	/**
	 * Set value of Code
	 * @param code
	 */
	public final void setCode(java.lang.String code)
	{
		setCode(getContext(), code);
	}

	/**
	 * Set value of Code
	 * @param context
	 * @param code
	 */
	public final void setCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String code)
	{
		getMendixObject().setValue(context, MemberNames.Code.toString(), code);
	}

	/**
	 * @return value of CodeSequnce
	 */
	public final java.lang.Integer getCodeSequnce()
	{
		return getCodeSequnce(getContext());
	}

	/**
	 * @param context
	 * @return value of CodeSequnce
	 */
	public final java.lang.Integer getCodeSequnce(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CodeSequnce.toString());
	}

	/**
	 * Set value of CodeSequnce
	 * @param codesequnce
	 */
	public final void setCodeSequnce(java.lang.Integer codesequnce)
	{
		setCodeSequnce(getContext(), codesequnce);
	}

	/**
	 * Set value of CodeSequnce
	 * @param context
	 * @param codesequnce
	 */
	public final void setCodeSequnce(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer codesequnce)
	{
		getMendixObject().setValue(context, MemberNames.CodeSequnce.toString(), codesequnce);
	}

	/**
	 * @return value of CodeName
	 */
	public final java.lang.String getCodeName()
	{
		return getCodeName(getContext());
	}

	/**
	 * @param context
	 * @return value of CodeName
	 */
	public final java.lang.String getCodeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CodeName.toString());
	}

	/**
	 * Set value of CodeName
	 * @param codename
	 */
	public final void setCodeName(java.lang.String codename)
	{
		setCodeName(getContext(), codename);
	}

	/**
	 * Set value of CodeName
	 * @param context
	 * @param codename
	 */
	public final void setCodeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String codename)
	{
		getMendixObject().setValue(context, MemberNames.CodeName.toString(), codename);
	}

	/**
	 * @return value of CodeNameEnglish
	 */
	public final java.lang.String getCodeNameEnglish()
	{
		return getCodeNameEnglish(getContext());
	}

	/**
	 * @param context
	 * @return value of CodeNameEnglish
	 */
	public final java.lang.String getCodeNameEnglish(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CodeNameEnglish.toString());
	}

	/**
	 * Set value of CodeNameEnglish
	 * @param codenameenglish
	 */
	public final void setCodeNameEnglish(java.lang.String codenameenglish)
	{
		setCodeNameEnglish(getContext(), codenameenglish);
	}

	/**
	 * Set value of CodeNameEnglish
	 * @param context
	 * @param codenameenglish
	 */
	public final void setCodeNameEnglish(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String codenameenglish)
	{
		getMendixObject().setValue(context, MemberNames.CodeNameEnglish.toString(), codenameenglish);
	}

	/**
	 * @return value of CodeDescription
	 */
	public final java.lang.String getCodeDescription()
	{
		return getCodeDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of CodeDescription
	 */
	public final java.lang.String getCodeDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CodeDescription.toString());
	}

	/**
	 * Set value of CodeDescription
	 * @param codedescription
	 */
	public final void setCodeDescription(java.lang.String codedescription)
	{
		setCodeDescription(getContext(), codedescription);
	}

	/**
	 * Set value of CodeDescription
	 * @param context
	 * @param codedescription
	 */
	public final void setCodeDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String codedescription)
	{
		getMendixObject().setValue(context, MemberNames.CodeDescription.toString(), codedescription);
	}

	/**
	 * @return value of IsCodeActive
	 */
	public final java.lang.Boolean getIsCodeActive()
	{
		return getIsCodeActive(getContext());
	}

	/**
	 * @param context
	 * @return value of IsCodeActive
	 */
	public final java.lang.Boolean getIsCodeActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsCodeActive.toString());
	}

	/**
	 * Set value of IsCodeActive
	 * @param iscodeactive
	 */
	public final void setIsCodeActive(java.lang.Boolean iscodeactive)
	{
		setIsCodeActive(getContext(), iscodeactive);
	}

	/**
	 * Set value of IsCodeActive
	 * @param context
	 * @param iscodeactive
	 */
	public final void setIsCodeActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iscodeactive)
	{
		getMendixObject().setValue(context, MemberNames.IsCodeActive.toString(), iscodeactive);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StandardCode_CodeType
	 */
	public final commons.proxies.CodeType getStandardCode_CodeType() throws com.mendix.core.CoreException
	{
		return getStandardCode_CodeType(getContext());
	}

	/**
	 * @param context
	 * @return value of StandardCode_CodeType
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.CodeType getStandardCode_CodeType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.CodeType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StandardCode_CodeType.toString());
		if (identifier != null) {
			result = commons.proxies.CodeType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StandardCode_CodeType
	 * @param standardcode_codetype
	 */
	public final void setStandardCode_CodeType(commons.proxies.CodeType standardcode_codetype)
	{
		setStandardCode_CodeType(getContext(), standardcode_codetype);
	}

	/**
	 * Set value of StandardCode_CodeType
	 * @param context
	 * @param standardcode_codetype
	 */
	public final void setStandardCode_CodeType(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.CodeType standardcode_codetype)
	{
		if (standardcode_codetype == null) {
			getMendixObject().setValue(context, MemberNames.StandardCode_CodeType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StandardCode_CodeType.toString(), standardcode_codetype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Version_StandardCode
	 */
	public final commons.proxies.Company getVersion_StandardCode() throws com.mendix.core.CoreException
	{
		return getVersion_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Version_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.Company getVersion_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.Company result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Version_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.Company.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Version_StandardCode
	 * @param version_standardcode
	 */
	public final void setVersion_StandardCode(commons.proxies.Company version_standardcode)
	{
		setVersion_StandardCode(getContext(), version_standardcode);
	}

	/**
	 * Set value of Version_StandardCode
	 * @param context
	 * @param version_standardcode
	 */
	public final void setVersion_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.Company version_standardcode)
	{
		if (version_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Version_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Version_StandardCode.toString(), version_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of StandardCode_Account
	 */
	public final administration.proxies.Account getStandardCode_Account() throws com.mendix.core.CoreException
	{
		return getStandardCode_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of StandardCode_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getStandardCode_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.StandardCode_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of StandardCode_Account
	 * @param standardcode_account
	 */
	public final void setStandardCode_Account(administration.proxies.Account standardcode_account)
	{
		setStandardCode_Account(getContext(), standardcode_account);
	}

	/**
	 * Set value of StandardCode_Account
	 * @param context
	 * @param standardcode_account
	 */
	public final void setStandardCode_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account standardcode_account)
	{
		if (standardcode_account == null) {
			getMendixObject().setValue(context, MemberNames.StandardCode_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.StandardCode_Account.toString(), standardcode_account.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return standardCodeMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final commons.proxies.StandardCode that = (commons.proxies.StandardCode) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
