// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package report.proxies;

public enum ENUM_ReportProcessType
{
	WorkProcessing(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "WorkProcessing" } }),
	WorkRequesting(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "WorkRequesting" } }),
	WorkComplete(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "WorkComplete" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_ReportProcessType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
