// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package report.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/29
 * 최종 수정자 : 
 * 최종 수정일 : 2023/10/29
 * 설명 : 월 기준 보전 비용 집계를 담는 엔터티 
 * Version 1.0 : 생성
 */
public class MonthlyDownCount implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject monthlyDownCountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Report.MonthlyDownCount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Month("Month"),
		Plant("Plant"),
		Location("Location"),
		Equipment("Equipment"),
		EquipmentType("EquipmentType"),
		MaintenanceCount("MaintenanceCount"),
		MaintenanceTime("MaintenanceTime");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MonthlyDownCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MonthlyDownCount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject monthlyDownCountMendixObject)
	{
		if (monthlyDownCountMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, monthlyDownCountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.monthlyDownCountMendixObject = monthlyDownCountMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static report.proxies.MonthlyDownCount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new report.proxies.MonthlyDownCount(context, mendixObject);
	}

	public static report.proxies.MonthlyDownCount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return report.proxies.MonthlyDownCount.initialize(context, mendixObject);
	}

	public static java.util.List<report.proxies.MonthlyDownCount> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> report.proxies.MonthlyDownCount.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Month
	 */
	public final java.util.Date getMonth()
	{
		return getMonth(getContext());
	}

	/**
	 * @param context
	 * @return value of Month
	 */
	public final java.util.Date getMonth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Month.toString());
	}

	/**
	 * Set value of Month
	 * @param month
	 */
	public final void setMonth(java.util.Date month)
	{
		setMonth(getContext(), month);
	}

	/**
	 * Set value of Month
	 * @param context
	 * @param month
	 */
	public final void setMonth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date month)
	{
		getMendixObject().setValue(context, MemberNames.Month.toString(), month);
	}

	/**
	 * @return value of Plant
	 */
	public final java.lang.String getPlant()
	{
		return getPlant(getContext());
	}

	/**
	 * @param context
	 * @return value of Plant
	 */
	public final java.lang.String getPlant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Plant.toString());
	}

	/**
	 * Set value of Plant
	 * @param plant
	 */
	public final void setPlant(java.lang.String plant)
	{
		setPlant(getContext(), plant);
	}

	/**
	 * Set value of Plant
	 * @param context
	 * @param plant
	 */
	public final void setPlant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plant)
	{
		getMendixObject().setValue(context, MemberNames.Plant.toString(), plant);
	}

	/**
	 * @return value of Location
	 */
	public final java.lang.String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final java.lang.String getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(java.lang.String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * @return value of Equipment
	 */
	public final java.lang.String getEquipment()
	{
		return getEquipment(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment
	 */
	public final java.lang.String getEquipment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Equipment.toString());
	}

	/**
	 * Set value of Equipment
	 * @param equipment
	 */
	public final void setEquipment(java.lang.String equipment)
	{
		setEquipment(getContext(), equipment);
	}

	/**
	 * Set value of Equipment
	 * @param context
	 * @param equipment
	 */
	public final void setEquipment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipment)
	{
		getMendixObject().setValue(context, MemberNames.Equipment.toString(), equipment);
	}

	/**
	 * @return value of EquipmentType
	 */
	public final java.lang.String getEquipmentType()
	{
		return getEquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentType
	 */
	public final java.lang.String getEquipmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentType.toString());
	}

	/**
	 * Set value of EquipmentType
	 * @param equipmenttype
	 */
	public final void setEquipmentType(java.lang.String equipmenttype)
	{
		setEquipmentType(getContext(), equipmenttype);
	}

	/**
	 * Set value of EquipmentType
	 * @param context
	 * @param equipmenttype
	 */
	public final void setEquipmentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttype)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentType.toString(), equipmenttype);
	}

	/**
	 * @return value of MaintenanceCount
	 */
	public final java.math.BigDecimal getMaintenanceCount()
	{
		return getMaintenanceCount(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintenanceCount
	 */
	public final java.math.BigDecimal getMaintenanceCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaintenanceCount.toString());
	}

	/**
	 * Set value of MaintenanceCount
	 * @param maintenancecount
	 */
	public final void setMaintenanceCount(java.math.BigDecimal maintenancecount)
	{
		setMaintenanceCount(getContext(), maintenancecount);
	}

	/**
	 * Set value of MaintenanceCount
	 * @param context
	 * @param maintenancecount
	 */
	public final void setMaintenanceCount(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal maintenancecount)
	{
		getMendixObject().setValue(context, MemberNames.MaintenanceCount.toString(), maintenancecount);
	}

	/**
	 * @return value of MaintenanceTime
	 */
	public final java.math.BigDecimal getMaintenanceTime()
	{
		return getMaintenanceTime(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintenanceTime
	 */
	public final java.math.BigDecimal getMaintenanceTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaintenanceTime.toString());
	}

	/**
	 * Set value of MaintenanceTime
	 * @param maintenancetime
	 */
	public final void setMaintenanceTime(java.math.BigDecimal maintenancetime)
	{
		setMaintenanceTime(getContext(), maintenancetime);
	}

	/**
	 * Set value of MaintenanceTime
	 * @param context
	 * @param maintenancetime
	 */
	public final void setMaintenanceTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal maintenancetime)
	{
		getMendixObject().setValue(context, MemberNames.MaintenanceTime.toString(), maintenancetime);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return monthlyDownCountMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final report.proxies.MonthlyDownCount that = (report.proxies.MonthlyDownCount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
