// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package report.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/29
 * 최종 수정자 : 
 * 최종 수정일 : 2023/10/29
 * 설명 : 1년 기준 설비 작업 현황이 상태별 카운트를 담는 엔터티
 * Version 1.0 : 생성
 */
public class MonthlyWorkOrderCount implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject monthlyWorkOrderCountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Report.MonthlyWorkOrderCount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Month("Month"),
		Plant("Plant"),
		Location("Location"),
		Equipment("Equipment"),
		Department("Department"),
		EquipmentType("EquipmentType"),
		Count("Count"),
		ReportProcessType("ReportProcessType"),
		WorkOrderPurpose("WorkOrderPurpose");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MonthlyWorkOrderCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MonthlyWorkOrderCount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject monthlyWorkOrderCountMendixObject)
	{
		if (monthlyWorkOrderCountMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, monthlyWorkOrderCountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.monthlyWorkOrderCountMendixObject = monthlyWorkOrderCountMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static report.proxies.MonthlyWorkOrderCount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new report.proxies.MonthlyWorkOrderCount(context, mendixObject);
	}

	public static report.proxies.MonthlyWorkOrderCount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return report.proxies.MonthlyWorkOrderCount.initialize(context, mendixObject);
	}

	public static java.util.List<report.proxies.MonthlyWorkOrderCount> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> report.proxies.MonthlyWorkOrderCount.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Month
	 */
	public final java.util.Date getMonth()
	{
		return getMonth(getContext());
	}

	/**
	 * @param context
	 * @return value of Month
	 */
	public final java.util.Date getMonth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Month.toString());
	}

	/**
	 * Set value of Month
	 * @param month
	 */
	public final void setMonth(java.util.Date month)
	{
		setMonth(getContext(), month);
	}

	/**
	 * Set value of Month
	 * @param context
	 * @param month
	 */
	public final void setMonth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date month)
	{
		getMendixObject().setValue(context, MemberNames.Month.toString(), month);
	}

	/**
	 * @return value of Plant
	 */
	public final java.lang.String getPlant()
	{
		return getPlant(getContext());
	}

	/**
	 * @param context
	 * @return value of Plant
	 */
	public final java.lang.String getPlant(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Plant.toString());
	}

	/**
	 * Set value of Plant
	 * @param plant
	 */
	public final void setPlant(java.lang.String plant)
	{
		setPlant(getContext(), plant);
	}

	/**
	 * Set value of Plant
	 * @param context
	 * @param plant
	 */
	public final void setPlant(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plant)
	{
		getMendixObject().setValue(context, MemberNames.Plant.toString(), plant);
	}

	/**
	 * @return value of Location
	 */
	public final java.lang.String getLocation()
	{
		return getLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of Location
	 */
	public final java.lang.String getLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Location.toString());
	}

	/**
	 * Set value of Location
	 * @param location
	 */
	public final void setLocation(java.lang.String location)
	{
		setLocation(getContext(), location);
	}

	/**
	 * Set value of Location
	 * @param context
	 * @param location
	 */
	public final void setLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String location)
	{
		getMendixObject().setValue(context, MemberNames.Location.toString(), location);
	}

	/**
	 * @return value of Equipment
	 */
	public final java.lang.String getEquipment()
	{
		return getEquipment(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment
	 */
	public final java.lang.String getEquipment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Equipment.toString());
	}

	/**
	 * Set value of Equipment
	 * @param equipment
	 */
	public final void setEquipment(java.lang.String equipment)
	{
		setEquipment(getContext(), equipment);
	}

	/**
	 * Set value of Equipment
	 * @param context
	 * @param equipment
	 */
	public final void setEquipment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipment)
	{
		getMendixObject().setValue(context, MemberNames.Equipment.toString(), equipment);
	}

	/**
	 * @return value of Department
	 */
	public final java.lang.String getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final java.lang.String getDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Department.toString());
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(java.lang.String department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String department)
	{
		getMendixObject().setValue(context, MemberNames.Department.toString(), department);
	}

	/**
	 * @return value of EquipmentType
	 */
	public final java.lang.String getEquipmentType()
	{
		return getEquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentType
	 */
	public final java.lang.String getEquipmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentType.toString());
	}

	/**
	 * Set value of EquipmentType
	 * @param equipmenttype
	 */
	public final void setEquipmentType(java.lang.String equipmenttype)
	{
		setEquipmentType(getContext(), equipmenttype);
	}

	/**
	 * Set value of EquipmentType
	 * @param context
	 * @param equipmenttype
	 */
	public final void setEquipmentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmenttype)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentType.toString(), equipmenttype);
	}

	/**
	 * @return value of Count
	 */
	public final java.lang.Integer getCount()
	{
		return getCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Count
	 */
	public final java.lang.Integer getCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Count.toString());
	}

	/**
	 * Set value of Count
	 * @param count
	 */
	public final void setCount(java.lang.Integer count)
	{
		setCount(getContext(), count);
	}

	/**
	 * Set value of Count
	 * @param context
	 * @param count
	 */
	public final void setCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer count)
	{
		getMendixObject().setValue(context, MemberNames.Count.toString(), count);
	}

	/**
	 * Get value of ReportProcessType
	 * @param reportprocesstype
	 */
	public final report.proxies.ENUM_ReportProcessType getReportProcessType()
	{
		return getReportProcessType(getContext());
	}

	/**
	 * @param context
	 * @return value of ReportProcessType
	 */
	public final report.proxies.ENUM_ReportProcessType getReportProcessType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ReportProcessType.toString());
		if (obj == null) {
			return null;
		}
		return report.proxies.ENUM_ReportProcessType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ReportProcessType
	 * @param reportprocesstype
	 */
	public final void setReportProcessType(report.proxies.ENUM_ReportProcessType reportprocesstype)
	{
		setReportProcessType(getContext(), reportprocesstype);
	}

	/**
	 * Set value of ReportProcessType
	 * @param context
	 * @param reportprocesstype
	 */
	public final void setReportProcessType(com.mendix.systemwideinterfaces.core.IContext context, report.proxies.ENUM_ReportProcessType reportprocesstype)
	{
		if (reportprocesstype != null) {
			getMendixObject().setValue(context, MemberNames.ReportProcessType.toString(), reportprocesstype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ReportProcessType.toString(), null);
		}
	}

	/**
	 * @return value of WorkOrderPurpose
	 */
	public final java.lang.String getWorkOrderPurpose()
	{
		return getWorkOrderPurpose(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderPurpose
	 */
	public final java.lang.String getWorkOrderPurpose(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkOrderPurpose.toString());
	}

	/**
	 * Set value of WorkOrderPurpose
	 * @param workorderpurpose
	 */
	public final void setWorkOrderPurpose(java.lang.String workorderpurpose)
	{
		setWorkOrderPurpose(getContext(), workorderpurpose);
	}

	/**
	 * Set value of WorkOrderPurpose
	 * @param context
	 * @param workorderpurpose
	 */
	public final void setWorkOrderPurpose(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workorderpurpose)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderPurpose.toString(), workorderpurpose);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return monthlyWorkOrderCountMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final report.proxies.MonthlyWorkOrderCount that = (report.proxies.MonthlyWorkOrderCount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
