// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mypage.proxies;

/**
 * 업무 일지 첨부파일
 */
public class Files extends system.proxies.FileDocument
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyPage.Files";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Files_WorkReport("MyPage.Files_WorkReport"),
		Files_WorkReportHelper("MyPage.Files_WorkReportHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Files(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Files(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject filesMendixObject)
	{
		super(context, filesMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, filesMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mypage.proxies.Files initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mypage.proxies.Files(context, mendixObject);
	}

	public static mypage.proxies.Files load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mypage.proxies.Files.initialize(context, mendixObject);
	}

	public static java.util.List<mypage.proxies.Files> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mypage.proxies.Files.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Files_WorkReport
	 */
	public final mypage.proxies.WorkReport getFiles_WorkReport() throws com.mendix.core.CoreException
	{
		return getFiles_WorkReport(getContext());
	}

	/**
	 * @param context
	 * @return value of Files_WorkReport
	 * @throws com.mendix.core.CoreException
	 */
	public final mypage.proxies.WorkReport getFiles_WorkReport(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mypage.proxies.WorkReport result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Files_WorkReport.toString());
		if (identifier != null) {
			result = mypage.proxies.WorkReport.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Files_WorkReport
	 * @param files_workreport
	 */
	public final void setFiles_WorkReport(mypage.proxies.WorkReport files_workreport)
	{
		setFiles_WorkReport(getContext(), files_workreport);
	}

	/**
	 * Set value of Files_WorkReport
	 * @param context
	 * @param files_workreport
	 */
	public final void setFiles_WorkReport(com.mendix.systemwideinterfaces.core.IContext context, mypage.proxies.WorkReport files_workreport)
	{
		if (files_workreport == null) {
			getMendixObject().setValue(context, MemberNames.Files_WorkReport.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Files_WorkReport.toString(), files_workreport.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Files_WorkReportHelper
	 */
	public final mypage.proxies.WorkReportHelper getFiles_WorkReportHelper() throws com.mendix.core.CoreException
	{
		return getFiles_WorkReportHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Files_WorkReportHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final mypage.proxies.WorkReportHelper getFiles_WorkReportHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		mypage.proxies.WorkReportHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Files_WorkReportHelper.toString());
		if (identifier != null) {
			result = mypage.proxies.WorkReportHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Files_WorkReportHelper
	 * @param files_workreporthelper
	 */
	public final void setFiles_WorkReportHelper(mypage.proxies.WorkReportHelper files_workreporthelper)
	{
		setFiles_WorkReportHelper(getContext(), files_workreporthelper);
	}

	/**
	 * Set value of Files_WorkReportHelper
	 * @param context
	 * @param files_workreporthelper
	 */
	public final void setFiles_WorkReportHelper(com.mendix.systemwideinterfaces.core.IContext context, mypage.proxies.WorkReportHelper files_workreporthelper)
	{
		if (files_workreporthelper == null) {
			getMendixObject().setValue(context, MemberNames.Files_WorkReportHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Files_WorkReportHelper.toString(), files_workreporthelper.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mypage.proxies.Files that = (mypage.proxies.Files) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
