// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mypage.proxies;

/**
 * 최초 작성자 : 이슬기
 * 최초 작성일 : 2023/11/28
 * 최종 수정자 : 이슬기
 * 최종 수정일 : 2023/12/07
 * 설명 : 내 설비 보기 필터링 헬퍼 엔터티
 * Version 1.1 : 필터링 로직 변경으로 인해 attributes 삭제
 * Version 1.0 : 생성
 */
public class FilterHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject filterHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyPage.FilterHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentType("EquipmentType"),
		WorkStatus("WorkStatus"),
		FilterHelper_EquipmentType("MyPage.FilterHelper_EquipmentType"),
		FilterHelper_Equipment("MyPage.FilterHelper_Equipment"),
		FilterHelper_StandardCode("MyPage.FilterHelper_StandardCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FilterHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FilterHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject filterHelperMendixObject)
	{
		if (filterHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, filterHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.filterHelperMendixObject = filterHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mypage.proxies.FilterHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mypage.proxies.FilterHelper(context, mendixObject);
	}

	public static mypage.proxies.FilterHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mypage.proxies.FilterHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of EquipmentType
	 */
	public final java.lang.Boolean getEquipmentType()
	{
		return getEquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentType
	 */
	public final java.lang.Boolean getEquipmentType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentType.toString());
	}

	/**
	 * Set value of EquipmentType
	 * @param equipmenttype
	 */
	public final void setEquipmentType(java.lang.Boolean equipmenttype)
	{
		setEquipmentType(getContext(), equipmenttype);
	}

	/**
	 * Set value of EquipmentType
	 * @param context
	 * @param equipmenttype
	 */
	public final void setEquipmentType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmenttype)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentType.toString(), equipmenttype);
	}

	/**
	 * @return value of WorkStatus
	 */
	public final java.lang.Boolean getWorkStatus()
	{
		return getWorkStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkStatus
	 */
	public final java.lang.Boolean getWorkStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WorkStatus.toString());
	}

	/**
	 * Set value of WorkStatus
	 * @param workstatus
	 */
	public final void setWorkStatus(java.lang.Boolean workstatus)
	{
		setWorkStatus(getContext(), workstatus);
	}

	/**
	 * Set value of WorkStatus
	 * @param context
	 * @param workstatus
	 */
	public final void setWorkStatus(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean workstatus)
	{
		getMendixObject().setValue(context, MemberNames.WorkStatus.toString(), workstatus);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FilterHelper_EquipmentType
	 */
	public final equipment_management.proxies.EquipmentType getFilterHelper_EquipmentType() throws com.mendix.core.CoreException
	{
		return getFilterHelper_EquipmentType(getContext());
	}

	/**
	 * @param context
	 * @return value of FilterHelper_EquipmentType
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.EquipmentType getFilterHelper_EquipmentType(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.EquipmentType result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FilterHelper_EquipmentType.toString());
		if (identifier != null) {
			result = equipment_management.proxies.EquipmentType.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FilterHelper_EquipmentType
	 * @param filterhelper_equipmenttype
	 */
	public final void setFilterHelper_EquipmentType(equipment_management.proxies.EquipmentType filterhelper_equipmenttype)
	{
		setFilterHelper_EquipmentType(getContext(), filterhelper_equipmenttype);
	}

	/**
	 * Set value of FilterHelper_EquipmentType
	 * @param context
	 * @param filterhelper_equipmenttype
	 */
	public final void setFilterHelper_EquipmentType(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.EquipmentType filterhelper_equipmenttype)
	{
		if (filterhelper_equipmenttype == null) {
			getMendixObject().setValue(context, MemberNames.FilterHelper_EquipmentType.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FilterHelper_EquipmentType.toString(), filterhelper_equipmenttype.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FilterHelper_Equipment
	 */
	public final equipment_management.proxies.Equipment getFilterHelper_Equipment() throws com.mendix.core.CoreException
	{
		return getFilterHelper_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of FilterHelper_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getFilterHelper_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FilterHelper_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FilterHelper_Equipment
	 * @param filterhelper_equipment
	 */
	public final void setFilterHelper_Equipment(equipment_management.proxies.Equipment filterhelper_equipment)
	{
		setFilterHelper_Equipment(getContext(), filterhelper_equipment);
	}

	/**
	 * Set value of FilterHelper_Equipment
	 * @param context
	 * @param filterhelper_equipment
	 */
	public final void setFilterHelper_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment filterhelper_equipment)
	{
		if (filterhelper_equipment == null) {
			getMendixObject().setValue(context, MemberNames.FilterHelper_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FilterHelper_Equipment.toString(), filterhelper_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FilterHelper_StandardCode
	 */
	public final commons.proxies.StandardCode getFilterHelper_StandardCode() throws com.mendix.core.CoreException
	{
		return getFilterHelper_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of FilterHelper_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getFilterHelper_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FilterHelper_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FilterHelper_StandardCode
	 * @param filterhelper_standardcode
	 */
	public final void setFilterHelper_StandardCode(commons.proxies.StandardCode filterhelper_standardcode)
	{
		setFilterHelper_StandardCode(getContext(), filterhelper_standardcode);
	}

	/**
	 * Set value of FilterHelper_StandardCode
	 * @param context
	 * @param filterhelper_standardcode
	 */
	public final void setFilterHelper_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode filterhelper_standardcode)
	{
		if (filterhelper_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.FilterHelper_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FilterHelper_StandardCode.toString(), filterhelper_standardcode.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return filterHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mypage.proxies.FilterHelper that = (mypage.proxies.FilterHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
