// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mypage.proxies;

/**
 * 최초 작성자 : 이슬기
 * 최초 작성일 : 2023/12/08
 * 최종 수정자 :
 * 최종 수정일 : 
 * 설명 : 업무일지
 * Version 1.0 : 생성
 */
public class WorkReport implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workReportMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyPage.WorkReport";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Content("Content"),
		Message("Message"),
		WorkReportNumber("WorkReportNumber"),
		isDeleted("isDeleted"),
		DeletedDate("DeletedDate"),
		FileCount("FileCount"),
		WorkReport_Employee("MyPage.WorkReport_Employee");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkReport(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workReportMendixObject)
	{
		if (workReportMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workReportMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workReportMendixObject = workReportMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mypage.proxies.WorkReport initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mypage.proxies.WorkReport(context, mendixObject);
	}

	public static mypage.proxies.WorkReport load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mypage.proxies.WorkReport.initialize(context, mendixObject);
	}

	public static java.util.List<mypage.proxies.WorkReport> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mypage.proxies.WorkReport.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of WorkReportNumber
	 */
	public final java.lang.Long getWorkReportNumber()
	{
		return getWorkReportNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkReportNumber
	 */
	public final java.lang.Long getWorkReportNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.WorkReportNumber.toString());
	}

	/**
	 * Set value of WorkReportNumber
	 * @param workreportnumber
	 */
	public final void setWorkReportNumber(java.lang.Long workreportnumber)
	{
		setWorkReportNumber(getContext(), workreportnumber);
	}

	/**
	 * Set value of WorkReportNumber
	 * @param context
	 * @param workreportnumber
	 */
	public final void setWorkReportNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long workreportnumber)
	{
		getMendixObject().setValue(context, MemberNames.WorkReportNumber.toString(), workreportnumber);
	}

	/**
	 * @return value of isDeleted
	 */
	public final java.lang.Boolean getisDeleted()
	{
		return getisDeleted(getContext());
	}

	/**
	 * @param context
	 * @return value of isDeleted
	 */
	public final java.lang.Boolean getisDeleted(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.isDeleted.toString());
	}

	/**
	 * Set value of isDeleted
	 * @param isdeleted
	 */
	public final void setisDeleted(java.lang.Boolean isdeleted)
	{
		setisDeleted(getContext(), isdeleted);
	}

	/**
	 * Set value of isDeleted
	 * @param context
	 * @param isdeleted
	 */
	public final void setisDeleted(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isdeleted)
	{
		getMendixObject().setValue(context, MemberNames.isDeleted.toString(), isdeleted);
	}

	/**
	 * @return value of DeletedDate
	 */
	public final java.util.Date getDeletedDate()
	{
		return getDeletedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DeletedDate
	 */
	public final java.util.Date getDeletedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DeletedDate.toString());
	}

	/**
	 * Set value of DeletedDate
	 * @param deleteddate
	 */
	public final void setDeletedDate(java.util.Date deleteddate)
	{
		setDeletedDate(getContext(), deleteddate);
	}

	/**
	 * Set value of DeletedDate
	 * @param context
	 * @param deleteddate
	 */
	public final void setDeletedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date deleteddate)
	{
		getMendixObject().setValue(context, MemberNames.DeletedDate.toString(), deleteddate);
	}

	/**
	 * @return value of FileCount
	 */
	public final java.lang.Integer getFileCount()
	{
		return getFileCount(getContext());
	}

	/**
	 * @param context
	 * @return value of FileCount
	 */
	public final java.lang.Integer getFileCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FileCount.toString());
	}

	/**
	 * Set value of FileCount
	 * @param filecount
	 */
	public final void setFileCount(java.lang.Integer filecount)
	{
		setFileCount(getContext(), filecount);
	}

	/**
	 * Set value of FileCount
	 * @param context
	 * @param filecount
	 */
	public final void setFileCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer filecount)
	{
		getMendixObject().setValue(context, MemberNames.FileCount.toString(), filecount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkReport_Employee
	 */
	public final cmms_administration.proxies.Employee getWorkReport_Employee() throws com.mendix.core.CoreException
	{
		return getWorkReport_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkReport_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getWorkReport_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkReport_Employee.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkReport_Employee
	 * @param workreport_employee
	 */
	public final void setWorkReport_Employee(cmms_administration.proxies.Employee workreport_employee)
	{
		setWorkReport_Employee(getContext(), workreport_employee);
	}

	/**
	 * Set value of WorkReport_Employee
	 * @param context
	 * @param workreport_employee
	 */
	public final void setWorkReport_Employee(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee workreport_employee)
	{
		if (workreport_employee == null) {
			getMendixObject().setValue(context, MemberNames.WorkReport_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkReport_Employee.toString(), workreport_employee.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workReportMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mypage.proxies.WorkReport that = (mypage.proxies.WorkReport) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
