// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mypage.proxies;

/**
 * 최초 작성자 : 이슬기
 * 최초 작성일 : 2023/12/08
 * 최종 수정자 :
 * 최종 수정일 : 
 * 설명 : 업무일지 엔터티 헬퍼
 * Version 1.0 : 생성
 */
public class WorkReportHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workReportHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyPage.WorkReportHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Content("Content"),
		Message("Message"),
		WorkReportNumber("WorkReportNumber"),
		FilesCount("FilesCount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkReportHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkReportHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workReportHelperMendixObject)
	{
		if (workReportHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workReportHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workReportHelperMendixObject = workReportHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static mypage.proxies.WorkReportHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new mypage.proxies.WorkReportHelper(context, mendixObject);
	}

	public static mypage.proxies.WorkReportHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return mypage.proxies.WorkReportHelper.initialize(context, mendixObject);
	}

	public static java.util.List<mypage.proxies.WorkReportHelper> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> mypage.proxies.WorkReportHelper.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Content
	 */
	public final java.lang.String getContent()
	{
		return getContent(getContext());
	}

	/**
	 * @param context
	 * @return value of Content
	 */
	public final java.lang.String getContent(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Content.toString());
	}

	/**
	 * Set value of Content
	 * @param content
	 */
	public final void setContent(java.lang.String content)
	{
		setContent(getContext(), content);
	}

	/**
	 * Set value of Content
	 * @param context
	 * @param content
	 */
	public final void setContent(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String content)
	{
		getMendixObject().setValue(context, MemberNames.Content.toString(), content);
	}

	/**
	 * @return value of Message
	 */
	public final java.lang.String getMessage()
	{
		return getMessage(getContext());
	}

	/**
	 * @param context
	 * @return value of Message
	 */
	public final java.lang.String getMessage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Message.toString());
	}

	/**
	 * Set value of Message
	 * @param message
	 */
	public final void setMessage(java.lang.String message)
	{
		setMessage(getContext(), message);
	}

	/**
	 * Set value of Message
	 * @param context
	 * @param message
	 */
	public final void setMessage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String message)
	{
		getMendixObject().setValue(context, MemberNames.Message.toString(), message);
	}

	/**
	 * @return value of WorkReportNumber
	 */
	public final java.lang.Integer getWorkReportNumber()
	{
		return getWorkReportNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkReportNumber
	 */
	public final java.lang.Integer getWorkReportNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.WorkReportNumber.toString());
	}

	/**
	 * Set value of WorkReportNumber
	 * @param workreportnumber
	 */
	public final void setWorkReportNumber(java.lang.Integer workreportnumber)
	{
		setWorkReportNumber(getContext(), workreportnumber);
	}

	/**
	 * Set value of WorkReportNumber
	 * @param context
	 * @param workreportnumber
	 */
	public final void setWorkReportNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer workreportnumber)
	{
		getMendixObject().setValue(context, MemberNames.WorkReportNumber.toString(), workreportnumber);
	}

	/**
	 * @return value of FilesCount
	 */
	public final java.lang.Integer getFilesCount()
	{
		return getFilesCount(getContext());
	}

	/**
	 * @param context
	 * @return value of FilesCount
	 */
	public final java.lang.Integer getFilesCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FilesCount.toString());
	}

	/**
	 * Set value of FilesCount
	 * @param filescount
	 */
	public final void setFilesCount(java.lang.Integer filescount)
	{
		setFilesCount(getContext(), filescount);
	}

	/**
	 * Set value of FilesCount
	 * @param context
	 * @param filescount
	 */
	public final void setFilesCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer filescount)
	{
		getMendixObject().setValue(context, MemberNames.FilesCount.toString(), filescount);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workReportHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final mypage.proxies.WorkReportHelper that = (mypage.proxies.WorkReportHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
