// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package google.proxies;

public class Google_UserInfo implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject google_UserInfoMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Google.Google_UserInfo";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		_id("_id"),
		Email("Email"),
		Verified_email("Verified_email"),
		Name("Name"),
		Given_name("Given_name"),
		Family_name("Family_name"),
		Picture("Picture"),
		Locale("Locale"),
		Sub("Sub");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Google_UserInfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Google_UserInfo(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject google_UserInfoMendixObject)
	{
		if (google_UserInfoMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, google_UserInfoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.google_UserInfoMendixObject = google_UserInfoMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static google.proxies.Google_UserInfo initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new google.proxies.Google_UserInfo(context, mendixObject);
	}

	public static google.proxies.Google_UserInfo load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return google.proxies.Google_UserInfo.initialize(context, mendixObject);
	}

	public static java.util.List<google.proxies.Google_UserInfo> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> google.proxies.Google_UserInfo.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of _id
	 */
	public final java.lang.String get_id()
	{
		return get_id(getContext());
	}

	/**
	 * @param context
	 * @return value of _id
	 */
	public final java.lang.String get_id(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames._id.toString());
	}

	/**
	 * Set value of _id
	 * @param _id
	 */
	public final void set_id(java.lang.String _id)
	{
		set_id(getContext(), _id);
	}

	/**
	 * Set value of _id
	 * @param context
	 * @param _id
	 */
	public final void set_id(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String _id)
	{
		getMendixObject().setValue(context, MemberNames._id.toString(), _id);
	}

	/**
	 * @return value of Email
	 */
	public final java.lang.String getEmail()
	{
		return getEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of Email
	 */
	public final java.lang.String getEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Email.toString());
	}

	/**
	 * Set value of Email
	 * @param email
	 */
	public final void setEmail(java.lang.String email)
	{
		setEmail(getContext(), email);
	}

	/**
	 * Set value of Email
	 * @param context
	 * @param email
	 */
	public final void setEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String email)
	{
		getMendixObject().setValue(context, MemberNames.Email.toString(), email);
	}

	/**
	 * @return value of Verified_email
	 */
	public final java.lang.Boolean getVerified_email()
	{
		return getVerified_email(getContext());
	}

	/**
	 * @param context
	 * @return value of Verified_email
	 */
	public final java.lang.Boolean getVerified_email(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Verified_email.toString());
	}

	/**
	 * Set value of Verified_email
	 * @param verified_email
	 */
	public final void setVerified_email(java.lang.Boolean verified_email)
	{
		setVerified_email(getContext(), verified_email);
	}

	/**
	 * Set value of Verified_email
	 * @param context
	 * @param verified_email
	 */
	public final void setVerified_email(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean verified_email)
	{
		getMendixObject().setValue(context, MemberNames.Verified_email.toString(), verified_email);
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Given_name
	 */
	public final java.lang.String getGiven_name()
	{
		return getGiven_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Given_name
	 */
	public final java.lang.String getGiven_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Given_name.toString());
	}

	/**
	 * Set value of Given_name
	 * @param given_name
	 */
	public final void setGiven_name(java.lang.String given_name)
	{
		setGiven_name(getContext(), given_name);
	}

	/**
	 * Set value of Given_name
	 * @param context
	 * @param given_name
	 */
	public final void setGiven_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String given_name)
	{
		getMendixObject().setValue(context, MemberNames.Given_name.toString(), given_name);
	}

	/**
	 * @return value of Family_name
	 */
	public final java.lang.String getFamily_name()
	{
		return getFamily_name(getContext());
	}

	/**
	 * @param context
	 * @return value of Family_name
	 */
	public final java.lang.String getFamily_name(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Family_name.toString());
	}

	/**
	 * Set value of Family_name
	 * @param family_name
	 */
	public final void setFamily_name(java.lang.String family_name)
	{
		setFamily_name(getContext(), family_name);
	}

	/**
	 * Set value of Family_name
	 * @param context
	 * @param family_name
	 */
	public final void setFamily_name(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String family_name)
	{
		getMendixObject().setValue(context, MemberNames.Family_name.toString(), family_name);
	}

	/**
	 * @return value of Picture
	 */
	public final java.lang.String getPicture()
	{
		return getPicture(getContext());
	}

	/**
	 * @param context
	 * @return value of Picture
	 */
	public final java.lang.String getPicture(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Picture.toString());
	}

	/**
	 * Set value of Picture
	 * @param picture
	 */
	public final void setPicture(java.lang.String picture)
	{
		setPicture(getContext(), picture);
	}

	/**
	 * Set value of Picture
	 * @param context
	 * @param picture
	 */
	public final void setPicture(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String picture)
	{
		getMendixObject().setValue(context, MemberNames.Picture.toString(), picture);
	}

	/**
	 * @return value of Locale
	 */
	public final java.lang.String getLocale()
	{
		return getLocale(getContext());
	}

	/**
	 * @param context
	 * @return value of Locale
	 */
	public final java.lang.String getLocale(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Locale.toString());
	}

	/**
	 * Set value of Locale
	 * @param locale
	 */
	public final void setLocale(java.lang.String locale)
	{
		setLocale(getContext(), locale);
	}

	/**
	 * Set value of Locale
	 * @param context
	 * @param locale
	 */
	public final void setLocale(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locale)
	{
		getMendixObject().setValue(context, MemberNames.Locale.toString(), locale);
	}

	/**
	 * @return value of Sub
	 */
	public final java.lang.String getSub()
	{
		return getSub(getContext());
	}

	/**
	 * @param context
	 * @return value of Sub
	 */
	public final java.lang.String getSub(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Sub.toString());
	}

	/**
	 * Set value of Sub
	 * @param sub
	 */
	public final void setSub(java.lang.String sub)
	{
		setSub(getContext(), sub);
	}

	/**
	 * Set value of Sub
	 * @param context
	 * @param sub
	 */
	public final void setSub(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sub)
	{
		getMendixObject().setValue(context, MemberNames.Sub.toString(), sub);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return google_UserInfoMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final google.proxies.Google_UserInfo that = (google.proxies.Google_UserInfo) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
