// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package globalsearch.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the GlobalSearch module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCO_SearchableObjectBuilder(
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ACO_SearchableObject");
		builder = builder.withParam("SearchableObject", _searchableObject);
		return builder;
	}

	public static boolean aCO_SearchableObject(
		IContext context,
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		Object result = aCO_SearchableObjectBuilder(
				_searchableObject
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_BuildIndexManualBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ACT_BuildIndexManual");
		return builder;
	}

	public static void aCT_BuildIndexManual(IContext context)
	{
		aCT_BuildIndexManualBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Index_ClearAllBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ACT_Index_ClearAll");
		return builder;
	}

	public static void aCT_Index_ClearAll(IContext context)
	{
		aCT_Index_ClearAllBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_IndexDataToFileDocument_ManualBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ACT_IndexDataToFileDocument_Manual");
		return builder;
	}

	public static void aCT_IndexDataToFileDocument_Manual(IContext context)
	{
		aCT_IndexDataToFileDocument_ManualBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_RestoreIndexFolderFromZipFileBuilder(
		globalsearch.proxies.IndexZipData _indexZipData
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ACT_RestoreIndexFolderFromZipFile");
		builder = builder.withParam("IndexZipData", _indexZipData);
		return builder;
	}

	public static void aCT_RestoreIndexFolderFromZipFile(
		IContext context,
		globalsearch.proxies.IndexZipData _indexZipData
	)
	{
		aCT_RestoreIndexFolderFromZipFileBuilder(
				_indexZipData
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Searcher_ClearBuilder(
		globalsearch.proxies.Searcher _searcher
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ACT_Searcher_Clear");
		builder = builder.withParam("Searcher", _searcher);
		return builder;
	}

	public static void aCT_Searcher_Clear(
		IContext context,
		globalsearch.proxies.Searcher _searcher
	)
	{
		aCT_Searcher_ClearBuilder(
				_searcher
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Searcher_SearchBuilder(
		globalsearch.proxies.Searcher _searcher
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ACT_Searcher_Search");
		builder = builder.withParam("Searcher", _searcher);
		return builder;
	}

	public static void aCT_Searcher_Search(
		IContext context,
		globalsearch.proxies.Searcher _searcher
	)
	{
		aCT_Searcher_SearchBuilder(
				_searcher
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSU_GlobalSearchBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ASU_GlobalSearch");
		return builder;
	}

	public static boolean aSU_GlobalSearch(IContext context)
	{
		Object result = aSU_GlobalSearchBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aSu_RestoreIndexdataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.ASu_RestoreIndexdata");
		return builder;
	}

	public static boolean aSu_RestoreIndexdata(IContext context)
	{
		Object result = aSu_RestoreIndexdataBuilder().execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bDE_SearchableObjectBuilder(
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.BDE_SearchableObject");
		builder = builder.withParam("SearchableObject", _searchableObject);
		return builder;
	}

	public static boolean bDE_SearchableObject(
		IContext context,
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		Object result = bDE_SearchableObjectBuilder(
				_searchableObject
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder bSd_StoreIndexDataBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.BSd_StoreIndexData");
		return builder;
	}

	public static void bSd_StoreIndexData(IContext context)
	{
		bSd_StoreIndexDataBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Searcher_CreateSearcherBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.DS_Searcher_CreateSearcher");
		return builder;
	}

	public static globalsearch.proxies.Searcher dS_Searcher_CreateSearcher(IContext context)
	{
		Object result = dS_Searcher_CreateSearcherBuilder().execute(context);
		return result == null ? null : globalsearch.proxies.Searcher.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_Searcher_DrillDownBuilder(
		globalsearch.proxies.Searcher _searcher
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.OCH_Searcher_DrillDown");
		builder = builder.withParam("Searcher", _searcher);
		return builder;
	}

	public static void oCH_Searcher_DrillDown(
		IContext context,
		globalsearch.proxies.Searcher _searcher
	)
	{
		oCH_Searcher_DrillDownBuilder(
				_searcher
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Actor_IndexBuilder(
		globalsearch.proxies.Actor _actor
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_Actor_Index");
		builder = builder.withParam("Actor", _actor);
		return builder;
	}

	public static void sUB_Actor_Index(
		IContext context,
		globalsearch.proxies.Actor _actor
	)
	{
		sUB_Actor_IndexBuilder(
				_actor
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_AfterStartupBuilder(
		java.util.List<globalsearch.proxies.SearchableObjectCache> _newCache
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_AfterStartup");
		builder = builder.withParam("NewCache", _newCache);
		return builder;
	}

	public static void sUB_AfterStartup(
		IContext context,
		java.util.List<globalsearch.proxies.SearchableObjectCache> _newCache
	)
	{
		sUB_AfterStartupBuilder(
				_newCache
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_BuildIndexBuilder(
		java.util.List<globalsearch.proxies.SearchableObjectCache> _newCache,
		boolean _isManual
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_BuildIndex");
		builder = builder.withParam("NewCache", _newCache);
		builder = builder.withParam("IsManual", _isManual);
		return builder;
	}

	public static void sUB_BuildIndex(
		IContext context,
		java.util.List<globalsearch.proxies.SearchableObjectCache> _newCache,
		boolean _isManual
	)
	{
		sUB_BuildIndexBuilder(
				_newCache,
				_isManual
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_DeleteIndexBuilder(
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_DeleteIndex");
		builder = builder.withParam("SearchableObject", _searchableObject);
		return builder;
	}

	public static boolean sUB_DeleteIndex(
		IContext context,
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		Object result = sUB_DeleteIndexBuilder(
				_searchableObject
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Facet_AddBuilder(
		java.util.List<globalsearch.proxies.Facet> _facetList,
		java.lang.String _key,
		java.lang.String _value
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_Facet_Add");
		builder = builder.withParam("FacetList", _facetList);
		builder = builder.withParam("Key", _key);
		builder = builder.withParam("Value", _value);
		return builder;
	}

	public static void sUB_Facet_Add(
		IContext context,
		java.util.List<globalsearch.proxies.Facet> _facetList,
		java.lang.String _key,
		java.lang.String _value
	)
	{
		sUB_Facet_AddBuilder(
				_facetList,
				_key,
				_value
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Facet_CreateListBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_Facet_CreateList");
		return builder;
	}

	public static java.util.List<globalsearch.proxies.Facet> sUB_Facet_CreateList(IContext context)
	{
		Object result = sUB_Facet_CreateListBuilder().execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> globalsearch.proxies.Facet.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_IndexDataToFileDocumentBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_IndexDataToFileDocument");
		return builder;
	}

	public static void sUB_IndexDataToFileDocument(IContext context)
	{
		sUB_IndexDataToFileDocumentBuilder().execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_IndexObjectBuilder(
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_IndexObject");
		builder = builder.withParam("SearchableObject", _searchableObject);
		return builder;
	}

	public static boolean sUB_IndexObject(
		IContext context,
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		Object result = sUB_IndexObjectBuilder(
				_searchableObject
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Movie_IndexBuilder(
		globalsearch.proxies.Movie _movie
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_Movie_Index");
		builder = builder.withParam("Movie", _movie);
		return builder;
	}

	public static void sUB_Movie_Index(
		IContext context,
		globalsearch.proxies.Movie _movie
	)
	{
		sUB_Movie_IndexBuilder(
				_movie
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_RestoreIndexZipdataToFolderBuilder(
		globalsearch.proxies.IndexZipData _indexZipData,
		boolean _delete
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("GlobalSearch.SUB_RestoreIndexZipdataToFolder");
		builder = builder.withParam("IndexZipData", _indexZipData);
		builder = builder.withParam("Delete", _delete);
		return builder;
	}

	public static boolean sUB_RestoreIndexZipdataToFolder(
		IContext context,
		globalsearch.proxies.IndexZipData _indexZipData,
		boolean _delete
	)
	{
		Object result = sUB_RestoreIndexZipdataToFolderBuilder(
				_indexZipData,
				_delete
			)
			.execute(context);
		return (boolean) result;
	}
}
