// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

public enum PersistenceType
{
	Persistable(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Persistent" }, new java.lang.String[] { "en_GB", "Persistable" }, new java.lang.String[] { "en_ZA", "Persistable" }, new java.lang.String[] { "ko_KR", "Persistable" } }),
	Non_persistent(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Niet peristent" }, new java.lang.String[] { "en_GB", "Non-persistent" }, new java.lang.String[] { "en_ZA", "Non-persistent" }, new java.lang.String[] { "ko_KR", "Non-persistent" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private PersistenceType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
