// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

public enum ReferenceType
{
	Reference(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Referentie" }, new java.lang.String[] { "en_GB", "Reference" }, new java.lang.String[] { "en_ZA", "Reference" }, new java.lang.String[] { "ko_KR", "Reference" } }),
	ReferenceSet(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Reference set" }, new java.lang.String[] { "en_GB", "Reference set" }, new java.lang.String[] { "en_ZA", "Reference set" }, new java.lang.String[] { "ko_KR", "Reference set" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ReferenceType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
