// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mxmodelreflection.proxies;

public enum Status
{
	Valid(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Geldig" }, new java.lang.String[] { "en_GB", "Valid" }, new java.lang.String[] { "en_ZA", "Valid" }, new java.lang.String[] { "ko_KR", "Valid" } }),
	Invalid(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Ongeldig" }, new java.lang.String[] { "en_GB", "Invalid" }, new java.lang.String[] { "en_ZA", "Invalid" }, new java.lang.String[] { "ko_KR", "Invalid" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Status(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
