// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmms_administration.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/08/30
 * 최종 수정자 : 
 * 최종 수정일 : 2023/08/30
 * 설명 : 부서
 * Version 1.0 : 생성
 */
public class Department implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject departmentMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMMS_Administration.Department";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		DepartmentCode("DepartmentCode"),
		DepartmentName("DepartmentName"),
		DepartmentEnglishName("DepartmentEnglishName"),
		DepartmentActive("DepartmentActive"),
		DepartmentLevel("DepartmentLevel"),
		ParentPath("ParentPath"),
		DepartmentDescription("DepartmentDescription"),
		DEPTNo("DEPTNo"),
		DEPTControlNo("DEPTControlNo"),
		WorkrecordCheck("WorkrecordCheck"),
		Parent_Department("CMMS_Administration.Parent_Department"),
		Department_Plant("CMMS_Administration.Department_Plant"),
		Department_DepartmentTreeHelper("CMMS_Administration.Department_DepartmentTreeHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Department(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Department(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject departmentMendixObject)
	{
		if (departmentMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, departmentMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.departmentMendixObject = departmentMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cmms_administration.proxies.Department initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cmms_administration.proxies.Department(context, mendixObject);
	}

	public static cmms_administration.proxies.Department load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cmms_administration.proxies.Department.initialize(context, mendixObject);
	}

	public static java.util.List<cmms_administration.proxies.Department> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> cmms_administration.proxies.Department.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of DepartmentCode
	 */
	public final java.lang.String getDepartmentCode()
	{
		return getDepartmentCode(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartmentCode
	 */
	public final java.lang.String getDepartmentCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DepartmentCode.toString());
	}

	/**
	 * Set value of DepartmentCode
	 * @param departmentcode
	 */
	public final void setDepartmentCode(java.lang.String departmentcode)
	{
		setDepartmentCode(getContext(), departmentcode);
	}

	/**
	 * Set value of DepartmentCode
	 * @param context
	 * @param departmentcode
	 */
	public final void setDepartmentCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String departmentcode)
	{
		getMendixObject().setValue(context, MemberNames.DepartmentCode.toString(), departmentcode);
	}

	/**
	 * @return value of DepartmentName
	 */
	public final java.lang.String getDepartmentName()
	{
		return getDepartmentName(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartmentName
	 */
	public final java.lang.String getDepartmentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DepartmentName.toString());
	}

	/**
	 * Set value of DepartmentName
	 * @param departmentname
	 */
	public final void setDepartmentName(java.lang.String departmentname)
	{
		setDepartmentName(getContext(), departmentname);
	}

	/**
	 * Set value of DepartmentName
	 * @param context
	 * @param departmentname
	 */
	public final void setDepartmentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String departmentname)
	{
		getMendixObject().setValue(context, MemberNames.DepartmentName.toString(), departmentname);
	}

	/**
	 * @return value of DepartmentEnglishName
	 */
	public final java.lang.String getDepartmentEnglishName()
	{
		return getDepartmentEnglishName(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartmentEnglishName
	 */
	public final java.lang.String getDepartmentEnglishName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DepartmentEnglishName.toString());
	}

	/**
	 * Set value of DepartmentEnglishName
	 * @param departmentenglishname
	 */
	public final void setDepartmentEnglishName(java.lang.String departmentenglishname)
	{
		setDepartmentEnglishName(getContext(), departmentenglishname);
	}

	/**
	 * Set value of DepartmentEnglishName
	 * @param context
	 * @param departmentenglishname
	 */
	public final void setDepartmentEnglishName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String departmentenglishname)
	{
		getMendixObject().setValue(context, MemberNames.DepartmentEnglishName.toString(), departmentenglishname);
	}

	/**
	 * @return value of DepartmentActive
	 */
	public final java.lang.Boolean getDepartmentActive()
	{
		return getDepartmentActive(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartmentActive
	 */
	public final java.lang.Boolean getDepartmentActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.DepartmentActive.toString());
	}

	/**
	 * Set value of DepartmentActive
	 * @param departmentactive
	 */
	public final void setDepartmentActive(java.lang.Boolean departmentactive)
	{
		setDepartmentActive(getContext(), departmentactive);
	}

	/**
	 * Set value of DepartmentActive
	 * @param context
	 * @param departmentactive
	 */
	public final void setDepartmentActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean departmentactive)
	{
		getMendixObject().setValue(context, MemberNames.DepartmentActive.toString(), departmentactive);
	}

	/**
	 * @return value of DepartmentLevel
	 */
	public final java.lang.Integer getDepartmentLevel()
	{
		return getDepartmentLevel(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartmentLevel
	 */
	public final java.lang.Integer getDepartmentLevel(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.DepartmentLevel.toString());
	}

	/**
	 * Set value of DepartmentLevel
	 * @param departmentlevel
	 */
	public final void setDepartmentLevel(java.lang.Integer departmentlevel)
	{
		setDepartmentLevel(getContext(), departmentlevel);
	}

	/**
	 * Set value of DepartmentLevel
	 * @param context
	 * @param departmentlevel
	 */
	public final void setDepartmentLevel(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer departmentlevel)
	{
		getMendixObject().setValue(context, MemberNames.DepartmentLevel.toString(), departmentlevel);
	}

	/**
	 * @return value of ParentPath
	 */
	public final java.lang.String getParentPath()
	{
		return getParentPath(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentPath
	 */
	public final java.lang.String getParentPath(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentPath.toString());
	}

	/**
	 * Set value of ParentPath
	 * @param parentpath
	 */
	public final void setParentPath(java.lang.String parentpath)
	{
		setParentPath(getContext(), parentpath);
	}

	/**
	 * Set value of ParentPath
	 * @param context
	 * @param parentpath
	 */
	public final void setParentPath(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentpath)
	{
		getMendixObject().setValue(context, MemberNames.ParentPath.toString(), parentpath);
	}

	/**
	 * @return value of DepartmentDescription
	 */
	public final java.lang.String getDepartmentDescription()
	{
		return getDepartmentDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartmentDescription
	 */
	public final java.lang.String getDepartmentDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DepartmentDescription.toString());
	}

	/**
	 * Set value of DepartmentDescription
	 * @param departmentdescription
	 */
	public final void setDepartmentDescription(java.lang.String departmentdescription)
	{
		setDepartmentDescription(getContext(), departmentdescription);
	}

	/**
	 * Set value of DepartmentDescription
	 * @param context
	 * @param departmentdescription
	 */
	public final void setDepartmentDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String departmentdescription)
	{
		getMendixObject().setValue(context, MemberNames.DepartmentDescription.toString(), departmentdescription);
	}

	/**
	 * @return value of DEPTNo
	 */
	public final java.lang.Long getDEPTNo()
	{
		return getDEPTNo(getContext());
	}

	/**
	 * @param context
	 * @return value of DEPTNo
	 */
	public final java.lang.Long getDEPTNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.DEPTNo.toString());
	}

	/**
	 * Set value of DEPTNo
	 * @param deptno
	 */
	public final void setDEPTNo(java.lang.Long deptno)
	{
		setDEPTNo(getContext(), deptno);
	}

	/**
	 * Set value of DEPTNo
	 * @param context
	 * @param deptno
	 */
	public final void setDEPTNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long deptno)
	{
		getMendixObject().setValue(context, MemberNames.DEPTNo.toString(), deptno);
	}

	/**
	 * @return value of DEPTControlNo
	 */
	public final java.lang.String getDEPTControlNo()
	{
		return getDEPTControlNo(getContext());
	}

	/**
	 * @param context
	 * @return value of DEPTControlNo
	 */
	public final java.lang.String getDEPTControlNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DEPTControlNo.toString());
	}

	/**
	 * Set value of DEPTControlNo
	 * @param deptcontrolno
	 */
	public final void setDEPTControlNo(java.lang.String deptcontrolno)
	{
		setDEPTControlNo(getContext(), deptcontrolno);
	}

	/**
	 * Set value of DEPTControlNo
	 * @param context
	 * @param deptcontrolno
	 */
	public final void setDEPTControlNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String deptcontrolno)
	{
		getMendixObject().setValue(context, MemberNames.DEPTControlNo.toString(), deptcontrolno);
	}

	/**
	 * @return value of WorkrecordCheck
	 */
	public final java.lang.Boolean getWorkrecordCheck()
	{
		return getWorkrecordCheck(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkrecordCheck
	 */
	public final java.lang.Boolean getWorkrecordCheck(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WorkrecordCheck.toString());
	}

	/**
	 * Set value of WorkrecordCheck
	 * @param workrecordcheck
	 */
	public final void setWorkrecordCheck(java.lang.Boolean workrecordcheck)
	{
		setWorkrecordCheck(getContext(), workrecordcheck);
	}

	/**
	 * Set value of WorkrecordCheck
	 * @param context
	 * @param workrecordcheck
	 */
	public final void setWorkrecordCheck(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean workrecordcheck)
	{
		getMendixObject().setValue(context, MemberNames.WorkrecordCheck.toString(), workrecordcheck);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Parent_Department
	 */
	public final cmms_administration.proxies.Department getParent_Department() throws com.mendix.core.CoreException
	{
		return getParent_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Parent_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Department getParent_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Parent_Department.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Parent_Department
	 * @param parent_department
	 */
	public final void setParent_Department(cmms_administration.proxies.Department parent_department)
	{
		setParent_Department(getContext(), parent_department);
	}

	/**
	 * Set value of Parent_Department
	 * @param context
	 * @param parent_department
	 */
	public final void setParent_Department(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Department parent_department)
	{
		if (parent_department == null) {
			getMendixObject().setValue(context, MemberNames.Parent_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Parent_Department.toString(), parent_department.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Department_Plant
	 */
	public final cmms_administration.proxies.Plant getDepartment_Plant() throws com.mendix.core.CoreException
	{
		return getDepartment_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of Department_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getDepartment_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Department_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Department_Plant
	 * @param department_plant
	 */
	public final void setDepartment_Plant(cmms_administration.proxies.Plant department_plant)
	{
		setDepartment_Plant(getContext(), department_plant);
	}

	/**
	 * Set value of Department_Plant
	 * @param context
	 * @param department_plant
	 */
	public final void setDepartment_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant department_plant)
	{
		if (department_plant == null) {
			getMendixObject().setValue(context, MemberNames.Department_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Department_Plant.toString(), department_plant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Department_DepartmentTreeHelper
	 */
	public final cmms_administration.proxies.DepartmentTreeHelper getDepartment_DepartmentTreeHelper() throws com.mendix.core.CoreException
	{
		return getDepartment_DepartmentTreeHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Department_DepartmentTreeHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.DepartmentTreeHelper getDepartment_DepartmentTreeHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.DepartmentTreeHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Department_DepartmentTreeHelper.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.DepartmentTreeHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Department_DepartmentTreeHelper
	 * @param department_departmenttreehelper
	 */
	public final void setDepartment_DepartmentTreeHelper(cmms_administration.proxies.DepartmentTreeHelper department_departmenttreehelper)
	{
		setDepartment_DepartmentTreeHelper(getContext(), department_departmenttreehelper);
	}

	/**
	 * Set value of Department_DepartmentTreeHelper
	 * @param context
	 * @param department_departmenttreehelper
	 */
	public final void setDepartment_DepartmentTreeHelper(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.DepartmentTreeHelper department_departmenttreehelper)
	{
		if (department_departmenttreehelper == null) {
			getMendixObject().setValue(context, MemberNames.Department_DepartmentTreeHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Department_DepartmentTreeHelper.toString(), department_departmenttreehelper.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return departmentMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cmms_administration.proxies.Department that = (cmms_administration.proxies.Department) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
