// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmms_administration.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/08/30
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/06
 * 설명 : 임직원 정보를 담는 엔터티
 * Version 1.1 : 엔터티 권한 설정 (Admin & Developer 권한 RW , 나머지는 본인 계정만 RW) // 이단비 
 * Version 1.0 : 생성
 */
public class Employee implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMMS_Administration.Employee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EnglishName("EnglishName"),
		EmployeeNumber("EmployeeNumber"),
		EmployeeCode("EmployeeCode"),
		PhoneNumber("PhoneNumber"),
		HourlyWage("HourlyWage"),
		CardNumber("CardNumber"),
		EmployeeSign("EmployeeSign"),
		EmployeeSeal("EmployeeSeal"),
		EmployeeDescription("EmployeeDescription"),
		IsRetired("IsRetired"),
		IsAbsence("IsAbsence"),
		EMPLNo("EMPLNo"),
		RequireCount("RequireCount"),
		ExecuteCount("ExecuteCount"),
		Worktime("Worktime"),
		SNSCheck("SNSCheck"),
		EmailCheck("EmailCheck"),
		EmployeeFullName("EmployeeFullName"),
		EmployeeActive("EmployeeActive"),
		EmployeeEmail("EmployeeEmail"),
		Employee_Department("CMMS_Administration.Employee_Department"),
		Employee_ProfilePhoto("CMMS_Administration.Employee_ProfilePhoto"),
		Employee_Plant("CMMS_Administration.Employee_Plant"),
		Employee_sign("CMMS_Administration.Employee_sign"),
		Employee_Seal("CMMS_Administration.Employee_Seal"),
		Employee_Employeehelper("CMMS_Administration.Employee_Employeehelper"),
		Employee_Account("CMMS_Administration.Employee_Account"),
		EmployeeOutsourcing_StandardCode("CMMS_Administration.EmployeeOutsourcing_StandardCode"),
		EmployeeLog_StandardCode("CMMS_Administration.EmployeeLog_StandardCode"),
		Position_StandardCode("CMMS_Administration.Position_StandardCode"),
		Duty_StandardCode("CMMS_Administration.Duty_StandardCode"),
		EmployeeFunction_StandardCode("CMMS_Administration.EmployeeFunction_StandardCode"),
		EmployeeWorkStatus_StandardCode("CMMS_Administration.EmployeeWorkStatus_StandardCode"),
		Employee_Equipment("CMMS_Administration.Employee_Equipment");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Employee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Employee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject)
	{
		if (employeeMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, employeeMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.employeeMendixObject = employeeMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cmms_administration.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cmms_administration.proxies.Employee(context, mendixObject);
	}

	public static cmms_administration.proxies.Employee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cmms_administration.proxies.Employee.initialize(context, mendixObject);
	}

	public static java.util.List<cmms_administration.proxies.Employee> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> cmms_administration.proxies.Employee.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of EnglishName
	 */
	public final java.lang.String getEnglishName()
	{
		return getEnglishName(getContext());
	}

	/**
	 * @param context
	 * @return value of EnglishName
	 */
	public final java.lang.String getEnglishName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EnglishName.toString());
	}

	/**
	 * Set value of EnglishName
	 * @param englishname
	 */
	public final void setEnglishName(java.lang.String englishname)
	{
		setEnglishName(getContext(), englishname);
	}

	/**
	 * Set value of EnglishName
	 * @param context
	 * @param englishname
	 */
	public final void setEnglishName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String englishname)
	{
		getMendixObject().setValue(context, MemberNames.EnglishName.toString(), englishname);
	}

	/**
	 * @return value of EmployeeNumber
	 */
	public final java.lang.String getEmployeeNumber()
	{
		return getEmployeeNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeNumber
	 */
	public final java.lang.String getEmployeeNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeNumber.toString());
	}

	/**
	 * Set value of EmployeeNumber
	 * @param employeenumber
	 */
	public final void setEmployeeNumber(java.lang.String employeenumber)
	{
		setEmployeeNumber(getContext(), employeenumber);
	}

	/**
	 * Set value of EmployeeNumber
	 * @param context
	 * @param employeenumber
	 */
	public final void setEmployeeNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeenumber)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeNumber.toString(), employeenumber);
	}

	/**
	 * @return value of EmployeeCode
	 */
	public final java.lang.String getEmployeeCode()
	{
		return getEmployeeCode(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeCode
	 */
	public final java.lang.String getEmployeeCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeCode.toString());
	}

	/**
	 * Set value of EmployeeCode
	 * @param employeecode
	 */
	public final void setEmployeeCode(java.lang.String employeecode)
	{
		setEmployeeCode(getContext(), employeecode);
	}

	/**
	 * Set value of EmployeeCode
	 * @param context
	 * @param employeecode
	 */
	public final void setEmployeeCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeecode)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeCode.toString(), employeecode);
	}

	/**
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber()
	{
		return getPhoneNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of PhoneNumber
	 */
	public final java.lang.String getPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PhoneNumber.toString());
	}

	/**
	 * Set value of PhoneNumber
	 * @param phonenumber
	 */
	public final void setPhoneNumber(java.lang.String phonenumber)
	{
		setPhoneNumber(getContext(), phonenumber);
	}

	/**
	 * Set value of PhoneNumber
	 * @param context
	 * @param phonenumber
	 */
	public final void setPhoneNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String phonenumber)
	{
		getMendixObject().setValue(context, MemberNames.PhoneNumber.toString(), phonenumber);
	}

	/**
	 * @return value of HourlyWage
	 */
	public final java.lang.Integer getHourlyWage()
	{
		return getHourlyWage(getContext());
	}

	/**
	 * @param context
	 * @return value of HourlyWage
	 */
	public final java.lang.Integer getHourlyWage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.HourlyWage.toString());
	}

	/**
	 * Set value of HourlyWage
	 * @param hourlywage
	 */
	public final void setHourlyWage(java.lang.Integer hourlywage)
	{
		setHourlyWage(getContext(), hourlywage);
	}

	/**
	 * Set value of HourlyWage
	 * @param context
	 * @param hourlywage
	 */
	public final void setHourlyWage(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer hourlywage)
	{
		getMendixObject().setValue(context, MemberNames.HourlyWage.toString(), hourlywage);
	}

	/**
	 * @return value of CardNumber
	 */
	public final java.lang.String getCardNumber()
	{
		return getCardNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of CardNumber
	 */
	public final java.lang.String getCardNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CardNumber.toString());
	}

	/**
	 * Set value of CardNumber
	 * @param cardnumber
	 */
	public final void setCardNumber(java.lang.String cardnumber)
	{
		setCardNumber(getContext(), cardnumber);
	}

	/**
	 * Set value of CardNumber
	 * @param context
	 * @param cardnumber
	 */
	public final void setCardNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cardnumber)
	{
		getMendixObject().setValue(context, MemberNames.CardNumber.toString(), cardnumber);
	}

	/**
	 * @return value of EmployeeSign
	 */
	public final java.lang.String getEmployeeSign()
	{
		return getEmployeeSign(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeSign
	 */
	public final java.lang.String getEmployeeSign(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeSign.toString());
	}

	/**
	 * Set value of EmployeeSign
	 * @param employeesign
	 */
	public final void setEmployeeSign(java.lang.String employeesign)
	{
		setEmployeeSign(getContext(), employeesign);
	}

	/**
	 * Set value of EmployeeSign
	 * @param context
	 * @param employeesign
	 */
	public final void setEmployeeSign(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeesign)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeSign.toString(), employeesign);
	}

	/**
	 * @return value of EmployeeSeal
	 */
	public final java.lang.String getEmployeeSeal()
	{
		return getEmployeeSeal(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeSeal
	 */
	public final java.lang.String getEmployeeSeal(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeSeal.toString());
	}

	/**
	 * Set value of EmployeeSeal
	 * @param employeeseal
	 */
	public final void setEmployeeSeal(java.lang.String employeeseal)
	{
		setEmployeeSeal(getContext(), employeeseal);
	}

	/**
	 * Set value of EmployeeSeal
	 * @param context
	 * @param employeeseal
	 */
	public final void setEmployeeSeal(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeeseal)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeSeal.toString(), employeeseal);
	}

	/**
	 * @return value of EmployeeDescription
	 */
	public final java.lang.String getEmployeeDescription()
	{
		return getEmployeeDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeDescription
	 */
	public final java.lang.String getEmployeeDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeDescription.toString());
	}

	/**
	 * Set value of EmployeeDescription
	 * @param employeedescription
	 */
	public final void setEmployeeDescription(java.lang.String employeedescription)
	{
		setEmployeeDescription(getContext(), employeedescription);
	}

	/**
	 * Set value of EmployeeDescription
	 * @param context
	 * @param employeedescription
	 */
	public final void setEmployeeDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeedescription)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeDescription.toString(), employeedescription);
	}

	/**
	 * @return value of IsRetired
	 */
	public final java.lang.Boolean getIsRetired()
	{
		return getIsRetired(getContext());
	}

	/**
	 * @param context
	 * @return value of IsRetired
	 */
	public final java.lang.Boolean getIsRetired(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsRetired.toString());
	}

	/**
	 * Set value of IsRetired
	 * @param isretired
	 */
	public final void setIsRetired(java.lang.Boolean isretired)
	{
		setIsRetired(getContext(), isretired);
	}

	/**
	 * Set value of IsRetired
	 * @param context
	 * @param isretired
	 */
	public final void setIsRetired(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isretired)
	{
		getMendixObject().setValue(context, MemberNames.IsRetired.toString(), isretired);
	}

	/**
	 * @return value of IsAbsence
	 */
	public final java.lang.Boolean getIsAbsence()
	{
		return getIsAbsence(getContext());
	}

	/**
	 * @param context
	 * @return value of IsAbsence
	 */
	public final java.lang.Boolean getIsAbsence(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsAbsence.toString());
	}

	/**
	 * Set value of IsAbsence
	 * @param isabsence
	 */
	public final void setIsAbsence(java.lang.Boolean isabsence)
	{
		setIsAbsence(getContext(), isabsence);
	}

	/**
	 * Set value of IsAbsence
	 * @param context
	 * @param isabsence
	 */
	public final void setIsAbsence(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isabsence)
	{
		getMendixObject().setValue(context, MemberNames.IsAbsence.toString(), isabsence);
	}

	/**
	 * @return value of EMPLNo
	 */
	public final java.lang.Long getEMPLNo()
	{
		return getEMPLNo(getContext());
	}

	/**
	 * @param context
	 * @return value of EMPLNo
	 */
	public final java.lang.Long getEMPLNo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.EMPLNo.toString());
	}

	/**
	 * Set value of EMPLNo
	 * @param emplno
	 */
	public final void setEMPLNo(java.lang.Long emplno)
	{
		setEMPLNo(getContext(), emplno);
	}

	/**
	 * Set value of EMPLNo
	 * @param context
	 * @param emplno
	 */
	public final void setEMPLNo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long emplno)
	{
		getMendixObject().setValue(context, MemberNames.EMPLNo.toString(), emplno);
	}

	/**
	 * @return value of RequireCount
	 */
	public final java.lang.Integer getRequireCount()
	{
		return getRequireCount(getContext());
	}

	/**
	 * @param context
	 * @return value of RequireCount
	 */
	public final java.lang.Integer getRequireCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RequireCount.toString());
	}

	/**
	 * Set value of RequireCount
	 * @param requirecount
	 */
	public final void setRequireCount(java.lang.Integer requirecount)
	{
		setRequireCount(getContext(), requirecount);
	}

	/**
	 * Set value of RequireCount
	 * @param context
	 * @param requirecount
	 */
	public final void setRequireCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer requirecount)
	{
		getMendixObject().setValue(context, MemberNames.RequireCount.toString(), requirecount);
	}

	/**
	 * @return value of ExecuteCount
	 */
	public final java.lang.Integer getExecuteCount()
	{
		return getExecuteCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ExecuteCount
	 */
	public final java.lang.Integer getExecuteCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ExecuteCount.toString());
	}

	/**
	 * Set value of ExecuteCount
	 * @param executecount
	 */
	public final void setExecuteCount(java.lang.Integer executecount)
	{
		setExecuteCount(getContext(), executecount);
	}

	/**
	 * Set value of ExecuteCount
	 * @param context
	 * @param executecount
	 */
	public final void setExecuteCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer executecount)
	{
		getMendixObject().setValue(context, MemberNames.ExecuteCount.toString(), executecount);
	}

	/**
	 * @return value of Worktime
	 */
	public final java.lang.Integer getWorktime()
	{
		return getWorktime(getContext());
	}

	/**
	 * @param context
	 * @return value of Worktime
	 */
	public final java.lang.Integer getWorktime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Worktime.toString());
	}

	/**
	 * Set value of Worktime
	 * @param worktime
	 */
	public final void setWorktime(java.lang.Integer worktime)
	{
		setWorktime(getContext(), worktime);
	}

	/**
	 * Set value of Worktime
	 * @param context
	 * @param worktime
	 */
	public final void setWorktime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer worktime)
	{
		getMendixObject().setValue(context, MemberNames.Worktime.toString(), worktime);
	}

	/**
	 * @return value of SNSCheck
	 */
	public final java.lang.Boolean getSNSCheck()
	{
		return getSNSCheck(getContext());
	}

	/**
	 * @param context
	 * @return value of SNSCheck
	 */
	public final java.lang.Boolean getSNSCheck(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SNSCheck.toString());
	}

	/**
	 * Set value of SNSCheck
	 * @param snscheck
	 */
	public final void setSNSCheck(java.lang.Boolean snscheck)
	{
		setSNSCheck(getContext(), snscheck);
	}

	/**
	 * Set value of SNSCheck
	 * @param context
	 * @param snscheck
	 */
	public final void setSNSCheck(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean snscheck)
	{
		getMendixObject().setValue(context, MemberNames.SNSCheck.toString(), snscheck);
	}

	/**
	 * @return value of EmailCheck
	 */
	public final java.lang.Boolean getEmailCheck()
	{
		return getEmailCheck(getContext());
	}

	/**
	 * @param context
	 * @return value of EmailCheck
	 */
	public final java.lang.Boolean getEmailCheck(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EmailCheck.toString());
	}

	/**
	 * Set value of EmailCheck
	 * @param emailcheck
	 */
	public final void setEmailCheck(java.lang.Boolean emailcheck)
	{
		setEmailCheck(getContext(), emailcheck);
	}

	/**
	 * Set value of EmailCheck
	 * @param context
	 * @param emailcheck
	 */
	public final void setEmailCheck(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean emailcheck)
	{
		getMendixObject().setValue(context, MemberNames.EmailCheck.toString(), emailcheck);
	}

	/**
	 * @return value of EmployeeFullName
	 */
	public final java.lang.String getEmployeeFullName()
	{
		return getEmployeeFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeFullName
	 */
	public final java.lang.String getEmployeeFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeFullName.toString());
	}

	/**
	 * Set value of EmployeeFullName
	 * @param employeefullname
	 */
	public final void setEmployeeFullName(java.lang.String employeefullname)
	{
		setEmployeeFullName(getContext(), employeefullname);
	}

	/**
	 * Set value of EmployeeFullName
	 * @param context
	 * @param employeefullname
	 */
	public final void setEmployeeFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeefullname)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeFullName.toString(), employeefullname);
	}

	/**
	 * @return value of EmployeeActive
	 */
	public final java.lang.Boolean getEmployeeActive()
	{
		return getEmployeeActive(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeActive
	 */
	public final java.lang.Boolean getEmployeeActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EmployeeActive.toString());
	}

	/**
	 * Set value of EmployeeActive
	 * @param employeeactive
	 */
	public final void setEmployeeActive(java.lang.Boolean employeeactive)
	{
		setEmployeeActive(getContext(), employeeactive);
	}

	/**
	 * Set value of EmployeeActive
	 * @param context
	 * @param employeeactive
	 */
	public final void setEmployeeActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean employeeactive)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeActive.toString(), employeeactive);
	}

	/**
	 * @return value of EmployeeEmail
	 */
	public final java.lang.String getEmployeeEmail()
	{
		return getEmployeeEmail(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeEmail
	 */
	public final java.lang.String getEmployeeEmail(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EmployeeEmail.toString());
	}

	/**
	 * Set value of EmployeeEmail
	 * @param employeeemail
	 */
	public final void setEmployeeEmail(java.lang.String employeeemail)
	{
		setEmployeeEmail(getContext(), employeeemail);
	}

	/**
	 * Set value of EmployeeEmail
	 * @param context
	 * @param employeeemail
	 */
	public final void setEmployeeEmail(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String employeeemail)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeEmail.toString(), employeeemail);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Department
	 */
	public final cmms_administration.proxies.Department getEmployee_Department() throws com.mendix.core.CoreException
	{
		return getEmployee_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Department getEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Department.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Department
	 * @param employee_department
	 */
	public final void setEmployee_Department(cmms_administration.proxies.Department employee_department)
	{
		setEmployee_Department(getContext(), employee_department);
	}

	/**
	 * Set value of Employee_Department
	 * @param context
	 * @param employee_department
	 */
	public final void setEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Department employee_department)
	{
		if (employee_department == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), employee_department.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_ProfilePhoto
	 */
	public final cmms_administration.proxies.ProfilePhoto getEmployee_ProfilePhoto() throws com.mendix.core.CoreException
	{
		return getEmployee_ProfilePhoto(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_ProfilePhoto
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.ProfilePhoto getEmployee_ProfilePhoto(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.ProfilePhoto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_ProfilePhoto.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.ProfilePhoto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_ProfilePhoto
	 * @param employee_profilephoto
	 */
	public final void setEmployee_ProfilePhoto(cmms_administration.proxies.ProfilePhoto employee_profilephoto)
	{
		setEmployee_ProfilePhoto(getContext(), employee_profilephoto);
	}

	/**
	 * Set value of Employee_ProfilePhoto
	 * @param context
	 * @param employee_profilephoto
	 */
	public final void setEmployee_ProfilePhoto(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.ProfilePhoto employee_profilephoto)
	{
		if (employee_profilephoto == null) {
			getMendixObject().setValue(context, MemberNames.Employee_ProfilePhoto.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_ProfilePhoto.toString(), employee_profilephoto.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Plant
	 */
	public final cmms_administration.proxies.Plant getEmployee_Plant() throws com.mendix.core.CoreException
	{
		return getEmployee_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getEmployee_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Plant
	 * @param employee_plant
	 */
	public final void setEmployee_Plant(cmms_administration.proxies.Plant employee_plant)
	{
		setEmployee_Plant(getContext(), employee_plant);
	}

	/**
	 * Set value of Employee_Plant
	 * @param context
	 * @param employee_plant
	 */
	public final void setEmployee_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant employee_plant)
	{
		if (employee_plant == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Plant.toString(), employee_plant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_sign
	 */
	public final cmms_administration.proxies.ProfilePhoto getEmployee_sign() throws com.mendix.core.CoreException
	{
		return getEmployee_sign(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_sign
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.ProfilePhoto getEmployee_sign(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.ProfilePhoto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_sign.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.ProfilePhoto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_sign
	 * @param employee_sign
	 */
	public final void setEmployee_sign(cmms_administration.proxies.ProfilePhoto employee_sign)
	{
		setEmployee_sign(getContext(), employee_sign);
	}

	/**
	 * Set value of Employee_sign
	 * @param context
	 * @param employee_sign
	 */
	public final void setEmployee_sign(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.ProfilePhoto employee_sign)
	{
		if (employee_sign == null) {
			getMendixObject().setValue(context, MemberNames.Employee_sign.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_sign.toString(), employee_sign.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Seal
	 */
	public final cmms_administration.proxies.ProfilePhoto getEmployee_Seal() throws com.mendix.core.CoreException
	{
		return getEmployee_Seal(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Seal
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.ProfilePhoto getEmployee_Seal(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.ProfilePhoto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Seal.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.ProfilePhoto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Seal
	 * @param employee_seal
	 */
	public final void setEmployee_Seal(cmms_administration.proxies.ProfilePhoto employee_seal)
	{
		setEmployee_Seal(getContext(), employee_seal);
	}

	/**
	 * Set value of Employee_Seal
	 * @param context
	 * @param employee_seal
	 */
	public final void setEmployee_Seal(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.ProfilePhoto employee_seal)
	{
		if (employee_seal == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Seal.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Seal.toString(), employee_seal.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Employeehelper
	 */
	public final cmms_administration.proxies.Employeehelper getEmployee_Employeehelper() throws com.mendix.core.CoreException
	{
		return getEmployee_Employeehelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Employeehelper
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employeehelper getEmployee_Employeehelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employeehelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Employeehelper.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employeehelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Employeehelper
	 * @param employee_employeehelper
	 */
	public final void setEmployee_Employeehelper(cmms_administration.proxies.Employeehelper employee_employeehelper)
	{
		setEmployee_Employeehelper(getContext(), employee_employeehelper);
	}

	/**
	 * Set value of Employee_Employeehelper
	 * @param context
	 * @param employee_employeehelper
	 */
	public final void setEmployee_Employeehelper(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employeehelper employee_employeehelper)
	{
		if (employee_employeehelper == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Employeehelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Employeehelper.toString(), employee_employeehelper.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Account
	 */
	public final administration.proxies.Account getEmployee_Account() throws com.mendix.core.CoreException
	{
		return getEmployee_Account(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Account
	 * @throws com.mendix.core.CoreException
	 */
	public final administration.proxies.Account getEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		administration.proxies.Account result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Account.toString());
		if (identifier != null) {
			result = administration.proxies.Account.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Account
	 * @param employee_account
	 */
	public final void setEmployee_Account(administration.proxies.Account employee_account)
	{
		setEmployee_Account(getContext(), employee_account);
	}

	/**
	 * Set value of Employee_Account
	 * @param context
	 * @param employee_account
	 */
	public final void setEmployee_Account(com.mendix.systemwideinterfaces.core.IContext context, administration.proxies.Account employee_account)
	{
		if (employee_account == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Account.toString(), employee_account.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmployeeOutsourcing_StandardCode
	 */
	public final commons.proxies.StandardCode getEmployeeOutsourcing_StandardCode() throws com.mendix.core.CoreException
	{
		return getEmployeeOutsourcing_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeOutsourcing_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getEmployeeOutsourcing_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmployeeOutsourcing_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmployeeOutsourcing_StandardCode
	 * @param employeeoutsourcing_standardcode
	 */
	public final void setEmployeeOutsourcing_StandardCode(commons.proxies.StandardCode employeeoutsourcing_standardcode)
	{
		setEmployeeOutsourcing_StandardCode(getContext(), employeeoutsourcing_standardcode);
	}

	/**
	 * Set value of EmployeeOutsourcing_StandardCode
	 * @param context
	 * @param employeeoutsourcing_standardcode
	 */
	public final void setEmployeeOutsourcing_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode employeeoutsourcing_standardcode)
	{
		if (employeeoutsourcing_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.EmployeeOutsourcing_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmployeeOutsourcing_StandardCode.toString(), employeeoutsourcing_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmployeeLog_StandardCode
	 */
	public final commons.proxies.StandardCode getEmployeeLog_StandardCode() throws com.mendix.core.CoreException
	{
		return getEmployeeLog_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeLog_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getEmployeeLog_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmployeeLog_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmployeeLog_StandardCode
	 * @param employeelog_standardcode
	 */
	public final void setEmployeeLog_StandardCode(commons.proxies.StandardCode employeelog_standardcode)
	{
		setEmployeeLog_StandardCode(getContext(), employeelog_standardcode);
	}

	/**
	 * Set value of EmployeeLog_StandardCode
	 * @param context
	 * @param employeelog_standardcode
	 */
	public final void setEmployeeLog_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode employeelog_standardcode)
	{
		if (employeelog_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.EmployeeLog_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmployeeLog_StandardCode.toString(), employeelog_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Position_StandardCode
	 */
	public final commons.proxies.StandardCode getPosition_StandardCode() throws com.mendix.core.CoreException
	{
		return getPosition_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Position_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getPosition_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Position_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Position_StandardCode
	 * @param position_standardcode
	 */
	public final void setPosition_StandardCode(commons.proxies.StandardCode position_standardcode)
	{
		setPosition_StandardCode(getContext(), position_standardcode);
	}

	/**
	 * Set value of Position_StandardCode
	 * @param context
	 * @param position_standardcode
	 */
	public final void setPosition_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode position_standardcode)
	{
		if (position_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Position_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Position_StandardCode.toString(), position_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Duty_StandardCode
	 */
	public final commons.proxies.StandardCode getDuty_StandardCode() throws com.mendix.core.CoreException
	{
		return getDuty_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Duty_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getDuty_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Duty_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Duty_StandardCode
	 * @param duty_standardcode
	 */
	public final void setDuty_StandardCode(commons.proxies.StandardCode duty_standardcode)
	{
		setDuty_StandardCode(getContext(), duty_standardcode);
	}

	/**
	 * Set value of Duty_StandardCode
	 * @param context
	 * @param duty_standardcode
	 */
	public final void setDuty_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode duty_standardcode)
	{
		if (duty_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Duty_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Duty_StandardCode.toString(), duty_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmployeeFunction_StandardCode
	 */
	public final commons.proxies.StandardCode getEmployeeFunction_StandardCode() throws com.mendix.core.CoreException
	{
		return getEmployeeFunction_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeFunction_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getEmployeeFunction_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmployeeFunction_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmployeeFunction_StandardCode
	 * @param employeefunction_standardcode
	 */
	public final void setEmployeeFunction_StandardCode(commons.proxies.StandardCode employeefunction_standardcode)
	{
		setEmployeeFunction_StandardCode(getContext(), employeefunction_standardcode);
	}

	/**
	 * Set value of EmployeeFunction_StandardCode
	 * @param context
	 * @param employeefunction_standardcode
	 */
	public final void setEmployeeFunction_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode employeefunction_standardcode)
	{
		if (employeefunction_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.EmployeeFunction_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmployeeFunction_StandardCode.toString(), employeefunction_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EmployeeWorkStatus_StandardCode
	 */
	public final commons.proxies.StandardCode getEmployeeWorkStatus_StandardCode() throws com.mendix.core.CoreException
	{
		return getEmployeeWorkStatus_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeWorkStatus_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getEmployeeWorkStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EmployeeWorkStatus_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EmployeeWorkStatus_StandardCode
	 * @param employeeworkstatus_standardcode
	 */
	public final void setEmployeeWorkStatus_StandardCode(commons.proxies.StandardCode employeeworkstatus_standardcode)
	{
		setEmployeeWorkStatus_StandardCode(getContext(), employeeworkstatus_standardcode);
	}

	/**
	 * Set value of EmployeeWorkStatus_StandardCode
	 * @param context
	 * @param employeeworkstatus_standardcode
	 */
	public final void setEmployeeWorkStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode employeeworkstatus_standardcode)
	{
		if (employeeworkstatus_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.EmployeeWorkStatus_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EmployeeWorkStatus_StandardCode.toString(), employeeworkstatus_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Equipment
	 */
	public final java.util.List<equipment_management.proxies.Equipment> getEmployee_Equipment() throws com.mendix.core.CoreException
	{
		return getEmployee_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<equipment_management.proxies.Equipment> getEmployee_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<equipment_management.proxies.Equipment> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Employee_Equipment.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(equipment_management.proxies.Equipment.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Employee_Equipment
	 * @param employee_equipment
	 */
	public final void setEmployee_Equipment(java.util.List<equipment_management.proxies.Equipment> employee_equipment)
	{
		setEmployee_Equipment(getContext(), employee_equipment);
	}

	/**
	 * Set value of Employee_Equipment
	 * @param context
	 * @param employee_equipment
	 */
	public final void setEmployee_Equipment(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<equipment_management.proxies.Equipment> employee_equipment)
	{
		var identifiers = employee_equipment
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Employee_Equipment.toString(), identifiers);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cmms_administration.proxies.Employee that = (cmms_administration.proxies.Employee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
