// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmms_administration.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/08/30
 * 최종 수정자 :
 * 최종 수정일 :
 * 설명 : 임직원 정보를 담는 엔터티
 * Version 1.0 : 생성
 */
public class ProfilePhoto extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMMS_Administration.ProfilePhoto";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ImageName("ImageName"),
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		Employee_ProfilePhoto("CMMS_Administration.Employee_ProfilePhoto"),
		Employee_sign("CMMS_Administration.Employee_sign"),
		Employee_Seal("CMMS_Administration.Employee_Seal");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ProfilePhoto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ProfilePhoto(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject profilePhotoMendixObject)
	{
		super(context, profilePhotoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, profilePhotoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cmms_administration.proxies.ProfilePhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cmms_administration.proxies.ProfilePhoto(context, mendixObject);
	}

	public static cmms_administration.proxies.ProfilePhoto load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cmms_administration.proxies.ProfilePhoto.initialize(context, mendixObject);
	}

	public static java.util.List<cmms_administration.proxies.ProfilePhoto> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> cmms_administration.proxies.ProfilePhoto.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName()
	{
		return getImageName(getContext());
	}

	/**
	 * @param context
	 * @return value of ImageName
	 */
	public final java.lang.String getImageName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ImageName.toString());
	}

	/**
	 * Set value of ImageName
	 * @param imagename
	 */
	public final void setImageName(java.lang.String imagename)
	{
		setImageName(getContext(), imagename);
	}

	/**
	 * Set value of ImageName
	 * @param context
	 * @param imagename
	 */
	public final void setImageName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String imagename)
	{
		getMendixObject().setValue(context, MemberNames.ImageName.toString(), imagename);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_ProfilePhoto
	 */
	public final cmms_administration.proxies.Employee getEmployee_ProfilePhoto() throws com.mendix.core.CoreException
	{
		return getEmployee_ProfilePhoto(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_ProfilePhoto
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getEmployee_ProfilePhoto(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_ProfilePhoto.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_ProfilePhoto
	 * @param employee_profilephoto
	 */
	public final void setEmployee_ProfilePhoto(cmms_administration.proxies.Employee employee_profilephoto)
	{
		setEmployee_ProfilePhoto(getContext(), employee_profilephoto);
	}

	/**
	 * Set value of Employee_ProfilePhoto
	 * @param context
	 * @param employee_profilephoto
	 */
	public final void setEmployee_ProfilePhoto(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee employee_profilephoto)
	{
		if (employee_profilephoto == null) {
			getMendixObject().setValue(context, MemberNames.Employee_ProfilePhoto.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_ProfilePhoto.toString(), employee_profilephoto.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_sign
	 */
	public final cmms_administration.proxies.Employee getEmployee_sign() throws com.mendix.core.CoreException
	{
		return getEmployee_sign(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_sign
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getEmployee_sign(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_sign.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_sign
	 * @param employee_sign
	 */
	public final void setEmployee_sign(cmms_administration.proxies.Employee employee_sign)
	{
		setEmployee_sign(getContext(), employee_sign);
	}

	/**
	 * Set value of Employee_sign
	 * @param context
	 * @param employee_sign
	 */
	public final void setEmployee_sign(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee employee_sign)
	{
		if (employee_sign == null) {
			getMendixObject().setValue(context, MemberNames.Employee_sign.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_sign.toString(), employee_sign.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Employee_Seal
	 */
	public final cmms_administration.proxies.Employee getEmployee_Seal() throws com.mendix.core.CoreException
	{
		return getEmployee_Seal(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Seal
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getEmployee_Seal(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Seal.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Employee_Seal
	 * @param employee_seal
	 */
	public final void setEmployee_Seal(cmms_administration.proxies.Employee employee_seal)
	{
		setEmployee_Seal(getContext(), employee_seal);
	}

	/**
	 * Set value of Employee_Seal
	 * @param context
	 * @param employee_seal
	 */
	public final void setEmployee_Seal(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee employee_seal)
	{
		if (employee_seal == null) {
			getMendixObject().setValue(context, MemberNames.Employee_Seal.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Employee_Seal.toString(), employee_seal.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cmms_administration.proxies.ProfilePhoto that = (cmms_administration.proxies.ProfilePhoto) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
