// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmms_administration.proxies;

public class UserSearchHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject userSearchHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "CMMS_Administration.UserSearchHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UserName("UserName"),
		UserSearchHelper_Department("CMMS_Administration.UserSearchHelper_Department");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UserSearchHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UserSearchHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject userSearchHelperMendixObject)
	{
		if (userSearchHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, userSearchHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.userSearchHelperMendixObject = userSearchHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static cmms_administration.proxies.UserSearchHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new cmms_administration.proxies.UserSearchHelper(context, mendixObject);
	}

	public static cmms_administration.proxies.UserSearchHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return cmms_administration.proxies.UserSearchHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of UserName
	 */
	public final java.lang.String getUserName()
	{
		return getUserName(getContext());
	}

	/**
	 * @param context
	 * @return value of UserName
	 */
	public final java.lang.String getUserName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UserName.toString());
	}

	/**
	 * Set value of UserName
	 * @param username
	 */
	public final void setUserName(java.lang.String username)
	{
		setUserName(getContext(), username);
	}

	/**
	 * Set value of UserName
	 * @param context
	 * @param username
	 */
	public final void setUserName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String username)
	{
		getMendixObject().setValue(context, MemberNames.UserName.toString(), username);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UserSearchHelper_Department
	 */
	public final cmms_administration.proxies.Department getUserSearchHelper_Department() throws com.mendix.core.CoreException
	{
		return getUserSearchHelper_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of UserSearchHelper_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Department getUserSearchHelper_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UserSearchHelper_Department.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UserSearchHelper_Department
	 * @param usersearchhelper_department
	 */
	public final void setUserSearchHelper_Department(cmms_administration.proxies.Department usersearchhelper_department)
	{
		setUserSearchHelper_Department(getContext(), usersearchhelper_department);
	}

	/**
	 * Set value of UserSearchHelper_Department
	 * @param context
	 * @param usersearchhelper_department
	 */
	public final void setUserSearchHelper_Department(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Department usersearchhelper_department)
	{
		if (usersearchhelper_department == null) {
			getMendixObject().setValue(context, MemberNames.UserSearchHelper_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UserSearchHelper_Department.toString(), usersearchhelper_department.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return userSearchHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final cmms_administration.proxies.UserSearchHelper that = (cmms_administration.proxies.UserSearchHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
