// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/05
 * 최종 수정자 : 
 * 최종 수정일 :
 * 설명 : Menu 클릭 시 해당하는 페이지를 지정해줄 수 있게 하는 Enum
 * V 0.1 : 최초 작성
 */
public enum Menu_Move_To_Report
{
	Report_Equipment_Maintenance_Status(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비 보전 현황 (경영자 정보)" } }),
	Report_Maintenance_Cost_Analysis(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "보전 비용 분석" } }),
	Report_Work_Order_Analysis(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업 건수 분석" } }),
	Report_Analysis_by_Failure_Type(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "고장 유형별 분석" } }),
	Report_Analysis_by_Failure_Cause(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "고장 원인별 분석" } }),
	Report_MTBF_Analysis(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "MTBF 분석" } }),
	Report_MTTR_Analysis(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "MTTR 분석" } }),
	Report_Failure_Rate(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "고장율" } }),
	Report_Repair_Rate(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "수리율" } }),
	Report_Equipment_Utilization_Rate(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비 가동율" } }),
	Report_Production_Operating_Rate(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "생산 가동율" } }),
	Report_Downtime_Analysis(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "정지 시간 분석" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Menu_Move_To_Report(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
