// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/05
 * 최종 수정자 : 
 * 최종 수정일 :
 * 설명 : Menu 클릭 시 해당하는 페이지를 지정해줄 수 있게 하는 Enum
 * V 0.1 : 최초 작성
 */
public enum Menu_Move_To_EDMS
{
	EDMS_Electronic_Document_Management(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "전자 문서 관리" } }),
	EDMS_Electronic_Document_Query(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "전자 문서 조회" } }),
	EDMS_EDM_Type_Tree(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "문서 분류 트리" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Menu_Move_To_EDMS(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
