// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/05
 * 최종 수정자 : 
 * 최종 수정일 :
 * 설명 : Menu 클릭 시 해당하는 페이지를 지정해줄 수 있게 하는 Enum
 * V 0.1 : 최초 작성
 */
public enum Menu_Move_To_Work_Management
{
	Work_Management_Work_Request(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업 요청" } }),
	Work_Management_Request_Approval(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "요청 승인" } }),
	Work_Management_Routine_Maiatenance(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "정기 보전" } }),
	Work_Management_Work_Assignment(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업 배정" } }),
	Work_Management_Work_Result_Regisration(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업 결과 등록" } }),
	Work_Management_Work_Completion(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업 완료 처리" } }),
	Work_Management_Work_History_Query(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업 이력 조회" } }),
	Work_Management_Work_Log(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업 일지 관리" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Menu_Move_To_Work_Management(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
