// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/06
 * 최종 수정자 : 
 * 최종 수정일 : 2023/09/06
 * 설명 : 모듈 결정용 Enum
 * Version 1.0 : 생성
 */
public enum Menu_Module
{
	Equipment_Check_Management(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "예방 점검 관리" } }),
	Work_Management(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "보전 작업 관리" } }),
	Check_History_Management(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "점검 일지 관리" } }),
	Monitoring(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "모니터링" } }),
	Equipment_Management(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비 정보 관리" } }),
	Material_Management(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "보전 자재 관리" } }),
	EDMS(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "전자 문서 관리 시스템" } }),
	Report(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "리포트" } }),
	CMMS_Administration(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "시스템관리" } }),
	SQL2008(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "SQL2008" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Menu_Module(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
