// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/05
 * 최종 수정자 : 
 * 최종 수정일 :
 * 설명 : Menu 클릭 시 해당하는 페이지를 지정해줄 수 있게 하는 Enum
 * V 0.1 : 최초 작성
 */
public enum Menu_Move_To_SQL2008
{
	SQL2008_Configuration_Settings(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "환경 설정 (회사, 다국어)" } }),
	CodeType_Settings(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "기준 코드 타입 설정" } }),
	SQL2008_Menu_Management(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "메뉴 관리" } }),
	SQL2008_Menu_by_Permission(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "권한별 메뉴" } }),
	SQL2008_Popup_Menu(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "팝업 메뉴 관리" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Menu_Move_To_SQL2008(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
