// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/05
 * 최종 수정자 : 
 * 최종 수정일 :
 * 설명 : Menu 클릭 시 해당하는 페이지를 지정해줄 수 있게 하는 Enum
 * V 0.1 : 최초 작성
 */
public enum Menu_Move_To_Equipment_Management
{
	Equipment_Management_Equipment_Information_Query(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비 정보 조회" } }),
	Equipment_Management_Equipment_BOM(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비별 자재 구성 관리(BOM)" } }),
	Equipment_Management_Equipment_Movement_History(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비 이동 관리" } }),
	Equipment_Management_Equipment_Master(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비 마스터" } }),
	Equipment_Management_Equipment_Image_Registration(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "설비 사진 등록" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private Menu_Move_To_Equipment_Management(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
