// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies;

/**
 * 최초 작성자 : 김동명
 * 최초 작성일 : 2023/09/05
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/06
 * 설명 : Topbar의 메뉴를 구성하기 위한 Entity
 * Version 1.1 : 엔터티 권한 설정 (Admin & Developer 권한 RW , 나머지 권한 R) // 이단비
 * Version 1.0 : 생성
 */
public class Menu implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject menuMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Development_Settings.Menu";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MenuName("MenuName"),
		ParentName("ParentName"),
		MenuNumber("MenuNumber"),
		MenuOrder("MenuOrder"),
		MenuNote("MenuNote"),
		Active("Active"),
		TitleMenu("TitleMenu"),
		MenuModule("MenuModule"),
		MenuMoveToCheckHistoryManagement("MenuMoveToCheckHistoryManagement"),
		MenuMoveToCMMSAdministration("MenuMoveToCMMSAdministration"),
		MenuMoveToEDMS("MenuMoveToEDMS"),
		MenuMoveToEquipmentCheckManagement("MenuMoveToEquipmentCheckManagement"),
		MenuMoveToEquipmentManagement("MenuMoveToEquipmentManagement"),
		MenuMoveToMaterialManagement("MenuMoveToMaterialManagement"),
		MenuMoveToMonitoring("MenuMoveToMonitoring"),
		MenuMoveToReport("MenuMoveToReport"),
		MenuMoveToSQL2008("MenuMoveToSQL2008"),
		MenuMoveToWorkManagement("MenuMoveToWorkManagement"),
		_Root("_Root"),
		_Haschild("_Haschild"),
		Menu_Menu("Development_Settings.Menu_Menu"),
		Menu_MenuHelper("Development_Settings.Menu_MenuHelper"),
		Menu_MenuHelperChild("Development_Settings.Menu_MenuHelperChild"),
		MenuChilden("Development_Settings.MenuChilden"),
		Menu_StandardCode("Development_Settings.Menu_StandardCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Menu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Menu(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject menuMendixObject)
	{
		if (menuMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, menuMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.menuMendixObject = menuMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static development_settings.proxies.Menu initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new development_settings.proxies.Menu(context, mendixObject);
	}

	public static development_settings.proxies.Menu load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return development_settings.proxies.Menu.initialize(context, mendixObject);
	}

	public static java.util.List<development_settings.proxies.Menu> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> development_settings.proxies.Menu.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MenuName
	 */
	public final java.lang.String getMenuName()
	{
		return getMenuName(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuName
	 */
	public final java.lang.String getMenuName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MenuName.toString());
	}

	/**
	 * Set value of MenuName
	 * @param menuname
	 */
	public final void setMenuName(java.lang.String menuname)
	{
		setMenuName(getContext(), menuname);
	}

	/**
	 * Set value of MenuName
	 * @param context
	 * @param menuname
	 */
	public final void setMenuName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String menuname)
	{
		getMendixObject().setValue(context, MemberNames.MenuName.toString(), menuname);
	}

	/**
	 * @return value of ParentName
	 */
	public final java.lang.String getParentName()
	{
		return getParentName(getContext());
	}

	/**
	 * @param context
	 * @return value of ParentName
	 */
	public final java.lang.String getParentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ParentName.toString());
	}

	/**
	 * Set value of ParentName
	 * @param parentname
	 */
	public final void setParentName(java.lang.String parentname)
	{
		setParentName(getContext(), parentname);
	}

	/**
	 * Set value of ParentName
	 * @param context
	 * @param parentname
	 */
	public final void setParentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String parentname)
	{
		getMendixObject().setValue(context, MemberNames.ParentName.toString(), parentname);
	}

	/**
	 * @return value of MenuNumber
	 */
	public final java.lang.Integer getMenuNumber()
	{
		return getMenuNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuNumber
	 */
	public final java.lang.Integer getMenuNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MenuNumber.toString());
	}

	/**
	 * Set value of MenuNumber
	 * @param menunumber
	 */
	public final void setMenuNumber(java.lang.Integer menunumber)
	{
		setMenuNumber(getContext(), menunumber);
	}

	/**
	 * Set value of MenuNumber
	 * @param context
	 * @param menunumber
	 */
	public final void setMenuNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer menunumber)
	{
		getMendixObject().setValue(context, MemberNames.MenuNumber.toString(), menunumber);
	}

	/**
	 * @return value of MenuOrder
	 */
	public final java.lang.Integer getMenuOrder()
	{
		return getMenuOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuOrder
	 */
	public final java.lang.Integer getMenuOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.MenuOrder.toString());
	}

	/**
	 * Set value of MenuOrder
	 * @param menuorder
	 */
	public final void setMenuOrder(java.lang.Integer menuorder)
	{
		setMenuOrder(getContext(), menuorder);
	}

	/**
	 * Set value of MenuOrder
	 * @param context
	 * @param menuorder
	 */
	public final void setMenuOrder(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer menuorder)
	{
		getMendixObject().setValue(context, MemberNames.MenuOrder.toString(), menuorder);
	}

	/**
	 * @return value of MenuNote
	 */
	public final java.lang.String getMenuNote()
	{
		return getMenuNote(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuNote
	 */
	public final java.lang.String getMenuNote(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MenuNote.toString());
	}

	/**
	 * Set value of MenuNote
	 * @param menunote
	 */
	public final void setMenuNote(java.lang.String menunote)
	{
		setMenuNote(getContext(), menunote);
	}

	/**
	 * Set value of MenuNote
	 * @param context
	 * @param menunote
	 */
	public final void setMenuNote(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String menunote)
	{
		getMendixObject().setValue(context, MemberNames.MenuNote.toString(), menunote);
	}

	/**
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive()
	{
		return getActive(getContext());
	}

	/**
	 * @param context
	 * @return value of Active
	 */
	public final java.lang.Boolean getActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Active.toString());
	}

	/**
	 * Set value of Active
	 * @param active
	 */
	public final void setActive(java.lang.Boolean active)
	{
		setActive(getContext(), active);
	}

	/**
	 * Set value of Active
	 * @param context
	 * @param active
	 */
	public final void setActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean active)
	{
		getMendixObject().setValue(context, MemberNames.Active.toString(), active);
	}

	/**
	 * @return value of TitleMenu
	 */
	public final java.lang.Boolean getTitleMenu()
	{
		return getTitleMenu(getContext());
	}

	/**
	 * @param context
	 * @return value of TitleMenu
	 */
	public final java.lang.Boolean getTitleMenu(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.TitleMenu.toString());
	}

	/**
	 * Set value of TitleMenu
	 * @param titlemenu
	 */
	public final void setTitleMenu(java.lang.Boolean titlemenu)
	{
		setTitleMenu(getContext(), titlemenu);
	}

	/**
	 * Set value of TitleMenu
	 * @param context
	 * @param titlemenu
	 */
	public final void setTitleMenu(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean titlemenu)
	{
		getMendixObject().setValue(context, MemberNames.TitleMenu.toString(), titlemenu);
	}

	/**
	 * Get value of MenuModule
	 * @param menumodule
	 */
	public final development_settings.proxies.Menu_Module getMenuModule()
	{
		return getMenuModule(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuModule
	 */
	public final development_settings.proxies.Menu_Module getMenuModule(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuModule.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Module.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuModule
	 * @param menumodule
	 */
	public final void setMenuModule(development_settings.proxies.Menu_Module menumodule)
	{
		setMenuModule(getContext(), menumodule);
	}

	/**
	 * Set value of MenuModule
	 * @param context
	 * @param menumodule
	 */
	public final void setMenuModule(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Module menumodule)
	{
		if (menumodule != null) {
			getMendixObject().setValue(context, MemberNames.MenuModule.toString(), menumodule.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuModule.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToCheckHistoryManagement
	 * @param menumovetocheckhistorymanagement
	 */
	public final development_settings.proxies.Menu_Move_To_Check_History_Management getMenuMoveToCheckHistoryManagement()
	{
		return getMenuMoveToCheckHistoryManagement(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToCheckHistoryManagement
	 */
	public final development_settings.proxies.Menu_Move_To_Check_History_Management getMenuMoveToCheckHistoryManagement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToCheckHistoryManagement.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_Check_History_Management.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToCheckHistoryManagement
	 * @param menumovetocheckhistorymanagement
	 */
	public final void setMenuMoveToCheckHistoryManagement(development_settings.proxies.Menu_Move_To_Check_History_Management menumovetocheckhistorymanagement)
	{
		setMenuMoveToCheckHistoryManagement(getContext(), menumovetocheckhistorymanagement);
	}

	/**
	 * Set value of MenuMoveToCheckHistoryManagement
	 * @param context
	 * @param menumovetocheckhistorymanagement
	 */
	public final void setMenuMoveToCheckHistoryManagement(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_Check_History_Management menumovetocheckhistorymanagement)
	{
		if (menumovetocheckhistorymanagement != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToCheckHistoryManagement.toString(), menumovetocheckhistorymanagement.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToCheckHistoryManagement.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToCMMSAdministration
	 * @param menumovetocmmsadministration
	 */
	public final development_settings.proxies.Menu_Move_To_CMMS_Administration getMenuMoveToCMMSAdministration()
	{
		return getMenuMoveToCMMSAdministration(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToCMMSAdministration
	 */
	public final development_settings.proxies.Menu_Move_To_CMMS_Administration getMenuMoveToCMMSAdministration(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToCMMSAdministration.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_CMMS_Administration.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToCMMSAdministration
	 * @param menumovetocmmsadministration
	 */
	public final void setMenuMoveToCMMSAdministration(development_settings.proxies.Menu_Move_To_CMMS_Administration menumovetocmmsadministration)
	{
		setMenuMoveToCMMSAdministration(getContext(), menumovetocmmsadministration);
	}

	/**
	 * Set value of MenuMoveToCMMSAdministration
	 * @param context
	 * @param menumovetocmmsadministration
	 */
	public final void setMenuMoveToCMMSAdministration(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_CMMS_Administration menumovetocmmsadministration)
	{
		if (menumovetocmmsadministration != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToCMMSAdministration.toString(), menumovetocmmsadministration.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToCMMSAdministration.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToEDMS
	 * @param menumovetoedms
	 */
	public final development_settings.proxies.Menu_Move_To_EDMS getMenuMoveToEDMS()
	{
		return getMenuMoveToEDMS(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToEDMS
	 */
	public final development_settings.proxies.Menu_Move_To_EDMS getMenuMoveToEDMS(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToEDMS.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_EDMS.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToEDMS
	 * @param menumovetoedms
	 */
	public final void setMenuMoveToEDMS(development_settings.proxies.Menu_Move_To_EDMS menumovetoedms)
	{
		setMenuMoveToEDMS(getContext(), menumovetoedms);
	}

	/**
	 * Set value of MenuMoveToEDMS
	 * @param context
	 * @param menumovetoedms
	 */
	public final void setMenuMoveToEDMS(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_EDMS menumovetoedms)
	{
		if (menumovetoedms != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToEDMS.toString(), menumovetoedms.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToEDMS.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToEquipmentCheckManagement
	 * @param menumovetoequipmentcheckmanagement
	 */
	public final development_settings.proxies.Menu_Move_To_Equipment_Check_Management getMenuMoveToEquipmentCheckManagement()
	{
		return getMenuMoveToEquipmentCheckManagement(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToEquipmentCheckManagement
	 */
	public final development_settings.proxies.Menu_Move_To_Equipment_Check_Management getMenuMoveToEquipmentCheckManagement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToEquipmentCheckManagement.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_Equipment_Check_Management.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToEquipmentCheckManagement
	 * @param menumovetoequipmentcheckmanagement
	 */
	public final void setMenuMoveToEquipmentCheckManagement(development_settings.proxies.Menu_Move_To_Equipment_Check_Management menumovetoequipmentcheckmanagement)
	{
		setMenuMoveToEquipmentCheckManagement(getContext(), menumovetoequipmentcheckmanagement);
	}

	/**
	 * Set value of MenuMoveToEquipmentCheckManagement
	 * @param context
	 * @param menumovetoequipmentcheckmanagement
	 */
	public final void setMenuMoveToEquipmentCheckManagement(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_Equipment_Check_Management menumovetoequipmentcheckmanagement)
	{
		if (menumovetoequipmentcheckmanagement != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToEquipmentCheckManagement.toString(), menumovetoequipmentcheckmanagement.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToEquipmentCheckManagement.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToEquipmentManagement
	 * @param menumovetoequipmentmanagement
	 */
	public final development_settings.proxies.Menu_Move_To_Equipment_Management getMenuMoveToEquipmentManagement()
	{
		return getMenuMoveToEquipmentManagement(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToEquipmentManagement
	 */
	public final development_settings.proxies.Menu_Move_To_Equipment_Management getMenuMoveToEquipmentManagement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToEquipmentManagement.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_Equipment_Management.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToEquipmentManagement
	 * @param menumovetoequipmentmanagement
	 */
	public final void setMenuMoveToEquipmentManagement(development_settings.proxies.Menu_Move_To_Equipment_Management menumovetoequipmentmanagement)
	{
		setMenuMoveToEquipmentManagement(getContext(), menumovetoequipmentmanagement);
	}

	/**
	 * Set value of MenuMoveToEquipmentManagement
	 * @param context
	 * @param menumovetoequipmentmanagement
	 */
	public final void setMenuMoveToEquipmentManagement(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_Equipment_Management menumovetoequipmentmanagement)
	{
		if (menumovetoequipmentmanagement != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToEquipmentManagement.toString(), menumovetoequipmentmanagement.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToEquipmentManagement.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToMaterialManagement
	 * @param menumovetomaterialmanagement
	 */
	public final development_settings.proxies.Menu_Move_To_Material_Management getMenuMoveToMaterialManagement()
	{
		return getMenuMoveToMaterialManagement(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToMaterialManagement
	 */
	public final development_settings.proxies.Menu_Move_To_Material_Management getMenuMoveToMaterialManagement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToMaterialManagement.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_Material_Management.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToMaterialManagement
	 * @param menumovetomaterialmanagement
	 */
	public final void setMenuMoveToMaterialManagement(development_settings.proxies.Menu_Move_To_Material_Management menumovetomaterialmanagement)
	{
		setMenuMoveToMaterialManagement(getContext(), menumovetomaterialmanagement);
	}

	/**
	 * Set value of MenuMoveToMaterialManagement
	 * @param context
	 * @param menumovetomaterialmanagement
	 */
	public final void setMenuMoveToMaterialManagement(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_Material_Management menumovetomaterialmanagement)
	{
		if (menumovetomaterialmanagement != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToMaterialManagement.toString(), menumovetomaterialmanagement.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToMaterialManagement.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToMonitoring
	 * @param menumovetomonitoring
	 */
	public final development_settings.proxies.Menu_Move_To_Monitoring getMenuMoveToMonitoring()
	{
		return getMenuMoveToMonitoring(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToMonitoring
	 */
	public final development_settings.proxies.Menu_Move_To_Monitoring getMenuMoveToMonitoring(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToMonitoring.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_Monitoring.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToMonitoring
	 * @param menumovetomonitoring
	 */
	public final void setMenuMoveToMonitoring(development_settings.proxies.Menu_Move_To_Monitoring menumovetomonitoring)
	{
		setMenuMoveToMonitoring(getContext(), menumovetomonitoring);
	}

	/**
	 * Set value of MenuMoveToMonitoring
	 * @param context
	 * @param menumovetomonitoring
	 */
	public final void setMenuMoveToMonitoring(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_Monitoring menumovetomonitoring)
	{
		if (menumovetomonitoring != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToMonitoring.toString(), menumovetomonitoring.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToMonitoring.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToReport
	 * @param menumovetoreport
	 */
	public final development_settings.proxies.Menu_Move_To_Report getMenuMoveToReport()
	{
		return getMenuMoveToReport(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToReport
	 */
	public final development_settings.proxies.Menu_Move_To_Report getMenuMoveToReport(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToReport.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_Report.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToReport
	 * @param menumovetoreport
	 */
	public final void setMenuMoveToReport(development_settings.proxies.Menu_Move_To_Report menumovetoreport)
	{
		setMenuMoveToReport(getContext(), menumovetoreport);
	}

	/**
	 * Set value of MenuMoveToReport
	 * @param context
	 * @param menumovetoreport
	 */
	public final void setMenuMoveToReport(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_Report menumovetoreport)
	{
		if (menumovetoreport != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToReport.toString(), menumovetoreport.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToReport.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToSQL2008
	 * @param menumovetosql2008
	 */
	public final development_settings.proxies.Menu_Move_To_SQL2008 getMenuMoveToSQL2008()
	{
		return getMenuMoveToSQL2008(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToSQL2008
	 */
	public final development_settings.proxies.Menu_Move_To_SQL2008 getMenuMoveToSQL2008(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToSQL2008.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_SQL2008.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToSQL2008
	 * @param menumovetosql2008
	 */
	public final void setMenuMoveToSQL2008(development_settings.proxies.Menu_Move_To_SQL2008 menumovetosql2008)
	{
		setMenuMoveToSQL2008(getContext(), menumovetosql2008);
	}

	/**
	 * Set value of MenuMoveToSQL2008
	 * @param context
	 * @param menumovetosql2008
	 */
	public final void setMenuMoveToSQL2008(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_SQL2008 menumovetosql2008)
	{
		if (menumovetosql2008 != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToSQL2008.toString(), menumovetosql2008.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToSQL2008.toString(), null);
		}
	}

	/**
	 * Get value of MenuMoveToWorkManagement
	 * @param menumovetoworkmanagement
	 */
	public final development_settings.proxies.Menu_Move_To_Work_Management getMenuMoveToWorkManagement()
	{
		return getMenuMoveToWorkManagement(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuMoveToWorkManagement
	 */
	public final development_settings.proxies.Menu_Move_To_Work_Management getMenuMoveToWorkManagement(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.MenuMoveToWorkManagement.toString());
		if (obj == null) {
			return null;
		}
		return development_settings.proxies.Menu_Move_To_Work_Management.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of MenuMoveToWorkManagement
	 * @param menumovetoworkmanagement
	 */
	public final void setMenuMoveToWorkManagement(development_settings.proxies.Menu_Move_To_Work_Management menumovetoworkmanagement)
	{
		setMenuMoveToWorkManagement(getContext(), menumovetoworkmanagement);
	}

	/**
	 * Set value of MenuMoveToWorkManagement
	 * @param context
	 * @param menumovetoworkmanagement
	 */
	public final void setMenuMoveToWorkManagement(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu_Move_To_Work_Management menumovetoworkmanagement)
	{
		if (menumovetoworkmanagement != null) {
			getMendixObject().setValue(context, MemberNames.MenuMoveToWorkManagement.toString(), menumovetoworkmanagement.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.MenuMoveToWorkManagement.toString(), null);
		}
	}

	/**
	 * @return value of _Root
	 */
	public final java.lang.Boolean get_Root()
	{
		return get_Root(getContext());
	}

	/**
	 * @param context
	 * @return value of _Root
	 */
	public final java.lang.Boolean get_Root(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._Root.toString());
	}

	/**
	 * Set value of _Root
	 * @param _root
	 */
	public final void set_Root(java.lang.Boolean _root)
	{
		set_Root(getContext(), _root);
	}

	/**
	 * Set value of _Root
	 * @param context
	 * @param _root
	 */
	public final void set_Root(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _root)
	{
		getMendixObject().setValue(context, MemberNames._Root.toString(), _root);
	}

	/**
	 * @return value of _Haschild
	 */
	public final java.lang.Boolean get_Haschild()
	{
		return get_Haschild(getContext());
	}

	/**
	 * @param context
	 * @return value of _Haschild
	 */
	public final java.lang.Boolean get_Haschild(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames._Haschild.toString());
	}

	/**
	 * Set value of _Haschild
	 * @param _haschild
	 */
	public final void set_Haschild(java.lang.Boolean _haschild)
	{
		set_Haschild(getContext(), _haschild);
	}

	/**
	 * Set value of _Haschild
	 * @param context
	 * @param _haschild
	 */
	public final void set_Haschild(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean _haschild)
	{
		getMendixObject().setValue(context, MemberNames._Haschild.toString(), _haschild);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Menu_Menu
	 */
	public final development_settings.proxies.Menu getMenu_Menu() throws com.mendix.core.CoreException
	{
		return getMenu_Menu(getContext());
	}

	/**
	 * @param context
	 * @return value of Menu_Menu
	 * @throws com.mendix.core.CoreException
	 */
	public final development_settings.proxies.Menu getMenu_Menu(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		development_settings.proxies.Menu result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Menu_Menu.toString());
		if (identifier != null) {
			result = development_settings.proxies.Menu.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Menu_Menu
	 * @param menu_menu
	 */
	public final void setMenu_Menu(development_settings.proxies.Menu menu_menu)
	{
		setMenu_Menu(getContext(), menu_menu);
	}

	/**
	 * Set value of Menu_Menu
	 * @param context
	 * @param menu_menu
	 */
	public final void setMenu_Menu(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Menu menu_menu)
	{
		if (menu_menu == null) {
			getMendixObject().setValue(context, MemberNames.Menu_Menu.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Menu_Menu.toString(), menu_menu.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Menu_MenuHelper
	 */
	public final development_settings.proxies.MenuHelper getMenu_MenuHelper() throws com.mendix.core.CoreException
	{
		return getMenu_MenuHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of Menu_MenuHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final development_settings.proxies.MenuHelper getMenu_MenuHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		development_settings.proxies.MenuHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Menu_MenuHelper.toString());
		if (identifier != null) {
			result = development_settings.proxies.MenuHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Menu_MenuHelper
	 * @param menu_menuhelper
	 */
	public final void setMenu_MenuHelper(development_settings.proxies.MenuHelper menu_menuhelper)
	{
		setMenu_MenuHelper(getContext(), menu_menuhelper);
	}

	/**
	 * Set value of Menu_MenuHelper
	 * @param context
	 * @param menu_menuhelper
	 */
	public final void setMenu_MenuHelper(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.MenuHelper menu_menuhelper)
	{
		if (menu_menuhelper == null) {
			getMendixObject().setValue(context, MemberNames.Menu_MenuHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Menu_MenuHelper.toString(), menu_menuhelper.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Menu_MenuHelperChild
	 */
	public final development_settings.proxies.MenuHelperChild getMenu_MenuHelperChild() throws com.mendix.core.CoreException
	{
		return getMenu_MenuHelperChild(getContext());
	}

	/**
	 * @param context
	 * @return value of Menu_MenuHelperChild
	 * @throws com.mendix.core.CoreException
	 */
	public final development_settings.proxies.MenuHelperChild getMenu_MenuHelperChild(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		development_settings.proxies.MenuHelperChild result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Menu_MenuHelperChild.toString());
		if (identifier != null) {
			result = development_settings.proxies.MenuHelperChild.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Menu_MenuHelperChild
	 * @param menu_menuhelperchild
	 */
	public final void setMenu_MenuHelperChild(development_settings.proxies.MenuHelperChild menu_menuhelperchild)
	{
		setMenu_MenuHelperChild(getContext(), menu_menuhelperchild);
	}

	/**
	 * Set value of Menu_MenuHelperChild
	 * @param context
	 * @param menu_menuhelperchild
	 */
	public final void setMenu_MenuHelperChild(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.MenuHelperChild menu_menuhelperchild)
	{
		if (menu_menuhelperchild == null) {
			getMendixObject().setValue(context, MemberNames.Menu_MenuHelperChild.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Menu_MenuHelperChild.toString(), menu_menuhelperchild.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MenuChilden
	 */
	public final java.util.List<development_settings.proxies.Menu> getMenuChilden() throws com.mendix.core.CoreException
	{
		return getMenuChilden(getContext());
	}

	/**
	 * @param context
	 * @return value of MenuChilden
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<development_settings.proxies.Menu> getMenuChilden(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<development_settings.proxies.Menu> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.MenuChilden.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(development_settings.proxies.Menu.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of MenuChilden
	 * @param menuchilden
	 */
	public final void setMenuChilden(java.util.List<development_settings.proxies.Menu> menuchilden)
	{
		setMenuChilden(getContext(), menuchilden);
	}

	/**
	 * Set value of MenuChilden
	 * @param context
	 * @param menuchilden
	 */
	public final void setMenuChilden(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<development_settings.proxies.Menu> menuchilden)
	{
		var identifiers = menuchilden
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.MenuChilden.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Menu_StandardCode
	 */
	public final commons.proxies.StandardCode getMenu_StandardCode() throws com.mendix.core.CoreException
	{
		return getMenu_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of Menu_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getMenu_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Menu_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Menu_StandardCode
	 * @param menu_standardcode
	 */
	public final void setMenu_StandardCode(commons.proxies.StandardCode menu_standardcode)
	{
		setMenu_StandardCode(getContext(), menu_standardcode);
	}

	/**
	 * Set value of Menu_StandardCode
	 * @param context
	 * @param menu_standardcode
	 */
	public final void setMenu_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode menu_standardcode)
	{
		if (menu_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.Menu_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Menu_StandardCode.toString(), menu_standardcode.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return menuMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final development_settings.proxies.Menu that = (development_settings.proxies.Menu) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
