// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package development_settings.proxies;

public class Selecthelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject selecthelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Development_Settings.Selecthelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Selecthelper_Tempview("Development_Settings.Selecthelper_Tempview"),
		Selecthelper_Menu("Development_Settings.Selecthelper_Menu");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Selecthelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Selecthelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject selecthelperMendixObject)
	{
		if (selecthelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, selecthelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.selecthelperMendixObject = selecthelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static development_settings.proxies.Selecthelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new development_settings.proxies.Selecthelper(context, mendixObject);
	}

	public static development_settings.proxies.Selecthelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return development_settings.proxies.Selecthelper.initialize(context, mendixObject);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Selecthelper_Tempview
	 */
	public final development_settings.proxies.Tempview getSelecthelper_Tempview() throws com.mendix.core.CoreException
	{
		return getSelecthelper_Tempview(getContext());
	}

	/**
	 * @param context
	 * @return value of Selecthelper_Tempview
	 * @throws com.mendix.core.CoreException
	 */
	public final development_settings.proxies.Tempview getSelecthelper_Tempview(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		development_settings.proxies.Tempview result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Selecthelper_Tempview.toString());
		if (identifier != null) {
			result = development_settings.proxies.Tempview.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Selecthelper_Tempview
	 * @param selecthelper_tempview
	 */
	public final void setSelecthelper_Tempview(development_settings.proxies.Tempview selecthelper_tempview)
	{
		setSelecthelper_Tempview(getContext(), selecthelper_tempview);
	}

	/**
	 * Set value of Selecthelper_Tempview
	 * @param context
	 * @param selecthelper_tempview
	 */
	public final void setSelecthelper_Tempview(com.mendix.systemwideinterfaces.core.IContext context, development_settings.proxies.Tempview selecthelper_tempview)
	{
		if (selecthelper_tempview == null) {
			getMendixObject().setValue(context, MemberNames.Selecthelper_Tempview.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Selecthelper_Tempview.toString(), selecthelper_tempview.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Selecthelper_Menu
	 */
	public final java.util.List<development_settings.proxies.Menu> getSelecthelper_Menu() throws com.mendix.core.CoreException
	{
		return getSelecthelper_Menu(getContext());
	}

	/**
	 * @param context
	 * @return value of Selecthelper_Menu
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<development_settings.proxies.Menu> getSelecthelper_Menu(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<development_settings.proxies.Menu> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.Selecthelper_Menu.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(development_settings.proxies.Menu.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of Selecthelper_Menu
	 * @param selecthelper_menu
	 */
	public final void setSelecthelper_Menu(java.util.List<development_settings.proxies.Menu> selecthelper_menu)
	{
		setSelecthelper_Menu(getContext(), selecthelper_menu);
	}

	/**
	 * Set value of Selecthelper_Menu
	 * @param context
	 * @param selecthelper_menu
	 */
	public final void setSelecthelper_Menu(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<development_settings.proxies.Menu> selecthelper_menu)
	{
		var identifiers = selecthelper_menu
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.Selecthelper_Menu.toString(), identifiers);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return selecthelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final development_settings.proxies.Selecthelper that = (development_settings.proxies.Selecthelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
