// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicdashboard.proxies;

public class ActionMapping implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject actionMappingMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicDashboard.ActionMapping";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		CurrentParentUUID("CurrentParentUUID"),
		DraggedUUID("DraggedUUID"),
		DroppedOnParentUUID("DroppedOnParentUUID"),
		DroppedOnUUID("DroppedOnUUID"),
		Index("Index");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ActionMapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ActionMapping(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject actionMappingMendixObject)
	{
		if (actionMappingMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, actionMappingMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.actionMappingMendixObject = actionMappingMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dynamicdashboard.proxies.ActionMapping initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicdashboard.proxies.ActionMapping(context, mendixObject);
	}

	public static dynamicdashboard.proxies.ActionMapping load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicdashboard.proxies.ActionMapping.initialize(context, mendixObject);
	}

	/**
	 * @return value of CurrentParentUUID
	 */
	public final java.lang.String getCurrentParentUUID()
	{
		return getCurrentParentUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of CurrentParentUUID
	 */
	public final java.lang.String getCurrentParentUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CurrentParentUUID.toString());
	}

	/**
	 * Set value of CurrentParentUUID
	 * @param currentparentuuid
	 */
	public final void setCurrentParentUUID(java.lang.String currentparentuuid)
	{
		setCurrentParentUUID(getContext(), currentparentuuid);
	}

	/**
	 * Set value of CurrentParentUUID
	 * @param context
	 * @param currentparentuuid
	 */
	public final void setCurrentParentUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String currentparentuuid)
	{
		getMendixObject().setValue(context, MemberNames.CurrentParentUUID.toString(), currentparentuuid);
	}

	/**
	 * @return value of DraggedUUID
	 */
	public final java.lang.String getDraggedUUID()
	{
		return getDraggedUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of DraggedUUID
	 */
	public final java.lang.String getDraggedUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DraggedUUID.toString());
	}

	/**
	 * Set value of DraggedUUID
	 * @param draggeduuid
	 */
	public final void setDraggedUUID(java.lang.String draggeduuid)
	{
		setDraggedUUID(getContext(), draggeduuid);
	}

	/**
	 * Set value of DraggedUUID
	 * @param context
	 * @param draggeduuid
	 */
	public final void setDraggedUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String draggeduuid)
	{
		getMendixObject().setValue(context, MemberNames.DraggedUUID.toString(), draggeduuid);
	}

	/**
	 * @return value of DroppedOnParentUUID
	 */
	public final java.lang.String getDroppedOnParentUUID()
	{
		return getDroppedOnParentUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of DroppedOnParentUUID
	 */
	public final java.lang.String getDroppedOnParentUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DroppedOnParentUUID.toString());
	}

	/**
	 * Set value of DroppedOnParentUUID
	 * @param droppedonparentuuid
	 */
	public final void setDroppedOnParentUUID(java.lang.String droppedonparentuuid)
	{
		setDroppedOnParentUUID(getContext(), droppedonparentuuid);
	}

	/**
	 * Set value of DroppedOnParentUUID
	 * @param context
	 * @param droppedonparentuuid
	 */
	public final void setDroppedOnParentUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String droppedonparentuuid)
	{
		getMendixObject().setValue(context, MemberNames.DroppedOnParentUUID.toString(), droppedonparentuuid);
	}

	/**
	 * @return value of DroppedOnUUID
	 */
	public final java.lang.String getDroppedOnUUID()
	{
		return getDroppedOnUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of DroppedOnUUID
	 */
	public final java.lang.String getDroppedOnUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.DroppedOnUUID.toString());
	}

	/**
	 * Set value of DroppedOnUUID
	 * @param droppedonuuid
	 */
	public final void setDroppedOnUUID(java.lang.String droppedonuuid)
	{
		setDroppedOnUUID(getContext(), droppedonuuid);
	}

	/**
	 * Set value of DroppedOnUUID
	 * @param context
	 * @param droppedonuuid
	 */
	public final void setDroppedOnUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String droppedonuuid)
	{
		getMendixObject().setValue(context, MemberNames.DroppedOnUUID.toString(), droppedonuuid);
	}

	/**
	 * @return value of Index
	 */
	public final java.lang.Integer getIndex()
	{
		return getIndex(getContext());
	}

	/**
	 * @param context
	 * @return value of Index
	 */
	public final java.lang.Integer getIndex(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Index.toString());
	}

	/**
	 * Set value of Index
	 * @param index
	 */
	public final void setIndex(java.lang.Integer index)
	{
		setIndex(getContext(), index);
	}

	/**
	 * Set value of Index
	 * @param context
	 * @param index
	 */
	public final void setIndex(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer index)
	{
		getMendixObject().setValue(context, MemberNames.Index.toString(), index);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return actionMappingMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicdashboard.proxies.ActionMapping that = (dynamicdashboard.proxies.ActionMapping) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
