// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicdashboard.proxies;

/**
 * 최초작성자 : 김동명
 * 최초작성일 : 2023/10/23
 * 최종수정자 :
 * 최종수정일 :
 * 
 * 설명 : 대시보드 Entity
 * 
 * V 1.0 : 최초생성
 */
public class Dashboard implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject dashboardMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicDashboard.Dashboard";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		DashboardType("DashboardType"),
		WorkOrderActive("WorkOrderActive"),
		WorkByPeriodActive("WorkByPeriodActive"),
		MaintananceCostActive("MaintananceCostActive"),
		MTBFActive("MTBFActive"),
		MTTRActive("MTTRActive"),
		SensorActive("SensorActive"),
		UUID("UUID"),
		SortValue("SortValue"),
		DashboardTypeSub("DashboardTypeSub");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Dashboard(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Dashboard(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject dashboardMendixObject)
	{
		if (dashboardMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, dashboardMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.dashboardMendixObject = dashboardMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dynamicdashboard.proxies.Dashboard initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicdashboard.proxies.Dashboard(context, mendixObject);
	}

	public static dynamicdashboard.proxies.Dashboard load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicdashboard.proxies.Dashboard.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicdashboard.proxies.Dashboard> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> dynamicdashboard.proxies.Dashboard.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * Get value of DashboardType
	 * @param dashboardtype
	 */
	public final dynamicdashboard.proxies.ENUM_Dashboard_ParentType getDashboardType()
	{
		return getDashboardType(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardType
	 */
	public final dynamicdashboard.proxies.ENUM_Dashboard_ParentType getDashboardType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DashboardType.toString());
		if (obj == null) {
			return null;
		}
		return dynamicdashboard.proxies.ENUM_Dashboard_ParentType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DashboardType
	 * @param dashboardtype
	 */
	public final void setDashboardType(dynamicdashboard.proxies.ENUM_Dashboard_ParentType dashboardtype)
	{
		setDashboardType(getContext(), dashboardtype);
	}

	/**
	 * Set value of DashboardType
	 * @param context
	 * @param dashboardtype
	 */
	public final void setDashboardType(com.mendix.systemwideinterfaces.core.IContext context, dynamicdashboard.proxies.ENUM_Dashboard_ParentType dashboardtype)
	{
		if (dashboardtype != null) {
			getMendixObject().setValue(context, MemberNames.DashboardType.toString(), dashboardtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DashboardType.toString(), null);
		}
	}

	/**
	 * @return value of WorkOrderActive
	 */
	public final java.lang.Boolean getWorkOrderActive()
	{
		return getWorkOrderActive(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderActive
	 */
	public final java.lang.Boolean getWorkOrderActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WorkOrderActive.toString());
	}

	/**
	 * Set value of WorkOrderActive
	 * @param workorderactive
	 */
	public final void setWorkOrderActive(java.lang.Boolean workorderactive)
	{
		setWorkOrderActive(getContext(), workorderactive);
	}

	/**
	 * Set value of WorkOrderActive
	 * @param context
	 * @param workorderactive
	 */
	public final void setWorkOrderActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean workorderactive)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderActive.toString(), workorderactive);
	}

	/**
	 * @return value of WorkByPeriodActive
	 */
	public final java.lang.Boolean getWorkByPeriodActive()
	{
		return getWorkByPeriodActive(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkByPeriodActive
	 */
	public final java.lang.Boolean getWorkByPeriodActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.WorkByPeriodActive.toString());
	}

	/**
	 * Set value of WorkByPeriodActive
	 * @param workbyperiodactive
	 */
	public final void setWorkByPeriodActive(java.lang.Boolean workbyperiodactive)
	{
		setWorkByPeriodActive(getContext(), workbyperiodactive);
	}

	/**
	 * Set value of WorkByPeriodActive
	 * @param context
	 * @param workbyperiodactive
	 */
	public final void setWorkByPeriodActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean workbyperiodactive)
	{
		getMendixObject().setValue(context, MemberNames.WorkByPeriodActive.toString(), workbyperiodactive);
	}

	/**
	 * @return value of MaintananceCostActive
	 */
	public final java.lang.Boolean getMaintananceCostActive()
	{
		return getMaintananceCostActive(getContext());
	}

	/**
	 * @param context
	 * @return value of MaintananceCostActive
	 */
	public final java.lang.Boolean getMaintananceCostActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MaintananceCostActive.toString());
	}

	/**
	 * Set value of MaintananceCostActive
	 * @param maintanancecostactive
	 */
	public final void setMaintananceCostActive(java.lang.Boolean maintanancecostactive)
	{
		setMaintananceCostActive(getContext(), maintanancecostactive);
	}

	/**
	 * Set value of MaintananceCostActive
	 * @param context
	 * @param maintanancecostactive
	 */
	public final void setMaintananceCostActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean maintanancecostactive)
	{
		getMendixObject().setValue(context, MemberNames.MaintananceCostActive.toString(), maintanancecostactive);
	}

	/**
	 * @return value of MTBFActive
	 */
	public final java.lang.Boolean getMTBFActive()
	{
		return getMTBFActive(getContext());
	}

	/**
	 * @param context
	 * @return value of MTBFActive
	 */
	public final java.lang.Boolean getMTBFActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MTBFActive.toString());
	}

	/**
	 * Set value of MTBFActive
	 * @param mtbfactive
	 */
	public final void setMTBFActive(java.lang.Boolean mtbfactive)
	{
		setMTBFActive(getContext(), mtbfactive);
	}

	/**
	 * Set value of MTBFActive
	 * @param context
	 * @param mtbfactive
	 */
	public final void setMTBFActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean mtbfactive)
	{
		getMendixObject().setValue(context, MemberNames.MTBFActive.toString(), mtbfactive);
	}

	/**
	 * @return value of MTTRActive
	 */
	public final java.lang.Boolean getMTTRActive()
	{
		return getMTTRActive(getContext());
	}

	/**
	 * @param context
	 * @return value of MTTRActive
	 */
	public final java.lang.Boolean getMTTRActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.MTTRActive.toString());
	}

	/**
	 * Set value of MTTRActive
	 * @param mttractive
	 */
	public final void setMTTRActive(java.lang.Boolean mttractive)
	{
		setMTTRActive(getContext(), mttractive);
	}

	/**
	 * Set value of MTTRActive
	 * @param context
	 * @param mttractive
	 */
	public final void setMTTRActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean mttractive)
	{
		getMendixObject().setValue(context, MemberNames.MTTRActive.toString(), mttractive);
	}

	/**
	 * @return value of SensorActive
	 */
	public final java.lang.Boolean getSensorActive()
	{
		return getSensorActive(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorActive
	 */
	public final java.lang.Boolean getSensorActive(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SensorActive.toString());
	}

	/**
	 * Set value of SensorActive
	 * @param sensoractive
	 */
	public final void setSensorActive(java.lang.Boolean sensoractive)
	{
		setSensorActive(getContext(), sensoractive);
	}

	/**
	 * Set value of SensorActive
	 * @param context
	 * @param sensoractive
	 */
	public final void setSensorActive(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean sensoractive)
	{
		getMendixObject().setValue(context, MemberNames.SensorActive.toString(), sensoractive);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of SortValue
	 */
	public final java.lang.Integer getSortValue()
	{
		return getSortValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SortValue
	 */
	public final java.lang.Integer getSortValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortValue.toString());
	}

	/**
	 * Set value of SortValue
	 * @param sortvalue
	 */
	public final void setSortValue(java.lang.Integer sortvalue)
	{
		setSortValue(getContext(), sortvalue);
	}

	/**
	 * Set value of SortValue
	 * @param context
	 * @param sortvalue
	 */
	public final void setSortValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortvalue)
	{
		getMendixObject().setValue(context, MemberNames.SortValue.toString(), sortvalue);
	}

	/**
	 * Get value of DashboardTypeSub
	 * @param dashboardtypesub
	 */
	public final dynamicdashboard.proxies.ENUM_Dashboard_ParentType getDashboardTypeSub()
	{
		return getDashboardTypeSub(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardTypeSub
	 */
	public final dynamicdashboard.proxies.ENUM_Dashboard_ParentType getDashboardTypeSub(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DashboardTypeSub.toString());
		if (obj == null) {
			return null;
		}
		return dynamicdashboard.proxies.ENUM_Dashboard_ParentType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DashboardTypeSub
	 * @param dashboardtypesub
	 */
	public final void setDashboardTypeSub(dynamicdashboard.proxies.ENUM_Dashboard_ParentType dashboardtypesub)
	{
		setDashboardTypeSub(getContext(), dashboardtypesub);
	}

	/**
	 * Set value of DashboardTypeSub
	 * @param context
	 * @param dashboardtypesub
	 */
	public final void setDashboardTypeSub(com.mendix.systemwideinterfaces.core.IContext context, dynamicdashboard.proxies.ENUM_Dashboard_ParentType dashboardtypesub)
	{
		if (dashboardtypesub != null) {
			getMendixObject().setValue(context, MemberNames.DashboardTypeSub.toString(), dashboardtypesub.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DashboardTypeSub.toString(), null);
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return dashboardMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicdashboard.proxies.Dashboard that = (dynamicdashboard.proxies.Dashboard) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
