// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicdashboard.proxies;

public enum ENUM_Dashboard_ParentType
{
	WorkOrder(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "작업 현황" } }),
	WorkByPeriod(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "기간별 작업 요청 현황" } }),
	MaintananceCost(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "보전 비용 현황" } }),
	MTBF(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "MTBF" } }),
	MTTR(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "MTTR" } }),
	Sensor(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "센서 모니터링" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_Dashboard_ParentType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
