// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicdashboard.proxies;

public enum ENUM_DashboardType_2
{
	Total(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "전체" } }),
	Plant(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "공장별" } }),
	Location(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "위치별" } }),
	Materail(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "자재별" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_DashboardType_2(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
