// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicdashboard.proxies;

public class JSONObject implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject jSONObjectMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicDashboard.JSONObject";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		JSONActionMapping("JSONActionMapping");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public JSONObject(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected JSONObject(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject jSONObjectMendixObject)
	{
		if (jSONObjectMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, jSONObjectMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.jSONObjectMendixObject = jSONObjectMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dynamicdashboard.proxies.JSONObject initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicdashboard.proxies.JSONObject(context, mendixObject);
	}

	public static dynamicdashboard.proxies.JSONObject load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicdashboard.proxies.JSONObject.initialize(context, mendixObject);
	}

	/**
	 * @return value of JSONActionMapping
	 */
	public final java.lang.String getJSONActionMapping()
	{
		return getJSONActionMapping(getContext());
	}

	/**
	 * @param context
	 * @return value of JSONActionMapping
	 */
	public final java.lang.String getJSONActionMapping(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.JSONActionMapping.toString());
	}

	/**
	 * Set value of JSONActionMapping
	 * @param jsonactionmapping
	 */
	public final void setJSONActionMapping(java.lang.String jsonactionmapping)
	{
		setJSONActionMapping(getContext(), jsonactionmapping);
	}

	/**
	 * Set value of JSONActionMapping
	 * @param context
	 * @param jsonactionmapping
	 */
	public final void setJSONActionMapping(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String jsonactionmapping)
	{
		getMendixObject().setValue(context, MemberNames.JSONActionMapping.toString(), jsonactionmapping);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return jSONObjectMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicdashboard.proxies.JSONObject that = (dynamicdashboard.proxies.JSONObject) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
