// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicdashboard.proxies;

public class MTTR implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject mTTRMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicDashboard.MTTR";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		MTTRName("MTTRName"),
		UUID("UUID"),
		SortValue("SortValue"),
		MTTR_Dashboard("DynamicDashboard.MTTR_Dashboard");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public MTTR(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected MTTR(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mTTRMendixObject)
	{
		if (mTTRMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, mTTRMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.mTTRMendixObject = mTTRMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dynamicdashboard.proxies.MTTR initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicdashboard.proxies.MTTR(context, mendixObject);
	}

	public static dynamicdashboard.proxies.MTTR load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicdashboard.proxies.MTTR.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicdashboard.proxies.MTTR> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> dynamicdashboard.proxies.MTTR.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of MTTRName
	 */
	public final java.lang.String getMTTRName()
	{
		return getMTTRName(getContext());
	}

	/**
	 * @param context
	 * @return value of MTTRName
	 */
	public final java.lang.String getMTTRName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MTTRName.toString());
	}

	/**
	 * Set value of MTTRName
	 * @param mttrname
	 */
	public final void setMTTRName(java.lang.String mttrname)
	{
		setMTTRName(getContext(), mttrname);
	}

	/**
	 * Set value of MTTRName
	 * @param context
	 * @param mttrname
	 */
	public final void setMTTRName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String mttrname)
	{
		getMendixObject().setValue(context, MemberNames.MTTRName.toString(), mttrname);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of SortValue
	 */
	public final java.lang.Integer getSortValue()
	{
		return getSortValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SortValue
	 */
	public final java.lang.Integer getSortValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortValue.toString());
	}

	/**
	 * Set value of SortValue
	 * @param sortvalue
	 */
	public final void setSortValue(java.lang.Integer sortvalue)
	{
		setSortValue(getContext(), sortvalue);
	}

	/**
	 * Set value of SortValue
	 * @param context
	 * @param sortvalue
	 */
	public final void setSortValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortvalue)
	{
		getMendixObject().setValue(context, MemberNames.SortValue.toString(), sortvalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of MTTR_Dashboard
	 */
	public final dynamicdashboard.proxies.Dashboard getMTTR_Dashboard() throws com.mendix.core.CoreException
	{
		return getMTTR_Dashboard(getContext());
	}

	/**
	 * @param context
	 * @return value of MTTR_Dashboard
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicdashboard.proxies.Dashboard getMTTR_Dashboard(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicdashboard.proxies.Dashboard result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.MTTR_Dashboard.toString());
		if (identifier != null) {
			result = dynamicdashboard.proxies.Dashboard.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of MTTR_Dashboard
	 * @param mttr_dashboard
	 */
	public final void setMTTR_Dashboard(dynamicdashboard.proxies.Dashboard mttr_dashboard)
	{
		setMTTR_Dashboard(getContext(), mttr_dashboard);
	}

	/**
	 * Set value of MTTR_Dashboard
	 * @param context
	 * @param mttr_dashboard
	 */
	public final void setMTTR_Dashboard(com.mendix.systemwideinterfaces.core.IContext context, dynamicdashboard.proxies.Dashboard mttr_dashboard)
	{
		if (mttr_dashboard == null) {
			getMendixObject().setValue(context, MemberNames.MTTR_Dashboard.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.MTTR_Dashboard.toString(), mttr_dashboard.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return mTTRMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicdashboard.proxies.MTTR that = (dynamicdashboard.proxies.MTTR) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
