// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicdashboard.proxies;

public class Sensor implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject sensorMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicDashboard.Sensor";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SensorName("SensorName"),
		UUID("UUID"),
		SortValue("SortValue"),
		Sensor_Dashboard("DynamicDashboard.Sensor_Dashboard");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Sensor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected Sensor(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject sensorMendixObject)
	{
		if (sensorMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, sensorMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.sensorMendixObject = sensorMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dynamicdashboard.proxies.Sensor initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicdashboard.proxies.Sensor(context, mendixObject);
	}

	public static dynamicdashboard.proxies.Sensor load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicdashboard.proxies.Sensor.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicdashboard.proxies.Sensor> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> dynamicdashboard.proxies.Sensor.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of SensorName
	 */
	public final java.lang.String getSensorName()
	{
		return getSensorName(getContext());
	}

	/**
	 * @param context
	 * @return value of SensorName
	 */
	public final java.lang.String getSensorName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SensorName.toString());
	}

	/**
	 * Set value of SensorName
	 * @param sensorname
	 */
	public final void setSensorName(java.lang.String sensorname)
	{
		setSensorName(getContext(), sensorname);
	}

	/**
	 * Set value of SensorName
	 * @param context
	 * @param sensorname
	 */
	public final void setSensorName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String sensorname)
	{
		getMendixObject().setValue(context, MemberNames.SensorName.toString(), sensorname);
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of SortValue
	 */
	public final java.lang.Integer getSortValue()
	{
		return getSortValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SortValue
	 */
	public final java.lang.Integer getSortValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortValue.toString());
	}

	/**
	 * Set value of SortValue
	 * @param sortvalue
	 */
	public final void setSortValue(java.lang.Integer sortvalue)
	{
		setSortValue(getContext(), sortvalue);
	}

	/**
	 * Set value of SortValue
	 * @param context
	 * @param sortvalue
	 */
	public final void setSortValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortvalue)
	{
		getMendixObject().setValue(context, MemberNames.SortValue.toString(), sortvalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Sensor_Dashboard
	 */
	public final dynamicdashboard.proxies.Dashboard getSensor_Dashboard() throws com.mendix.core.CoreException
	{
		return getSensor_Dashboard(getContext());
	}

	/**
	 * @param context
	 * @return value of Sensor_Dashboard
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicdashboard.proxies.Dashboard getSensor_Dashboard(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicdashboard.proxies.Dashboard result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Sensor_Dashboard.toString());
		if (identifier != null) {
			result = dynamicdashboard.proxies.Dashboard.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Sensor_Dashboard
	 * @param sensor_dashboard
	 */
	public final void setSensor_Dashboard(dynamicdashboard.proxies.Dashboard sensor_dashboard)
	{
		setSensor_Dashboard(getContext(), sensor_dashboard);
	}

	/**
	 * Set value of Sensor_Dashboard
	 * @param context
	 * @param sensor_dashboard
	 */
	public final void setSensor_Dashboard(com.mendix.systemwideinterfaces.core.IContext context, dynamicdashboard.proxies.Dashboard sensor_dashboard)
	{
		if (sensor_dashboard == null) {
			getMendixObject().setValue(context, MemberNames.Sensor_Dashboard.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Sensor_Dashboard.toString(), sensor_dashboard.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return sensorMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicdashboard.proxies.Sensor that = (dynamicdashboard.proxies.Sensor) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
