// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package dynamicdashboard.proxies;

public class WorkOrder implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "DynamicDashboard.WorkOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkOrderName("WorkOrderName"),
		DashboardType("DashboardType"),
		WidgetType("WidgetType"),
		PeriodType("PeriodType"),
		UUID("UUID"),
		SortValue("SortValue"),
		WorkOrder_Dashboard("DynamicDashboard.WorkOrder_Dashboard");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderMendixObject)
	{
		if (workOrderMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderMendixObject = workOrderMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static dynamicdashboard.proxies.WorkOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new dynamicdashboard.proxies.WorkOrder(context, mendixObject);
	}

	public static dynamicdashboard.proxies.WorkOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return dynamicdashboard.proxies.WorkOrder.initialize(context, mendixObject);
	}

	public static java.util.List<dynamicdashboard.proxies.WorkOrder> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> dynamicdashboard.proxies.WorkOrder.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of WorkOrderName
	 */
	public final java.lang.String getWorkOrderName()
	{
		return getWorkOrderName(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderName
	 */
	public final java.lang.String getWorkOrderName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkOrderName.toString());
	}

	/**
	 * Set value of WorkOrderName
	 * @param workordername
	 */
	public final void setWorkOrderName(java.lang.String workordername)
	{
		setWorkOrderName(getContext(), workordername);
	}

	/**
	 * Set value of WorkOrderName
	 * @param context
	 * @param workordername
	 */
	public final void setWorkOrderName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workordername)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderName.toString(), workordername);
	}

	/**
	 * Get value of DashboardType
	 * @param dashboardtype
	 */
	public final dynamicdashboard.proxies.ENUM_DashboardType getDashboardType()
	{
		return getDashboardType(getContext());
	}

	/**
	 * @param context
	 * @return value of DashboardType
	 */
	public final dynamicdashboard.proxies.ENUM_DashboardType getDashboardType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.DashboardType.toString());
		if (obj == null) {
			return null;
		}
		return dynamicdashboard.proxies.ENUM_DashboardType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of DashboardType
	 * @param dashboardtype
	 */
	public final void setDashboardType(dynamicdashboard.proxies.ENUM_DashboardType dashboardtype)
	{
		setDashboardType(getContext(), dashboardtype);
	}

	/**
	 * Set value of DashboardType
	 * @param context
	 * @param dashboardtype
	 */
	public final void setDashboardType(com.mendix.systemwideinterfaces.core.IContext context, dynamicdashboard.proxies.ENUM_DashboardType dashboardtype)
	{
		if (dashboardtype != null) {
			getMendixObject().setValue(context, MemberNames.DashboardType.toString(), dashboardtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.DashboardType.toString(), null);
		}
	}

	/**
	 * Get value of WidgetType
	 * @param widgettype
	 */
	public final dynamicdashboard.proxies.ENUM_WidgetType getWidgetType()
	{
		return getWidgetType(getContext());
	}

	/**
	 * @param context
	 * @return value of WidgetType
	 */
	public final dynamicdashboard.proxies.ENUM_WidgetType getWidgetType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.WidgetType.toString());
		if (obj == null) {
			return null;
		}
		return dynamicdashboard.proxies.ENUM_WidgetType.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of WidgetType
	 * @param widgettype
	 */
	public final void setWidgetType(dynamicdashboard.proxies.ENUM_WidgetType widgettype)
	{
		setWidgetType(getContext(), widgettype);
	}

	/**
	 * Set value of WidgetType
	 * @param context
	 * @param widgettype
	 */
	public final void setWidgetType(com.mendix.systemwideinterfaces.core.IContext context, dynamicdashboard.proxies.ENUM_WidgetType widgettype)
	{
		if (widgettype != null) {
			getMendixObject().setValue(context, MemberNames.WidgetType.toString(), widgettype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.WidgetType.toString(), null);
		}
	}

	/**
	 * Get value of PeriodType
	 * @param periodtype
	 */
	public final dynamicdashboard.proxies.ENUM_Period getPeriodType()
	{
		return getPeriodType(getContext());
	}

	/**
	 * @param context
	 * @return value of PeriodType
	 */
	public final dynamicdashboard.proxies.ENUM_Period getPeriodType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.PeriodType.toString());
		if (obj == null) {
			return null;
		}
		return dynamicdashboard.proxies.ENUM_Period.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of PeriodType
	 * @param periodtype
	 */
	public final void setPeriodType(dynamicdashboard.proxies.ENUM_Period periodtype)
	{
		setPeriodType(getContext(), periodtype);
	}

	/**
	 * Set value of PeriodType
	 * @param context
	 * @param periodtype
	 */
	public final void setPeriodType(com.mendix.systemwideinterfaces.core.IContext context, dynamicdashboard.proxies.ENUM_Period periodtype)
	{
		if (periodtype != null) {
			getMendixObject().setValue(context, MemberNames.PeriodType.toString(), periodtype.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.PeriodType.toString(), null);
		}
	}

	/**
	 * @return value of UUID
	 */
	public final java.lang.String getUUID()
	{
		return getUUID(getContext());
	}

	/**
	 * @param context
	 * @return value of UUID
	 */
	public final java.lang.String getUUID(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UUID.toString());
	}

	/**
	 * Set value of UUID
	 * @param uuid
	 */
	public final void setUUID(java.lang.String uuid)
	{
		setUUID(getContext(), uuid);
	}

	/**
	 * Set value of UUID
	 * @param context
	 * @param uuid
	 */
	public final void setUUID(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String uuid)
	{
		getMendixObject().setValue(context, MemberNames.UUID.toString(), uuid);
	}

	/**
	 * @return value of SortValue
	 */
	public final java.lang.Integer getSortValue()
	{
		return getSortValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SortValue
	 */
	public final java.lang.Integer getSortValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.SortValue.toString());
	}

	/**
	 * Set value of SortValue
	 * @param sortvalue
	 */
	public final void setSortValue(java.lang.Integer sortvalue)
	{
		setSortValue(getContext(), sortvalue);
	}

	/**
	 * Set value of SortValue
	 * @param context
	 * @param sortvalue
	 */
	public final void setSortValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer sortvalue)
	{
		getMendixObject().setValue(context, MemberNames.SortValue.toString(), sortvalue);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrder_Dashboard
	 */
	public final dynamicdashboard.proxies.Dashboard getWorkOrder_Dashboard() throws com.mendix.core.CoreException
	{
		return getWorkOrder_Dashboard(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrder_Dashboard
	 * @throws com.mendix.core.CoreException
	 */
	public final dynamicdashboard.proxies.Dashboard getWorkOrder_Dashboard(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		dynamicdashboard.proxies.Dashboard result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrder_Dashboard.toString());
		if (identifier != null) {
			result = dynamicdashboard.proxies.Dashboard.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrder_Dashboard
	 * @param workorder_dashboard
	 */
	public final void setWorkOrder_Dashboard(dynamicdashboard.proxies.Dashboard workorder_dashboard)
	{
		setWorkOrder_Dashboard(getContext(), workorder_dashboard);
	}

	/**
	 * Set value of WorkOrder_Dashboard
	 * @param context
	 * @param workorder_dashboard
	 */
	public final void setWorkOrder_Dashboard(com.mendix.systemwideinterfaces.core.IContext context, dynamicdashboard.proxies.Dashboard workorder_dashboard)
	{
		if (workorder_dashboard == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrder_Dashboard.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrder_Dashboard.toString(), workorder_dashboard.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final dynamicdashboard.proxies.WorkOrder that = (dynamicdashboard.proxies.WorkOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
