// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum LogNodes
{
	CommunityCommons(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "CommunityCommons" }, new java.lang.String[] { "ko_KR", "CommunityCommons" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private LogNodes(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
