// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package communitycommons.proxies;

public enum SanitizerPolicy
{
	BLOCKS(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Allows common block elements including <p>, <h1>, etc." } }),
	FORMATTING(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Allows common formatting elements including <b>, <i> etc." } }),
	IMAGES(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Allows <img> elements from HTTP, HTTPS and relative sources" } }),
	LINKS(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Allows HTTP, HTTPS, MAILTO and relative links" } }),
	STYLES(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Allows certain safe CSS properties in style=\"...\" attributes" } }),
	TABLES(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Allows common table elements" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private SanitizerPolicy(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
