// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public enum ENU_SigningAlgorithm
{
	HS256(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "HS256" } }),
	HS384(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "HS384" } }),
	HS512(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "HS512" } }),
	RS256(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "RS256" } }),
	RS384(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "RS384" } }),
	RS512(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "RS512" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENU_SigningAlgorithm(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
