// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies;

public enum ENU_UserProvisioningFlows
{
	_Default(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Standard OIDC" } }),
	Using_UserInfo_Endpoint(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Using UserInfo Endpoint" } }),
	Salesforce_Example(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Salesforce Example" } }),
	Google(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Google" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENU_UserProvisioningFlows(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
