// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package oidc.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the OIDC module

	/**
	* This constant represents selected ACRvalues, contains selected scopes, we can provide multiple values with space.     
Examples: acr1 acr2
	*/
	public static java.lang.String getACRValues()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.ACRValues");
	}

	/**
	* This constant represents well-known endpoint URL. 
	*/
	public static java.lang.String getAutomaticConfigurationURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.AutomaticConfigurationURL");
	}

	/**
	* This constant represents callback response mode, contains caption of OIDC.ENU_ResponseMode. 
	* Default value is Query
	* Example: Query
	*/
	public static java.lang.String getCallbackResponseMode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.CallbackResponseMode");
	}

	/**
	* This constant represents client alias.
	*/
	public static java.lang.String getClientAlias()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.ClientAlias");
	}

	/**
	* This constant represents client authentication method, contains caption of OIDC.ENU_ClientAuthenticationMethod 
	* Default value is client_secret_basic
	* Examples: client_secret_post 
	*/
	public static java.lang.String getClientAuthenticationMethod()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.ClientAuthenticationMethod");
	}

	/**
	* This constant represents client id.
	*/
	public static java.lang.String getClientID()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.ClientID");
	}

	/**
	* This constant represents client secret.
	*/
	public static java.lang.String getClientSecret()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.ClientSecret");
	}

	/**
	* This constant represents custom access token processing microflow, contains   CompleteName column value of mxmodelreflection$microflows table.  
	* Example : OIDC.Default_PIB_TokenProcessing_CustomATP
	*/
	public static java.lang.String getCustomATP()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.CustomATP");
	}

	/**
	* This constant represents custom callback url.
	*/
	public static java.lang.String getCustomCallbackURL()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.CustomCallbackURL");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.LogNode");
	}

	/**
	*  This constant represents selected claim values, contains selected claims, we can provide multiple values with space.
	* Examples: auth_time created_at 
	*/
	public static java.lang.String getSelectedClaim()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.SelectedClaim");
	}

	/**
	* This constant represents selected Scope values, contains selected scopes, we can provide multiple values with space. 
Examples: openid profile email
	*/
	public static java.lang.String getSelectedScope()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.SelectedScope");
	}

	/**
	* This constant represents end session endpoint.
	*/
	public static java.lang.String getSessionEndPoint()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.SessionEndPoint");
	}

	/**
	* This constant represents custom user provisioning, contains caption of OIDC.ENU_UserProvisioningFlows. 
	* Default value is Standard OIDC
Example: Standard OIDC
	*/
	public static java.lang.String getUserProvisioningFlow()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("OIDC.UserProvisioningFlow");
	}
}