// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 박성안
 * 최초 작성일 : 2023/11/6
 * 설명 : WorkOrder Kanban 필터 팝업에 여러 설비를 검색할 수 있게 하기 위한 엔터티
 * Version 1.0 : 생성
 */
public class DepartmentHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject departmentHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.DepartmentHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Department("Department"),
		DepartmentHelper_FilterHelper("Work_Management.DepartmentHelper_FilterHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DepartmentHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected DepartmentHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject departmentHelperMendixObject)
	{
		if (departmentHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, departmentHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.departmentHelperMendixObject = departmentHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.DepartmentHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.DepartmentHelper(context, mendixObject);
	}

	public static work_management.proxies.DepartmentHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.DepartmentHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Department
	 */
	public final java.lang.String getDepartment()
	{
		return getDepartment(getContext());
	}

	/**
	 * @param context
	 * @return value of Department
	 */
	public final java.lang.String getDepartment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Department.toString());
	}

	/**
	 * Set value of Department
	 * @param department
	 */
	public final void setDepartment(java.lang.String department)
	{
		setDepartment(getContext(), department);
	}

	/**
	 * Set value of Department
	 * @param context
	 * @param department
	 */
	public final void setDepartment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String department)
	{
		getMendixObject().setValue(context, MemberNames.Department.toString(), department);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of DepartmentHelper_FilterHelper
	 */
	public final work_management.proxies.FilterHelper getDepartmentHelper_FilterHelper() throws com.mendix.core.CoreException
	{
		return getDepartmentHelper_FilterHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of DepartmentHelper_FilterHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.FilterHelper getDepartmentHelper_FilterHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.FilterHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DepartmentHelper_FilterHelper.toString());
		if (identifier != null) {
			result = work_management.proxies.FilterHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of DepartmentHelper_FilterHelper
	 * @param departmenthelper_filterhelper
	 */
	public final void setDepartmentHelper_FilterHelper(work_management.proxies.FilterHelper departmenthelper_filterhelper)
	{
		setDepartmentHelper_FilterHelper(getContext(), departmenthelper_filterhelper);
	}

	/**
	 * Set value of DepartmentHelper_FilterHelper
	 * @param context
	 * @param departmenthelper_filterhelper
	 */
	public final void setDepartmentHelper_FilterHelper(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.FilterHelper departmenthelper_filterhelper)
	{
		if (departmenthelper_filterhelper == null) {
			getMendixObject().setValue(context, MemberNames.DepartmentHelper_FilterHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.DepartmentHelper_FilterHelper.toString(), departmenthelper_filterhelper.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return departmentHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.DepartmentHelper that = (work_management.proxies.DepartmentHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
