// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public enum ENUM_WorkOrderProcessStatus
{
	Request(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Request" } }),
	Approved(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Approved" } }),
	Rejected(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Rejected" } }),
	Processing(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Processing" } }),
	Complete(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "Complete" } }),
	FinalComplete(new java.lang.String[][] { new java.lang.String[] { "ko_KR", "FinalComplete" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ENUM_WorkOrderProcessStatus(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
