// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 박성안
 * 최초 작성일 : 2023/11/6
 * 설명 : WorkOrder Kanban 필터 팝업에 여러 설비를 검색할 수 있게 하기 위한 엔터티
 * Version 1.0 : 생성
 */
public class EquipmentHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject equipmentHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.EquipmentHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Equipment("Equipment"),
		EquipmentHelper_FilterHelper("Work_Management.EquipmentHelper_FilterHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public EquipmentHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected EquipmentHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject equipmentHelperMendixObject)
	{
		if (equipmentHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, equipmentHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.equipmentHelperMendixObject = equipmentHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.EquipmentHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.EquipmentHelper(context, mendixObject);
	}

	public static work_management.proxies.EquipmentHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.EquipmentHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of Equipment
	 */
	public final java.lang.String getEquipment()
	{
		return getEquipment(getContext());
	}

	/**
	 * @param context
	 * @return value of Equipment
	 */
	public final java.lang.String getEquipment(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Equipment.toString());
	}

	/**
	 * Set value of Equipment
	 * @param equipment
	 */
	public final void setEquipment(java.lang.String equipment)
	{
		setEquipment(getContext(), equipment);
	}

	/**
	 * Set value of Equipment
	 * @param context
	 * @param equipment
	 */
	public final void setEquipment(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipment)
	{
		getMendixObject().setValue(context, MemberNames.Equipment.toString(), equipment);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of EquipmentHelper_FilterHelper
	 */
	public final work_management.proxies.FilterHelper getEquipmentHelper_FilterHelper() throws com.mendix.core.CoreException
	{
		return getEquipmentHelper_FilterHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentHelper_FilterHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.FilterHelper getEquipmentHelper_FilterHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.FilterHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.EquipmentHelper_FilterHelper.toString());
		if (identifier != null) {
			result = work_management.proxies.FilterHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of EquipmentHelper_FilterHelper
	 * @param equipmenthelper_filterhelper
	 */
	public final void setEquipmentHelper_FilterHelper(work_management.proxies.FilterHelper equipmenthelper_filterhelper)
	{
		setEquipmentHelper_FilterHelper(getContext(), equipmenthelper_filterhelper);
	}

	/**
	 * Set value of EquipmentHelper_FilterHelper
	 * @param context
	 * @param equipmenthelper_filterhelper
	 */
	public final void setEquipmentHelper_FilterHelper(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.FilterHelper equipmenthelper_filterhelper)
	{
		if (equipmenthelper_filterhelper == null) {
			getMendixObject().setValue(context, MemberNames.EquipmentHelper_FilterHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.EquipmentHelper_FilterHelper.toString(), equipmenthelper_filterhelper.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return equipmentHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.EquipmentHelper that = (work_management.proxies.EquipmentHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
