// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/20
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/20
 * 설명 : 작업요청 이미지 엔터티
 * Version 1.0 : 생성
 */
public class FieldPhoto extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.FieldPhoto";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		FieldPhoto_WorkOrder("Work_Management.FieldPhoto_WorkOrder");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public FieldPhoto(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected FieldPhoto(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject fieldPhotoMendixObject)
	{
		super(context, fieldPhotoMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, fieldPhotoMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.FieldPhoto initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.FieldPhoto(context, mendixObject);
	}

	public static work_management.proxies.FieldPhoto load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.FieldPhoto.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.FieldPhoto> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.FieldPhoto.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FieldPhoto_WorkOrder
	 */
	public final work_management.proxies.WorkOrder getFieldPhoto_WorkOrder() throws com.mendix.core.CoreException
	{
		return getFieldPhoto_WorkOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldPhoto_WorkOrder
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrder getFieldPhoto_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FieldPhoto_WorkOrder.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrder.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FieldPhoto_WorkOrder
	 * @param fieldphoto_workorder
	 */
	public final void setFieldPhoto_WorkOrder(work_management.proxies.WorkOrder fieldphoto_workorder)
	{
		setFieldPhoto_WorkOrder(getContext(), fieldphoto_workorder);
	}

	/**
	 * Set value of FieldPhoto_WorkOrder
	 * @param context
	 * @param fieldphoto_workorder
	 */
	public final void setFieldPhoto_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrder fieldphoto_workorder)
	{
		if (fieldphoto_workorder == null) {
			getMendixObject().setValue(context, MemberNames.FieldPhoto_WorkOrder.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FieldPhoto_WorkOrder.toString(), fieldphoto_workorder.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.FieldPhoto that = (work_management.proxies.FieldPhoto) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
