// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public class ResultImage extends system.proxies.Image
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.ResultImage";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PublicThumbnailPath("PublicThumbnailPath"),
		FileID("FileID"),
		Name("Name"),
		DeleteAfterDownload("DeleteAfterDownload"),
		Contents("Contents"),
		HasContents("HasContents"),
		Size("Size"),
		BeforeImage_WorkOrderResult("Work_Management.BeforeImage_WorkOrderResult"),
		AfterImage_WorkOrderResult("Work_Management.AfterImage_WorkOrderResult");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public ResultImage(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected ResultImage(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject resultImageMendixObject)
	{
		super(context, resultImageMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, resultImageMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.ResultImage initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.ResultImage(context, mendixObject);
	}

	public static work_management.proxies.ResultImage load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.ResultImage.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.ResultImage> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.ResultImage.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BeforeImage_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrderResult getBeforeImage_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getBeforeImage_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of BeforeImage_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderResult getBeforeImage_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BeforeImage_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BeforeImage_WorkOrderResult
	 * @param beforeimage_workorderresult
	 */
	public final void setBeforeImage_WorkOrderResult(work_management.proxies.WorkOrderResult beforeimage_workorderresult)
	{
		setBeforeImage_WorkOrderResult(getContext(), beforeimage_workorderresult);
	}

	/**
	 * Set value of BeforeImage_WorkOrderResult
	 * @param context
	 * @param beforeimage_workorderresult
	 */
	public final void setBeforeImage_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderResult beforeimage_workorderresult)
	{
		if (beforeimage_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.BeforeImage_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BeforeImage_WorkOrderResult.toString(), beforeimage_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AfterImage_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrderResult getAfterImage_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getAfterImage_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of AfterImage_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderResult getAfterImage_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AfterImage_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AfterImage_WorkOrderResult
	 * @param afterimage_workorderresult
	 */
	public final void setAfterImage_WorkOrderResult(work_management.proxies.WorkOrderResult afterimage_workorderresult)
	{
		setAfterImage_WorkOrderResult(getContext(), afterimage_workorderresult);
	}

	/**
	 * Set value of AfterImage_WorkOrderResult
	 * @param context
	 * @param afterimage_workorderresult
	 */
	public final void setAfterImage_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderResult afterimage_workorderresult)
	{
		if (afterimage_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.AfterImage_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AfterImage_WorkOrderResult.toString(), afterimage_workorderresult.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.ResultImage that = (work_management.proxies.ResultImage) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
