// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public class UsedMaterialHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject usedMaterialHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.UsedMaterialHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UseDescription("UseDescription"),
		UsedQuantity("UsedQuantity"),
		RemainedQuantity("RemainedQuantity"),
		WarehouseName("WarehouseName"),
		WarehouseLocation("WarehouseLocation"),
		StockLocation("StockLocation"),
		GatheringCode("GatheringCode"),
		UsedMaterialHelper_Material("Work_Management.UsedMaterialHelper_Material");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UsedMaterialHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected UsedMaterialHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject usedMaterialHelperMendixObject)
	{
		if (usedMaterialHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, usedMaterialHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.usedMaterialHelperMendixObject = usedMaterialHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.UsedMaterialHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.UsedMaterialHelper(context, mendixObject);
	}

	public static work_management.proxies.UsedMaterialHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.UsedMaterialHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of UseDescription
	 */
	public final java.lang.String getUseDescription()
	{
		return getUseDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of UseDescription
	 */
	public final java.lang.String getUseDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UseDescription.toString());
	}

	/**
	 * Set value of UseDescription
	 * @param usedescription
	 */
	public final void setUseDescription(java.lang.String usedescription)
	{
		setUseDescription(getContext(), usedescription);
	}

	/**
	 * Set value of UseDescription
	 * @param context
	 * @param usedescription
	 */
	public final void setUseDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usedescription)
	{
		getMendixObject().setValue(context, MemberNames.UseDescription.toString(), usedescription);
	}

	/**
	 * @return value of UsedQuantity
	 */
	public final java.math.BigDecimal getUsedQuantity()
	{
		return getUsedQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of UsedQuantity
	 */
	public final java.math.BigDecimal getUsedQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.UsedQuantity.toString());
	}

	/**
	 * Set value of UsedQuantity
	 * @param usedquantity
	 */
	public final void setUsedQuantity(java.math.BigDecimal usedquantity)
	{
		setUsedQuantity(getContext(), usedquantity);
	}

	/**
	 * Set value of UsedQuantity
	 * @param context
	 * @param usedquantity
	 */
	public final void setUsedQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal usedquantity)
	{
		getMendixObject().setValue(context, MemberNames.UsedQuantity.toString(), usedquantity);
	}

	/**
	 * @return value of RemainedQuantity
	 */
	public final java.math.BigDecimal getRemainedQuantity()
	{
		return getRemainedQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of RemainedQuantity
	 */
	public final java.math.BigDecimal getRemainedQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RemainedQuantity.toString());
	}

	/**
	 * Set value of RemainedQuantity
	 * @param remainedquantity
	 */
	public final void setRemainedQuantity(java.math.BigDecimal remainedquantity)
	{
		setRemainedQuantity(getContext(), remainedquantity);
	}

	/**
	 * Set value of RemainedQuantity
	 * @param context
	 * @param remainedquantity
	 */
	public final void setRemainedQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal remainedquantity)
	{
		getMendixObject().setValue(context, MemberNames.RemainedQuantity.toString(), remainedquantity);
	}

	/**
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName()
	{
		return getWarehouseName(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseName.toString());
	}

	/**
	 * Set value of WarehouseName
	 * @param warehousename
	 */
	public final void setWarehouseName(java.lang.String warehousename)
	{
		setWarehouseName(getContext(), warehousename);
	}

	/**
	 * Set value of WarehouseName
	 * @param context
	 * @param warehousename
	 */
	public final void setWarehouseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehousename)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseName.toString(), warehousename);
	}

	/**
	 * @return value of WarehouseLocation
	 */
	public final java.lang.String getWarehouseLocation()
	{
		return getWarehouseLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseLocation
	 */
	public final java.lang.String getWarehouseLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseLocation.toString());
	}

	/**
	 * Set value of WarehouseLocation
	 * @param warehouselocation
	 */
	public final void setWarehouseLocation(java.lang.String warehouselocation)
	{
		setWarehouseLocation(getContext(), warehouselocation);
	}

	/**
	 * Set value of WarehouseLocation
	 * @param context
	 * @param warehouselocation
	 */
	public final void setWarehouseLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehouselocation)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseLocation.toString(), warehouselocation);
	}

	/**
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation()
	{
		return getStockLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StockLocation.toString());
	}

	/**
	 * Set value of StockLocation
	 * @param stocklocation
	 */
	public final void setStockLocation(java.lang.String stocklocation)
	{
		setStockLocation(getContext(), stocklocation);
	}

	/**
	 * Set value of StockLocation
	 * @param context
	 * @param stocklocation
	 */
	public final void setStockLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stocklocation)
	{
		getMendixObject().setValue(context, MemberNames.StockLocation.toString(), stocklocation);
	}

	/**
	 * @return value of GatheringCode
	 */
	public final java.lang.String getGatheringCode()
	{
		return getGatheringCode(getContext());
	}

	/**
	 * @param context
	 * @return value of GatheringCode
	 */
	public final java.lang.String getGatheringCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GatheringCode.toString());
	}

	/**
	 * Set value of GatheringCode
	 * @param gatheringcode
	 */
	public final void setGatheringCode(java.lang.String gatheringcode)
	{
		setGatheringCode(getContext(), gatheringcode);
	}

	/**
	 * Set value of GatheringCode
	 * @param context
	 * @param gatheringcode
	 */
	public final void setGatheringCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gatheringcode)
	{
		getMendixObject().setValue(context, MemberNames.GatheringCode.toString(), gatheringcode);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of UsedMaterialHelper_Material
	 */
	public final material_management.proxies.Material getUsedMaterialHelper_Material() throws com.mendix.core.CoreException
	{
		return getUsedMaterialHelper_Material(getContext());
	}

	/**
	 * @param context
	 * @return value of UsedMaterialHelper_Material
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.Material getUsedMaterialHelper_Material(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.Material result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.UsedMaterialHelper_Material.toString());
		if (identifier != null) {
			result = material_management.proxies.Material.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of UsedMaterialHelper_Material
	 * @param usedmaterialhelper_material
	 */
	public final void setUsedMaterialHelper_Material(material_management.proxies.Material usedmaterialhelper_material)
	{
		setUsedMaterialHelper_Material(getContext(), usedmaterialhelper_material);
	}

	/**
	 * Set value of UsedMaterialHelper_Material
	 * @param context
	 * @param usedmaterialhelper_material
	 */
	public final void setUsedMaterialHelper_Material(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.Material usedmaterialhelper_material)
	{
		if (usedmaterialhelper_material == null) {
			getMendixObject().setValue(context, MemberNames.UsedMaterialHelper_Material.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.UsedMaterialHelper_Material.toString(), usedmaterialhelper_material.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return usedMaterialHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.UsedMaterialHelper that = (work_management.proxies.UsedMaterialHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
