// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public class WorkOrderPartners implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderPartnersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderPartners";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PartnerCost("PartnerCost"),
		PartnerWorkStartDate("PartnerWorkStartDate"),
		PartnerWorkEndDate("PartnerWorkEndDate"),
		PartnerWorkTime("PartnerWorkTime"),
		PartnerWorkDescription("PartnerWorkDescription"),
		WorkOrderPartners_WorkOrderResult("Work_Management.WorkOrderPartners_WorkOrderResult"),
		WorkOrderPartners_BusinessPartner("Work_Management.WorkOrderPartners_BusinessPartner");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderPartners(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderPartners(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderPartnersMendixObject)
	{
		if (workOrderPartnersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderPartnersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderPartnersMendixObject = workOrderPartnersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderPartners initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderPartners(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderPartners load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderPartners.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.WorkOrderPartners> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.WorkOrderPartners.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of PartnerCost
	 */
	public final java.lang.Integer getPartnerCost()
	{
		return getPartnerCost(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerCost
	 */
	public final java.lang.Integer getPartnerCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PartnerCost.toString());
	}

	/**
	 * Set value of PartnerCost
	 * @param partnercost
	 */
	public final void setPartnerCost(java.lang.Integer partnercost)
	{
		setPartnerCost(getContext(), partnercost);
	}

	/**
	 * Set value of PartnerCost
	 * @param context
	 * @param partnercost
	 */
	public final void setPartnerCost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer partnercost)
	{
		getMendixObject().setValue(context, MemberNames.PartnerCost.toString(), partnercost);
	}

	/**
	 * @return value of PartnerWorkStartDate
	 */
	public final java.util.Date getPartnerWorkStartDate()
	{
		return getPartnerWorkStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerWorkStartDate
	 */
	public final java.util.Date getPartnerWorkStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PartnerWorkStartDate.toString());
	}

	/**
	 * Set value of PartnerWorkStartDate
	 * @param partnerworkstartdate
	 */
	public final void setPartnerWorkStartDate(java.util.Date partnerworkstartdate)
	{
		setPartnerWorkStartDate(getContext(), partnerworkstartdate);
	}

	/**
	 * Set value of PartnerWorkStartDate
	 * @param context
	 * @param partnerworkstartdate
	 */
	public final void setPartnerWorkStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date partnerworkstartdate)
	{
		getMendixObject().setValue(context, MemberNames.PartnerWorkStartDate.toString(), partnerworkstartdate);
	}

	/**
	 * @return value of PartnerWorkEndDate
	 */
	public final java.util.Date getPartnerWorkEndDate()
	{
		return getPartnerWorkEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerWorkEndDate
	 */
	public final java.util.Date getPartnerWorkEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.PartnerWorkEndDate.toString());
	}

	/**
	 * Set value of PartnerWorkEndDate
	 * @param partnerworkenddate
	 */
	public final void setPartnerWorkEndDate(java.util.Date partnerworkenddate)
	{
		setPartnerWorkEndDate(getContext(), partnerworkenddate);
	}

	/**
	 * Set value of PartnerWorkEndDate
	 * @param context
	 * @param partnerworkenddate
	 */
	public final void setPartnerWorkEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date partnerworkenddate)
	{
		getMendixObject().setValue(context, MemberNames.PartnerWorkEndDate.toString(), partnerworkenddate);
	}

	/**
	 * @return value of PartnerWorkTime
	 */
	public final java.lang.String getPartnerWorkTime()
	{
		return getPartnerWorkTime(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerWorkTime
	 */
	public final java.lang.String getPartnerWorkTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerWorkTime.toString());
	}

	/**
	 * Set value of PartnerWorkTime
	 * @param partnerworktime
	 */
	public final void setPartnerWorkTime(java.lang.String partnerworktime)
	{
		setPartnerWorkTime(getContext(), partnerworktime);
	}

	/**
	 * Set value of PartnerWorkTime
	 * @param context
	 * @param partnerworktime
	 */
	public final void setPartnerWorkTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnerworktime)
	{
		getMendixObject().setValue(context, MemberNames.PartnerWorkTime.toString(), partnerworktime);
	}

	/**
	 * @return value of PartnerWorkDescription
	 */
	public final java.lang.String getPartnerWorkDescription()
	{
		return getPartnerWorkDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerWorkDescription
	 */
	public final java.lang.String getPartnerWorkDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerWorkDescription.toString());
	}

	/**
	 * Set value of PartnerWorkDescription
	 * @param partnerworkdescription
	 */
	public final void setPartnerWorkDescription(java.lang.String partnerworkdescription)
	{
		setPartnerWorkDescription(getContext(), partnerworkdescription);
	}

	/**
	 * Set value of PartnerWorkDescription
	 * @param context
	 * @param partnerworkdescription
	 */
	public final void setPartnerWorkDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnerworkdescription)
	{
		getMendixObject().setValue(context, MemberNames.PartnerWorkDescription.toString(), partnerworkdescription);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderPartners_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderPartners_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getWorkOrderPartners_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderPartners_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderPartners_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderPartners_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderPartners_WorkOrderResult
	 * @param workorderpartners_workorderresult
	 */
	public final void setWorkOrderPartners_WorkOrderResult(work_management.proxies.WorkOrderResult workorderpartners_workorderresult)
	{
		setWorkOrderPartners_WorkOrderResult(getContext(), workorderpartners_workorderresult);
	}

	/**
	 * Set value of WorkOrderPartners_WorkOrderResult
	 * @param context
	 * @param workorderpartners_workorderresult
	 */
	public final void setWorkOrderPartners_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderResult workorderpartners_workorderresult)
	{
		if (workorderpartners_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderPartners_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderPartners_WorkOrderResult.toString(), workorderpartners_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderPartners_BusinessPartner
	 */
	public final material_management.proxies.BusinessPartner getWorkOrderPartners_BusinessPartner() throws com.mendix.core.CoreException
	{
		return getWorkOrderPartners_BusinessPartner(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderPartners_BusinessPartner
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.BusinessPartner getWorkOrderPartners_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.BusinessPartner result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderPartners_BusinessPartner.toString());
		if (identifier != null) {
			result = material_management.proxies.BusinessPartner.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderPartners_BusinessPartner
	 * @param workorderpartners_businesspartner
	 */
	public final void setWorkOrderPartners_BusinessPartner(material_management.proxies.BusinessPartner workorderpartners_businesspartner)
	{
		setWorkOrderPartners_BusinessPartner(getContext(), workorderpartners_businesspartner);
	}

	/**
	 * Set value of WorkOrderPartners_BusinessPartner
	 * @param context
	 * @param workorderpartners_businesspartner
	 */
	public final void setWorkOrderPartners_BusinessPartner(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.BusinessPartner workorderpartners_businesspartner)
	{
		if (workorderpartners_businesspartner == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderPartners_BusinessPartner.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderPartners_BusinessPartner.toString(), workorderpartners_businesspartner.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderPartnersMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderPartners that = (work_management.proxies.WorkOrderPartners) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
