// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/20
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/20
 * 설명 : 작업관리 화면의 페이지 헬퍼로 현재 공장, 로그인 사원, 사원의 부서 정보 및 검색 필터를 담는 헬퍼이다.
 * Version 1.0 : 생성
 */
public class WorkOrderPageHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderPageHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderPageHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UserFilter("UserFilter"),
		WorkOrderPageHelper_WorkBoardCountHelper("Work_Management.WorkOrderPageHelper_WorkBoardCountHelper"),
		WorkOrderPageHelper_Employee("Work_Management.WorkOrderPageHelper_Employee"),
		WorkOrderPageHelper_Department("Work_Management.WorkOrderPageHelper_Department"),
		WorkOrderPageHelper_Plant("Work_Management.WorkOrderPageHelper_Plant"),
		WorkOrderStatusFilter_StandardCode("Work_Management.WorkOrderStatusFilter_StandardCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderPageHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderPageHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderPageHelperMendixObject)
	{
		if (workOrderPageHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderPageHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderPageHelperMendixObject = workOrderPageHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderPageHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderPageHelper(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderPageHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderPageHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of UserFilter
	 */
	public final java.lang.Boolean getUserFilter()
	{
		return getUserFilter(getContext());
	}

	/**
	 * @param context
	 * @return value of UserFilter
	 */
	public final java.lang.Boolean getUserFilter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.UserFilter.toString());
	}

	/**
	 * Set value of UserFilter
	 * @param userfilter
	 */
	public final void setUserFilter(java.lang.Boolean userfilter)
	{
		setUserFilter(getContext(), userfilter);
	}

	/**
	 * Set value of UserFilter
	 * @param context
	 * @param userfilter
	 */
	public final void setUserFilter(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean userfilter)
	{
		getMendixObject().setValue(context, MemberNames.UserFilter.toString(), userfilter);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderPageHelper_WorkBoardCountHelper
	 */
	public final work_management.proxies.WorkBoardCountHelper getWorkOrderPageHelper_WorkBoardCountHelper() throws com.mendix.core.CoreException
	{
		return getWorkOrderPageHelper_WorkBoardCountHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderPageHelper_WorkBoardCountHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkBoardCountHelper getWorkOrderPageHelper_WorkBoardCountHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkBoardCountHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderPageHelper_WorkBoardCountHelper.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkBoardCountHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderPageHelper_WorkBoardCountHelper
	 * @param workorderpagehelper_workboardcounthelper
	 */
	public final void setWorkOrderPageHelper_WorkBoardCountHelper(work_management.proxies.WorkBoardCountHelper workorderpagehelper_workboardcounthelper)
	{
		setWorkOrderPageHelper_WorkBoardCountHelper(getContext(), workorderpagehelper_workboardcounthelper);
	}

	/**
	 * Set value of WorkOrderPageHelper_WorkBoardCountHelper
	 * @param context
	 * @param workorderpagehelper_workboardcounthelper
	 */
	public final void setWorkOrderPageHelper_WorkBoardCountHelper(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkBoardCountHelper workorderpagehelper_workboardcounthelper)
	{
		if (workorderpagehelper_workboardcounthelper == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_WorkBoardCountHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_WorkBoardCountHelper.toString(), workorderpagehelper_workboardcounthelper.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderPageHelper_Employee
	 */
	public final cmms_administration.proxies.Employee getWorkOrderPageHelper_Employee() throws com.mendix.core.CoreException
	{
		return getWorkOrderPageHelper_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderPageHelper_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getWorkOrderPageHelper_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderPageHelper_Employee.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderPageHelper_Employee
	 * @param workorderpagehelper_employee
	 */
	public final void setWorkOrderPageHelper_Employee(cmms_administration.proxies.Employee workorderpagehelper_employee)
	{
		setWorkOrderPageHelper_Employee(getContext(), workorderpagehelper_employee);
	}

	/**
	 * Set value of WorkOrderPageHelper_Employee
	 * @param context
	 * @param workorderpagehelper_employee
	 */
	public final void setWorkOrderPageHelper_Employee(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee workorderpagehelper_employee)
	{
		if (workorderpagehelper_employee == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_Employee.toString(), workorderpagehelper_employee.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderPageHelper_Department
	 */
	public final cmms_administration.proxies.Department getWorkOrderPageHelper_Department() throws com.mendix.core.CoreException
	{
		return getWorkOrderPageHelper_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderPageHelper_Department
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Department getWorkOrderPageHelper_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderPageHelper_Department.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Department.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderPageHelper_Department
	 * @param workorderpagehelper_department
	 */
	public final void setWorkOrderPageHelper_Department(cmms_administration.proxies.Department workorderpagehelper_department)
	{
		setWorkOrderPageHelper_Department(getContext(), workorderpagehelper_department);
	}

	/**
	 * Set value of WorkOrderPageHelper_Department
	 * @param context
	 * @param workorderpagehelper_department
	 */
	public final void setWorkOrderPageHelper_Department(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Department workorderpagehelper_department)
	{
		if (workorderpagehelper_department == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_Department.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_Department.toString(), workorderpagehelper_department.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderPageHelper_Plant
	 */
	public final cmms_administration.proxies.Plant getWorkOrderPageHelper_Plant() throws com.mendix.core.CoreException
	{
		return getWorkOrderPageHelper_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderPageHelper_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getWorkOrderPageHelper_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderPageHelper_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderPageHelper_Plant
	 * @param workorderpagehelper_plant
	 */
	public final void setWorkOrderPageHelper_Plant(cmms_administration.proxies.Plant workorderpagehelper_plant)
	{
		setWorkOrderPageHelper_Plant(getContext(), workorderpagehelper_plant);
	}

	/**
	 * Set value of WorkOrderPageHelper_Plant
	 * @param context
	 * @param workorderpagehelper_plant
	 */
	public final void setWorkOrderPageHelper_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant workorderpagehelper_plant)
	{
		if (workorderpagehelper_plant == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_Plant.toString(), workorderpagehelper_plant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderStatusFilter_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkOrderStatusFilter_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkOrderStatusFilter_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderStatusFilter_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkOrderStatusFilter_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderStatusFilter_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderStatusFilter_StandardCode
	 * @param workorderstatusfilter_standardcode
	 */
	public final void setWorkOrderStatusFilter_StandardCode(commons.proxies.StandardCode workorderstatusfilter_standardcode)
	{
		setWorkOrderStatusFilter_StandardCode(getContext(), workorderstatusfilter_standardcode);
	}

	/**
	 * Set value of WorkOrderStatusFilter_StandardCode
	 * @param context
	 * @param workorderstatusfilter_standardcode
	 */
	public final void setWorkOrderStatusFilter_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workorderstatusfilter_standardcode)
	{
		if (workorderstatusfilter_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderStatusFilter_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderStatusFilter_StandardCode.toString(), workorderstatusfilter_standardcode.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderPageHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderPageHelper that = (work_management.proxies.WorkOrderPageHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
