// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public class WorkOrderMaterials implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderMaterialsMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderMaterials";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		UsedQuantity("UsedQuantity"),
		MaterialCost("MaterialCost"),
		UsedMaterialDescription("UsedMaterialDescription"),
		RemainedQuantity("RemainedQuantity"),
		WarehouseName("WarehouseName"),
		WarehouseLocation("WarehouseLocation"),
		StockLocation("StockLocation"),
		GatheringCode("GatheringCode"),
		WorkOrderMaterials_WorkOrderResult("Work_Management.WorkOrderMaterials_WorkOrderResult"),
		WorkOrderMaterials_WorkOrderTasks("Work_Management.WorkOrderMaterials_WorkOrderTasks"),
		WorkOrderMaterials_Material("Work_Management.WorkOrderMaterials_Material");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderMaterials(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderMaterials(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderMaterialsMendixObject)
	{
		if (workOrderMaterialsMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderMaterialsMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderMaterialsMendixObject = workOrderMaterialsMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderMaterials initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderMaterials(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderMaterials load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderMaterials.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.WorkOrderMaterials> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.WorkOrderMaterials.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of UsedQuantity
	 */
	public final java.math.BigDecimal getUsedQuantity()
	{
		return getUsedQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of UsedQuantity
	 */
	public final java.math.BigDecimal getUsedQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.UsedQuantity.toString());
	}

	/**
	 * Set value of UsedQuantity
	 * @param usedquantity
	 */
	public final void setUsedQuantity(java.math.BigDecimal usedquantity)
	{
		setUsedQuantity(getContext(), usedquantity);
	}

	/**
	 * Set value of UsedQuantity
	 * @param context
	 * @param usedquantity
	 */
	public final void setUsedQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal usedquantity)
	{
		getMendixObject().setValue(context, MemberNames.UsedQuantity.toString(), usedquantity);
	}

	/**
	 * @return value of MaterialCost
	 */
	public final java.math.BigDecimal getMaterialCost()
	{
		return getMaterialCost(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCost
	 */
	public final java.math.BigDecimal getMaterialCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaterialCost.toString());
	}

	/**
	 * Set value of MaterialCost
	 * @param materialcost
	 */
	public final void setMaterialCost(java.math.BigDecimal materialcost)
	{
		setMaterialCost(getContext(), materialcost);
	}

	/**
	 * Set value of MaterialCost
	 * @param context
	 * @param materialcost
	 */
	public final void setMaterialCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal materialcost)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCost.toString(), materialcost);
	}

	/**
	 * @return value of UsedMaterialDescription
	 */
	public final java.lang.String getUsedMaterialDescription()
	{
		return getUsedMaterialDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of UsedMaterialDescription
	 */
	public final java.lang.String getUsedMaterialDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.UsedMaterialDescription.toString());
	}

	/**
	 * Set value of UsedMaterialDescription
	 * @param usedmaterialdescription
	 */
	public final void setUsedMaterialDescription(java.lang.String usedmaterialdescription)
	{
		setUsedMaterialDescription(getContext(), usedmaterialdescription);
	}

	/**
	 * Set value of UsedMaterialDescription
	 * @param context
	 * @param usedmaterialdescription
	 */
	public final void setUsedMaterialDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String usedmaterialdescription)
	{
		getMendixObject().setValue(context, MemberNames.UsedMaterialDescription.toString(), usedmaterialdescription);
	}

	/**
	 * @return value of RemainedQuantity
	 */
	public final java.math.BigDecimal getRemainedQuantity()
	{
		return getRemainedQuantity(getContext());
	}

	/**
	 * @param context
	 * @return value of RemainedQuantity
	 */
	public final java.math.BigDecimal getRemainedQuantity(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.RemainedQuantity.toString());
	}

	/**
	 * Set value of RemainedQuantity
	 * @param remainedquantity
	 */
	public final void setRemainedQuantity(java.math.BigDecimal remainedquantity)
	{
		setRemainedQuantity(getContext(), remainedquantity);
	}

	/**
	 * Set value of RemainedQuantity
	 * @param context
	 * @param remainedquantity
	 */
	public final void setRemainedQuantity(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal remainedquantity)
	{
		getMendixObject().setValue(context, MemberNames.RemainedQuantity.toString(), remainedquantity);
	}

	/**
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName()
	{
		return getWarehouseName(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseName
	 */
	public final java.lang.String getWarehouseName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseName.toString());
	}

	/**
	 * Set value of WarehouseName
	 * @param warehousename
	 */
	public final void setWarehouseName(java.lang.String warehousename)
	{
		setWarehouseName(getContext(), warehousename);
	}

	/**
	 * Set value of WarehouseName
	 * @param context
	 * @param warehousename
	 */
	public final void setWarehouseName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehousename)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseName.toString(), warehousename);
	}

	/**
	 * @return value of WarehouseLocation
	 */
	public final java.lang.String getWarehouseLocation()
	{
		return getWarehouseLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of WarehouseLocation
	 */
	public final java.lang.String getWarehouseLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WarehouseLocation.toString());
	}

	/**
	 * Set value of WarehouseLocation
	 * @param warehouselocation
	 */
	public final void setWarehouseLocation(java.lang.String warehouselocation)
	{
		setWarehouseLocation(getContext(), warehouselocation);
	}

	/**
	 * Set value of WarehouseLocation
	 * @param context
	 * @param warehouselocation
	 */
	public final void setWarehouseLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String warehouselocation)
	{
		getMendixObject().setValue(context, MemberNames.WarehouseLocation.toString(), warehouselocation);
	}

	/**
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation()
	{
		return getStockLocation(getContext());
	}

	/**
	 * @param context
	 * @return value of StockLocation
	 */
	public final java.lang.String getStockLocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.StockLocation.toString());
	}

	/**
	 * Set value of StockLocation
	 * @param stocklocation
	 */
	public final void setStockLocation(java.lang.String stocklocation)
	{
		setStockLocation(getContext(), stocklocation);
	}

	/**
	 * Set value of StockLocation
	 * @param context
	 * @param stocklocation
	 */
	public final void setStockLocation(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String stocklocation)
	{
		getMendixObject().setValue(context, MemberNames.StockLocation.toString(), stocklocation);
	}

	/**
	 * @return value of GatheringCode
	 */
	public final java.lang.String getGatheringCode()
	{
		return getGatheringCode(getContext());
	}

	/**
	 * @param context
	 * @return value of GatheringCode
	 */
	public final java.lang.String getGatheringCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.GatheringCode.toString());
	}

	/**
	 * Set value of GatheringCode
	 * @param gatheringcode
	 */
	public final void setGatheringCode(java.lang.String gatheringcode)
	{
		setGatheringCode(getContext(), gatheringcode);
	}

	/**
	 * Set value of GatheringCode
	 * @param context
	 * @param gatheringcode
	 */
	public final void setGatheringCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String gatheringcode)
	{
		getMendixObject().setValue(context, MemberNames.GatheringCode.toString(), gatheringcode);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderMaterials_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderMaterials_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getWorkOrderMaterials_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderMaterials_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderMaterials_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderMaterials_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderMaterials_WorkOrderResult
	 * @param workordermaterials_workorderresult
	 */
	public final void setWorkOrderMaterials_WorkOrderResult(work_management.proxies.WorkOrderResult workordermaterials_workorderresult)
	{
		setWorkOrderMaterials_WorkOrderResult(getContext(), workordermaterials_workorderresult);
	}

	/**
	 * Set value of WorkOrderMaterials_WorkOrderResult
	 * @param context
	 * @param workordermaterials_workorderresult
	 */
	public final void setWorkOrderMaterials_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderResult workordermaterials_workorderresult)
	{
		if (workordermaterials_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderMaterials_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderMaterials_WorkOrderResult.toString(), workordermaterials_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderMaterials_WorkOrderTasks
	 */
	public final work_management.proxies.WorkOrderTasks getWorkOrderMaterials_WorkOrderTasks() throws com.mendix.core.CoreException
	{
		return getWorkOrderMaterials_WorkOrderTasks(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderMaterials_WorkOrderTasks
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderTasks getWorkOrderMaterials_WorkOrderTasks(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderTasks result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderMaterials_WorkOrderTasks.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderTasks.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderMaterials_WorkOrderTasks
	 * @param workordermaterials_workordertasks
	 */
	public final void setWorkOrderMaterials_WorkOrderTasks(work_management.proxies.WorkOrderTasks workordermaterials_workordertasks)
	{
		setWorkOrderMaterials_WorkOrderTasks(getContext(), workordermaterials_workordertasks);
	}

	/**
	 * Set value of WorkOrderMaterials_WorkOrderTasks
	 * @param context
	 * @param workordermaterials_workordertasks
	 */
	public final void setWorkOrderMaterials_WorkOrderTasks(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderTasks workordermaterials_workordertasks)
	{
		if (workordermaterials_workordertasks == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderMaterials_WorkOrderTasks.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderMaterials_WorkOrderTasks.toString(), workordermaterials_workordertasks.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderMaterials_Material
	 */
	public final material_management.proxies.Material getWorkOrderMaterials_Material() throws com.mendix.core.CoreException
	{
		return getWorkOrderMaterials_Material(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderMaterials_Material
	 * @throws com.mendix.core.CoreException
	 */
	public final material_management.proxies.Material getWorkOrderMaterials_Material(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		material_management.proxies.Material result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderMaterials_Material.toString());
		if (identifier != null) {
			result = material_management.proxies.Material.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderMaterials_Material
	 * @param workordermaterials_material
	 */
	public final void setWorkOrderMaterials_Material(material_management.proxies.Material workordermaterials_material)
	{
		setWorkOrderMaterials_Material(getContext(), workordermaterials_material);
	}

	/**
	 * Set value of WorkOrderMaterials_Material
	 * @param context
	 * @param workordermaterials_material
	 */
	public final void setWorkOrderMaterials_Material(com.mendix.systemwideinterfaces.core.IContext context, material_management.proxies.Material workordermaterials_material)
	{
		if (workordermaterials_material == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderMaterials_Material.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderMaterials_Material.toString(), workordermaterials_material.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderMaterialsMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderMaterials that = (work_management.proxies.WorkOrderMaterials) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
