// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/10
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/10
 * 설명 : 작업요청/워크오더 내용을 답는 엔터티\\
 * Version 1.0 : 생성
 */
public class WorkOrderResult extends globalsearch.proxies.SearchableObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkStartDate("WorkStartDate"),
		WorkEndDate("WorkEndDate"),
		EquipmentStopTime("EquipmentStopTime"),
		EstimatedCost("EstimatedCost"),
		WorkDescription("WorkDescription"),
		RequestPlanDate("RequestPlanDate"),
		RequestPlanDescription("RequestPlanDescription"),
		TaskTaskCount("TaskTaskCount"),
		TaskFailureCount("TaskFailureCount"),
		FailureTypeDescription("FailureTypeDescription"),
		FailureReasonDescription("FailureReasonDescription"),
		CorrectiveActionDescription("CorrectiveActionDescription"),
		MaterialCost("MaterialCost"),
		PartnerCost("PartnerCost"),
		LaborCost("LaborCost"),
		ETCCost("ETCCost"),
		TotalCost("TotalCost"),
		IsWorkTaskRecord("IsWorkTaskRecord"),
		IsErrorMaintenance("IsErrorMaintenance"),
		TotalTasktimeHour("TotalTasktimeHour"),
		WorkOrder_WorkOrderResult("Work_Management.WorkOrder_WorkOrderResult"),
		ResultFile_WorkOrderResult("Work_Management.ResultFile_WorkOrderResult"),
		BeforeImage_WorkOrderResult("Work_Management.BeforeImage_WorkOrderResult"),
		AfterImage_WorkOrderResult("Work_Management.AfterImage_WorkOrderResult"),
		WorkOrderCostCenter_StandardCode("Work_Management.WorkOrderCostCenter_StandardCode"),
		WorkOrderFailureType_StandardCode("Work_Management.WorkOrderFailureType_StandardCode"),
		WorkOrderFailureReason_StandardCode("Work_Management.WorkOrderFailureReason_StandardCode"),
		WorkOrderCorrectiveAction_StandardCode("Work_Management.WorkOrderCorrectiveAction_StandardCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderResultMendixObject)
	{
		super(context, workOrderResultMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderResultMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderResult(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderResult.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.WorkOrderResult> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.WorkOrderResult.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of WorkStartDate
	 */
	public final java.util.Date getWorkStartDate()
	{
		return getWorkStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkStartDate
	 */
	public final java.util.Date getWorkStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkStartDate.toString());
	}

	/**
	 * Set value of WorkStartDate
	 * @param workstartdate
	 */
	public final void setWorkStartDate(java.util.Date workstartdate)
	{
		setWorkStartDate(getContext(), workstartdate);
	}

	/**
	 * Set value of WorkStartDate
	 * @param context
	 * @param workstartdate
	 */
	public final void setWorkStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workstartdate)
	{
		getMendixObject().setValue(context, MemberNames.WorkStartDate.toString(), workstartdate);
	}

	/**
	 * @return value of WorkEndDate
	 */
	public final java.util.Date getWorkEndDate()
	{
		return getWorkEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkEndDate
	 */
	public final java.util.Date getWorkEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkEndDate.toString());
	}

	/**
	 * Set value of WorkEndDate
	 * @param workenddate
	 */
	public final void setWorkEndDate(java.util.Date workenddate)
	{
		setWorkEndDate(getContext(), workenddate);
	}

	/**
	 * Set value of WorkEndDate
	 * @param context
	 * @param workenddate
	 */
	public final void setWorkEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workenddate)
	{
		getMendixObject().setValue(context, MemberNames.WorkEndDate.toString(), workenddate);
	}

	/**
	 * @return value of EquipmentStopTime
	 */
	public final java.math.BigDecimal getEquipmentStopTime()
	{
		return getEquipmentStopTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentStopTime
	 */
	public final java.math.BigDecimal getEquipmentStopTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.EquipmentStopTime.toString());
	}

	/**
	 * Set value of EquipmentStopTime
	 * @param equipmentstoptime
	 */
	public final void setEquipmentStopTime(java.math.BigDecimal equipmentstoptime)
	{
		setEquipmentStopTime(getContext(), equipmentstoptime);
	}

	/**
	 * Set value of EquipmentStopTime
	 * @param context
	 * @param equipmentstoptime
	 */
	public final void setEquipmentStopTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal equipmentstoptime)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentStopTime.toString(), equipmentstoptime);
	}

	/**
	 * @return value of EstimatedCost
	 */
	public final java.lang.Integer getEstimatedCost()
	{
		return getEstimatedCost(getContext());
	}

	/**
	 * @param context
	 * @return value of EstimatedCost
	 */
	public final java.lang.Integer getEstimatedCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.EstimatedCost.toString());
	}

	/**
	 * Set value of EstimatedCost
	 * @param estimatedcost
	 */
	public final void setEstimatedCost(java.lang.Integer estimatedcost)
	{
		setEstimatedCost(getContext(), estimatedcost);
	}

	/**
	 * Set value of EstimatedCost
	 * @param context
	 * @param estimatedcost
	 */
	public final void setEstimatedCost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer estimatedcost)
	{
		getMendixObject().setValue(context, MemberNames.EstimatedCost.toString(), estimatedcost);
	}

	/**
	 * @return value of WorkDescription
	 */
	public final java.lang.String getWorkDescription()
	{
		return getWorkDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkDescription
	 */
	public final java.lang.String getWorkDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkDescription.toString());
	}

	/**
	 * Set value of WorkDescription
	 * @param workdescription
	 */
	public final void setWorkDescription(java.lang.String workdescription)
	{
		setWorkDescription(getContext(), workdescription);
	}

	/**
	 * Set value of WorkDescription
	 * @param context
	 * @param workdescription
	 */
	public final void setWorkDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workdescription)
	{
		getMendixObject().setValue(context, MemberNames.WorkDescription.toString(), workdescription);
	}

	/**
	 * @return value of RequestPlanDate
	 */
	public final java.util.Date getRequestPlanDate()
	{
		return getRequestPlanDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestPlanDate
	 */
	public final java.util.Date getRequestPlanDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RequestPlanDate.toString());
	}

	/**
	 * Set value of RequestPlanDate
	 * @param requestplandate
	 */
	public final void setRequestPlanDate(java.util.Date requestplandate)
	{
		setRequestPlanDate(getContext(), requestplandate);
	}

	/**
	 * Set value of RequestPlanDate
	 * @param context
	 * @param requestplandate
	 */
	public final void setRequestPlanDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date requestplandate)
	{
		getMendixObject().setValue(context, MemberNames.RequestPlanDate.toString(), requestplandate);
	}

	/**
	 * @return value of RequestPlanDescription
	 */
	public final java.lang.String getRequestPlanDescription()
	{
		return getRequestPlanDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestPlanDescription
	 */
	public final java.lang.String getRequestPlanDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestPlanDescription.toString());
	}

	/**
	 * Set value of RequestPlanDescription
	 * @param requestplandescription
	 */
	public final void setRequestPlanDescription(java.lang.String requestplandescription)
	{
		setRequestPlanDescription(getContext(), requestplandescription);
	}

	/**
	 * Set value of RequestPlanDescription
	 * @param context
	 * @param requestplandescription
	 */
	public final void setRequestPlanDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestplandescription)
	{
		getMendixObject().setValue(context, MemberNames.RequestPlanDescription.toString(), requestplandescription);
	}

	/**
	 * @return value of TaskTaskCount
	 */
	public final java.lang.Integer getTaskTaskCount()
	{
		return getTaskTaskCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskTaskCount
	 */
	public final java.lang.Integer getTaskTaskCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TaskTaskCount.toString());
	}

	/**
	 * Set value of TaskTaskCount
	 * @param tasktaskcount
	 */
	public final void setTaskTaskCount(java.lang.Integer tasktaskcount)
	{
		setTaskTaskCount(getContext(), tasktaskcount);
	}

	/**
	 * Set value of TaskTaskCount
	 * @param context
	 * @param tasktaskcount
	 */
	public final void setTaskTaskCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer tasktaskcount)
	{
		getMendixObject().setValue(context, MemberNames.TaskTaskCount.toString(), tasktaskcount);
	}

	/**
	 * @return value of TaskFailureCount
	 */
	public final java.lang.Integer getTaskFailureCount()
	{
		return getTaskFailureCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskFailureCount
	 */
	public final java.lang.Integer getTaskFailureCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TaskFailureCount.toString());
	}

	/**
	 * Set value of TaskFailureCount
	 * @param taskfailurecount
	 */
	public final void setTaskFailureCount(java.lang.Integer taskfailurecount)
	{
		setTaskFailureCount(getContext(), taskfailurecount);
	}

	/**
	 * Set value of TaskFailureCount
	 * @param context
	 * @param taskfailurecount
	 */
	public final void setTaskFailureCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer taskfailurecount)
	{
		getMendixObject().setValue(context, MemberNames.TaskFailureCount.toString(), taskfailurecount);
	}

	/**
	 * @return value of FailureTypeDescription
	 */
	public final java.lang.String getFailureTypeDescription()
	{
		return getFailureTypeDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of FailureTypeDescription
	 */
	public final java.lang.String getFailureTypeDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FailureTypeDescription.toString());
	}

	/**
	 * Set value of FailureTypeDescription
	 * @param failuretypedescription
	 */
	public final void setFailureTypeDescription(java.lang.String failuretypedescription)
	{
		setFailureTypeDescription(getContext(), failuretypedescription);
	}

	/**
	 * Set value of FailureTypeDescription
	 * @param context
	 * @param failuretypedescription
	 */
	public final void setFailureTypeDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String failuretypedescription)
	{
		getMendixObject().setValue(context, MemberNames.FailureTypeDescription.toString(), failuretypedescription);
	}

	/**
	 * @return value of FailureReasonDescription
	 */
	public final java.lang.String getFailureReasonDescription()
	{
		return getFailureReasonDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of FailureReasonDescription
	 */
	public final java.lang.String getFailureReasonDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FailureReasonDescription.toString());
	}

	/**
	 * Set value of FailureReasonDescription
	 * @param failurereasondescription
	 */
	public final void setFailureReasonDescription(java.lang.String failurereasondescription)
	{
		setFailureReasonDescription(getContext(), failurereasondescription);
	}

	/**
	 * Set value of FailureReasonDescription
	 * @param context
	 * @param failurereasondescription
	 */
	public final void setFailureReasonDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String failurereasondescription)
	{
		getMendixObject().setValue(context, MemberNames.FailureReasonDescription.toString(), failurereasondescription);
	}

	/**
	 * @return value of CorrectiveActionDescription
	 */
	public final java.lang.String getCorrectiveActionDescription()
	{
		return getCorrectiveActionDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of CorrectiveActionDescription
	 */
	public final java.lang.String getCorrectiveActionDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CorrectiveActionDescription.toString());
	}

	/**
	 * Set value of CorrectiveActionDescription
	 * @param correctiveactiondescription
	 */
	public final void setCorrectiveActionDescription(java.lang.String correctiveactiondescription)
	{
		setCorrectiveActionDescription(getContext(), correctiveactiondescription);
	}

	/**
	 * Set value of CorrectiveActionDescription
	 * @param context
	 * @param correctiveactiondescription
	 */
	public final void setCorrectiveActionDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String correctiveactiondescription)
	{
		getMendixObject().setValue(context, MemberNames.CorrectiveActionDescription.toString(), correctiveactiondescription);
	}

	/**
	 * @return value of MaterialCost
	 */
	public final java.math.BigDecimal getMaterialCost()
	{
		return getMaterialCost(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCost
	 */
	public final java.math.BigDecimal getMaterialCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaterialCost.toString());
	}

	/**
	 * Set value of MaterialCost
	 * @param materialcost
	 */
	public final void setMaterialCost(java.math.BigDecimal materialcost)
	{
		setMaterialCost(getContext(), materialcost);
	}

	/**
	 * Set value of MaterialCost
	 * @param context
	 * @param materialcost
	 */
	public final void setMaterialCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal materialcost)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCost.toString(), materialcost);
	}

	/**
	 * @return value of PartnerCost
	 */
	public final java.math.BigDecimal getPartnerCost()
	{
		return getPartnerCost(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerCost
	 */
	public final java.math.BigDecimal getPartnerCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PartnerCost.toString());
	}

	/**
	 * Set value of PartnerCost
	 * @param partnercost
	 */
	public final void setPartnerCost(java.math.BigDecimal partnercost)
	{
		setPartnerCost(getContext(), partnercost);
	}

	/**
	 * Set value of PartnerCost
	 * @param context
	 * @param partnercost
	 */
	public final void setPartnerCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal partnercost)
	{
		getMendixObject().setValue(context, MemberNames.PartnerCost.toString(), partnercost);
	}

	/**
	 * @return value of LaborCost
	 */
	public final java.math.BigDecimal getLaborCost()
	{
		return getLaborCost(getContext());
	}

	/**
	 * @param context
	 * @return value of LaborCost
	 */
	public final java.math.BigDecimal getLaborCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LaborCost.toString());
	}

	/**
	 * Set value of LaborCost
	 * @param laborcost
	 */
	public final void setLaborCost(java.math.BigDecimal laborcost)
	{
		setLaborCost(getContext(), laborcost);
	}

	/**
	 * Set value of LaborCost
	 * @param context
	 * @param laborcost
	 */
	public final void setLaborCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal laborcost)
	{
		getMendixObject().setValue(context, MemberNames.LaborCost.toString(), laborcost);
	}

	/**
	 * @return value of ETCCost
	 */
	public final java.math.BigDecimal getETCCost()
	{
		return getETCCost(getContext());
	}

	/**
	 * @param context
	 * @return value of ETCCost
	 */
	public final java.math.BigDecimal getETCCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ETCCost.toString());
	}

	/**
	 * Set value of ETCCost
	 * @param etccost
	 */
	public final void setETCCost(java.math.BigDecimal etccost)
	{
		setETCCost(getContext(), etccost);
	}

	/**
	 * Set value of ETCCost
	 * @param context
	 * @param etccost
	 */
	public final void setETCCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal etccost)
	{
		getMendixObject().setValue(context, MemberNames.ETCCost.toString(), etccost);
	}

	/**
	 * @return value of TotalCost
	 */
	public final java.math.BigDecimal getTotalCost()
	{
		return getTotalCost(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCost
	 */
	public final java.math.BigDecimal getTotalCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalCost.toString());
	}

	/**
	 * Set value of TotalCost
	 * @param totalcost
	 */
	public final void setTotalCost(java.math.BigDecimal totalcost)
	{
		setTotalCost(getContext(), totalcost);
	}

	/**
	 * Set value of TotalCost
	 * @param context
	 * @param totalcost
	 */
	public final void setTotalCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalcost)
	{
		getMendixObject().setValue(context, MemberNames.TotalCost.toString(), totalcost);
	}

	/**
	 * @return value of IsWorkTaskRecord
	 */
	public final java.lang.Boolean getIsWorkTaskRecord()
	{
		return getIsWorkTaskRecord(getContext());
	}

	/**
	 * @param context
	 * @return value of IsWorkTaskRecord
	 */
	public final java.lang.Boolean getIsWorkTaskRecord(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsWorkTaskRecord.toString());
	}

	/**
	 * Set value of IsWorkTaskRecord
	 * @param isworktaskrecord
	 */
	public final void setIsWorkTaskRecord(java.lang.Boolean isworktaskrecord)
	{
		setIsWorkTaskRecord(getContext(), isworktaskrecord);
	}

	/**
	 * Set value of IsWorkTaskRecord
	 * @param context
	 * @param isworktaskrecord
	 */
	public final void setIsWorkTaskRecord(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean isworktaskrecord)
	{
		getMendixObject().setValue(context, MemberNames.IsWorkTaskRecord.toString(), isworktaskrecord);
	}

	/**
	 * @return value of IsErrorMaintenance
	 */
	public final java.lang.Boolean getIsErrorMaintenance()
	{
		return getIsErrorMaintenance(getContext());
	}

	/**
	 * @param context
	 * @return value of IsErrorMaintenance
	 */
	public final java.lang.Boolean getIsErrorMaintenance(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.IsErrorMaintenance.toString());
	}

	/**
	 * Set value of IsErrorMaintenance
	 * @param iserrormaintenance
	 */
	public final void setIsErrorMaintenance(java.lang.Boolean iserrormaintenance)
	{
		setIsErrorMaintenance(getContext(), iserrormaintenance);
	}

	/**
	 * Set value of IsErrorMaintenance
	 * @param context
	 * @param iserrormaintenance
	 */
	public final void setIsErrorMaintenance(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean iserrormaintenance)
	{
		getMendixObject().setValue(context, MemberNames.IsErrorMaintenance.toString(), iserrormaintenance);
	}

	/**
	 * @return value of TotalTasktimeHour
	 */
	public final java.math.BigDecimal getTotalTasktimeHour()
	{
		return getTotalTasktimeHour(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalTasktimeHour
	 */
	public final java.math.BigDecimal getTotalTasktimeHour(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalTasktimeHour.toString());
	}

	/**
	 * Set value of TotalTasktimeHour
	 * @param totaltasktimehour
	 */
	public final void setTotalTasktimeHour(java.math.BigDecimal totaltasktimehour)
	{
		setTotalTasktimeHour(getContext(), totaltasktimehour);
	}

	/**
	 * Set value of TotalTasktimeHour
	 * @param context
	 * @param totaltasktimehour
	 */
	public final void setTotalTasktimeHour(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totaltasktimehour)
	{
		getMendixObject().setValue(context, MemberNames.TotalTasktimeHour.toString(), totaltasktimehour);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrder_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrder getWorkOrder_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getWorkOrder_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrder_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrder getWorkOrder_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrder result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrder_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrder.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrder_WorkOrderResult
	 * @param workorder_workorderresult
	 */
	public final void setWorkOrder_WorkOrderResult(work_management.proxies.WorkOrder workorder_workorderresult)
	{
		setWorkOrder_WorkOrderResult(getContext(), workorder_workorderresult);
	}

	/**
	 * Set value of WorkOrder_WorkOrderResult
	 * @param context
	 * @param workorder_workorderresult
	 */
	public final void setWorkOrder_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrder workorder_workorderresult)
	{
		if (workorder_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrder_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrder_WorkOrderResult.toString(), workorder_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ResultFile_WorkOrderResult
	 */
	public final work_management.proxies.ResultFile getResultFile_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getResultFile_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of ResultFile_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.ResultFile getResultFile_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.ResultFile result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ResultFile_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.ResultFile.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ResultFile_WorkOrderResult
	 * @param resultfile_workorderresult
	 */
	public final void setResultFile_WorkOrderResult(work_management.proxies.ResultFile resultfile_workorderresult)
	{
		setResultFile_WorkOrderResult(getContext(), resultfile_workorderresult);
	}

	/**
	 * Set value of ResultFile_WorkOrderResult
	 * @param context
	 * @param resultfile_workorderresult
	 */
	public final void setResultFile_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.ResultFile resultfile_workorderresult)
	{
		if (resultfile_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.ResultFile_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ResultFile_WorkOrderResult.toString(), resultfile_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of BeforeImage_WorkOrderResult
	 */
	public final work_management.proxies.ResultImage getBeforeImage_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getBeforeImage_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of BeforeImage_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.ResultImage getBeforeImage_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.ResultImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.BeforeImage_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.ResultImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of BeforeImage_WorkOrderResult
	 * @param beforeimage_workorderresult
	 */
	public final void setBeforeImage_WorkOrderResult(work_management.proxies.ResultImage beforeimage_workorderresult)
	{
		setBeforeImage_WorkOrderResult(getContext(), beforeimage_workorderresult);
	}

	/**
	 * Set value of BeforeImage_WorkOrderResult
	 * @param context
	 * @param beforeimage_workorderresult
	 */
	public final void setBeforeImage_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.ResultImage beforeimage_workorderresult)
	{
		if (beforeimage_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.BeforeImage_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.BeforeImage_WorkOrderResult.toString(), beforeimage_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AfterImage_WorkOrderResult
	 */
	public final work_management.proxies.ResultImage getAfterImage_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getAfterImage_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of AfterImage_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.ResultImage getAfterImage_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.ResultImage result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AfterImage_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.ResultImage.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AfterImage_WorkOrderResult
	 * @param afterimage_workorderresult
	 */
	public final void setAfterImage_WorkOrderResult(work_management.proxies.ResultImage afterimage_workorderresult)
	{
		setAfterImage_WorkOrderResult(getContext(), afterimage_workorderresult);
	}

	/**
	 * Set value of AfterImage_WorkOrderResult
	 * @param context
	 * @param afterimage_workorderresult
	 */
	public final void setAfterImage_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.ResultImage afterimage_workorderresult)
	{
		if (afterimage_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.AfterImage_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AfterImage_WorkOrderResult.toString(), afterimage_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderCostCenter_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkOrderCostCenter_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkOrderCostCenter_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderCostCenter_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkOrderCostCenter_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderCostCenter_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderCostCenter_StandardCode
	 * @param workordercostcenter_standardcode
	 */
	public final void setWorkOrderCostCenter_StandardCode(commons.proxies.StandardCode workordercostcenter_standardcode)
	{
		setWorkOrderCostCenter_StandardCode(getContext(), workordercostcenter_standardcode);
	}

	/**
	 * Set value of WorkOrderCostCenter_StandardCode
	 * @param context
	 * @param workordercostcenter_standardcode
	 */
	public final void setWorkOrderCostCenter_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workordercostcenter_standardcode)
	{
		if (workordercostcenter_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderCostCenter_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderCostCenter_StandardCode.toString(), workordercostcenter_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderFailureType_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkOrderFailureType_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkOrderFailureType_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderFailureType_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkOrderFailureType_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderFailureType_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderFailureType_StandardCode
	 * @param workorderfailuretype_standardcode
	 */
	public final void setWorkOrderFailureType_StandardCode(commons.proxies.StandardCode workorderfailuretype_standardcode)
	{
		setWorkOrderFailureType_StandardCode(getContext(), workorderfailuretype_standardcode);
	}

	/**
	 * Set value of WorkOrderFailureType_StandardCode
	 * @param context
	 * @param workorderfailuretype_standardcode
	 */
	public final void setWorkOrderFailureType_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workorderfailuretype_standardcode)
	{
		if (workorderfailuretype_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderFailureType_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderFailureType_StandardCode.toString(), workorderfailuretype_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderFailureReason_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkOrderFailureReason_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkOrderFailureReason_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderFailureReason_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkOrderFailureReason_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderFailureReason_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderFailureReason_StandardCode
	 * @param workorderfailurereason_standardcode
	 */
	public final void setWorkOrderFailureReason_StandardCode(commons.proxies.StandardCode workorderfailurereason_standardcode)
	{
		setWorkOrderFailureReason_StandardCode(getContext(), workorderfailurereason_standardcode);
	}

	/**
	 * Set value of WorkOrderFailureReason_StandardCode
	 * @param context
	 * @param workorderfailurereason_standardcode
	 */
	public final void setWorkOrderFailureReason_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workorderfailurereason_standardcode)
	{
		if (workorderfailurereason_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderFailureReason_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderFailureReason_StandardCode.toString(), workorderfailurereason_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderCorrectiveAction_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkOrderCorrectiveAction_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkOrderCorrectiveAction_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderCorrectiveAction_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkOrderCorrectiveAction_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderCorrectiveAction_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderCorrectiveAction_StandardCode
	 * @param workordercorrectiveaction_standardcode
	 */
	public final void setWorkOrderCorrectiveAction_StandardCode(commons.proxies.StandardCode workordercorrectiveaction_standardcode)
	{
		setWorkOrderCorrectiveAction_StandardCode(getContext(), workordercorrectiveaction_standardcode);
	}

	/**
	 * Set value of WorkOrderCorrectiveAction_StandardCode
	 * @param context
	 * @param workordercorrectiveaction_standardcode
	 */
	public final void setWorkOrderCorrectiveAction_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workordercorrectiveaction_standardcode)
	{
		if (workordercorrectiveaction_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderCorrectiveAction_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderCorrectiveAction_StandardCode.toString(), workordercorrectiveaction_standardcode.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderResult that = (work_management.proxies.WorkOrderResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
