// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/20
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/20
 * 설명 : 작업관리 화면의 도넛 차트를 내용을 담는 엔터티이다
 * Version 1.0 : 생성
 */
public class WorkChart implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workChartMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkChart";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Count("Count"),
		ProcessingStatus("ProcessingStatus"),
		Color("Color"),
		TImeStamp("TImeStamp");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkChart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkChart(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workChartMendixObject)
	{
		if (workChartMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workChartMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workChartMendixObject = workChartMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkChart initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkChart(context, mendixObject);
	}

	public static work_management.proxies.WorkChart load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkChart.initialize(context, mendixObject);
	}

	/**
	 * @return value of Count
	 */
	public final java.lang.Integer getCount()
	{
		return getCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Count
	 */
	public final java.lang.Integer getCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Count.toString());
	}

	/**
	 * Set value of Count
	 * @param count
	 */
	public final void setCount(java.lang.Integer count)
	{
		setCount(getContext(), count);
	}

	/**
	 * Set value of Count
	 * @param context
	 * @param count
	 */
	public final void setCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer count)
	{
		getMendixObject().setValue(context, MemberNames.Count.toString(), count);
	}

	/**
	 * Get value of ProcessingStatus
	 * @param processingstatus
	 */
	public final work_management.proxies.ENUM_WorkOrderStatus getProcessingStatus()
	{
		return getProcessingStatus(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingStatus
	 */
	public final work_management.proxies.ENUM_WorkOrderStatus getProcessingStatus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		Object obj = getMendixObject().getValue(context, MemberNames.ProcessingStatus.toString());
		if (obj == null) {
			return null;
		}
		return work_management.proxies.ENUM_WorkOrderStatus.valueOf((java.lang.String) obj);
	}

	/**
	 * Set value of ProcessingStatus
	 * @param processingstatus
	 */
	public final void setProcessingStatus(work_management.proxies.ENUM_WorkOrderStatus processingstatus)
	{
		setProcessingStatus(getContext(), processingstatus);
	}

	/**
	 * Set value of ProcessingStatus
	 * @param context
	 * @param processingstatus
	 */
	public final void setProcessingStatus(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.ENUM_WorkOrderStatus processingstatus)
	{
		if (processingstatus != null) {
			getMendixObject().setValue(context, MemberNames.ProcessingStatus.toString(), processingstatus.toString());
		} else {
			getMendixObject().setValue(context, MemberNames.ProcessingStatus.toString(), null);
		}
	}

	/**
	 * @return value of Color
	 */
	public final java.lang.String getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final java.lang.String getColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Color.toString());
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(java.lang.String color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String color)
	{
		getMendixObject().setValue(context, MemberNames.Color.toString(), color);
	}

	/**
	 * @return value of TImeStamp
	 */
	public final java.lang.String getTImeStamp()
	{
		return getTImeStamp(getContext());
	}

	/**
	 * @param context
	 * @return value of TImeStamp
	 */
	public final java.lang.String getTImeStamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TImeStamp.toString());
	}

	/**
	 * Set value of TImeStamp
	 * @param timestamp
	 */
	public final void setTImeStamp(java.lang.String timestamp)
	{
		setTImeStamp(getContext(), timestamp);
	}

	/**
	 * Set value of TImeStamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTImeStamp(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String timestamp)
	{
		getMendixObject().setValue(context, MemberNames.TImeStamp.toString(), timestamp);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workChartMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkChart that = (work_management.proxies.WorkChart) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
