// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 박성안
 * 최초 작성일 : 2023/11/29
 * 설명 : WorkOrder Kanban 작업실행, 완료 팝업에 여러 엔터티에 각 연결된 attr를 한번에 보여주기 위함
 * Version 1.0 : 생성
 */
public class WorkOrderToShow implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderToShowMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderToShow";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkerFullName("WorkerFullName"),
		MaterialName("MaterialName"),
		EquipmentName("EquipmentName"),
		PartnerName("PartnerName"),
		TotalTaskCount("TotalTaskCount"),
		FinishedTaskCount("FinishedTaskCount"),
		ProgressRate("ProgressRate");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderToShow(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderToShow(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderToShowMendixObject)
	{
		if (workOrderToShowMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderToShowMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderToShowMendixObject = workOrderToShowMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderToShow initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderToShow(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderToShow load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderToShow.initialize(context, mendixObject);
	}

	/**
	 * @return value of WorkerFullName
	 */
	public final java.lang.String getWorkerFullName()
	{
		return getWorkerFullName(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkerFullName
	 */
	public final java.lang.String getWorkerFullName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkerFullName.toString());
	}

	/**
	 * Set value of WorkerFullName
	 * @param workerfullname
	 */
	public final void setWorkerFullName(java.lang.String workerfullname)
	{
		setWorkerFullName(getContext(), workerfullname);
	}

	/**
	 * Set value of WorkerFullName
	 * @param context
	 * @param workerfullname
	 */
	public final void setWorkerFullName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workerfullname)
	{
		getMendixObject().setValue(context, MemberNames.WorkerFullName.toString(), workerfullname);
	}

	/**
	 * @return value of MaterialName
	 */
	public final java.lang.String getMaterialName()
	{
		return getMaterialName(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialName
	 */
	public final java.lang.String getMaterialName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.MaterialName.toString());
	}

	/**
	 * Set value of MaterialName
	 * @param materialname
	 */
	public final void setMaterialName(java.lang.String materialname)
	{
		setMaterialName(getContext(), materialname);
	}

	/**
	 * Set value of MaterialName
	 * @param context
	 * @param materialname
	 */
	public final void setMaterialName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String materialname)
	{
		getMendixObject().setValue(context, MemberNames.MaterialName.toString(), materialname);
	}

	/**
	 * @return value of EquipmentName
	 */
	public final java.lang.String getEquipmentName()
	{
		return getEquipmentName(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentName
	 */
	public final java.lang.String getEquipmentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EquipmentName.toString());
	}

	/**
	 * Set value of EquipmentName
	 * @param equipmentname
	 */
	public final void setEquipmentName(java.lang.String equipmentname)
	{
		setEquipmentName(getContext(), equipmentname);
	}

	/**
	 * Set value of EquipmentName
	 * @param context
	 * @param equipmentname
	 */
	public final void setEquipmentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String equipmentname)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentName.toString(), equipmentname);
	}

	/**
	 * @return value of PartnerName
	 */
	public final java.lang.String getPartnerName()
	{
		return getPartnerName(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerName
	 */
	public final java.lang.String getPartnerName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PartnerName.toString());
	}

	/**
	 * Set value of PartnerName
	 * @param partnername
	 */
	public final void setPartnerName(java.lang.String partnername)
	{
		setPartnerName(getContext(), partnername);
	}

	/**
	 * Set value of PartnerName
	 * @param context
	 * @param partnername
	 */
	public final void setPartnerName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String partnername)
	{
		getMendixObject().setValue(context, MemberNames.PartnerName.toString(), partnername);
	}

	/**
	 * @return value of TotalTaskCount
	 */
	public final java.lang.Integer getTotalTaskCount()
	{
		return getTotalTaskCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalTaskCount
	 */
	public final java.lang.Integer getTotalTaskCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalTaskCount.toString());
	}

	/**
	 * Set value of TotalTaskCount
	 * @param totaltaskcount
	 */
	public final void setTotalTaskCount(java.lang.Integer totaltaskcount)
	{
		setTotalTaskCount(getContext(), totaltaskcount);
	}

	/**
	 * Set value of TotalTaskCount
	 * @param context
	 * @param totaltaskcount
	 */
	public final void setTotalTaskCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totaltaskcount)
	{
		getMendixObject().setValue(context, MemberNames.TotalTaskCount.toString(), totaltaskcount);
	}

	/**
	 * @return value of FinishedTaskCount
	 */
	public final java.lang.Integer getFinishedTaskCount()
	{
		return getFinishedTaskCount(getContext());
	}

	/**
	 * @param context
	 * @return value of FinishedTaskCount
	 */
	public final java.lang.Integer getFinishedTaskCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.FinishedTaskCount.toString());
	}

	/**
	 * Set value of FinishedTaskCount
	 * @param finishedtaskcount
	 */
	public final void setFinishedTaskCount(java.lang.Integer finishedtaskcount)
	{
		setFinishedTaskCount(getContext(), finishedtaskcount);
	}

	/**
	 * Set value of FinishedTaskCount
	 * @param context
	 * @param finishedtaskcount
	 */
	public final void setFinishedTaskCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer finishedtaskcount)
	{
		getMendixObject().setValue(context, MemberNames.FinishedTaskCount.toString(), finishedtaskcount);
	}

	/**
	 * @return value of ProgressRate
	 */
	public final java.math.BigDecimal getProgressRate()
	{
		return getProgressRate(getContext());
	}

	/**
	 * @param context
	 * @return value of ProgressRate
	 */
	public final java.math.BigDecimal getProgressRate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ProgressRate.toString());
	}

	/**
	 * Set value of ProgressRate
	 * @param progressrate
	 */
	public final void setProgressRate(java.math.BigDecimal progressrate)
	{
		setProgressRate(getContext(), progressrate);
	}

	/**
	 * Set value of ProgressRate
	 * @param context
	 * @param progressrate
	 */
	public final void setProgressRate(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal progressrate)
	{
		getMendixObject().setValue(context, MemberNames.ProgressRate.toString(), progressrate);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderToShowMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderToShow that = (work_management.proxies.WorkOrderToShow) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
