// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/20
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/20
 * 설명 : 작업관리 화면의 에디트 팝업에서 어떤 항목(요청, 승인, 배정, 계획 완료 등)의 아코디언을 보여할지 정볼를 생성하여 팝업을 띄운다 
 * Version 1.0 : 생성
 */
public class WorkOrderEditHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderEditHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderEditHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		EquipmentOption("EquipmentOption"),
		RequestOption("RequestOption"),
		ApprovalOption("ApprovalOption"),
		AssignmentOption("AssignmentOption"),
		PlanOption("PlanOption"),
		ProcessOption("ProcessOption"),
		CompleteOption("CompleteOption");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderEditHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderEditHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderEditHelperMendixObject)
	{
		if (workOrderEditHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderEditHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderEditHelperMendixObject = workOrderEditHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderEditHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderEditHelper(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderEditHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderEditHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of EquipmentOption
	 */
	public final java.lang.Boolean getEquipmentOption()
	{
		return getEquipmentOption(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentOption
	 */
	public final java.lang.Boolean getEquipmentOption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.EquipmentOption.toString());
	}

	/**
	 * Set value of EquipmentOption
	 * @param equipmentoption
	 */
	public final void setEquipmentOption(java.lang.Boolean equipmentoption)
	{
		setEquipmentOption(getContext(), equipmentoption);
	}

	/**
	 * Set value of EquipmentOption
	 * @param context
	 * @param equipmentoption
	 */
	public final void setEquipmentOption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean equipmentoption)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentOption.toString(), equipmentoption);
	}

	/**
	 * @return value of RequestOption
	 */
	public final java.lang.Boolean getRequestOption()
	{
		return getRequestOption(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestOption
	 */
	public final java.lang.Boolean getRequestOption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.RequestOption.toString());
	}

	/**
	 * Set value of RequestOption
	 * @param requestoption
	 */
	public final void setRequestOption(java.lang.Boolean requestoption)
	{
		setRequestOption(getContext(), requestoption);
	}

	/**
	 * Set value of RequestOption
	 * @param context
	 * @param requestoption
	 */
	public final void setRequestOption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean requestoption)
	{
		getMendixObject().setValue(context, MemberNames.RequestOption.toString(), requestoption);
	}

	/**
	 * @return value of ApprovalOption
	 */
	public final java.lang.Boolean getApprovalOption()
	{
		return getApprovalOption(getContext());
	}

	/**
	 * @param context
	 * @return value of ApprovalOption
	 */
	public final java.lang.Boolean getApprovalOption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ApprovalOption.toString());
	}

	/**
	 * Set value of ApprovalOption
	 * @param approvaloption
	 */
	public final void setApprovalOption(java.lang.Boolean approvaloption)
	{
		setApprovalOption(getContext(), approvaloption);
	}

	/**
	 * Set value of ApprovalOption
	 * @param context
	 * @param approvaloption
	 */
	public final void setApprovalOption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean approvaloption)
	{
		getMendixObject().setValue(context, MemberNames.ApprovalOption.toString(), approvaloption);
	}

	/**
	 * @return value of AssignmentOption
	 */
	public final java.lang.Boolean getAssignmentOption()
	{
		return getAssignmentOption(getContext());
	}

	/**
	 * @param context
	 * @return value of AssignmentOption
	 */
	public final java.lang.Boolean getAssignmentOption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.AssignmentOption.toString());
	}

	/**
	 * Set value of AssignmentOption
	 * @param assignmentoption
	 */
	public final void setAssignmentOption(java.lang.Boolean assignmentoption)
	{
		setAssignmentOption(getContext(), assignmentoption);
	}

	/**
	 * Set value of AssignmentOption
	 * @param context
	 * @param assignmentoption
	 */
	public final void setAssignmentOption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean assignmentoption)
	{
		getMendixObject().setValue(context, MemberNames.AssignmentOption.toString(), assignmentoption);
	}

	/**
	 * @return value of PlanOption
	 */
	public final java.lang.Boolean getPlanOption()
	{
		return getPlanOption(getContext());
	}

	/**
	 * @param context
	 * @return value of PlanOption
	 */
	public final java.lang.Boolean getPlanOption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.PlanOption.toString());
	}

	/**
	 * Set value of PlanOption
	 * @param planoption
	 */
	public final void setPlanOption(java.lang.Boolean planoption)
	{
		setPlanOption(getContext(), planoption);
	}

	/**
	 * Set value of PlanOption
	 * @param context
	 * @param planoption
	 */
	public final void setPlanOption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean planoption)
	{
		getMendixObject().setValue(context, MemberNames.PlanOption.toString(), planoption);
	}

	/**
	 * @return value of ProcessOption
	 */
	public final java.lang.Boolean getProcessOption()
	{
		return getProcessOption(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessOption
	 */
	public final java.lang.Boolean getProcessOption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.ProcessOption.toString());
	}

	/**
	 * Set value of ProcessOption
	 * @param processoption
	 */
	public final void setProcessOption(java.lang.Boolean processoption)
	{
		setProcessOption(getContext(), processoption);
	}

	/**
	 * Set value of ProcessOption
	 * @param context
	 * @param processoption
	 */
	public final void setProcessOption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean processoption)
	{
		getMendixObject().setValue(context, MemberNames.ProcessOption.toString(), processoption);
	}

	/**
	 * @return value of CompleteOption
	 */
	public final java.lang.Boolean getCompleteOption()
	{
		return getCompleteOption(getContext());
	}

	/**
	 * @param context
	 * @return value of CompleteOption
	 */
	public final java.lang.Boolean getCompleteOption(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.CompleteOption.toString());
	}

	/**
	 * Set value of CompleteOption
	 * @param completeoption
	 */
	public final void setCompleteOption(java.lang.Boolean completeoption)
	{
		setCompleteOption(getContext(), completeoption);
	}

	/**
	 * Set value of CompleteOption
	 * @param context
	 * @param completeoption
	 */
	public final void setCompleteOption(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean completeoption)
	{
		getMendixObject().setValue(context, MemberNames.CompleteOption.toString(), completeoption);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderEditHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderEditHelper that = (work_management.proxies.WorkOrderEditHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
