// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public class WorkHistory extends globalsearch.proxies.SearchableObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkHistory";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		PlantCode("PlantCode"),
		PlantName("PlantName"),
		LocationCode("LocationCode"),
		LocationName("LocationName"),
		WorkOrderCode("WorkOrderCode"),
		WorkOrderDescription("WorkOrderDescription"),
		WorkOrderEquipmentCode("WorkOrderEquipmentCode"),
		WorkOrderEquipmentName("WorkOrderEquipmentName"),
		WorkRequestDate("WorkRequestDate"),
		WorkRequester("WorkRequester"),
		WorkRequesterCode("WorkRequesterCode"),
		WorkApproveDate("WorkApproveDate"),
		WorkApprover("WorkApprover"),
		WorkApproverCode("WorkApproverCode"),
		WorkAssignedDate("WorkAssignedDate"),
		WorkAssigner("WorkAssigner"),
		WorkAssignerCode("WorkAssignerCode"),
		WorkAssignedManager("WorkAssignedManager"),
		WorkAssignedManagerCode("WorkAssignedManagerCode"),
		WorkStartDate("WorkStartDate"),
		WorkEndDate("WorkEndDate"),
		EquipmentStopTime("EquipmentStopTime"),
		WorkResultFailureType("WorkResultFailureType"),
		WorkResultFailureReason("WorkResultFailureReason"),
		WorkResultCorrectiveAction("WorkResultCorrectiveAction"),
		MaterialCost("MaterialCost"),
		LaborCost("LaborCost"),
		PartnerCost("PartnerCost"),
		ETCCost("ETCCost"),
		TasksCount("TasksCount"),
		WorkResultDescription("WorkResultDescription"),
		TotalCost("TotalCost");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkHistory(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkHistory(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workHistoryMendixObject)
	{
		super(context, workHistoryMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, workHistoryMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkHistory initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkHistory(context, mendixObject);
	}

	public static work_management.proxies.WorkHistory load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkHistory.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.WorkHistory> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.WorkHistory.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of PlantCode
	 */
	public final java.lang.String getPlantCode()
	{
		return getPlantCode(getContext());
	}

	/**
	 * @param context
	 * @return value of PlantCode
	 */
	public final java.lang.String getPlantCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlantCode.toString());
	}

	/**
	 * Set value of PlantCode
	 * @param plantcode
	 */
	public final void setPlantCode(java.lang.String plantcode)
	{
		setPlantCode(getContext(), plantcode);
	}

	/**
	 * Set value of PlantCode
	 * @param context
	 * @param plantcode
	 */
	public final void setPlantCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plantcode)
	{
		getMendixObject().setValue(context, MemberNames.PlantCode.toString(), plantcode);
	}

	/**
	 * @return value of PlantName
	 */
	public final java.lang.String getPlantName()
	{
		return getPlantName(getContext());
	}

	/**
	 * @param context
	 * @return value of PlantName
	 */
	public final java.lang.String getPlantName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.PlantName.toString());
	}

	/**
	 * Set value of PlantName
	 * @param plantname
	 */
	public final void setPlantName(java.lang.String plantname)
	{
		setPlantName(getContext(), plantname);
	}

	/**
	 * Set value of PlantName
	 * @param context
	 * @param plantname
	 */
	public final void setPlantName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String plantname)
	{
		getMendixObject().setValue(context, MemberNames.PlantName.toString(), plantname);
	}

	/**
	 * @return value of LocationCode
	 */
	public final java.lang.String getLocationCode()
	{
		return getLocationCode(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationCode
	 */
	public final java.lang.String getLocationCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationCode.toString());
	}

	/**
	 * Set value of LocationCode
	 * @param locationcode
	 */
	public final void setLocationCode(java.lang.String locationcode)
	{
		setLocationCode(getContext(), locationcode);
	}

	/**
	 * Set value of LocationCode
	 * @param context
	 * @param locationcode
	 */
	public final void setLocationCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationcode)
	{
		getMendixObject().setValue(context, MemberNames.LocationCode.toString(), locationcode);
	}

	/**
	 * @return value of LocationName
	 */
	public final java.lang.String getLocationName()
	{
		return getLocationName(getContext());
	}

	/**
	 * @param context
	 * @return value of LocationName
	 */
	public final java.lang.String getLocationName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.LocationName.toString());
	}

	/**
	 * Set value of LocationName
	 * @param locationname
	 */
	public final void setLocationName(java.lang.String locationname)
	{
		setLocationName(getContext(), locationname);
	}

	/**
	 * Set value of LocationName
	 * @param context
	 * @param locationname
	 */
	public final void setLocationName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String locationname)
	{
		getMendixObject().setValue(context, MemberNames.LocationName.toString(), locationname);
	}

	/**
	 * @return value of WorkOrderCode
	 */
	public final java.lang.String getWorkOrderCode()
	{
		return getWorkOrderCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderCode
	 */
	public final java.lang.String getWorkOrderCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkOrderCode.toString());
	}

	/**
	 * Set value of WorkOrderCode
	 * @param workordercode
	 */
	public final void setWorkOrderCode(java.lang.String workordercode)
	{
		setWorkOrderCode(getContext(), workordercode);
	}

	/**
	 * Set value of WorkOrderCode
	 * @param context
	 * @param workordercode
	 */
	public final void setWorkOrderCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workordercode)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderCode.toString(), workordercode);
	}

	/**
	 * @return value of WorkOrderDescription
	 */
	public final java.lang.String getWorkOrderDescription()
	{
		return getWorkOrderDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderDescription
	 */
	public final java.lang.String getWorkOrderDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkOrderDescription.toString());
	}

	/**
	 * Set value of WorkOrderDescription
	 * @param workorderdescription
	 */
	public final void setWorkOrderDescription(java.lang.String workorderdescription)
	{
		setWorkOrderDescription(getContext(), workorderdescription);
	}

	/**
	 * Set value of WorkOrderDescription
	 * @param context
	 * @param workorderdescription
	 */
	public final void setWorkOrderDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workorderdescription)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderDescription.toString(), workorderdescription);
	}

	/**
	 * @return value of WorkOrderEquipmentCode
	 */
	public final java.lang.String getWorkOrderEquipmentCode()
	{
		return getWorkOrderEquipmentCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderEquipmentCode
	 */
	public final java.lang.String getWorkOrderEquipmentCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkOrderEquipmentCode.toString());
	}

	/**
	 * Set value of WorkOrderEquipmentCode
	 * @param workorderequipmentcode
	 */
	public final void setWorkOrderEquipmentCode(java.lang.String workorderequipmentcode)
	{
		setWorkOrderEquipmentCode(getContext(), workorderequipmentcode);
	}

	/**
	 * Set value of WorkOrderEquipmentCode
	 * @param context
	 * @param workorderequipmentcode
	 */
	public final void setWorkOrderEquipmentCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workorderequipmentcode)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderEquipmentCode.toString(), workorderequipmentcode);
	}

	/**
	 * @return value of WorkOrderEquipmentName
	 */
	public final java.lang.String getWorkOrderEquipmentName()
	{
		return getWorkOrderEquipmentName(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderEquipmentName
	 */
	public final java.lang.String getWorkOrderEquipmentName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkOrderEquipmentName.toString());
	}

	/**
	 * Set value of WorkOrderEquipmentName
	 * @param workorderequipmentname
	 */
	public final void setWorkOrderEquipmentName(java.lang.String workorderequipmentname)
	{
		setWorkOrderEquipmentName(getContext(), workorderequipmentname);
	}

	/**
	 * Set value of WorkOrderEquipmentName
	 * @param context
	 * @param workorderequipmentname
	 */
	public final void setWorkOrderEquipmentName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workorderequipmentname)
	{
		getMendixObject().setValue(context, MemberNames.WorkOrderEquipmentName.toString(), workorderequipmentname);
	}

	/**
	 * @return value of WorkRequestDate
	 */
	public final java.util.Date getWorkRequestDate()
	{
		return getWorkRequestDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkRequestDate
	 */
	public final java.util.Date getWorkRequestDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkRequestDate.toString());
	}

	/**
	 * Set value of WorkRequestDate
	 * @param workrequestdate
	 */
	public final void setWorkRequestDate(java.util.Date workrequestdate)
	{
		setWorkRequestDate(getContext(), workrequestdate);
	}

	/**
	 * Set value of WorkRequestDate
	 * @param context
	 * @param workrequestdate
	 */
	public final void setWorkRequestDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workrequestdate)
	{
		getMendixObject().setValue(context, MemberNames.WorkRequestDate.toString(), workrequestdate);
	}

	/**
	 * @return value of WorkRequester
	 */
	public final java.lang.String getWorkRequester()
	{
		return getWorkRequester(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkRequester
	 */
	public final java.lang.String getWorkRequester(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkRequester.toString());
	}

	/**
	 * Set value of WorkRequester
	 * @param workrequester
	 */
	public final void setWorkRequester(java.lang.String workrequester)
	{
		setWorkRequester(getContext(), workrequester);
	}

	/**
	 * Set value of WorkRequester
	 * @param context
	 * @param workrequester
	 */
	public final void setWorkRequester(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workrequester)
	{
		getMendixObject().setValue(context, MemberNames.WorkRequester.toString(), workrequester);
	}

	/**
	 * @return value of WorkRequesterCode
	 */
	public final java.lang.String getWorkRequesterCode()
	{
		return getWorkRequesterCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkRequesterCode
	 */
	public final java.lang.String getWorkRequesterCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkRequesterCode.toString());
	}

	/**
	 * Set value of WorkRequesterCode
	 * @param workrequestercode
	 */
	public final void setWorkRequesterCode(java.lang.String workrequestercode)
	{
		setWorkRequesterCode(getContext(), workrequestercode);
	}

	/**
	 * Set value of WorkRequesterCode
	 * @param context
	 * @param workrequestercode
	 */
	public final void setWorkRequesterCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workrequestercode)
	{
		getMendixObject().setValue(context, MemberNames.WorkRequesterCode.toString(), workrequestercode);
	}

	/**
	 * @return value of WorkApproveDate
	 */
	public final java.util.Date getWorkApproveDate()
	{
		return getWorkApproveDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkApproveDate
	 */
	public final java.util.Date getWorkApproveDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkApproveDate.toString());
	}

	/**
	 * Set value of WorkApproveDate
	 * @param workapprovedate
	 */
	public final void setWorkApproveDate(java.util.Date workapprovedate)
	{
		setWorkApproveDate(getContext(), workapprovedate);
	}

	/**
	 * Set value of WorkApproveDate
	 * @param context
	 * @param workapprovedate
	 */
	public final void setWorkApproveDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workapprovedate)
	{
		getMendixObject().setValue(context, MemberNames.WorkApproveDate.toString(), workapprovedate);
	}

	/**
	 * @return value of WorkApprover
	 */
	public final java.lang.String getWorkApprover()
	{
		return getWorkApprover(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkApprover
	 */
	public final java.lang.String getWorkApprover(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkApprover.toString());
	}

	/**
	 * Set value of WorkApprover
	 * @param workapprover
	 */
	public final void setWorkApprover(java.lang.String workapprover)
	{
		setWorkApprover(getContext(), workapprover);
	}

	/**
	 * Set value of WorkApprover
	 * @param context
	 * @param workapprover
	 */
	public final void setWorkApprover(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workapprover)
	{
		getMendixObject().setValue(context, MemberNames.WorkApprover.toString(), workapprover);
	}

	/**
	 * @return value of WorkApproverCode
	 */
	public final java.lang.String getWorkApproverCode()
	{
		return getWorkApproverCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkApproverCode
	 */
	public final java.lang.String getWorkApproverCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkApproverCode.toString());
	}

	/**
	 * Set value of WorkApproverCode
	 * @param workapprovercode
	 */
	public final void setWorkApproverCode(java.lang.String workapprovercode)
	{
		setWorkApproverCode(getContext(), workapprovercode);
	}

	/**
	 * Set value of WorkApproverCode
	 * @param context
	 * @param workapprovercode
	 */
	public final void setWorkApproverCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workapprovercode)
	{
		getMendixObject().setValue(context, MemberNames.WorkApproverCode.toString(), workapprovercode);
	}

	/**
	 * @return value of WorkAssignedDate
	 */
	public final java.util.Date getWorkAssignedDate()
	{
		return getWorkAssignedDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkAssignedDate
	 */
	public final java.util.Date getWorkAssignedDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkAssignedDate.toString());
	}

	/**
	 * Set value of WorkAssignedDate
	 * @param workassigneddate
	 */
	public final void setWorkAssignedDate(java.util.Date workassigneddate)
	{
		setWorkAssignedDate(getContext(), workassigneddate);
	}

	/**
	 * Set value of WorkAssignedDate
	 * @param context
	 * @param workassigneddate
	 */
	public final void setWorkAssignedDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workassigneddate)
	{
		getMendixObject().setValue(context, MemberNames.WorkAssignedDate.toString(), workassigneddate);
	}

	/**
	 * @return value of WorkAssigner
	 */
	public final java.lang.String getWorkAssigner()
	{
		return getWorkAssigner(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkAssigner
	 */
	public final java.lang.String getWorkAssigner(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkAssigner.toString());
	}

	/**
	 * Set value of WorkAssigner
	 * @param workassigner
	 */
	public final void setWorkAssigner(java.lang.String workassigner)
	{
		setWorkAssigner(getContext(), workassigner);
	}

	/**
	 * Set value of WorkAssigner
	 * @param context
	 * @param workassigner
	 */
	public final void setWorkAssigner(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workassigner)
	{
		getMendixObject().setValue(context, MemberNames.WorkAssigner.toString(), workassigner);
	}

	/**
	 * @return value of WorkAssignerCode
	 */
	public final java.lang.String getWorkAssignerCode()
	{
		return getWorkAssignerCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkAssignerCode
	 */
	public final java.lang.String getWorkAssignerCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkAssignerCode.toString());
	}

	/**
	 * Set value of WorkAssignerCode
	 * @param workassignercode
	 */
	public final void setWorkAssignerCode(java.lang.String workassignercode)
	{
		setWorkAssignerCode(getContext(), workassignercode);
	}

	/**
	 * Set value of WorkAssignerCode
	 * @param context
	 * @param workassignercode
	 */
	public final void setWorkAssignerCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workassignercode)
	{
		getMendixObject().setValue(context, MemberNames.WorkAssignerCode.toString(), workassignercode);
	}

	/**
	 * @return value of WorkAssignedManager
	 */
	public final java.lang.String getWorkAssignedManager()
	{
		return getWorkAssignedManager(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkAssignedManager
	 */
	public final java.lang.String getWorkAssignedManager(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkAssignedManager.toString());
	}

	/**
	 * Set value of WorkAssignedManager
	 * @param workassignedmanager
	 */
	public final void setWorkAssignedManager(java.lang.String workassignedmanager)
	{
		setWorkAssignedManager(getContext(), workassignedmanager);
	}

	/**
	 * Set value of WorkAssignedManager
	 * @param context
	 * @param workassignedmanager
	 */
	public final void setWorkAssignedManager(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workassignedmanager)
	{
		getMendixObject().setValue(context, MemberNames.WorkAssignedManager.toString(), workassignedmanager);
	}

	/**
	 * @return value of WorkAssignedManagerCode
	 */
	public final java.lang.String getWorkAssignedManagerCode()
	{
		return getWorkAssignedManagerCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkAssignedManagerCode
	 */
	public final java.lang.String getWorkAssignedManagerCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkAssignedManagerCode.toString());
	}

	/**
	 * Set value of WorkAssignedManagerCode
	 * @param workassignedmanagercode
	 */
	public final void setWorkAssignedManagerCode(java.lang.String workassignedmanagercode)
	{
		setWorkAssignedManagerCode(getContext(), workassignedmanagercode);
	}

	/**
	 * Set value of WorkAssignedManagerCode
	 * @param context
	 * @param workassignedmanagercode
	 */
	public final void setWorkAssignedManagerCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workassignedmanagercode)
	{
		getMendixObject().setValue(context, MemberNames.WorkAssignedManagerCode.toString(), workassignedmanagercode);
	}

	/**
	 * @return value of WorkStartDate
	 */
	public final java.util.Date getWorkStartDate()
	{
		return getWorkStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkStartDate
	 */
	public final java.util.Date getWorkStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkStartDate.toString());
	}

	/**
	 * Set value of WorkStartDate
	 * @param workstartdate
	 */
	public final void setWorkStartDate(java.util.Date workstartdate)
	{
		setWorkStartDate(getContext(), workstartdate);
	}

	/**
	 * Set value of WorkStartDate
	 * @param context
	 * @param workstartdate
	 */
	public final void setWorkStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workstartdate)
	{
		getMendixObject().setValue(context, MemberNames.WorkStartDate.toString(), workstartdate);
	}

	/**
	 * @return value of WorkEndDate
	 */
	public final java.util.Date getWorkEndDate()
	{
		return getWorkEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkEndDate
	 */
	public final java.util.Date getWorkEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkEndDate.toString());
	}

	/**
	 * Set value of WorkEndDate
	 * @param workenddate
	 */
	public final void setWorkEndDate(java.util.Date workenddate)
	{
		setWorkEndDate(getContext(), workenddate);
	}

	/**
	 * Set value of WorkEndDate
	 * @param context
	 * @param workenddate
	 */
	public final void setWorkEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workenddate)
	{
		getMendixObject().setValue(context, MemberNames.WorkEndDate.toString(), workenddate);
	}

	/**
	 * @return value of EquipmentStopTime
	 */
	public final java.math.BigDecimal getEquipmentStopTime()
	{
		return getEquipmentStopTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentStopTime
	 */
	public final java.math.BigDecimal getEquipmentStopTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.EquipmentStopTime.toString());
	}

	/**
	 * Set value of EquipmentStopTime
	 * @param equipmentstoptime
	 */
	public final void setEquipmentStopTime(java.math.BigDecimal equipmentstoptime)
	{
		setEquipmentStopTime(getContext(), equipmentstoptime);
	}

	/**
	 * Set value of EquipmentStopTime
	 * @param context
	 * @param equipmentstoptime
	 */
	public final void setEquipmentStopTime(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal equipmentstoptime)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentStopTime.toString(), equipmentstoptime);
	}

	/**
	 * @return value of WorkResultFailureType
	 */
	public final java.lang.String getWorkResultFailureType()
	{
		return getWorkResultFailureType(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkResultFailureType
	 */
	public final java.lang.String getWorkResultFailureType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkResultFailureType.toString());
	}

	/**
	 * Set value of WorkResultFailureType
	 * @param workresultfailuretype
	 */
	public final void setWorkResultFailureType(java.lang.String workresultfailuretype)
	{
		setWorkResultFailureType(getContext(), workresultfailuretype);
	}

	/**
	 * Set value of WorkResultFailureType
	 * @param context
	 * @param workresultfailuretype
	 */
	public final void setWorkResultFailureType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workresultfailuretype)
	{
		getMendixObject().setValue(context, MemberNames.WorkResultFailureType.toString(), workresultfailuretype);
	}

	/**
	 * @return value of WorkResultFailureReason
	 */
	public final java.lang.String getWorkResultFailureReason()
	{
		return getWorkResultFailureReason(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkResultFailureReason
	 */
	public final java.lang.String getWorkResultFailureReason(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkResultFailureReason.toString());
	}

	/**
	 * Set value of WorkResultFailureReason
	 * @param workresultfailurereason
	 */
	public final void setWorkResultFailureReason(java.lang.String workresultfailurereason)
	{
		setWorkResultFailureReason(getContext(), workresultfailurereason);
	}

	/**
	 * Set value of WorkResultFailureReason
	 * @param context
	 * @param workresultfailurereason
	 */
	public final void setWorkResultFailureReason(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workresultfailurereason)
	{
		getMendixObject().setValue(context, MemberNames.WorkResultFailureReason.toString(), workresultfailurereason);
	}

	/**
	 * @return value of WorkResultCorrectiveAction
	 */
	public final java.lang.String getWorkResultCorrectiveAction()
	{
		return getWorkResultCorrectiveAction(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkResultCorrectiveAction
	 */
	public final java.lang.String getWorkResultCorrectiveAction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkResultCorrectiveAction.toString());
	}

	/**
	 * Set value of WorkResultCorrectiveAction
	 * @param workresultcorrectiveaction
	 */
	public final void setWorkResultCorrectiveAction(java.lang.String workresultcorrectiveaction)
	{
		setWorkResultCorrectiveAction(getContext(), workresultcorrectiveaction);
	}

	/**
	 * Set value of WorkResultCorrectiveAction
	 * @param context
	 * @param workresultcorrectiveaction
	 */
	public final void setWorkResultCorrectiveAction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workresultcorrectiveaction)
	{
		getMendixObject().setValue(context, MemberNames.WorkResultCorrectiveAction.toString(), workresultcorrectiveaction);
	}

	/**
	 * @return value of MaterialCost
	 */
	public final java.math.BigDecimal getMaterialCost()
	{
		return getMaterialCost(getContext());
	}

	/**
	 * @param context
	 * @return value of MaterialCost
	 */
	public final java.math.BigDecimal getMaterialCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MaterialCost.toString());
	}

	/**
	 * Set value of MaterialCost
	 * @param materialcost
	 */
	public final void setMaterialCost(java.math.BigDecimal materialcost)
	{
		setMaterialCost(getContext(), materialcost);
	}

	/**
	 * Set value of MaterialCost
	 * @param context
	 * @param materialcost
	 */
	public final void setMaterialCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal materialcost)
	{
		getMendixObject().setValue(context, MemberNames.MaterialCost.toString(), materialcost);
	}

	/**
	 * @return value of LaborCost
	 */
	public final java.math.BigDecimal getLaborCost()
	{
		return getLaborCost(getContext());
	}

	/**
	 * @param context
	 * @return value of LaborCost
	 */
	public final java.math.BigDecimal getLaborCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LaborCost.toString());
	}

	/**
	 * Set value of LaborCost
	 * @param laborcost
	 */
	public final void setLaborCost(java.math.BigDecimal laborcost)
	{
		setLaborCost(getContext(), laborcost);
	}

	/**
	 * Set value of LaborCost
	 * @param context
	 * @param laborcost
	 */
	public final void setLaborCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal laborcost)
	{
		getMendixObject().setValue(context, MemberNames.LaborCost.toString(), laborcost);
	}

	/**
	 * @return value of PartnerCost
	 */
	public final java.math.BigDecimal getPartnerCost()
	{
		return getPartnerCost(getContext());
	}

	/**
	 * @param context
	 * @return value of PartnerCost
	 */
	public final java.math.BigDecimal getPartnerCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.PartnerCost.toString());
	}

	/**
	 * Set value of PartnerCost
	 * @param partnercost
	 */
	public final void setPartnerCost(java.math.BigDecimal partnercost)
	{
		setPartnerCost(getContext(), partnercost);
	}

	/**
	 * Set value of PartnerCost
	 * @param context
	 * @param partnercost
	 */
	public final void setPartnerCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal partnercost)
	{
		getMendixObject().setValue(context, MemberNames.PartnerCost.toString(), partnercost);
	}

	/**
	 * @return value of ETCCost
	 */
	public final java.math.BigDecimal getETCCost()
	{
		return getETCCost(getContext());
	}

	/**
	 * @param context
	 * @return value of ETCCost
	 */
	public final java.math.BigDecimal getETCCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.ETCCost.toString());
	}

	/**
	 * Set value of ETCCost
	 * @param etccost
	 */
	public final void setETCCost(java.math.BigDecimal etccost)
	{
		setETCCost(getContext(), etccost);
	}

	/**
	 * Set value of ETCCost
	 * @param context
	 * @param etccost
	 */
	public final void setETCCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal etccost)
	{
		getMendixObject().setValue(context, MemberNames.ETCCost.toString(), etccost);
	}

	/**
	 * @return value of TasksCount
	 */
	public final java.lang.Integer getTasksCount()
	{
		return getTasksCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TasksCount
	 */
	public final java.lang.Integer getTasksCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TasksCount.toString());
	}

	/**
	 * Set value of TasksCount
	 * @param taskscount
	 */
	public final void setTasksCount(java.lang.Integer taskscount)
	{
		setTasksCount(getContext(), taskscount);
	}

	/**
	 * Set value of TasksCount
	 * @param context
	 * @param taskscount
	 */
	public final void setTasksCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer taskscount)
	{
		getMendixObject().setValue(context, MemberNames.TasksCount.toString(), taskscount);
	}

	/**
	 * @return value of WorkResultDescription
	 */
	public final java.lang.String getWorkResultDescription()
	{
		return getWorkResultDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkResultDescription
	 */
	public final java.lang.String getWorkResultDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkResultDescription.toString());
	}

	/**
	 * Set value of WorkResultDescription
	 * @param workresultdescription
	 */
	public final void setWorkResultDescription(java.lang.String workresultdescription)
	{
		setWorkResultDescription(getContext(), workresultdescription);
	}

	/**
	 * Set value of WorkResultDescription
	 * @param context
	 * @param workresultdescription
	 */
	public final void setWorkResultDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workresultdescription)
	{
		getMendixObject().setValue(context, MemberNames.WorkResultDescription.toString(), workresultdescription);
	}

	/**
	 * @return value of TotalCost
	 */
	public final java.math.BigDecimal getTotalCost()
	{
		return getTotalCost(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCost
	 */
	public final java.math.BigDecimal getTotalCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalCost.toString());
	}

	/**
	 * Set value of TotalCost
	 * @param totalcost
	 */
	public final void setTotalCost(java.math.BigDecimal totalcost)
	{
		setTotalCost(getContext(), totalcost);
	}

	/**
	 * Set value of TotalCost
	 * @param context
	 * @param totalcost
	 */
	public final void setTotalCost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalcost)
	{
		getMendixObject().setValue(context, MemberNames.TotalCost.toString(), totalcost);
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkHistory that = (work_management.proxies.WorkHistory) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
