// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 박성안
 * 최초 작성일 : 2023/11/6
 * 설명 : WorkOrder Kanban 카운트를 위한 엔터티
 * Version 1.0 : 생성
 */
public class WorkBoardCountHelper implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workBoardCountHelperMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkBoardCountHelper";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SearchUser("SearchUser"),
		TotalCount("TotalCount"),
		RequestCount("RequestCount"),
		ApprovalCount("ApprovalCount"),
		AssignmentCount("AssignmentCount"),
		PlanningCount("PlanningCount"),
		ExecutionCount("ExecutionCount"),
		CompletionCount("CompletionCount"),
		RejectCount("RejectCount"),
		WorkBoardCountHelper_WorkOrder("Work_Management.WorkBoardCountHelper_WorkOrder"),
		WorkOrderPageHelper_WorkBoardCountHelper("Work_Management.WorkOrderPageHelper_WorkBoardCountHelper");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkBoardCountHelper(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkBoardCountHelper(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workBoardCountHelperMendixObject)
	{
		if (workBoardCountHelperMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workBoardCountHelperMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workBoardCountHelperMendixObject = workBoardCountHelperMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkBoardCountHelper initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkBoardCountHelper(context, mendixObject);
	}

	public static work_management.proxies.WorkBoardCountHelper load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkBoardCountHelper.initialize(context, mendixObject);
	}

	/**
	 * @return value of SearchUser
	 */
	public final java.lang.Boolean getSearchUser()
	{
		return getSearchUser(getContext());
	}

	/**
	 * @param context
	 * @return value of SearchUser
	 */
	public final java.lang.Boolean getSearchUser(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.SearchUser.toString());
	}

	/**
	 * Set value of SearchUser
	 * @param searchuser
	 */
	public final void setSearchUser(java.lang.Boolean searchuser)
	{
		setSearchUser(getContext(), searchuser);
	}

	/**
	 * Set value of SearchUser
	 * @param context
	 * @param searchuser
	 */
	public final void setSearchUser(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean searchuser)
	{
		getMendixObject().setValue(context, MemberNames.SearchUser.toString(), searchuser);
	}

	/**
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount()
	{
		return getTotalCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalCount.toString());
	}

	/**
	 * Set value of TotalCount
	 * @param totalcount
	 */
	public final void setTotalCount(java.lang.Integer totalcount)
	{
		setTotalCount(getContext(), totalcount);
	}

	/**
	 * Set value of TotalCount
	 * @param context
	 * @param totalcount
	 */
	public final void setTotalCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalcount)
	{
		getMendixObject().setValue(context, MemberNames.TotalCount.toString(), totalcount);
	}

	/**
	 * @return value of RequestCount
	 */
	public final java.lang.Integer getRequestCount()
	{
		return getRequestCount(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestCount
	 */
	public final java.lang.Integer getRequestCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RequestCount.toString());
	}

	/**
	 * Set value of RequestCount
	 * @param requestcount
	 */
	public final void setRequestCount(java.lang.Integer requestcount)
	{
		setRequestCount(getContext(), requestcount);
	}

	/**
	 * Set value of RequestCount
	 * @param context
	 * @param requestcount
	 */
	public final void setRequestCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer requestcount)
	{
		getMendixObject().setValue(context, MemberNames.RequestCount.toString(), requestcount);
	}

	/**
	 * @return value of ApprovalCount
	 */
	public final java.lang.Integer getApprovalCount()
	{
		return getApprovalCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ApprovalCount
	 */
	public final java.lang.Integer getApprovalCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ApprovalCount.toString());
	}

	/**
	 * Set value of ApprovalCount
	 * @param approvalcount
	 */
	public final void setApprovalCount(java.lang.Integer approvalcount)
	{
		setApprovalCount(getContext(), approvalcount);
	}

	/**
	 * Set value of ApprovalCount
	 * @param context
	 * @param approvalcount
	 */
	public final void setApprovalCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer approvalcount)
	{
		getMendixObject().setValue(context, MemberNames.ApprovalCount.toString(), approvalcount);
	}

	/**
	 * @return value of AssignmentCount
	 */
	public final java.lang.Integer getAssignmentCount()
	{
		return getAssignmentCount(getContext());
	}

	/**
	 * @param context
	 * @return value of AssignmentCount
	 */
	public final java.lang.Integer getAssignmentCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.AssignmentCount.toString());
	}

	/**
	 * Set value of AssignmentCount
	 * @param assignmentcount
	 */
	public final void setAssignmentCount(java.lang.Integer assignmentcount)
	{
		setAssignmentCount(getContext(), assignmentcount);
	}

	/**
	 * Set value of AssignmentCount
	 * @param context
	 * @param assignmentcount
	 */
	public final void setAssignmentCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer assignmentcount)
	{
		getMendixObject().setValue(context, MemberNames.AssignmentCount.toString(), assignmentcount);
	}

	/**
	 * @return value of PlanningCount
	 */
	public final java.lang.Integer getPlanningCount()
	{
		return getPlanningCount(getContext());
	}

	/**
	 * @param context
	 * @return value of PlanningCount
	 */
	public final java.lang.Integer getPlanningCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.PlanningCount.toString());
	}

	/**
	 * Set value of PlanningCount
	 * @param planningcount
	 */
	public final void setPlanningCount(java.lang.Integer planningcount)
	{
		setPlanningCount(getContext(), planningcount);
	}

	/**
	 * Set value of PlanningCount
	 * @param context
	 * @param planningcount
	 */
	public final void setPlanningCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer planningcount)
	{
		getMendixObject().setValue(context, MemberNames.PlanningCount.toString(), planningcount);
	}

	/**
	 * @return value of ExecutionCount
	 */
	public final java.lang.Integer getExecutionCount()
	{
		return getExecutionCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ExecutionCount
	 */
	public final java.lang.Integer getExecutionCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ExecutionCount.toString());
	}

	/**
	 * Set value of ExecutionCount
	 * @param executioncount
	 */
	public final void setExecutionCount(java.lang.Integer executioncount)
	{
		setExecutionCount(getContext(), executioncount);
	}

	/**
	 * Set value of ExecutionCount
	 * @param context
	 * @param executioncount
	 */
	public final void setExecutionCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer executioncount)
	{
		getMendixObject().setValue(context, MemberNames.ExecutionCount.toString(), executioncount);
	}

	/**
	 * @return value of CompletionCount
	 */
	public final java.lang.Integer getCompletionCount()
	{
		return getCompletionCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CompletionCount
	 */
	public final java.lang.Integer getCompletionCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CompletionCount.toString());
	}

	/**
	 * Set value of CompletionCount
	 * @param completioncount
	 */
	public final void setCompletionCount(java.lang.Integer completioncount)
	{
		setCompletionCount(getContext(), completioncount);
	}

	/**
	 * Set value of CompletionCount
	 * @param context
	 * @param completioncount
	 */
	public final void setCompletionCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer completioncount)
	{
		getMendixObject().setValue(context, MemberNames.CompletionCount.toString(), completioncount);
	}

	/**
	 * @return value of RejectCount
	 */
	public final java.lang.Integer getRejectCount()
	{
		return getRejectCount(getContext());
	}

	/**
	 * @param context
	 * @return value of RejectCount
	 */
	public final java.lang.Integer getRejectCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.RejectCount.toString());
	}

	/**
	 * Set value of RejectCount
	 * @param rejectcount
	 */
	public final void setRejectCount(java.lang.Integer rejectcount)
	{
		setRejectCount(getContext(), rejectcount);
	}

	/**
	 * Set value of RejectCount
	 * @param context
	 * @param rejectcount
	 */
	public final void setRejectCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer rejectcount)
	{
		getMendixObject().setValue(context, MemberNames.RejectCount.toString(), rejectcount);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkBoardCountHelper_WorkOrder
	 */
	public final java.util.List<work_management.proxies.WorkOrder> getWorkBoardCountHelper_WorkOrder() throws com.mendix.core.CoreException
	{
		return getWorkBoardCountHelper_WorkOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkBoardCountHelper_WorkOrder
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<work_management.proxies.WorkOrder> getWorkBoardCountHelper_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<work_management.proxies.WorkOrder> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.WorkBoardCountHelper_WorkOrder.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(work_management.proxies.WorkOrder.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of WorkBoardCountHelper_WorkOrder
	 * @param workboardcounthelper_workorder
	 */
	public final void setWorkBoardCountHelper_WorkOrder(java.util.List<work_management.proxies.WorkOrder> workboardcounthelper_workorder)
	{
		setWorkBoardCountHelper_WorkOrder(getContext(), workboardcounthelper_workorder);
	}

	/**
	 * Set value of WorkBoardCountHelper_WorkOrder
	 * @param context
	 * @param workboardcounthelper_workorder
	 */
	public final void setWorkBoardCountHelper_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<work_management.proxies.WorkOrder> workboardcounthelper_workorder)
	{
		var identifiers = workboardcounthelper_workorder
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.WorkBoardCountHelper_WorkOrder.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderPageHelper_WorkBoardCountHelper
	 */
	public final work_management.proxies.WorkOrderPageHelper getWorkOrderPageHelper_WorkBoardCountHelper() throws com.mendix.core.CoreException
	{
		return getWorkOrderPageHelper_WorkBoardCountHelper(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderPageHelper_WorkBoardCountHelper
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderPageHelper getWorkOrderPageHelper_WorkBoardCountHelper(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderPageHelper result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderPageHelper_WorkBoardCountHelper.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderPageHelper.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderPageHelper_WorkBoardCountHelper
	 * @param workorderpagehelper_workboardcounthelper
	 */
	public final void setWorkOrderPageHelper_WorkBoardCountHelper(work_management.proxies.WorkOrderPageHelper workorderpagehelper_workboardcounthelper)
	{
		setWorkOrderPageHelper_WorkBoardCountHelper(getContext(), workorderpagehelper_workboardcounthelper);
	}

	/**
	 * Set value of WorkOrderPageHelper_WorkBoardCountHelper
	 * @param context
	 * @param workorderpagehelper_workboardcounthelper
	 */
	public final void setWorkOrderPageHelper_WorkBoardCountHelper(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderPageHelper workorderpagehelper_workboardcounthelper)
	{
		if (workorderpagehelper_workboardcounthelper == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_WorkBoardCountHelper.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderPageHelper_WorkBoardCountHelper.toString(), workorderpagehelper_workboardcounthelper.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workBoardCountHelperMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkBoardCountHelper that = (work_management.proxies.WorkBoardCountHelper) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
