// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public class WorkOrderTasks implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderTasksMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderTasks";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TaskNumber("TaskNumber"),
		TaskStartDate("TaskStartDate"),
		TaskEndDate("TaskEndDate"),
		TaskTime("TaskTime"),
		FailureTypeDescription("FailureTypeDescription"),
		FailureReasonDescription("FailureReasonDescription"),
		CorrectiveActionDescription("CorrectiveActionDescription"),
		TaskDescription("TaskDescription"),
		WorkOrderTasks_WorkOrderResult("Work_Management.WorkOrderTasks_WorkOrderResult"),
		TaskProcessingStatus_StandardCode("Work_Management.TaskProcessingStatus_StandardCode"),
		WorkOrderTasks_Equipment("Work_Management.WorkOrderTasks_Equipment"),
		WorkOrderTasksFailureType_StandardCode("Work_Management.WorkOrderTasksFailureType_StandardCode"),
		WorkOrderTasksFailureReason_StandardCode("Work_Management.WorkOrderTasksFailureReason_StandardCode"),
		WorkOrderTasksCorrectiveAction_StandardCode("Work_Management.WorkOrderTasksCorrectiveAction_StandardCode");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderTasks(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderTasks(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderTasksMendixObject)
	{
		if (workOrderTasksMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderTasksMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderTasksMendixObject = workOrderTasksMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderTasks initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderTasks(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderTasks load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderTasks.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.WorkOrderTasks> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.WorkOrderTasks.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of TaskNumber
	 */
	public final java.lang.Integer getTaskNumber()
	{
		return getTaskNumber(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskNumber
	 */
	public final java.lang.Integer getTaskNumber(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TaskNumber.toString());
	}

	/**
	 * Set value of TaskNumber
	 * @param tasknumber
	 */
	public final void setTaskNumber(java.lang.Integer tasknumber)
	{
		setTaskNumber(getContext(), tasknumber);
	}

	/**
	 * Set value of TaskNumber
	 * @param context
	 * @param tasknumber
	 */
	public final void setTaskNumber(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer tasknumber)
	{
		getMendixObject().setValue(context, MemberNames.TaskNumber.toString(), tasknumber);
	}

	/**
	 * @return value of TaskStartDate
	 */
	public final java.util.Date getTaskStartDate()
	{
		return getTaskStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskStartDate
	 */
	public final java.util.Date getTaskStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TaskStartDate.toString());
	}

	/**
	 * Set value of TaskStartDate
	 * @param taskstartdate
	 */
	public final void setTaskStartDate(java.util.Date taskstartdate)
	{
		setTaskStartDate(getContext(), taskstartdate);
	}

	/**
	 * Set value of TaskStartDate
	 * @param context
	 * @param taskstartdate
	 */
	public final void setTaskStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date taskstartdate)
	{
		getMendixObject().setValue(context, MemberNames.TaskStartDate.toString(), taskstartdate);
	}

	/**
	 * @return value of TaskEndDate
	 */
	public final java.util.Date getTaskEndDate()
	{
		return getTaskEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskEndDate
	 */
	public final java.util.Date getTaskEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.TaskEndDate.toString());
	}

	/**
	 * Set value of TaskEndDate
	 * @param taskenddate
	 */
	public final void setTaskEndDate(java.util.Date taskenddate)
	{
		setTaskEndDate(getContext(), taskenddate);
	}

	/**
	 * Set value of TaskEndDate
	 * @param context
	 * @param taskenddate
	 */
	public final void setTaskEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date taskenddate)
	{
		getMendixObject().setValue(context, MemberNames.TaskEndDate.toString(), taskenddate);
	}

	/**
	 * @return value of TaskTime
	 */
	public final java.lang.String getTaskTime()
	{
		return getTaskTime(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskTime
	 */
	public final java.lang.String getTaskTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskTime.toString());
	}

	/**
	 * Set value of TaskTime
	 * @param tasktime
	 */
	public final void setTaskTime(java.lang.String tasktime)
	{
		setTaskTime(getContext(), tasktime);
	}

	/**
	 * Set value of TaskTime
	 * @param context
	 * @param tasktime
	 */
	public final void setTaskTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String tasktime)
	{
		getMendixObject().setValue(context, MemberNames.TaskTime.toString(), tasktime);
	}

	/**
	 * @return value of FailureTypeDescription
	 */
	public final java.lang.String getFailureTypeDescription()
	{
		return getFailureTypeDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of FailureTypeDescription
	 */
	public final java.lang.String getFailureTypeDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FailureTypeDescription.toString());
	}

	/**
	 * Set value of FailureTypeDescription
	 * @param failuretypedescription
	 */
	public final void setFailureTypeDescription(java.lang.String failuretypedescription)
	{
		setFailureTypeDescription(getContext(), failuretypedescription);
	}

	/**
	 * Set value of FailureTypeDescription
	 * @param context
	 * @param failuretypedescription
	 */
	public final void setFailureTypeDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String failuretypedescription)
	{
		getMendixObject().setValue(context, MemberNames.FailureTypeDescription.toString(), failuretypedescription);
	}

	/**
	 * @return value of FailureReasonDescription
	 */
	public final java.lang.String getFailureReasonDescription()
	{
		return getFailureReasonDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of FailureReasonDescription
	 */
	public final java.lang.String getFailureReasonDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.FailureReasonDescription.toString());
	}

	/**
	 * Set value of FailureReasonDescription
	 * @param failurereasondescription
	 */
	public final void setFailureReasonDescription(java.lang.String failurereasondescription)
	{
		setFailureReasonDescription(getContext(), failurereasondescription);
	}

	/**
	 * Set value of FailureReasonDescription
	 * @param context
	 * @param failurereasondescription
	 */
	public final void setFailureReasonDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String failurereasondescription)
	{
		getMendixObject().setValue(context, MemberNames.FailureReasonDescription.toString(), failurereasondescription);
	}

	/**
	 * @return value of CorrectiveActionDescription
	 */
	public final java.lang.String getCorrectiveActionDescription()
	{
		return getCorrectiveActionDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of CorrectiveActionDescription
	 */
	public final java.lang.String getCorrectiveActionDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CorrectiveActionDescription.toString());
	}

	/**
	 * Set value of CorrectiveActionDescription
	 * @param correctiveactiondescription
	 */
	public final void setCorrectiveActionDescription(java.lang.String correctiveactiondescription)
	{
		setCorrectiveActionDescription(getContext(), correctiveactiondescription);
	}

	/**
	 * Set value of CorrectiveActionDescription
	 * @param context
	 * @param correctiveactiondescription
	 */
	public final void setCorrectiveActionDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String correctiveactiondescription)
	{
		getMendixObject().setValue(context, MemberNames.CorrectiveActionDescription.toString(), correctiveactiondescription);
	}

	/**
	 * @return value of TaskDescription
	 */
	public final java.lang.String getTaskDescription()
	{
		return getTaskDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskDescription
	 */
	public final java.lang.String getTaskDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TaskDescription.toString());
	}

	/**
	 * Set value of TaskDescription
	 * @param taskdescription
	 */
	public final void setTaskDescription(java.lang.String taskdescription)
	{
		setTaskDescription(getContext(), taskdescription);
	}

	/**
	 * Set value of TaskDescription
	 * @param context
	 * @param taskdescription
	 */
	public final void setTaskDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String taskdescription)
	{
		getMendixObject().setValue(context, MemberNames.TaskDescription.toString(), taskdescription);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderTasks_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderTasks_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getWorkOrderTasks_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderTasks_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderTasks_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderTasks_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderTasks_WorkOrderResult
	 * @param workordertasks_workorderresult
	 */
	public final void setWorkOrderTasks_WorkOrderResult(work_management.proxies.WorkOrderResult workordertasks_workorderresult)
	{
		setWorkOrderTasks_WorkOrderResult(getContext(), workordertasks_workorderresult);
	}

	/**
	 * Set value of WorkOrderTasks_WorkOrderResult
	 * @param context
	 * @param workordertasks_workorderresult
	 */
	public final void setWorkOrderTasks_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderResult workordertasks_workorderresult)
	{
		if (workordertasks_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasks_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasks_WorkOrderResult.toString(), workordertasks_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of TaskProcessingStatus_StandardCode
	 */
	public final commons.proxies.StandardCode getTaskProcessingStatus_StandardCode() throws com.mendix.core.CoreException
	{
		return getTaskProcessingStatus_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of TaskProcessingStatus_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getTaskProcessingStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.TaskProcessingStatus_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of TaskProcessingStatus_StandardCode
	 * @param taskprocessingstatus_standardcode
	 */
	public final void setTaskProcessingStatus_StandardCode(commons.proxies.StandardCode taskprocessingstatus_standardcode)
	{
		setTaskProcessingStatus_StandardCode(getContext(), taskprocessingstatus_standardcode);
	}

	/**
	 * Set value of TaskProcessingStatus_StandardCode
	 * @param context
	 * @param taskprocessingstatus_standardcode
	 */
	public final void setTaskProcessingStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode taskprocessingstatus_standardcode)
	{
		if (taskprocessingstatus_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.TaskProcessingStatus_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.TaskProcessingStatus_StandardCode.toString(), taskprocessingstatus_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderTasks_Equipment
	 */
	public final equipment_management.proxies.Equipment getWorkOrderTasks_Equipment() throws com.mendix.core.CoreException
	{
		return getWorkOrderTasks_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderTasks_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getWorkOrderTasks_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderTasks_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderTasks_Equipment
	 * @param workordertasks_equipment
	 */
	public final void setWorkOrderTasks_Equipment(equipment_management.proxies.Equipment workordertasks_equipment)
	{
		setWorkOrderTasks_Equipment(getContext(), workordertasks_equipment);
	}

	/**
	 * Set value of WorkOrderTasks_Equipment
	 * @param context
	 * @param workordertasks_equipment
	 */
	public final void setWorkOrderTasks_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment workordertasks_equipment)
	{
		if (workordertasks_equipment == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasks_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasks_Equipment.toString(), workordertasks_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderTasksFailureType_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkOrderTasksFailureType_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkOrderTasksFailureType_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderTasksFailureType_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkOrderTasksFailureType_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderTasksFailureType_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderTasksFailureType_StandardCode
	 * @param workordertasksfailuretype_standardcode
	 */
	public final void setWorkOrderTasksFailureType_StandardCode(commons.proxies.StandardCode workordertasksfailuretype_standardcode)
	{
		setWorkOrderTasksFailureType_StandardCode(getContext(), workordertasksfailuretype_standardcode);
	}

	/**
	 * Set value of WorkOrderTasksFailureType_StandardCode
	 * @param context
	 * @param workordertasksfailuretype_standardcode
	 */
	public final void setWorkOrderTasksFailureType_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workordertasksfailuretype_standardcode)
	{
		if (workordertasksfailuretype_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasksFailureType_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasksFailureType_StandardCode.toString(), workordertasksfailuretype_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderTasksFailureReason_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkOrderTasksFailureReason_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkOrderTasksFailureReason_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderTasksFailureReason_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkOrderTasksFailureReason_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderTasksFailureReason_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderTasksFailureReason_StandardCode
	 * @param workordertasksfailurereason_standardcode
	 */
	public final void setWorkOrderTasksFailureReason_StandardCode(commons.proxies.StandardCode workordertasksfailurereason_standardcode)
	{
		setWorkOrderTasksFailureReason_StandardCode(getContext(), workordertasksfailurereason_standardcode);
	}

	/**
	 * Set value of WorkOrderTasksFailureReason_StandardCode
	 * @param context
	 * @param workordertasksfailurereason_standardcode
	 */
	public final void setWorkOrderTasksFailureReason_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workordertasksfailurereason_standardcode)
	{
		if (workordertasksfailurereason_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasksFailureReason_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasksFailureReason_StandardCode.toString(), workordertasksfailurereason_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderTasksCorrectiveAction_StandardCode
	 */
	public final commons.proxies.StandardCode getWorkOrderTasksCorrectiveAction_StandardCode() throws com.mendix.core.CoreException
	{
		return getWorkOrderTasksCorrectiveAction_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderTasksCorrectiveAction_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWorkOrderTasksCorrectiveAction_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderTasksCorrectiveAction_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderTasksCorrectiveAction_StandardCode
	 * @param workordertaskscorrectiveaction_standardcode
	 */
	public final void setWorkOrderTasksCorrectiveAction_StandardCode(commons.proxies.StandardCode workordertaskscorrectiveaction_standardcode)
	{
		setWorkOrderTasksCorrectiveAction_StandardCode(getContext(), workordertaskscorrectiveaction_standardcode);
	}

	/**
	 * Set value of WorkOrderTasksCorrectiveAction_StandardCode
	 * @param context
	 * @param workordertaskscorrectiveaction_standardcode
	 */
	public final void setWorkOrderTasksCorrectiveAction_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode workordertaskscorrectiveaction_standardcode)
	{
		if (workordertaskscorrectiveaction_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasksCorrectiveAction_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderTasksCorrectiveAction_StandardCode.toString(), workordertaskscorrectiveaction_standardcode.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderTasksMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderTasks that = (work_management.proxies.WorkOrderTasks) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
