// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public class WorkOrderWorkers implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderWorkersMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderWorkers";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		WorkStartDate("WorkStartDate"),
		WorkEndDate("WorkEndDate"),
		WorkTIme("WorkTIme"),
		WorkCost("WorkCost"),
		WorkResultDescription("WorkResultDescription"),
		WorkOrderWorkers_WorkOrderResult("Work_Management.WorkOrderWorkers_WorkOrderResult"),
		WorkOrderWorkers_Employee("Work_Management.WorkOrderWorkers_Employee");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderWorkers(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderWorkers(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderWorkersMendixObject)
	{
		if (workOrderWorkersMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderWorkersMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderWorkersMendixObject = workOrderWorkersMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderWorkers initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderWorkers(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderWorkers load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderWorkers.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.WorkOrderWorkers> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.WorkOrderWorkers.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of WorkStartDate
	 */
	public final java.util.Date getWorkStartDate()
	{
		return getWorkStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkStartDate
	 */
	public final java.util.Date getWorkStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkStartDate.toString());
	}

	/**
	 * Set value of WorkStartDate
	 * @param workstartdate
	 */
	public final void setWorkStartDate(java.util.Date workstartdate)
	{
		setWorkStartDate(getContext(), workstartdate);
	}

	/**
	 * Set value of WorkStartDate
	 * @param context
	 * @param workstartdate
	 */
	public final void setWorkStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workstartdate)
	{
		getMendixObject().setValue(context, MemberNames.WorkStartDate.toString(), workstartdate);
	}

	/**
	 * @return value of WorkEndDate
	 */
	public final java.util.Date getWorkEndDate()
	{
		return getWorkEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkEndDate
	 */
	public final java.util.Date getWorkEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.WorkEndDate.toString());
	}

	/**
	 * Set value of WorkEndDate
	 * @param workenddate
	 */
	public final void setWorkEndDate(java.util.Date workenddate)
	{
		setWorkEndDate(getContext(), workenddate);
	}

	/**
	 * Set value of WorkEndDate
	 * @param context
	 * @param workenddate
	 */
	public final void setWorkEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date workenddate)
	{
		getMendixObject().setValue(context, MemberNames.WorkEndDate.toString(), workenddate);
	}

	/**
	 * @return value of WorkTIme
	 */
	public final java.lang.String getWorkTIme()
	{
		return getWorkTIme(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkTIme
	 */
	public final java.lang.String getWorkTIme(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkTIme.toString());
	}

	/**
	 * Set value of WorkTIme
	 * @param worktime
	 */
	public final void setWorkTIme(java.lang.String worktime)
	{
		setWorkTIme(getContext(), worktime);
	}

	/**
	 * Set value of WorkTIme
	 * @param context
	 * @param worktime
	 */
	public final void setWorkTIme(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String worktime)
	{
		getMendixObject().setValue(context, MemberNames.WorkTIme.toString(), worktime);
	}

	/**
	 * @return value of WorkCost
	 */
	public final java.lang.Integer getWorkCost()
	{
		return getWorkCost(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkCost
	 */
	public final java.lang.Integer getWorkCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.WorkCost.toString());
	}

	/**
	 * Set value of WorkCost
	 * @param workcost
	 */
	public final void setWorkCost(java.lang.Integer workcost)
	{
		setWorkCost(getContext(), workcost);
	}

	/**
	 * Set value of WorkCost
	 * @param context
	 * @param workcost
	 */
	public final void setWorkCost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer workcost)
	{
		getMendixObject().setValue(context, MemberNames.WorkCost.toString(), workcost);
	}

	/**
	 * @return value of WorkResultDescription
	 */
	public final java.lang.String getWorkResultDescription()
	{
		return getWorkResultDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkResultDescription
	 */
	public final java.lang.String getWorkResultDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.WorkResultDescription.toString());
	}

	/**
	 * Set value of WorkResultDescription
	 * @param workresultdescription
	 */
	public final void setWorkResultDescription(java.lang.String workresultdescription)
	{
		setWorkResultDescription(getContext(), workresultdescription);
	}

	/**
	 * Set value of WorkResultDescription
	 * @param context
	 * @param workresultdescription
	 */
	public final void setWorkResultDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String workresultdescription)
	{
		getMendixObject().setValue(context, MemberNames.WorkResultDescription.toString(), workresultdescription);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderWorkers_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderWorkers_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getWorkOrderWorkers_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderWorkers_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderWorkers_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderWorkers_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderWorkers_WorkOrderResult
	 * @param workorderworkers_workorderresult
	 */
	public final void setWorkOrderWorkers_WorkOrderResult(work_management.proxies.WorkOrderResult workorderworkers_workorderresult)
	{
		setWorkOrderWorkers_WorkOrderResult(getContext(), workorderworkers_workorderresult);
	}

	/**
	 * Set value of WorkOrderWorkers_WorkOrderResult
	 * @param context
	 * @param workorderworkers_workorderresult
	 */
	public final void setWorkOrderWorkers_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderResult workorderworkers_workorderresult)
	{
		if (workorderworkers_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderWorkers_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderWorkers_WorkOrderResult.toString(), workorderworkers_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderWorkers_Employee
	 */
	public final cmms_administration.proxies.Employee getWorkOrderWorkers_Employee() throws com.mendix.core.CoreException
	{
		return getWorkOrderWorkers_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderWorkers_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getWorkOrderWorkers_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderWorkers_Employee.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderWorkers_Employee
	 * @param workorderworkers_employee
	 */
	public final void setWorkOrderWorkers_Employee(cmms_administration.proxies.Employee workorderworkers_employee)
	{
		setWorkOrderWorkers_Employee(getContext(), workorderworkers_employee);
	}

	/**
	 * Set value of WorkOrderWorkers_Employee
	 * @param context
	 * @param workorderworkers_employee
	 */
	public final void setWorkOrderWorkers_Employee(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee workorderworkers_employee)
	{
		if (workorderworkers_employee == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderWorkers_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderWorkers_Employee.toString(), workorderworkers_employee.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderWorkersMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderWorkers that = (work_management.proxies.WorkOrderWorkers) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
