// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/10
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/10
 * 설명 : 작업요청/워크오더 내용을 답는 엔터티\\
 * Version 1.0 : 생성
 */
public class WorkOrder extends globalsearch.proxies.SearchableObject
{
	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrder";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		RequestCode("RequestCode"),
		EquipmentDownDate("EquipmentDownDate"),
		RequestDate("RequestDate"),
		RequestDescription("RequestDescription"),
		RequestDelayDay("RequestDelayDay"),
		ApproveDescription("ApproveDescription"),
		ApproveDate("ApproveDate"),
		AssignDate("AssignDate"),
		DesiredStartDate("DesiredStartDate"),
		DesiredEndDate("DesiredEndDate"),
		EstimatedWorkTime("EstimatedWorkTime"),
		AssignmentDescription("AssignmentDescription"),
		RequestPlanDate("RequestPlanDate"),
		RequestPlanDescription("RequestPlanDescription"),
		Count("Count"),
		Allday("Allday"),
		Color("Color"),
		CalendarTitle("CalendarTitle"),
		CalendarStartDate("CalendarStartDate"),
		CalendarEndDate("CalendarEndDate"),
		FieldPhoto_WorkOrder("Work_Management.FieldPhoto_WorkOrder"),
		WorkOrder_WorkOrderResult("Work_Management.WorkOrder_WorkOrderResult"),
		WO_Equipment("Work_Management.WO_Equipment"),
		WOPurpose_StandardCode("Work_Management.WOPurpose_StandardCode"),
		WOStatus_StandardCode("Work_Management.WOStatus_StandardCode"),
		WOPriority_StandardCode("Work_Management.WOPriority_StandardCode"),
		WorkOrder_Plant("Work_Management.WorkOrder_Plant"),
		RequestPlan_Material("Work_Management.RequestPlan_Material"),
		ApproveStatus_StandardCode("Work_Management.ApproveStatus_StandardCode"),
		Approver_Employee("Work_Management.Approver_Employee"),
		Assigner_Employee("Work_Management.Assigner_Employee"),
		AssignedManager_Employee("Work_Management.AssignedManager_Employee"),
		AssignedWorkers_Employee("Work_Management.AssignedWorkers_Employee"),
		Requester_Employee("Work_Management.Requester_Employee");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrder(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrder(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderMendixObject)
	{
		super(context, workOrderMendixObject);
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrder initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrder(context, mendixObject);
	}

	public static work_management.proxies.WorkOrder load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrder.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.WorkOrder> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.WorkOrder.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of RequestCode
	 */
	public final java.lang.String getRequestCode()
	{
		return getRequestCode(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestCode
	 */
	public final java.lang.String getRequestCode(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestCode.toString());
	}

	/**
	 * Set value of RequestCode
	 * @param requestcode
	 */
	public final void setRequestCode(java.lang.String requestcode)
	{
		setRequestCode(getContext(), requestcode);
	}

	/**
	 * Set value of RequestCode
	 * @param context
	 * @param requestcode
	 */
	public final void setRequestCode(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestcode)
	{
		getMendixObject().setValue(context, MemberNames.RequestCode.toString(), requestcode);
	}

	/**
	 * @return value of EquipmentDownDate
	 */
	public final java.util.Date getEquipmentDownDate()
	{
		return getEquipmentDownDate(getContext());
	}

	/**
	 * @param context
	 * @return value of EquipmentDownDate
	 */
	public final java.util.Date getEquipmentDownDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.EquipmentDownDate.toString());
	}

	/**
	 * Set value of EquipmentDownDate
	 * @param equipmentdowndate
	 */
	public final void setEquipmentDownDate(java.util.Date equipmentdowndate)
	{
		setEquipmentDownDate(getContext(), equipmentdowndate);
	}

	/**
	 * Set value of EquipmentDownDate
	 * @param context
	 * @param equipmentdowndate
	 */
	public final void setEquipmentDownDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date equipmentdowndate)
	{
		getMendixObject().setValue(context, MemberNames.EquipmentDownDate.toString(), equipmentdowndate);
	}

	/**
	 * @return value of RequestDate
	 */
	public final java.util.Date getRequestDate()
	{
		return getRequestDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestDate
	 */
	public final java.util.Date getRequestDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RequestDate.toString());
	}

	/**
	 * Set value of RequestDate
	 * @param requestdate
	 */
	public final void setRequestDate(java.util.Date requestdate)
	{
		setRequestDate(getContext(), requestdate);
	}

	/**
	 * Set value of RequestDate
	 * @param context
	 * @param requestdate
	 */
	public final void setRequestDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date requestdate)
	{
		getMendixObject().setValue(context, MemberNames.RequestDate.toString(), requestdate);
	}

	/**
	 * @return value of RequestDescription
	 */
	public final java.lang.String getRequestDescription()
	{
		return getRequestDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestDescription
	 */
	public final java.lang.String getRequestDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestDescription.toString());
	}

	/**
	 * Set value of RequestDescription
	 * @param requestdescription
	 */
	public final void setRequestDescription(java.lang.String requestdescription)
	{
		setRequestDescription(getContext(), requestdescription);
	}

	/**
	 * Set value of RequestDescription
	 * @param context
	 * @param requestdescription
	 */
	public final void setRequestDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestdescription)
	{
		getMendixObject().setValue(context, MemberNames.RequestDescription.toString(), requestdescription);
	}

	/**
	 * @return value of RequestDelayDay
	 */
	public final java.lang.Long getRequestDelayDay()
	{
		return getRequestDelayDay(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestDelayDay
	 */
	public final java.lang.Long getRequestDelayDay(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.RequestDelayDay.toString());
	}

	/**
	 * Set value of RequestDelayDay
	 * @param requestdelayday
	 */
	public final void setRequestDelayDay(java.lang.Long requestdelayday)
	{
		setRequestDelayDay(getContext(), requestdelayday);
	}

	/**
	 * Set value of RequestDelayDay
	 * @param context
	 * @param requestdelayday
	 */
	public final void setRequestDelayDay(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long requestdelayday)
	{
		getMendixObject().setValue(context, MemberNames.RequestDelayDay.toString(), requestdelayday);
	}

	/**
	 * @return value of ApproveDescription
	 */
	public final java.lang.String getApproveDescription()
	{
		return getApproveDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ApproveDescription
	 */
	public final java.lang.String getApproveDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ApproveDescription.toString());
	}

	/**
	 * Set value of ApproveDescription
	 * @param approvedescription
	 */
	public final void setApproveDescription(java.lang.String approvedescription)
	{
		setApproveDescription(getContext(), approvedescription);
	}

	/**
	 * Set value of ApproveDescription
	 * @param context
	 * @param approvedescription
	 */
	public final void setApproveDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String approvedescription)
	{
		getMendixObject().setValue(context, MemberNames.ApproveDescription.toString(), approvedescription);
	}

	/**
	 * @return value of ApproveDate
	 */
	public final java.util.Date getApproveDate()
	{
		return getApproveDate(getContext());
	}

	/**
	 * @param context
	 * @return value of ApproveDate
	 */
	public final java.util.Date getApproveDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.ApproveDate.toString());
	}

	/**
	 * Set value of ApproveDate
	 * @param approvedate
	 */
	public final void setApproveDate(java.util.Date approvedate)
	{
		setApproveDate(getContext(), approvedate);
	}

	/**
	 * Set value of ApproveDate
	 * @param context
	 * @param approvedate
	 */
	public final void setApproveDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date approvedate)
	{
		getMendixObject().setValue(context, MemberNames.ApproveDate.toString(), approvedate);
	}

	/**
	 * @return value of AssignDate
	 */
	public final java.util.Date getAssignDate()
	{
		return getAssignDate(getContext());
	}

	/**
	 * @param context
	 * @return value of AssignDate
	 */
	public final java.util.Date getAssignDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.AssignDate.toString());
	}

	/**
	 * Set value of AssignDate
	 * @param assigndate
	 */
	public final void setAssignDate(java.util.Date assigndate)
	{
		setAssignDate(getContext(), assigndate);
	}

	/**
	 * Set value of AssignDate
	 * @param context
	 * @param assigndate
	 */
	public final void setAssignDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date assigndate)
	{
		getMendixObject().setValue(context, MemberNames.AssignDate.toString(), assigndate);
	}

	/**
	 * @return value of DesiredStartDate
	 */
	public final java.util.Date getDesiredStartDate()
	{
		return getDesiredStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DesiredStartDate
	 */
	public final java.util.Date getDesiredStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DesiredStartDate.toString());
	}

	/**
	 * Set value of DesiredStartDate
	 * @param desiredstartdate
	 */
	public final void setDesiredStartDate(java.util.Date desiredstartdate)
	{
		setDesiredStartDate(getContext(), desiredstartdate);
	}

	/**
	 * Set value of DesiredStartDate
	 * @param context
	 * @param desiredstartdate
	 */
	public final void setDesiredStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date desiredstartdate)
	{
		getMendixObject().setValue(context, MemberNames.DesiredStartDate.toString(), desiredstartdate);
	}

	/**
	 * @return value of DesiredEndDate
	 */
	public final java.util.Date getDesiredEndDate()
	{
		return getDesiredEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of DesiredEndDate
	 */
	public final java.util.Date getDesiredEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DesiredEndDate.toString());
	}

	/**
	 * Set value of DesiredEndDate
	 * @param desiredenddate
	 */
	public final void setDesiredEndDate(java.util.Date desiredenddate)
	{
		setDesiredEndDate(getContext(), desiredenddate);
	}

	/**
	 * Set value of DesiredEndDate
	 * @param context
	 * @param desiredenddate
	 */
	public final void setDesiredEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date desiredenddate)
	{
		getMendixObject().setValue(context, MemberNames.DesiredEndDate.toString(), desiredenddate);
	}

	/**
	 * @return value of EstimatedWorkTime
	 */
	public final java.lang.String getEstimatedWorkTime()
	{
		return getEstimatedWorkTime(getContext());
	}

	/**
	 * @param context
	 * @return value of EstimatedWorkTime
	 */
	public final java.lang.String getEstimatedWorkTime(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.EstimatedWorkTime.toString());
	}

	/**
	 * Set value of EstimatedWorkTime
	 * @param estimatedworktime
	 */
	public final void setEstimatedWorkTime(java.lang.String estimatedworktime)
	{
		setEstimatedWorkTime(getContext(), estimatedworktime);
	}

	/**
	 * Set value of EstimatedWorkTime
	 * @param context
	 * @param estimatedworktime
	 */
	public final void setEstimatedWorkTime(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String estimatedworktime)
	{
		getMendixObject().setValue(context, MemberNames.EstimatedWorkTime.toString(), estimatedworktime);
	}

	/**
	 * @return value of AssignmentDescription
	 */
	public final java.lang.String getAssignmentDescription()
	{
		return getAssignmentDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of AssignmentDescription
	 */
	public final java.lang.String getAssignmentDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AssignmentDescription.toString());
	}

	/**
	 * Set value of AssignmentDescription
	 * @param assignmentdescription
	 */
	public final void setAssignmentDescription(java.lang.String assignmentdescription)
	{
		setAssignmentDescription(getContext(), assignmentdescription);
	}

	/**
	 * Set value of AssignmentDescription
	 * @param context
	 * @param assignmentdescription
	 */
	public final void setAssignmentDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String assignmentdescription)
	{
		getMendixObject().setValue(context, MemberNames.AssignmentDescription.toString(), assignmentdescription);
	}

	/**
	 * @return value of RequestPlanDate
	 */
	public final java.util.Date getRequestPlanDate()
	{
		return getRequestPlanDate(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestPlanDate
	 */
	public final java.util.Date getRequestPlanDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.RequestPlanDate.toString());
	}

	/**
	 * Set value of RequestPlanDate
	 * @param requestplandate
	 */
	public final void setRequestPlanDate(java.util.Date requestplandate)
	{
		setRequestPlanDate(getContext(), requestplandate);
	}

	/**
	 * Set value of RequestPlanDate
	 * @param context
	 * @param requestplandate
	 */
	public final void setRequestPlanDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date requestplandate)
	{
		getMendixObject().setValue(context, MemberNames.RequestPlanDate.toString(), requestplandate);
	}

	/**
	 * @return value of RequestPlanDescription
	 */
	public final java.lang.String getRequestPlanDescription()
	{
		return getRequestPlanDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestPlanDescription
	 */
	public final java.lang.String getRequestPlanDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.RequestPlanDescription.toString());
	}

	/**
	 * Set value of RequestPlanDescription
	 * @param requestplandescription
	 */
	public final void setRequestPlanDescription(java.lang.String requestplandescription)
	{
		setRequestPlanDescription(getContext(), requestplandescription);
	}

	/**
	 * Set value of RequestPlanDescription
	 * @param context
	 * @param requestplandescription
	 */
	public final void setRequestPlanDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String requestplandescription)
	{
		getMendixObject().setValue(context, MemberNames.RequestPlanDescription.toString(), requestplandescription);
	}

	/**
	 * @return value of Count
	 */
	public final java.lang.Integer getCount()
	{
		return getCount(getContext());
	}

	/**
	 * @param context
	 * @return value of Count
	 */
	public final java.lang.Integer getCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.Count.toString());
	}

	/**
	 * Set value of Count
	 * @param count
	 */
	public final void setCount(java.lang.Integer count)
	{
		setCount(getContext(), count);
	}

	/**
	 * Set value of Count
	 * @param context
	 * @param count
	 */
	public final void setCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer count)
	{
		getMendixObject().setValue(context, MemberNames.Count.toString(), count);
	}

	/**
	 * @return value of Allday
	 */
	public final java.lang.Boolean getAllday()
	{
		return getAllday(getContext());
	}

	/**
	 * @param context
	 * @return value of Allday
	 */
	public final java.lang.Boolean getAllday(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Boolean) getMendixObject().getValue(context, MemberNames.Allday.toString());
	}

	/**
	 * Set value of Allday
	 * @param allday
	 */
	public final void setAllday(java.lang.Boolean allday)
	{
		setAllday(getContext(), allday);
	}

	/**
	 * Set value of Allday
	 * @param context
	 * @param allday
	 */
	public final void setAllday(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Boolean allday)
	{
		getMendixObject().setValue(context, MemberNames.Allday.toString(), allday);
	}

	/**
	 * @return value of Color
	 */
	public final java.lang.String getColor()
	{
		return getColor(getContext());
	}

	/**
	 * @param context
	 * @return value of Color
	 */
	public final java.lang.String getColor(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Color.toString());
	}

	/**
	 * Set value of Color
	 * @param color
	 */
	public final void setColor(java.lang.String color)
	{
		setColor(getContext(), color);
	}

	/**
	 * Set value of Color
	 * @param context
	 * @param color
	 */
	public final void setColor(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String color)
	{
		getMendixObject().setValue(context, MemberNames.Color.toString(), color);
	}

	/**
	 * @return value of CalendarTitle
	 */
	public final java.lang.String getCalendarTitle()
	{
		return getCalendarTitle(getContext());
	}

	/**
	 * @param context
	 * @return value of CalendarTitle
	 */
	public final java.lang.String getCalendarTitle(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.CalendarTitle.toString());
	}

	/**
	 * Set value of CalendarTitle
	 * @param calendartitle
	 */
	public final void setCalendarTitle(java.lang.String calendartitle)
	{
		setCalendarTitle(getContext(), calendartitle);
	}

	/**
	 * Set value of CalendarTitle
	 * @param context
	 * @param calendartitle
	 */
	public final void setCalendarTitle(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String calendartitle)
	{
		getMendixObject().setValue(context, MemberNames.CalendarTitle.toString(), calendartitle);
	}

	/**
	 * @return value of CalendarStartDate
	 */
	public final java.util.Date getCalendarStartDate()
	{
		return getCalendarStartDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CalendarStartDate
	 */
	public final java.util.Date getCalendarStartDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CalendarStartDate.toString());
	}

	/**
	 * Set value of CalendarStartDate
	 * @param calendarstartdate
	 */
	public final void setCalendarStartDate(java.util.Date calendarstartdate)
	{
		setCalendarStartDate(getContext(), calendarstartdate);
	}

	/**
	 * Set value of CalendarStartDate
	 * @param context
	 * @param calendarstartdate
	 */
	public final void setCalendarStartDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date calendarstartdate)
	{
		getMendixObject().setValue(context, MemberNames.CalendarStartDate.toString(), calendarstartdate);
	}

	/**
	 * @return value of CalendarEndDate
	 */
	public final java.util.Date getCalendarEndDate()
	{
		return getCalendarEndDate(getContext());
	}

	/**
	 * @param context
	 * @return value of CalendarEndDate
	 */
	public final java.util.Date getCalendarEndDate(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.CalendarEndDate.toString());
	}

	/**
	 * Set value of CalendarEndDate
	 * @param calendarenddate
	 */
	public final void setCalendarEndDate(java.util.Date calendarenddate)
	{
		setCalendarEndDate(getContext(), calendarenddate);
	}

	/**
	 * Set value of CalendarEndDate
	 * @param context
	 * @param calendarenddate
	 */
	public final void setCalendarEndDate(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date calendarenddate)
	{
		getMendixObject().setValue(context, MemberNames.CalendarEndDate.toString(), calendarenddate);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of FieldPhoto_WorkOrder
	 */
	public final work_management.proxies.FieldPhoto getFieldPhoto_WorkOrder() throws com.mendix.core.CoreException
	{
		return getFieldPhoto_WorkOrder(getContext());
	}

	/**
	 * @param context
	 * @return value of FieldPhoto_WorkOrder
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.FieldPhoto getFieldPhoto_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.FieldPhoto result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.FieldPhoto_WorkOrder.toString());
		if (identifier != null) {
			result = work_management.proxies.FieldPhoto.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of FieldPhoto_WorkOrder
	 * @param fieldphoto_workorder
	 */
	public final void setFieldPhoto_WorkOrder(work_management.proxies.FieldPhoto fieldphoto_workorder)
	{
		setFieldPhoto_WorkOrder(getContext(), fieldphoto_workorder);
	}

	/**
	 * Set value of FieldPhoto_WorkOrder
	 * @param context
	 * @param fieldphoto_workorder
	 */
	public final void setFieldPhoto_WorkOrder(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.FieldPhoto fieldphoto_workorder)
	{
		if (fieldphoto_workorder == null) {
			getMendixObject().setValue(context, MemberNames.FieldPhoto_WorkOrder.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.FieldPhoto_WorkOrder.toString(), fieldphoto_workorder.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrder_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrder_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getWorkOrder_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrder_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrder_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrder_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrder_WorkOrderResult
	 * @param workorder_workorderresult
	 */
	public final void setWorkOrder_WorkOrderResult(work_management.proxies.WorkOrderResult workorder_workorderresult)
	{
		setWorkOrder_WorkOrderResult(getContext(), workorder_workorderresult);
	}

	/**
	 * Set value of WorkOrder_WorkOrderResult
	 * @param context
	 * @param workorder_workorderresult
	 */
	public final void setWorkOrder_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderResult workorder_workorderresult)
	{
		if (workorder_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrder_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrder_WorkOrderResult.toString(), workorder_workorderresult.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WO_Equipment
	 */
	public final equipment_management.proxies.Equipment getWO_Equipment() throws com.mendix.core.CoreException
	{
		return getWO_Equipment(getContext());
	}

	/**
	 * @param context
	 * @return value of WO_Equipment
	 * @throws com.mendix.core.CoreException
	 */
	public final equipment_management.proxies.Equipment getWO_Equipment(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		equipment_management.proxies.Equipment result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WO_Equipment.toString());
		if (identifier != null) {
			result = equipment_management.proxies.Equipment.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WO_Equipment
	 * @param wo_equipment
	 */
	public final void setWO_Equipment(equipment_management.proxies.Equipment wo_equipment)
	{
		setWO_Equipment(getContext(), wo_equipment);
	}

	/**
	 * Set value of WO_Equipment
	 * @param context
	 * @param wo_equipment
	 */
	public final void setWO_Equipment(com.mendix.systemwideinterfaces.core.IContext context, equipment_management.proxies.Equipment wo_equipment)
	{
		if (wo_equipment == null) {
			getMendixObject().setValue(context, MemberNames.WO_Equipment.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WO_Equipment.toString(), wo_equipment.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WOPurpose_StandardCode
	 */
	public final commons.proxies.StandardCode getWOPurpose_StandardCode() throws com.mendix.core.CoreException
	{
		return getWOPurpose_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WOPurpose_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWOPurpose_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WOPurpose_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WOPurpose_StandardCode
	 * @param wopurpose_standardcode
	 */
	public final void setWOPurpose_StandardCode(commons.proxies.StandardCode wopurpose_standardcode)
	{
		setWOPurpose_StandardCode(getContext(), wopurpose_standardcode);
	}

	/**
	 * Set value of WOPurpose_StandardCode
	 * @param context
	 * @param wopurpose_standardcode
	 */
	public final void setWOPurpose_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode wopurpose_standardcode)
	{
		if (wopurpose_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WOPurpose_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WOPurpose_StandardCode.toString(), wopurpose_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WOStatus_StandardCode
	 */
	public final commons.proxies.StandardCode getWOStatus_StandardCode() throws com.mendix.core.CoreException
	{
		return getWOStatus_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WOStatus_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWOStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WOStatus_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WOStatus_StandardCode
	 * @param wostatus_standardcode
	 */
	public final void setWOStatus_StandardCode(commons.proxies.StandardCode wostatus_standardcode)
	{
		setWOStatus_StandardCode(getContext(), wostatus_standardcode);
	}

	/**
	 * Set value of WOStatus_StandardCode
	 * @param context
	 * @param wostatus_standardcode
	 */
	public final void setWOStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode wostatus_standardcode)
	{
		if (wostatus_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WOStatus_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WOStatus_StandardCode.toString(), wostatus_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WOPriority_StandardCode
	 */
	public final commons.proxies.StandardCode getWOPriority_StandardCode() throws com.mendix.core.CoreException
	{
		return getWOPriority_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of WOPriority_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getWOPriority_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WOPriority_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WOPriority_StandardCode
	 * @param wopriority_standardcode
	 */
	public final void setWOPriority_StandardCode(commons.proxies.StandardCode wopriority_standardcode)
	{
		setWOPriority_StandardCode(getContext(), wopriority_standardcode);
	}

	/**
	 * Set value of WOPriority_StandardCode
	 * @param context
	 * @param wopriority_standardcode
	 */
	public final void setWOPriority_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode wopriority_standardcode)
	{
		if (wopriority_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.WOPriority_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WOPriority_StandardCode.toString(), wopriority_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrder_Plant
	 */
	public final cmms_administration.proxies.Plant getWorkOrder_Plant() throws com.mendix.core.CoreException
	{
		return getWorkOrder_Plant(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrder_Plant
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Plant getWorkOrder_Plant(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Plant result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrder_Plant.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Plant.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrder_Plant
	 * @param workorder_plant
	 */
	public final void setWorkOrder_Plant(cmms_administration.proxies.Plant workorder_plant)
	{
		setWorkOrder_Plant(getContext(), workorder_plant);
	}

	/**
	 * Set value of WorkOrder_Plant
	 * @param context
	 * @param workorder_plant
	 */
	public final void setWorkOrder_Plant(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Plant workorder_plant)
	{
		if (workorder_plant == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrder_Plant.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrder_Plant.toString(), workorder_plant.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of RequestPlan_Material
	 */
	public final java.util.List<material_management.proxies.Material> getRequestPlan_Material() throws com.mendix.core.CoreException
	{
		return getRequestPlan_Material(getContext());
	}

	/**
	 * @param context
	 * @return value of RequestPlan_Material
	 * @throws com.mendix.core.CoreException
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<material_management.proxies.Material> getRequestPlan_Material(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<material_management.proxies.Material> result = new java.util.ArrayList<>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.RequestPlan_Material.toString());
		if (valueObject == null) {
			return result;
		}
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject)) {
			result.add(material_management.proxies.Material.initialize(context, mendixObject));
		}
		return result;
	}

	/**
	 * Set value of RequestPlan_Material
	 * @param requestplan_material
	 */
	public final void setRequestPlan_Material(java.util.List<material_management.proxies.Material> requestplan_material)
	{
		setRequestPlan_Material(getContext(), requestplan_material);
	}

	/**
	 * Set value of RequestPlan_Material
	 * @param context
	 * @param requestplan_material
	 */
	public final void setRequestPlan_Material(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<material_management.proxies.Material> requestplan_material)
	{
		var identifiers = requestplan_material
			.stream()
			.map(proxyObject -> proxyObject.getMendixObject().getId())
			.collect(java.util.stream.Collectors.toList());
		
		getMendixObject().setValue(context, MemberNames.RequestPlan_Material.toString(), identifiers);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of ApproveStatus_StandardCode
	 */
	public final commons.proxies.StandardCode getApproveStatus_StandardCode() throws com.mendix.core.CoreException
	{
		return getApproveStatus_StandardCode(getContext());
	}

	/**
	 * @param context
	 * @return value of ApproveStatus_StandardCode
	 * @throws com.mendix.core.CoreException
	 */
	public final commons.proxies.StandardCode getApproveStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		commons.proxies.StandardCode result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.ApproveStatus_StandardCode.toString());
		if (identifier != null) {
			result = commons.proxies.StandardCode.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of ApproveStatus_StandardCode
	 * @param approvestatus_standardcode
	 */
	public final void setApproveStatus_StandardCode(commons.proxies.StandardCode approvestatus_standardcode)
	{
		setApproveStatus_StandardCode(getContext(), approvestatus_standardcode);
	}

	/**
	 * Set value of ApproveStatus_StandardCode
	 * @param context
	 * @param approvestatus_standardcode
	 */
	public final void setApproveStatus_StandardCode(com.mendix.systemwideinterfaces.core.IContext context, commons.proxies.StandardCode approvestatus_standardcode)
	{
		if (approvestatus_standardcode == null) {
			getMendixObject().setValue(context, MemberNames.ApproveStatus_StandardCode.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.ApproveStatus_StandardCode.toString(), approvestatus_standardcode.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Approver_Employee
	 */
	public final cmms_administration.proxies.Employee getApprover_Employee() throws com.mendix.core.CoreException
	{
		return getApprover_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Approver_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getApprover_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Approver_Employee.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Approver_Employee
	 * @param approver_employee
	 */
	public final void setApprover_Employee(cmms_administration.proxies.Employee approver_employee)
	{
		setApprover_Employee(getContext(), approver_employee);
	}

	/**
	 * Set value of Approver_Employee
	 * @param context
	 * @param approver_employee
	 */
	public final void setApprover_Employee(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee approver_employee)
	{
		if (approver_employee == null) {
			getMendixObject().setValue(context, MemberNames.Approver_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Approver_Employee.toString(), approver_employee.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Assigner_Employee
	 */
	public final cmms_administration.proxies.Employee getAssigner_Employee() throws com.mendix.core.CoreException
	{
		return getAssigner_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Assigner_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getAssigner_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Assigner_Employee.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Assigner_Employee
	 * @param assigner_employee
	 */
	public final void setAssigner_Employee(cmms_administration.proxies.Employee assigner_employee)
	{
		setAssigner_Employee(getContext(), assigner_employee);
	}

	/**
	 * Set value of Assigner_Employee
	 * @param context
	 * @param assigner_employee
	 */
	public final void setAssigner_Employee(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee assigner_employee)
	{
		if (assigner_employee == null) {
			getMendixObject().setValue(context, MemberNames.Assigner_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Assigner_Employee.toString(), assigner_employee.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AssignedManager_Employee
	 */
	public final cmms_administration.proxies.Employee getAssignedManager_Employee() throws com.mendix.core.CoreException
	{
		return getAssignedManager_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of AssignedManager_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getAssignedManager_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AssignedManager_Employee.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AssignedManager_Employee
	 * @param assignedmanager_employee
	 */
	public final void setAssignedManager_Employee(cmms_administration.proxies.Employee assignedmanager_employee)
	{
		setAssignedManager_Employee(getContext(), assignedmanager_employee);
	}

	/**
	 * Set value of AssignedManager_Employee
	 * @param context
	 * @param assignedmanager_employee
	 */
	public final void setAssignedManager_Employee(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee assignedmanager_employee)
	{
		if (assignedmanager_employee == null) {
			getMendixObject().setValue(context, MemberNames.AssignedManager_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AssignedManager_Employee.toString(), assignedmanager_employee.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of AssignedWorkers_Employee
	 */
	public final cmms_administration.proxies.Employee getAssignedWorkers_Employee() throws com.mendix.core.CoreException
	{
		return getAssignedWorkers_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of AssignedWorkers_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getAssignedWorkers_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.AssignedWorkers_Employee.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of AssignedWorkers_Employee
	 * @param assignedworkers_employee
	 */
	public final void setAssignedWorkers_Employee(cmms_administration.proxies.Employee assignedworkers_employee)
	{
		setAssignedWorkers_Employee(getContext(), assignedworkers_employee);
	}

	/**
	 * Set value of AssignedWorkers_Employee
	 * @param context
	 * @param assignedworkers_employee
	 */
	public final void setAssignedWorkers_Employee(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee assignedworkers_employee)
	{
		if (assignedworkers_employee == null) {
			getMendixObject().setValue(context, MemberNames.AssignedWorkers_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.AssignedWorkers_Employee.toString(), assignedworkers_employee.getMendixObject().getId());
		}
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of Requester_Employee
	 */
	public final cmms_administration.proxies.Employee getRequester_Employee() throws com.mendix.core.CoreException
	{
		return getRequester_Employee(getContext());
	}

	/**
	 * @param context
	 * @return value of Requester_Employee
	 * @throws com.mendix.core.CoreException
	 */
	public final cmms_administration.proxies.Employee getRequester_Employee(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		cmms_administration.proxies.Employee result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Requester_Employee.toString());
		if (identifier != null) {
			result = cmms_administration.proxies.Employee.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of Requester_Employee
	 * @param requester_employee
	 */
	public final void setRequester_Employee(cmms_administration.proxies.Employee requester_employee)
	{
		setRequester_Employee(getContext(), requester_employee);
	}

	/**
	 * Set value of Requester_Employee
	 * @param context
	 * @param requester_employee
	 */
	public final void setRequester_Employee(com.mendix.systemwideinterfaces.core.IContext context, cmms_administration.proxies.Employee requester_employee)
	{
		if (requester_employee == null) {
			getMendixObject().setValue(context, MemberNames.Requester_Employee.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.Requester_Employee.toString(), requester_employee.getMendixObject().getId());
		}
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrder that = (work_management.proxies.WorkOrder) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
