// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

/**
 * 최초 작성자 : 이단비
 * 최초 작성일 : 2023/10/20
 * 최종 수정자 : 이단비
 * 최종 수정일 : 2023/10/20
 * 설명 : 작업관리 현황 정보를 담는 엔터티이다.
 * Version 1.0 : 생성
 */
public class WorkOrderCount implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderCountMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderCount";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TotalAccumulatedCount("TotalAccumulatedCount"),
		TotalCount("TotalCount"),
		CompleteCount("CompleteCount"),
		ProcessingCount("ProcessingCount"),
		OpenCount("OpenCount");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderCount(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderCountMendixObject)
	{
		if (workOrderCountMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderCountMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderCountMendixObject = workOrderCountMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderCount initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderCount(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderCount load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderCount.initialize(context, mendixObject);
	}

	/**
	 * @return value of TotalAccumulatedCount
	 */
	public final java.lang.Integer getTotalAccumulatedCount()
	{
		return getTotalAccumulatedCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalAccumulatedCount
	 */
	public final java.lang.Integer getTotalAccumulatedCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalAccumulatedCount.toString());
	}

	/**
	 * Set value of TotalAccumulatedCount
	 * @param totalaccumulatedcount
	 */
	public final void setTotalAccumulatedCount(java.lang.Integer totalaccumulatedcount)
	{
		setTotalAccumulatedCount(getContext(), totalaccumulatedcount);
	}

	/**
	 * Set value of TotalAccumulatedCount
	 * @param context
	 * @param totalaccumulatedcount
	 */
	public final void setTotalAccumulatedCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalaccumulatedcount)
	{
		getMendixObject().setValue(context, MemberNames.TotalAccumulatedCount.toString(), totalaccumulatedcount);
	}

	/**
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount()
	{
		return getTotalCount(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalCount
	 */
	public final java.lang.Integer getTotalCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.TotalCount.toString());
	}

	/**
	 * Set value of TotalCount
	 * @param totalcount
	 */
	public final void setTotalCount(java.lang.Integer totalcount)
	{
		setTotalCount(getContext(), totalcount);
	}

	/**
	 * Set value of TotalCount
	 * @param context
	 * @param totalcount
	 */
	public final void setTotalCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer totalcount)
	{
		getMendixObject().setValue(context, MemberNames.TotalCount.toString(), totalcount);
	}

	/**
	 * @return value of CompleteCount
	 */
	public final java.lang.Integer getCompleteCount()
	{
		return getCompleteCount(getContext());
	}

	/**
	 * @param context
	 * @return value of CompleteCount
	 */
	public final java.lang.Integer getCompleteCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.CompleteCount.toString());
	}

	/**
	 * Set value of CompleteCount
	 * @param completecount
	 */
	public final void setCompleteCount(java.lang.Integer completecount)
	{
		setCompleteCount(getContext(), completecount);
	}

	/**
	 * Set value of CompleteCount
	 * @param context
	 * @param completecount
	 */
	public final void setCompleteCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer completecount)
	{
		getMendixObject().setValue(context, MemberNames.CompleteCount.toString(), completecount);
	}

	/**
	 * @return value of ProcessingCount
	 */
	public final java.lang.Integer getProcessingCount()
	{
		return getProcessingCount(getContext());
	}

	/**
	 * @param context
	 * @return value of ProcessingCount
	 */
	public final java.lang.Integer getProcessingCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ProcessingCount.toString());
	}

	/**
	 * Set value of ProcessingCount
	 * @param processingcount
	 */
	public final void setProcessingCount(java.lang.Integer processingcount)
	{
		setProcessingCount(getContext(), processingcount);
	}

	/**
	 * Set value of ProcessingCount
	 * @param context
	 * @param processingcount
	 */
	public final void setProcessingCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer processingcount)
	{
		getMendixObject().setValue(context, MemberNames.ProcessingCount.toString(), processingcount);
	}

	/**
	 * @return value of OpenCount
	 */
	public final java.lang.Integer getOpenCount()
	{
		return getOpenCount(getContext());
	}

	/**
	 * @param context
	 * @return value of OpenCount
	 */
	public final java.lang.Integer getOpenCount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.OpenCount.toString());
	}

	/**
	 * Set value of OpenCount
	 * @param opencount
	 */
	public final void setOpenCount(java.lang.Integer opencount)
	{
		setOpenCount(getContext(), opencount);
	}

	/**
	 * Set value of OpenCount
	 * @param context
	 * @param opencount
	 */
	public final void setOpenCount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer opencount)
	{
		getMendixObject().setValue(context, MemberNames.OpenCount.toString(), opencount);
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderCountMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderCount that = (work_management.proxies.WorkOrderCount) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
