// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package work_management.proxies;

public class WorkOrderETC implements com.mendix.systemwideinterfaces.core.IEntityProxy
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject workOrderETCMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Work_Management.WorkOrderETC";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		ETCCost("ETCCost"),
		ETCDescription("ETCDescription"),
		WorkOrderETC_WorkOrderResult("Work_Management.WorkOrderETC_WorkOrderResult");

		private final java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public WorkOrderETC(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, entityName));
	}

	protected WorkOrderETC(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject workOrderETCMendixObject)
	{
		if (workOrderETCMendixObject == null) {
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		}
		if (!com.mendix.core.Core.isSubClassOf(entityName, workOrderETCMendixObject.getType())) {
			throw new java.lang.IllegalArgumentException(String.format("The given object is not a %s", entityName));
		}	

		this.workOrderETCMendixObject = workOrderETCMendixObject;
		this.context = context;
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 * @param context The context to be used
	 * @param mendixObject The Mendix object for the new instance
	 * @return a new instance of this proxy class
	 */
	public static work_management.proxies.WorkOrderETC initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new work_management.proxies.WorkOrderETC(context, mendixObject);
	}

	public static work_management.proxies.WorkOrderETC load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return work_management.proxies.WorkOrderETC.initialize(context, mendixObject);
	}

	public static java.util.List<work_management.proxies.WorkOrderETC> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		return com.mendix.core.Core.createXPathQuery(String.format("//%1$s%2$s", entityName, xpathConstraint))
			.execute(context)
			.stream()
			.map(obj -> work_management.proxies.WorkOrderETC.initialize(context, obj))
			.collect(java.util.stream.Collectors.toList());
	}

	/**
	 * @return value of ETCCost
	 */
	public final java.lang.Integer getETCCost()
	{
		return getETCCost(getContext());
	}

	/**
	 * @param context
	 * @return value of ETCCost
	 */
	public final java.lang.Integer getETCCost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Integer) getMendixObject().getValue(context, MemberNames.ETCCost.toString());
	}

	/**
	 * Set value of ETCCost
	 * @param etccost
	 */
	public final void setETCCost(java.lang.Integer etccost)
	{
		setETCCost(getContext(), etccost);
	}

	/**
	 * Set value of ETCCost
	 * @param context
	 * @param etccost
	 */
	public final void setETCCost(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Integer etccost)
	{
		getMendixObject().setValue(context, MemberNames.ETCCost.toString(), etccost);
	}

	/**
	 * @return value of ETCDescription
	 */
	public final java.lang.String getETCDescription()
	{
		return getETCDescription(getContext());
	}

	/**
	 * @param context
	 * @return value of ETCDescription
	 */
	public final java.lang.String getETCDescription(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.ETCDescription.toString());
	}

	/**
	 * Set value of ETCDescription
	 * @param etcdescription
	 */
	public final void setETCDescription(java.lang.String etcdescription)
	{
		setETCDescription(getContext(), etcdescription);
	}

	/**
	 * Set value of ETCDescription
	 * @param context
	 * @param etcdescription
	 */
	public final void setETCDescription(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String etcdescription)
	{
		getMendixObject().setValue(context, MemberNames.ETCDescription.toString(), etcdescription);
	}

	/**
	 * @throws com.mendix.core.CoreException
	 * @return value of WorkOrderETC_WorkOrderResult
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderETC_WorkOrderResult() throws com.mendix.core.CoreException
	{
		return getWorkOrderETC_WorkOrderResult(getContext());
	}

	/**
	 * @param context
	 * @return value of WorkOrderETC_WorkOrderResult
	 * @throws com.mendix.core.CoreException
	 */
	public final work_management.proxies.WorkOrderResult getWorkOrderETC_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		work_management.proxies.WorkOrderResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.WorkOrderETC_WorkOrderResult.toString());
		if (identifier != null) {
			result = work_management.proxies.WorkOrderResult.load(context, identifier);
		}
		return result;
	}

	/**
	 * Set value of WorkOrderETC_WorkOrderResult
	 * @param workorderetc_workorderresult
	 */
	public final void setWorkOrderETC_WorkOrderResult(work_management.proxies.WorkOrderResult workorderetc_workorderresult)
	{
		setWorkOrderETC_WorkOrderResult(getContext(), workorderetc_workorderresult);
	}

	/**
	 * Set value of WorkOrderETC_WorkOrderResult
	 * @param context
	 * @param workorderetc_workorderresult
	 */
	public final void setWorkOrderETC_WorkOrderResult(com.mendix.systemwideinterfaces.core.IContext context, work_management.proxies.WorkOrderResult workorderetc_workorderresult)
	{
		if (workorderetc_workorderresult == null) {
			getMendixObject().setValue(context, MemberNames.WorkOrderETC_WorkOrderResult.toString(), null);
		} else {
			getMendixObject().setValue(context, MemberNames.WorkOrderETC_WorkOrderResult.toString(), workorderetc_workorderresult.getMendixObject().getId());
		}
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return workOrderETCMendixObject;
	}

	@Override
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this) {
			return true;
		}
		if (obj != null && getClass().equals(obj.getClass()))
		{
			final work_management.proxies.WorkOrderETC that = (work_management.proxies.WorkOrderETC) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

  /**
   * Gives full name ("Module.Entity" name) of the type of the entity.
   *
   * @return the name
   */
	public static java.lang.String getType()
	{
		return entityName;
	}
}
