// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmms_globalsearch.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the CMMS_GlobalSearch module

	public static java.lang.Long getNumberOfResults()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("CMMS_GlobalSearch.NumberOfResults");
	}
}