// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package cmms_globalsearch.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the CMMS_GlobalSearch module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_Search_OverviewBuilder(
		globalsearch.proxies.Searcher _searcher
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CMMS_GlobalSearch.ACT_Search_Overview");
		builder = builder.withParam("Searcher", _searcher);
		return builder;
	}

	public static void aCT_Search_Overview(
		IContext context,
		globalsearch.proxies.Searcher _searcher
	)
	{
		aCT_Search_OverviewBuilder(
				_searcher
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_DeleteIndexBuilder(
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CMMS_GlobalSearch.SUB_DeleteIndex");
		builder = builder.withParam("SearchableObject", _searchableObject);
		return builder;
	}

	public static boolean sUB_DeleteIndex(
		IContext context,
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		Object result = sUB_DeleteIndexBuilder(
				_searchableObject
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Equipment_IndexBuilder(
		equipment_management.proxies.Equipment _equipment
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CMMS_GlobalSearch.SUB_Equipment_Index");
		builder = builder.withParam("Equipment", _equipment);
		return builder;
	}

	public static void sUB_Equipment_Index(
		IContext context,
		equipment_management.proxies.Equipment _equipment
	)
	{
		sUB_Equipment_IndexBuilder(
				_equipment
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_IndexObjectBuilder(
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CMMS_GlobalSearch.SUB_IndexObject");
		builder = builder.withParam("SearchableObject", _searchableObject);
		return builder;
	}

	public static boolean sUB_IndexObject(
		IContext context,
		globalsearch.proxies.SearchableObject _searchableObject
	)
	{
		Object result = sUB_IndexObjectBuilder(
				_searchableObject
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Sensor_IndexBuilder(
		monitoring.proxies.Sensor _sensor
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CMMS_GlobalSearch.SUB_Sensor_Index");
		builder = builder.withParam("Sensor", _sensor);
		return builder;
	}

	public static void sUB_Sensor_Index(
		IContext context,
		monitoring.proxies.Sensor _sensor
	)
	{
		sUB_Sensor_IndexBuilder(
				_sensor
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_WorkHistory_IndexBuilder(
		work_management.proxies.WorkHistory _workHistory
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CMMS_GlobalSearch.SUB_WorkHistory_Index");
		builder = builder.withParam("WorkHistory", _workHistory);
		return builder;
	}

	public static void sUB_WorkHistory_Index(
		IContext context,
		work_management.proxies.WorkHistory _workHistory
	)
	{
		sUB_WorkHistory_IndexBuilder(
				_workHistory
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_WorkOrder_IndexBuilder(
		work_management.proxies.WorkOrder _workOrder
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CMMS_GlobalSearch.SUB_WorkOrder_Index");
		builder = builder.withParam("WorkOrder", _workOrder);
		return builder;
	}

	public static void sUB_WorkOrder_Index(
		IContext context,
		work_management.proxies.WorkOrder _workOrder
	)
	{
		sUB_WorkOrder_IndexBuilder(
				_workOrder
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_WorkOrderResult_IndexBuilder(
		work_management.proxies.WorkOrderResult _workOrderResult
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("CMMS_GlobalSearch.SUB_WorkOrderResult_Index");
		builder = builder.withParam("WorkOrderResult", _workOrderResult);
		return builder;
	}

	public static void sUB_WorkOrderResult_Index(
		IContext context,
		work_management.proxies.WorkOrderResult _workOrderResult
	)
	{
		sUB_WorkOrderResult_IndexBuilder(
				_workOrderResult
			)
			.execute(context);
	}
}
