// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package commons.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the Commons module

	/**
	* 최초작성자 : 김동명
	* 최초작성일 : 2023-11-27
	* 
	* 설명 : 구글 SSO 관련 로그노드를 위한 상수
	* 
	* V1.0 : 최초작성
	*/
	public static java.lang.String getGoogleSSO()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Commons.GoogleSSO");
	}
}