// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package globalsearch.proxies.constants;

import com.mendix.core.Core;

public final class Constants
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Constants() {}

	// These are the constants for the GlobalSearch module

	public static boolean getIndexAfterStartup()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("GlobalSearch.IndexAfterStartup");
	}

	/**
	* Set this constant to true to restore zipped index data after application startup.
	*/
	public static boolean getIndexFileRestoreAfterStartup()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("GlobalSearch.IndexFileRestoreAfterStartup");
	}

	/**
	* Set this constant to True to store index data before shutdown.
	*/
	public static boolean getIndexFileStoreBeforeShutdown()
	{
		return (java.lang.Boolean)Core.getConfiguration().getConstantValue("GlobalSearch.IndexFileStoreBeforeShutdown");
	}

	public static java.lang.String getLogNode()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("GlobalSearch.LogNode");
	}

	/**
	* In case of searching on multiple words, slop is used to configure how far away these words can be in the text to return a search result. Default is set to 5, high numbers are not recommended.
	*/
	public static java.lang.Long getSlop()
	{
		return (java.lang.Long)Core.getConfiguration().getConstantValue("GlobalSearch.Slop");
	}
}