// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum ImportActions
{
	SynchronizeObjects(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Synchroniseer objecten" }, new java.lang.String[] { "en_GB", "Synchronize objects" }, new java.lang.String[] { "en_ZA", "Synchronize objects" }, new java.lang.String[] { "ko_KR", "Synchronize objects" } }),
	SynchronizeOnlyExisting(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Synchroniseer alleen bestaande objecten, negeer de rest" }, new java.lang.String[] { "en_GB", "Synchronize only existing objects, ignore others" }, new java.lang.String[] { "en_ZA", "Synchronize only existing objects, ignore others" }, new java.lang.String[] { "ko_KR", "Synchronize only existing objects, ignore others" } }),
	CreateObjects(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Creeër een object voor iedere rij" }, new java.lang.String[] { "en_GB", "Create an object for each row" }, new java.lang.String[] { "en_ZA", "Create an object for each row" }, new java.lang.String[] { "ko_KR", "Create an object for each row" } }),
	OnlyCreateNewObjects(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Creeër alleen niet bestaande objecten" }, new java.lang.String[] { "en_GB", "Only create not existing object" }, new java.lang.String[] { "en_ZA", "Only create not existing object" }, new java.lang.String[] { "ko_KR", "Only create not existing object" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private ImportActions(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
