// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum RemoveIndicator
{
	TrackChanges(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Hou alleen de wijzigingen bij" }, new java.lang.String[] { "en_GB", "Track changes" }, new java.lang.String[] { "en_ZA", "Track changes" }, new java.lang.String[] { "ko_KR", "Track changes" } }),
	RemoveUnchangedObjects(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Verwijder alle ongewijzigde objecten" }, new java.lang.String[] { "en_GB", "Remove unchanged objects" }, new java.lang.String[] { "en_ZA", "Remove unchanged objects" }, new java.lang.String[] { "ko_KR", "Remove unchanged objects" } }),
	Nothing(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Niets" }, new java.lang.String[] { "en_GB", "Nothing" }, new java.lang.String[] { "en_ZA", "Nothing" }, new java.lang.String[] { "ko_KR", "Nothing" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private RemoveIndicator(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
