// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package excelimporter.proxies;

public enum TemplateType
{
	Normal(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Normaal" }, new java.lang.String[] { "en_GB", "Normal" }, new java.lang.String[] { "en_ZA", "Normal" }, new java.lang.String[] { "ko_KR", "Normal" } }),
	Wizard(new java.lang.String[][] { new java.lang.String[] { "nl_NL", "Wizard" }, new java.lang.String[] { "en_GB", "Wizard" }, new java.lang.String[] { "en_ZA", "Wizard" }, new java.lang.String[] { "ko_KR", "Wizard" } });

	private final java.util.Map<java.lang.String, java.lang.String> captions;

	private TemplateType(java.lang.String[][] captionStrings)
	{
		this.captions = new java.util.HashMap<>();
		for (java.lang.String[] captionString : captionStrings) {
			captions.put(captionString[0], captionString[1]);
		}
	}

	public java.lang.String getCaption(java.lang.String languageCode)
	{
		return captions.getOrDefault(languageCode, "ko_KR");
	}

	public java.lang.String getCaption()
	{
		return captions.get("ko_KR");
	}
}
