// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package mypage.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the MyPage module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_File_DeleteBuilder(
		mypage.proxies.Files _files
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_File_Delete");
		builder = builder.withParam("Files", _files);
		return builder;
	}

	public static void aCT_File_Delete(
		IContext context,
		mypage.proxies.Files _files
	)
	{
		aCT_File_DeleteBuilder(
				_files
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_File_DownloadBuilder(
		mypage.proxies.Files _files
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_File_Download");
		builder = builder.withParam("Files", _files);
		return builder;
	}

	public static void aCT_File_Download(
		IContext context,
		mypage.proxies.Files _files
	)
	{
		aCT_File_DownloadBuilder(
				_files
			)
			.execute(context);
	}
	/**
	 * 내 설비 보기 페이지 내 내 설비 삭제 로직
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MyEquipment_DeleteBuilder(
		equipment_management.proxies.Equipment _equipment,
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_MyEquipment_Delete");
		builder = builder.withParam("Equipment", _equipment);
		builder = builder.withParam("FilterHelper", _filterHelper);
		return builder;
	}

	/**
	 * 내 설비 보기 페이지 내 내 설비 삭제 로직
	 */
	public static void aCT_MyEquipment_Delete(
		IContext context,
		equipment_management.proxies.Equipment _equipment,
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		aCT_MyEquipment_DeleteBuilder(
				_equipment,
				_filterHelper
			)
			.execute(context);
	}
	/**
	 * 내 설비 추가 팝업에서 저장 로직
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MyEquipment_SaveBuilder(
		java.util.List<equipment_management.proxies.Equipment> _equipmentList,
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_MyEquipment_Save");
		builder = builder.withParam("EquipmentList", _equipmentList);
		builder = builder.withParam("FilterHelper", _filterHelper);
		return builder;
	}

	/**
	 * 내 설비 추가 팝업에서 저장 로직
	 */
	public static void aCT_MyEquipment_Save(
		IContext context,
		java.util.List<equipment_management.proxies.Equipment> _equipmentList,
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		aCT_MyEquipment_SaveBuilder(
				_equipmentList,
				_filterHelper
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_MyWorkReport_OverviewBuilder(
		cmms_administration.proxies.Employee _employee
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_MyWorkReport_Overview");
		builder = builder.withParam("Employee", _employee);
		return builder;
	}

	public static void aCT_MyWorkReport_Overview(
		IContext context,
		cmms_administration.proxies.Employee _employee
	)
	{
		aCT_MyWorkReport_OverviewBuilder(
				_employee
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_WorkReport_DeleteBuilder(
		mypage.proxies.WorkReport _workReport
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_WorkReport_Delete");
		builder = builder.withParam("WorkReport", _workReport);
		return builder;
	}

	public static void aCT_WorkReport_Delete(
		IContext context,
		mypage.proxies.WorkReport _workReport
	)
	{
		aCT_WorkReport_DeleteBuilder(
				_workReport
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_WorkReport_EditBuilder(
		mypage.proxies.WorkReport _workReport,
		mypage.proxies.DatePickHelepr _datePickHelepr
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_WorkReport_Edit");
		builder = builder.withParam("WorkReport", _workReport);
		builder = builder.withParam("DatePickHelepr", _datePickHelepr);
		return builder;
	}

	public static void aCT_WorkReport_Edit(
		IContext context,
		mypage.proxies.WorkReport _workReport,
		mypage.proxies.DatePickHelepr _datePickHelepr
	)
	{
		aCT_WorkReport_EditBuilder(
				_workReport,
				_datePickHelepr
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_WorkReport_NewBuilder(
		mypage.proxies.DatePickHelepr _datePickHelepr
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_WorkReport_New");
		builder = builder.withParam("DatePickHelepr", _datePickHelepr);
		return builder;
	}

	public static void aCT_WorkReport_New(
		IContext context,
		mypage.proxies.DatePickHelepr _datePickHelepr
	)
	{
		aCT_WorkReport_NewBuilder(
				_datePickHelepr
			)
			.execute(context);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder aCT_WorkReportHelper_SaveBuilder(
		mypage.proxies.WorkReportHelper _workReportHelper,
		mypage.proxies.DatePickHelepr _datePickHelepr
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.ACT_WorkReportHelper_Save");
		builder = builder.withParam("WorkReportHelper", _workReportHelper);
		builder = builder.withParam("DatePickHelepr", _datePickHelepr);
		return builder;
	}

	public static void aCT_WorkReportHelper_Save(
		IContext context,
		mypage.proxies.WorkReportHelper _workReportHelper,
		mypage.proxies.DatePickHelepr _datePickHelepr
	)
	{
		aCT_WorkReportHelper_SaveBuilder(
				_workReportHelper,
				_datePickHelepr
			)
			.execute(context);
	}
	/**
	 * Company DS MF
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Company_SideBarBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.DS_Company_SideBar");
		return builder;
	}

	/**
	 * Company DS MF
	 */
	public static commons.proxies.Company dS_Company_SideBar(IContext context)
	{
		Object result = dS_Company_SideBarBuilder().execute(context);
		return result == null ? null : commons.proxies.Company.initialize(context, (IMendixObject) result);
	}
	/**
	 * Employee DS MF
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_Employee_SideBarBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.DS_Employee_SideBar");
		return builder;
	}

	/**
	 * Employee DS MF
	 */
	public static cmms_administration.proxies.Employee dS_Employee_SideBar(IContext context)
	{
		Object result = dS_Employee_SideBarBuilder().execute(context);
		return result == null ? null : cmms_administration.proxies.Employee.initialize(context, (IMendixObject) result);
	}
	/**
	 * 내 설비 보기 페이지 내 필터링 로직
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_MyEquipment_GalleryBuilder(
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.DS_MyEquipment_Gallery");
		builder = builder.withParam("FilterHelper", _filterHelper);
		return builder;
	}

	/**
	 * 내 설비 보기 페이지 내 필터링 로직
	 */
	public static java.util.List<equipment_management.proxies.Equipment> dS_MyEquipment_Gallery(
		IContext context,
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		Object result = dS_MyEquipment_GalleryBuilder(
				_filterHelper
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> equipment_management.proxies.Equipment.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder dS_MyWorkReportBuilder(
		mypage.proxies.DatePickHelepr _datePickHelepr
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.DS_MyWorkReport");
		builder = builder.withParam("DatePickHelepr", _datePickHelepr);
		return builder;
	}

	public static java.util.List<mypage.proxies.WorkReport> dS_MyWorkReport(
		IContext context,
		mypage.proxies.DatePickHelepr _datePickHelepr
	)
	{
		Object result = dS_MyWorkReportBuilder(
				_datePickHelepr
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> mypage.proxies.WorkReport.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder file_WorkReport_DeleteBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.File_WorkReport_Delete");
		return builder;
	}

	public static void file_WorkReport_Delete(IContext context)
	{
		file_WorkReport_DeleteBuilder().execute(context);
	}
	/**
	 * 내 설비 보기 페이지 내 전체 설비 분류 필터
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_FilterHelper_EquipmentTypeBuilder(
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.OCH_FilterHelper_EquipmentType");
		builder = builder.withParam("FilterHelper", _filterHelper);
		return builder;
	}

	/**
	 * 내 설비 보기 페이지 내 전체 설비 분류 필터
	 */
	public static void oCH_FilterHelper_EquipmentType(
		IContext context,
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		oCH_FilterHelper_EquipmentTypeBuilder(
				_filterHelper
			)
			.execute(context);
	}
	/**
	 * 내 설비 보기 페이지 내 작업 수순 분류 필터
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder oCH_FilterHelper_StatusBuilder(
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.OCH_FilterHelper_Status");
		builder = builder.withParam("FilterHelper", _filterHelper);
		return builder;
	}

	/**
	 * 내 설비 보기 페이지 내 작업 수순 분류 필터
	 */
	public static void oCH_FilterHelper_Status(
		IContext context,
		mypage.proxies.FilterHelper _filterHelper
	)
	{
		oCH_FilterHelper_StatusBuilder(
				_filterHelper
			)
			.execute(context);
	}
	/**
	 * FilterHelper 엔터티 생성
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_Create_FilterHelperBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.SUB_Create_FilterHelper");
		return builder;
	}

	/**
	 * FilterHelper 엔터티 생성
	 */
	public static mypage.proxies.FilterHelper sUB_Create_FilterHelper(IContext context)
	{
		Object result = sUB_Create_FilterHelperBuilder().execute(context);
		return result == null ? null : mypage.proxies.FilterHelper.initialize(context, (IMendixObject) result);
	}
	/**
	 * 내 설비 보기 필터링 로직
	 */
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_MyEquipmentFilterBuilder(
		mypage.proxies.FilterHelper _filterHelper,
		java.util.List<equipment_management.proxies.Equipment> _equipmentList
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.SUB_MyEquipmentFilter");
		builder = builder.withParam("FilterHelper", _filterHelper);
		builder = builder.withParam("EquipmentList", _equipmentList);
		return builder;
	}

	/**
	 * 내 설비 보기 필터링 로직
	 */
	public static java.util.List<equipment_management.proxies.Equipment> sUB_MyEquipmentFilter(
		IContext context,
		mypage.proxies.FilterHelper _filterHelper,
		java.util.List<equipment_management.proxies.Equipment> _equipmentList
	)
	{
		Object result = sUB_MyEquipmentFilterBuilder(
				_filterHelper,
				_equipmentList
			)
			.execute(context);
		return result == null ? null : com.mendix.utils.ListUtils.map((java.util.List<IMendixObject>) result, obj -> equipment_management.proxies.Equipment.initialize(context, obj));
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder sUB_WorkReportHelper_ValidationBuilder(
		mypage.proxies.WorkReportHelper _workReportHelper
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.SUB_WorkReportHelper_Validation");
		builder = builder.withParam("WorkReportHelper", _workReportHelper);
		return builder;
	}

	public static boolean sUB_WorkReportHelper_Validation(
		IContext context,
		mypage.proxies.WorkReportHelper _workReportHelper
	)
	{
		Object result = sUB_WorkReportHelper_ValidationBuilder(
				_workReportHelper
			)
			.execute(context);
		return (boolean) result;
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder workReport_CreateBuilder()
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("MyPage.WorkReport_Create");
		return builder;
	}

	public static mypage.proxies.WorkReport workReport_Create(IContext context)
	{
		Object result = workReport_CreateBuilder().execute(context);
		return result == null ? null : mypage.proxies.WorkReport.initialize(context, (IMendixObject) result);
	}
}
