// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package google.proxies.microflows;

import com.mendix.core.Core;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public final class Microflows
{
	/**
	 * Private constructor to prevent instantiation of this class. 
	 */
	private Microflows() {}

	// These are the microflows for the Google module
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder userProvisioning_Google_SBBuilder(
		oidc.proxies.Token _oAuthToken,
		java.lang.String _openIDTokenJSON
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Google.UserProvisioning_Google_SB");
		builder = builder.withParam("OAuthToken", _oAuthToken);
		builder = builder.withParam("OpenIDTokenJSON", _openIDTokenJSON);
		return builder;
	}

	public static administration.proxies.Account userProvisioning_Google_SB(
		IContext context,
		oidc.proxies.Token _oAuthToken,
		java.lang.String _openIDTokenJSON
	)
	{
		Object result = userProvisioning_Google_SBBuilder(
				_oAuthToken,
				_openIDTokenJSON
			)
			.execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, (IMendixObject) result);
	}
	public static com.mendix.core.actionmanagement.MicroflowCallBuilder userProvisioning_SBBuilder(
		oidc.proxies.Token _oAuthToken
	)
	{
		com.mendix.core.actionmanagement.MicroflowCallBuilder builder = Core.microflowCall("Google.UserProvisioning_SB");
		builder = builder.withParam("OAuthToken", _oAuthToken);
		return builder;
	}

	public static administration.proxies.Account userProvisioning_SB(
		IContext context,
		oidc.proxies.Token _oAuthToken
	)
	{
		Object result = userProvisioning_SBBuilder(
				_oAuthToken
			)
			.execute(context);
		return result == null ? null : administration.proxies.Account.initialize(context, (IMendixObject) result);
	}
}
